### ISSUE TITLE
[Bug] pressing backspace with the wildmenu reopens it in the wrong position

### ISSUE THREAD

**Issue by akinsho** [folke/noice.nvim#1]
Hi @folke,

Just tried this plugin out, and it's fantastic out of the box 🚀. Really cool that it works so well despite all the lingering bugs in the `vim.ui_attach` api.

Since it's still WIP thought I'd report an issue I noticed using it.

I've noticed that whilst autocompleting with the wildmenu (at least I assume the menu that looks like the cmp window is the wildmenu). When I hit backspace, the window re-opens in the wrong position, just above the original commandline position.

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/22454918/193285800-66519270-462d-4acb-8271-e036c8f522e2.png">

I'm currently using `cmdheight=0` if that's relevant and can reproduce it using the following steps, note the specific completion is somewhat arbitrary, it's just one I noticed.

1. type `cmenu<space>`
2. press `<tab>` to open the wildmenu (or whatever key you have setup)
3. select the first completion item (if you don't use preselect)
4. Press backspace
5. See bug

**Comment by folke** [comment]
I checked and the popup completions I get bottom left aren't even coming from the cmdline, but are completions for the cursor I'm at in the orginal window.

I'll just implement a simple popup view that looks similar, but doesn't do anything.

**Comment by folke** [comment]
The fix was actually easy. The problem was that the cmdline window did not have `buftype=nofile` set, so the regular `cmp` also tried to show completions at the same time 😄

**Comment by akinsho** [comment]
@folke thanks for picking this up so quickly, I can still reproduce the issue on the latest commit unfortunately 🤔

**Comment by folke** [comment]
This should be fixed now in the latest version. Things I changed:

- I made a [proper fix](https://github.com/folke/noice.nvim/blob/e1d93f1f49657d996c330bee1f560cee8790bcf8/lua/noice/hacks.lua#L170) to the existing **cmp** api functions to get the position, screen position and line of the cmdline when **Noice** is active. Will see to make a PR to cmp that exposes an API to set the cmdline position from other plugins, but this works for now.
- I implemented a proper **cmp** source **noice_popupmenu** that is automatically added when no other cmdline sources have been configured.

With these changes, things should work as expected:
- cmp popupmenu should always be positioned correctly
- pmenu items (the ones I get from `ui_attach/ext_popupmenu` will be used for completion if no other cmp cmdline sources were configured
- if you're using `cmp-cmdline`, then that will work as it did before

Let me know if you encounter any more issues!

**Comment by akinsho** [comment]
@folke that sounds great 👍🏿, I'm not able to test further though as I plan to stay on 0.8 stable rather than nightly and the requirement has understandably been raised to nightly. I've found working on nightly too inconvenient. I'll close these out as is given the changes you've applied 👍🏿

**Comment by folke** [comment]
@akinsho I relaxed the requirements back to 0.8.0 for now.

They might change again, if new fixes/functionality becomes available in 0.9.0, but for now, it should work.

You might still want to not use **Noice** though, if you want a stable Neovim ;)

**Comment by akinsho** [comment]
@folke just tested it out on 0.8, and it works nicely, both issues are resolved as you say. Totally get you re. changing the requirement up to 0.9 at some point, I understand that maintaining the workarounds might get inconvenient or incompatible with 0.9 changes. Maybe when the time comes to bump it you can leave the 0.8 version in a branch, since presumably/hopefully that should be fine to continue to use as is till 0.9 is released.

Re. Noice's on stability, I'm less worried about a handful of plugins that might not be super stable (as that's easy to disable temporarily) as long as the editor is playing up around some crucial deadline 🤣
