### ISSUE TITLE
'attempt to call field `ui_attach` (nil value)' on initial setup

### ISSUE THREAD

**Issue by Raekh** [folke/noice.nvim#100]
**Describe the bug**
Upon launching neovim, greated with an error about ui_attach. Commands like :Noice or :NoiceLog are not registered afterwards.

**Which version of Neovim are you using?**
NVIM v0.8.0-dev-984-g568737d5b-dirty
Build type: Release
LuaJIT 2.1.0-beta3

**To Reproduce**
1. Use default conf with use({}) syntax
2. :PackerInstall and relaunch nvim
3. Error

**Noice Log**
Cannot use NoiceLog as the command is not registered

**Comment by folke** [comment]
It means you're not running on Neovim 0.8.0 stable or 0.9.0 nightly. `vim.ui_attach` is a new API method.

**Comment by folke** [comment]
what is the exact error you get? Can you post a screenshot?

**Comment by Raekh** [comment]
You're right, just updated it via homebrew. Thanks =)
