### ISSUE TITLE
bug: message for selecting code actions is not displayed when using noice & snacks

### ISSUE THREAD

**Issue by Theo-Steiner** [folke/noice.nvim#1002]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

MacOS Sonoma 14.5

### Describe the bug

The message for selecting code actions is not displayed until enter/escape is pressed when using snacks & noice.
If we remove snacks, the message selecting the code action options is displayed immediately.

### Steps To Reproduce

1. open the `repro.lua` config: `nvim -u repro.lua repro.lua`
2. run `lua vim.lsp.buf.code_action()`
3. verify that nothing is shown
4. hit enter & the code actions are shown (now it's too late though, since we already hit enter)

### Expected Behavior

As soon as we run `lua vim.lsp.buf.code_action()`, the selectable options should be shown in a floating message.

(it would be even cooler if there were a custom UI for selecting code actions, but that's a feature request for another time)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

local reproduction = "hi"
local reproduction = "hi"

require("lazy.minit").repro({
	spec = {
		{
			"folke/snacks.nvim",
			opts = {
				notifier = { enabled = true },
			}
		},
		{
			"folke/noice.nvim",
			dependencies = {
				"nvim-lua/popup.nvim",
				"MunifTanjim/nui.nvim",
			},
			config = function()
				require("noice").setup()
			end
		},
		{
			"williamboman/mason.nvim",
			dependencies = {
				"williamboman/mason-lspconfig.nvim",
				"neovim/nvim-lspconfig",
			},
			config = function()
				require("mason").setup()
				require("mason-lspconfig").setup({ ensure_installed = { "lua_ls" } })
				local lspconfig = require("lspconfig")
				require("mason-lspconfig").setup_handlers({
					function(server_name)
						lspconfig[server_name].setup({})
					end,
				})
			end,
		}
	},
})
```

Edit: update reproduction to reliably produce lsp code action options

**Comment by folke** [comment]
Opened upstream issue https://github.com/neovim/neovim/issues/31314

**Comment by folke** [comment]
Seems that functionality was added in core two days ago, to be able to fix this :)
https://github.com/neovim/neovim/pull/31279

Make sure to install a nightly from today. Update noice and also update snacks to make it all work nicely together.

**Comment by dgmora** [comment]
Hello, thanks! I've just checked and it's not blocking anymore, but it doesn't looking great:

<img width="1215" alt="Screenshot 2024-11-23 at 10 34 17" src="https://github.com/user-attachments/assets/1b387953-c78f-4b5f-a425-27a9f45c30d3">

When you type nothing gets displayed. But after pressing Enter, it displays what you typed (`1` in this case):

<img width="844" alt="Screenshot 2024-11-23 at 10 35 14" src="https://github.com/user-attachments/assets/6eca87d1-844b-4d4b-b499-5b16314be3d5">

**Comment by folke** [comment]
@dgmora noice does not get any input, so I can't display what you type while `inputlist` is still running.

**Comment by luukvbaal** [comment]
> When you type, nothing gets displayed. But after pressing Enter, it displays what you typed (1 in this case):

Yep, something needs to be done there still. Might make more sense to route this to `cmdline_show` but otherwise at least set the message kind to `number_prompt` as well for these key press "messages".

**Comment by folke** [comment]
`cmdline_show` with `prompt` would indeed make a lot of sense in this case.
