### ISSUE TITLE
bug: Code actions don't render until after hitting the escape key, then they can't be interacted with

### ISSUE THREAD

**Issue by insidewhy** [folke/noice.nvim#1005]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Linux

### Describe the bug

Code actions don't seem to work with noice and a default configuration like this:

```lua
    {
      "folke/noice.nvim",
      event = "VeryLazy",
      opts = {
        -- add any options here
      },
      dependencies = {
        -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
        "MunifTanjim/nui.nvim",
        -- OPTIONAL:
        --   `nvim-notify` is only needed, if you want to use the notification view.
        --   If not available, we use `mini` as the fallback
        "rcarriga/nvim-notify",
      },
    }
```

At first an empty notification appears in the top right of the screen, then a non-interactive action selection appears as a normal prompt after pressing `escape`.

### Steps To Reproduce

1. Trigger code actions via `vim.lsp.buf.code_action`
2. Noice renders a large empty block appears in the top right of the screen, during this time no keys work except for escape.
3. Press escape
4. A `messages` notification appears listing the code actions with the last line saying to type a number or select a code action with the mouse. By this time it's too late as the keys are back to controlling the window

### Expected Behavior

I guess the empty block being rendered should be where I can select my action, and I suppose if I did opt to press `escape` then I wouldn't get a notification with the actions in.

**Comment by folke** [comment]
You need Neovim nightly from at most two days ago to fix this.

**Comment by vinchi777** [comment]
I am on the latest nightly (NVIM v0.11.0-dev-1325+g30726c778c)
It turns out the code actions message box is too transparent. And only appears clearly after pressing ESC.
