### ISSUE TITLE
bug: unable to setup notify.nvim 

### ISSUE THREAD

**Issue by OlymDing** [folke/noice.nvim#1008]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

POP!_OS 22.04

### Describe the bug

I once setup my notify.nvim as right-bottom pop-up with "top_down = false", but the new noice.nvim's built-in notify seems to ignore my setting and keeps popping-up at right-top corner. for more settings like stages or fps, they are NOT configured either

my solution so far is let noice's repo checkout at commit [08d6e35](https://github.com/folke/noice.nvim/commit/08d6e350fe71c626417b666e218de113aac2e184) and everything just works fine.

if I directly call "require("notify")("test text")", it works OK, which means maybe the wrong "notify" is called in noice?

or if the "new notify" is decided to be included in this project, if there a valid way to configure it ? so far I haven't get any information about it from the doc

### Steps To Reproduce

1. clone the latest commit of noice from main branch (or just run Lazy update)
2. setup notify by " require("notify").setup({...}) "
3. try to log something, but notify's config doesn't work at all

### Expected Behavior

notifications are expected to be popped up at right bottom like this:
![image](https://github.com/user-attachments/assets/afbe595e-34d3-45ce-b407-d3b7dba78835)

but this is what happened after I updated my noice:
![image](https://github.com/user-attachments/assets/ce61c9f8-3aae-4b37-b9a6-246659cff6cc)

**Comment by folke** [comment]
> but the new noice.nvim's built-in notify seems to ignore my setting and keeps popping-up at right-top corner. for more settings like stages or fps, they are NOT configured either

The snacks notifier is completely different as `nvim-notify` and has different options. There are no stages, fps etc with snacks.

Either way, to use `nvim-notify`, you need to disable the snacks notifier:

```lua
{
  "snacks.nvim",
  opts = {notifier = {enabled = false}}
}
```

**Comment by OlymDing** [comment]
thanks

**Comment by OlymDing** [comment]
> > but the new noice.nvim's built-in notify seems to ignore my setting and keeps popping-up at right-top corner. for more settings like stages or fps, they are NOT configured either
> 
> The snacks notifier is completely different as `nvim-notify` and has different options. There are no stages, fps etc with snacks.
> 
> Either way, to use `nvim-notify`, you need to disable the snacks notifier:
> 
> ```lua
> {
>   "snacks.nvim",
>   opts = {notifier = {enabled = false}}
> }
> ```

that works, thanks !

**Comment by CX330Blake** [comment]
Thanks, it saves my morning!
