### ISSUE TITLE
screen stuck at redraw

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/noice.nvim#101]
**Describe the bug**
Noice causes elements of the screen to pend and being stuck at redraw (not sure if this is really the right description): see demo below.

https://user-images.githubusercontent.com/15387611/197359586-64679b95-8c6e-4269-bd22-3b0bd7e0e267.mov

**To Reproduce**
I noticed this behaviour while updating after yesterday's commits: I tried to go through them but I cannot identify which one can cause it. In the example above, though I am not using the `minimal.lua`, I am using exclusively 

- noice
- LSP
- lualine
- (some colour scheme)

(the behaviour happens with noice only too, I just wanted to show it with statusline so that it's more "visual"). Removing noice solves the problem. Can you reproduce this behaviour as well?

**Comment by folke** [comment]
Can't reproduce. Most likely a Neovim issue, since Noice doesn't have any control on painting the actual ui, like statusline etc.

I use Neovim nightly, so maybe it has been fixed in the meantime?

**Comment by gennaro-tedesco** [comment]
You're right that it was a neovim issue being fixed in the meantime; I ran nightly but I was a few (nightly) commits behind: building the very latest fixes the UI hanging. Apologies for the noise!
