### ISSUE TITLE
bug: LSP hover triggering E5108

### ISSUE THREAD

**Issue by anhari** [folke/noice.nvim#1010]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-662+gc0a8abf18-Homebrew Build type: Release LuaJIT 2.1.1724512491 Run "nvim -V1 -v" for more info

### Operating system/version

macOS 15.1.1

### Describe the bug

```
E5108: Error executing lua ...ovim/HEAD-c0a8abf/share/nvim/runtime/lua/vim/lsp/rpc.lua:291: Cannot serialise function: type not supported
stack traceback:
	[C]: in function 'encode'
	...ovim/HEAD-c0a8abf/share/nvim/runtime/lua/vim/lsp/rpc.lua:291: in function 'encode_and_send'
	...ovim/HEAD-c0a8abf/share/nvim/runtime/lua/vim/lsp/rpc.lua:338: in function 'request'
	...m/HEAD-c0a8abf/share/nvim/runtime/lua/vim/lsp/client.lua:679: in function 'request'
	...r/neovim/HEAD-c0a8abf/share/nvim/runtime/lua/vim/lsp.lua:888: in function 'buf_request'
	....local/share/nvim/lazy/noice.nvim/lua/noice/lsp/init.lua:66: in function 'hover'
	[string ":lua"]:1: in main chunk
```

### Steps To Reproduce

1. Install `noice.nvim`
```
return {
	"folke/noice.nvim",
	event = "VeryLazy",
	opts = {},
	dependencies = {
		"MunifTanjim/nui.nvim",
		"rcarriga/nvim-notify",
	}
}
```
2. Open a file with a language server
3. Run `:lua vim.lsp.buf.hover()<cr>` over a symbol

### Expected Behavior

Should be able to trigger LSP hovers without error.

### Repro

Couldn't get the repro script to work, but if I roll back [this](https://github.com/folke/noice.nvim/commit/c6f6fb178ebe9b4fd90383de743c3399f8c3a37c#diff-d1d8839ea281035a0a1858e1e5db16fa30c3c889ed30230b8f7eb1fa898e6d74L55) change, things work again.

**Comment by folke** [comment]
Use Neovim stable or a recent nightly. Old nightlies are not supported

**Comment by sadtab** [comment]
I have the same issue with `v0.11.0-dev-1010+g86832dcd19`  (It's the last nightly at this moment)

**Comment by folke** [comment]
@sadtab you're not using that nightly if you get that error. Check your install
