### ISSUE TITLE
bug: Noice integration with LSP 'steals' the focus into Signature buffer. 

### ISSUE THREAD

**Issue by YounesElhjouji** [folke/noice.nvim#1016]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

macOS 14.3.1

### Describe the bug

**Setup**: NvChad, Noice, LSPConfig, Mason

**Why I blame noice?** 
The buffer that 'hijacks' my cursor is of buftype 'noice'

Description of the issue:
The issue happens for functions with documentation when I type '(' as the first character within the function.
E.g. in javascript 
`myList.filter((item) => {})`
When I type the second '(' after 'filter' what happens is that I automatically exit insert mode into normal mode and my cursor is transformed into the function signature/docs buffer.
[Video of Reproduction](https://github.com/user-attachments/assets/7b51b56e-ddde-42b1-ba38-6be4fd493554)

This issue is not fixed by disabling other plugins such as nvim-autopairs which automatically creates a closing ')' 
The issue is only fixed by disabling noice
The issue is reproducible across languages. I reproduced it with ts, js, python, and lua.
Disabling lsp signature, hover, and progress through setup does not fix the issue. I have attempted many different noice setups to disconnect lsp from noice, but none seem to work.

Checking ':imap (' does not give any mappings that would cause opening parentheses to switch mode and buffer, and opening parantheses in general does not cause this issue unless within a function with floating signature open.

### Steps To Reproduce

1. With noice and lsp config installed + your language LSP configured
2. Type a function call of a valid function with docs and type '(' as the first character within the function call
3. The cursor is moved to the signature buffer and set to normal mode 

### Expected Behavior

I expect to stay within my buffer and in insert mode when I type 'Date.now(('

### Repro

```lua
-- These are my plugins on top of latest nvchad. Everything is up to date

return {
  -- {
  --   "nvimtools/none-ls.nvim",
  --   event = "VeryLazy",
  --   opts = function()
  --     return require "configs.null-ls"
  --   end,
  -- },
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    opts = {
      -- add any options here
    },
    dependencies = {
      "hrsh7th/nvim-cmp",
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    },
  },
  {
    "neovim/nvim-lspconfig",
    config = function()
      require("nvchad.configs.lspconfig").defaults()
      require "configs.lspconfig"
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "lua-language-server",
        "stylua",
        "html-lsp",
        "css-lsp",
        "prettier",
        "ruff",
        "black",
        "isort",
        "typescript-language-server",
        "tailwindcss-language-server",
      },
    },
  },
  {
    "numtostr/BufOnly.nvim",
    lazy = false,
  },
  {
    "windwp/nvim-ts-autotag",
    ft = {
      "javascript",
      "typescript",
      "javascriptreact",
      "typescriptreact",
    },
    config = function()
      require("nvim-ts-autotag").setup()
    end,
  },
  {
    "MeanderingProgrammer/render-markdown.nvim",
    ft = { "markdown" },
    dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
    ---@module 'render-markdown'
    ---@type render.md.UserConfig
    opts = {},
  },
}
```

**Comment by folke** [comment]
No idea what's causing this, but for sure not noice...

**Comment by chkg2a** [comment]
this issue is still persistent. After removing noice. The bug is gone

**Comment by chkg2a** [comment]
for now the only solutions seems to disable the signature.

```lua
lsp = {
    signature = {
      enabled = false,
    }
}
```

**Comment by YounesElhjouji** [comment]
@chkg2a 
This allows me to keep the signature and avoid the error 

```
require("noice").setup({
  lsp = {
    signature = {
      enabled = false,
      auto_open = true
    }
  }
})
```

I said in my report of the issue 

> Disabling lsp signature, hover, and progress through setup does not fix the issue. I have attempted many different noice setups to disconnect lsp from noice, but none seem to work.

This is incorrect, I thought this because my noice configuration was setup improperly 

@folke Please take a look at this again, it does seem related to noice.
