### ISSUE TITLE
bug: fn @ line 76 in lua>noice>message>init.lua causes vim to focus the lsp  window on hover which turns out to be super annoying. 

### ISSUE THREAD

**Issue by theTechGoose** [folke/noice.nvim#1017]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1295+gbf5c1346c5

### Operating system/version

MacOs 14.5

### Describe the bug

I cloned the repo and commented out the lines and it fixed it. Tried to do a pull request to make it easy but for whatever reason I'm unable to create a branch on this repo.

I fixed my own issue but I thought that I would put this here incase anyone else has the same problem please feel free to close.

Clone noice.nvim
and comment out the internals of the message() class member
```
function Message:focus()
  local win = self:win()
  if win then
    -- vim.api.nvim_set_current_win(win)
    -- switch to normal mode
    -- vim.cmd("stopinsert")
    return true
  end
end
```

and then reference it in your lazy nvim like this
	```
{
		dir = "~/.config/nvim/lua/local-plugins/noice.nvim",
    event = "VeryLazy",
		opts = {
			lsp = {
				-- override markdown rendering so that **cmp** and other plugins use **Treesitter**
				override = {
					["vim.lsp.util.convert_input_to_markdown_lines"] = true,
					["vim.lsp.util.stylize_markdown"] = true,
					["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
				},
			},
			-- you can enable a preset for easier configuration
			presets = {
				bottom_search = true, -- use a classic bottom cmdline for search
				command_palette = true, -- position the cmdline and popupmenu together
				long_message_to_split = true, -- long messages will be sent to a split
				inc_rename = false, -- enables an input dialog for inc-rename.nvim
				lsp_doc_border = false, -- add a border to hover docs and signature help
			},
		},
		dependencies = {
			"MunifTanjim/nui.nvim",
			"rcarriga/nvim-notify",
		},
	},

```

### Steps To Reproduce

This is a solution?

### Expected Behavior

For it to not auto focus the hover window.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That can only happen when you do the keymap to open hover is already open.
Not a bug

**Comment by theTechGoose** [comment]
Can you please explain in a little more detail? I tried my best to understand how the plugin works im just coming up a little short.

**Comment by theTechGoose** [comment]
Nope, I undertand; I have an auto command to make hover happen, I need to disable that in my config If I am going to use noice. Is that correct?

**Comment by folke** [comment]
Ah yes, indeed :)

The hover works similar to the hover in Neovim.
When you hover `K` when it's already open, then you focus the hover window.
That's quite convenient, but wouldn't work with an autocmd like that.
