### ISSUE TITLE
`command-preview` block cursor refresh of cmdline when move

### ISSUE THREAD

**Issue by wangl-cc** [folke/noice.nvim#103]
**Describe the bug**
When enter a command with `command-preview` like `:s/foo/bar`, the cursor of cmdline will not refresh when move, until insert or delete.

**Which version of Neovim are you using?**
NVIM v0.9.0-dev-150+g2f9b94a26

**To Reproduce**
1. Enter a command with `command-preview` like `:s/foo/bar`,
2. Try move cursor.

**Expected Behavior**
The cursor will refresh.

**Screenshots**

https://user-images.githubusercontent.com/40141251/197363853-cfffcb7c-94ff-44fd-8e6e-55c9ba371509.mov

**Noice Log**
No log during reproducing.

**Comment by folke** [comment]
That's a known issue on the Neovim side. See the tracking issue for noice. It's a problem with substitute, seems to work fine with other command preview stuff

**Comment by folke** [comment]
https://github.com/neovim/neovim/issues/20463

**Comment by wangl-cc** [comment]
My bad, forget to check known issues.

**Comment by b0o** [comment]
Seems like this is happening again when using noice with inc-rename on `NVIM v0.11.0-dev-168+ge20c5fba2c`.

**Comment by folke** [comment]
Yes indeed. changing the cmdline is working correctly during substitute on nightly, but moving does not.
feel free to post an issue upstream.

**Comment by b0o** [comment]
Seems to be fixed now, thanks @folke!

**Comment by folke** [comment]
Yes indeed! We're using real (fake) cursors now in noice.
It uses the Neovim API to draw the real cursor in the noice windows, but it's still fake, since those windows are not the current window.

Only drawback is that if a redraw happens somewhere not by noice, then the cursor may disappear (briefly).

**Comment by seanturner026** [comment]
I think I'm encountering this issue again in nvim 11? The below minimal config doesn't track the current substitution. In the below video the first edit of `blah.txt` is using the config and shows the cursor not tracking the current substitution. The `nvim --clean blah.txt` (second edit) has the cursor tracking the second substitution. 

Also, not totally sure if this is the relevant issue. Happy to make a new issue or copy this elsewhere if that makes sense.

```lua
vim.opt.hlsearch = false

local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
  local out = vim.fn.system { 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath }
  if vim.v.shell_error ~= 0 then
    error('Error cloning lazy.nvim:\n' .. out)
  end
end
local rtp = vim.opt.rtp
rtp:prepend(lazypath)

require("lazy").setup({
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    opts = {},
    dependencies = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
      }
    }
  }
)
```

https://imgur.com/a/WanGT9U
