### ISSUE TITLE
Don't set `filetype` for command line

### ISSUE THREAD

**Issue by clason** [folke/noice.nvim#104]
Noice supports syntax highlighting for the command line (which is nice!), but apparently does so by setting the filetype -- which triggers all manner of autocommands, such as attaching a language server. 

Instead, Noice should just set `vim.bo.syntax` directly, or -- since Noice only supports treesitter highlighting, IIUC -- use `vim.treesitter.start(bufnr, language)`.

(Compare how telescope does this, which has the same issue with its previews.)

**Comment by folke** [comment]
Good point!
