### ISSUE TITLE
Popupmenu does not show all fields of `complete-items`

### ISSUE THREAD

**Issue by clason** [folke/noice.nvim#105]
When using noice's popupmenu for completion, it only shows the `word` but not the `menu` or `info` (see `:h complete-items`). E.g., LSP servers like  `lua-language-server` will show `field` or `snippet` as `kind`, which is missing here.

**Comment by folke** [comment]
What's the easiest way to get completion items with those details? In my testing, it was ways empty

**Comment by clason** [comment]
`complete_info()` should contain all those under `items`.

**Comment by clason** [comment]
Look at `vim.lsp.util.text_document_completion_list_to_complete_items()`, too.

**Comment by folke** [comment]
Added kinds with icons (can be disabled).

(ignore the unexpected exp)

![image](https://user-images.githubusercontent.com/292349/197415917-9b95ba4a-22a3-42d7-83c7-85b923793df4.png)

**Comment by folke** [comment]
Not sure what to do with the menu and info items.

The menu ones that I've seen, are not really useful. Typically point to a file where the symbol is coming from.

Info apparently can contain details that should ideally be shown in some kind of detail window next to the completion item.

I'll leave it like this for now. May see later to add menu and info

**Comment by clason** [comment]
> Info apparently can contain details that should ideally be shown in some kind of detail window next to the completion item.

Yes, exactly (nudge, nudge ;))

> The menu ones that I've seen, are not really useful. Typically point to a file where the symbol is coming from.

VimTeX uses that to preview a generated citation for BibTeX entries. (I don't expect anybody to understand that, but it is _very_ useful, and a dealbreaker for me.)

**Comment by folke** [comment]
So basically both menu and info should go into some kind of preview window next to the item?

**Comment by folke** [comment]
Would be helpful if you could provide a screenshot on how it looks like for you without Noice

**Comment by clason** [comment]
Sorry, I appreciate that the issue was curt to the point of being unhelpful; a minimal reproducing example in this case just has a lot of moving parts. Here's a screenshot with VimTeX:

<img width="723" alt="Screenshot 2022-10-24 at 00 00 21" src="https://user-images.githubusercontent.com/2361214/197420205-0f80a9fd-bdc9-4dba-8389-41125dfccde1.png">

**Comment by clason** [comment]
(only `info` is supposed to be a separate window for the selected item)

**Comment by folke** [comment]
ok, cool. So `abbr/word, menu, icon, kind`

**Comment by clason** [comment]
not necessarily in that order -- I'd have to trawl the source code for the pum.

But *déjà vu*! Maybe this issue (and the linked PR) is helpful: https://github.com/smolck/uivonim/issues/10

**Comment by clason** [comment]
It's 
```
abbr/word    menu    kind    (info)
```

**Comment by folke** [comment]
Added menu as well!

**Comment by clason** [comment]
Thanks! Looks good, _except_ that the non-selected `menu` (but not `word`) entries have a different (for me barely visible) highlight group?

**Comment by folke** [comment]
https://github.com/folke/noice.nvim#-highlight-groups

The one you're looking for is `NoiceCompletionItemMenu`

**Comment by clason** [comment]
Hmm, I'd prefer the default to be the same as for  `word` (`menu` is there to pick the right entry, so it being barely visible defeats the purpose ;))

**Comment by folke** [comment]
Changed! :)

**Comment by clason** [comment]
Thanks!

On a related note, I've seen screenshots where the typed prefix is highlighted in the completion pum; I couldn't find any highlight group for that, though -- or is that from a different plugin/config?

**Comment by folke** [comment]
That's `NoicePopupmenuMatch`. Linked to `Special`.

**Comment by clason** [comment]
Ah, that only works on the commandline, not the completion popup! That explains it.

**Comment by folke** [comment]
It should also work in other places. For other places, I calculate the prefix as the longest prefix match of all completion items, which won't work if there's items in there with a completely different prefix.

I don't get any information of the prefix through `ext_popupmenu`, so not sure if there's a better way.
