### ISSUE TITLE
Noice crashes Neovim when using neovim-qt

### ISSUE THREAD

**Issue by khalidchawtany** [folke/noice.nvim#106]
**Describe the bug**
Using neovim-qt noice crashed neovim.

**Which version of Neovim are you using?**
```
NVIM v0.9.0-dev-156+g7693e424
Build type: Release
LuaJIT 2.1.0-beta3
```

Gui(specify which GUI client you are using)? Nightly? Version?
```
NVIM-QT v0.2.17.9999
Build type:
Compilation: -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.5
```

**To Reproduce**
1.  Use the `min.lua` **from below!!!!!!!!!**.
2. `/Applications/neovim-qt/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/nvim-qt -- -u ./min.lua`
3.  `:e ~/some_dir/some_file`
4.  Press `cdf` to cd to the dir of the some_file
5.  Neovim crashes with the message `Neovim fatal error "The Neovim process has crashed"`

**Expected Behavior**
Neovim not to crash

**Screenshots**

**Noice Log**
Noice log is empty

<details>
<summary>min.lua</summary>
<pre>
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "folke/noice.nvim",
        requires = {
          "MunifTanjim/nui.nvim",
        },
        -- commit = "c7fdaec", -- Bad commit
        -- commit = "6276d2d", -- Good commit
      },
      {
        "folke/tokyonight.nvim",
      },
      {
        "nvim-treesitter/nvim-treesitter" -- need this else get warning about treesitter for vim
      }

      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
_G.load_config = function()
  vim.opt.termguicolors = true
  vim.cmd([[colorscheme tokyonight]])

  vim.cmd([[TSInstall vim]])
  vim.cmd([[e  ~/Desktop/min.lua]])                   -- edit any file
  vim.cmd([[ nnoremap cdf :lcd %:p:h<cr>:pwd<cr> ]])  -- crashes if I press cdf to cd to the file path

  require("noice").setup()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Noice and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])

</pre>
</details>

**Comment by folke** [comment]
That mapping doesnt seem to work?
Tried with terminal vim

**Comment by folke** [comment]
Doing the mapping, opens the cmdline
![image](https://user-images.githubusercontent.com/292349/197475665-79bd09b1-b90e-4edf-a5b7-76899f997062.png)

Pressing enter gives me:
![image](https://user-images.githubusercontent.com/292349/197475737-35d5072f-0870-48cc-a595-0cb957607bb1.png)

**Comment by khalidchawtany** [comment]
I know that it works in the terminal. However, when using neovim-qt it crashes. This caused by the hide cursor commit c7fdaec6befb99b91f3ab8bfc6a6ad8ab5a10b62

I had a `<cr>` at the end of the mapping and the `e some_file`! 
So it should cd to the file path not just show the cmd_line and wait for the press enter.

**Comment by folke** [comment]
That;s what I mean. It doesn't work in the terminal for me. The command is wrong. It's indeed missing the `<cr>`, but also the `:pwd` is incorrect

**Comment by folke** [comment]
Using the mapping below, works for me in terminal and in `nvim-qt`
```lua
vim.cmd([[ nnoremap cdf :lcd %:p:h <cr> ]]) -- crashes if I press cdf to cd to the file path
```

Are you using the latest version if `nvim-qt`?

**Comment by khalidchawtany** [comment]
This is how it is written on my side. However, github messed it up and removed the `<cr>`s. I am sorry. I should have checked before submitting.

![Screen Shot 2022-10-24 at 11 23 50 AM](https://user-images.githubusercontent.com/1681606/197481410-df04dab5-8143-454e-aece-e8529757084e.png)

```
  vim.cmd([[TSInstall vim]])
  vim.cmd([[e  ~/Desktop/min.lua]])                   -- edit any file
  vim.cmd([[ nnoremap cdf :lcd %:p:h<cr>:pwd<cr> ]])  -- crashes if I press cdf to cd to the file path
```

[v0.2.17](https://github.com/equalsraf/neovim-qt/releases/tag/v0.2.17) is the latest release of neovim-qt

**Comment by khalidchawtany** [comment]
Without the `:pwd<cr>` it does not crash.

**Comment by folke** [comment]
Still works for me with that mapping

**Comment by folke** [comment]
```
❯ nvim-qt --version
NVIM-QT v0.2.17.0
Build type: 
Compilation:-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.5
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/bin/../share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/bin/../share/nvim-qt/runtime

NVIM v0.9.0-dev-155+g771824128
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az628-278

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by folke** [comment]
Was able to trigger the crash with Neovim stable.

Seems fixed on nightly though, so closing this.

**Comment by khalidchawtany** [comment]
I am using the HEAD version of neovim. I am addicted to compiling neovim source every morning :)
I just pulled and recompiled again just to be sure.

```
NVIM-QT v0.2.17.9999
Build type:
Compilation: -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.5
Environment:
  nvim: nvim
  args: --cmd let &rtp.=',/Users/juju/Development/Applications/neovim-qt/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime' --cmd set termguicolors
  runtime: /Users/juju/Development/Applications/neovim-qt/neovim-qt/build/bin/nvim-qt.app/Contents/MacOS/../Resources/runtime

NVIM v0.9.0-dev-157+g7fddb6d5
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by juju@JuJus-MacBook-Pro-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by folke** [comment]
Either way, carshing of Neovim is a Neovim bug. Nothing I can do about that from Noice.

**Comment by khalidchawtany** [comment]
Thanks. You are right. I was hesitant to report it here since no plugin should be able to crash neovim.
