### ISSUE TITLE
Noice not working well with winbar

### ISSUE THREAD

**Issue by InsigMath** [folke/noice.nvim#110]
**Describe the bug**
Having both noice and winbar (with default configrations on both) causes visual issues when going to command or search mode. 

**Which version of Neovim are you using?**
Nightly: NVIM v0.9.0-dev-16-g56998feeb

**To Reproduce**
1. Use packer to install both winbar and noice
2. Open up any file and type ":" and you will see the winbar script ontop of the popup and it will change the look of the popup. I will include a an image below.

**Screenshots**
![winbar issue with noice](https://user-images.githubusercontent.com/2395535/197617906-94a68e2a-e9d1-4e55-a8df-7d0fb41b9d3a.png)

**Comment by folke** [comment]
https://github.com/fgheng/winbar.nvim#configuration

Have you added `noice` to the `exclude_filetype` of winbar?

**Comment by InsigMath** [comment]
I swear I thought I included that but I just tried that now and that fixed the issue, sorry that was a very silly issue on my end. Thanks for the help though!
