### ISSUE TITLE
`vim.fn.inputlist` quirks

### ISSUE THREAD

**Issue by ranjithshegde** [folke/noice.nvim#112]
Firstly, apologies as I keep coming here with more issues and not fixes!

Is there a config option or perhaps making it a default behavior to always keep the prompt window open until choice for `vim.fn.inputlist` made or exited?

With `orgmode` plugin which heavily uses `inputlist` for a variety of functionality, from opening files to exporting pdfs, the popup view for choice stays on for a couple of seconds and disappears, like this

![Peek 2022-10-25 09-27](https://user-images.githubusercontent.com/10258296/197711008-b60faee6-4f9b-4d4c-9c83-72088fe0c160.gif)

On the other hand, I dont know if this is chiefly a problem of `inputlist`. I tried to reproduce with a simple example and it works as expected

![Peek 2022-10-25 09-35](https://user-images.githubusercontent.com/10258296/197712204-e445c5bb-f900-4596-a9bc-a87cf5282e39.gif)

**Logs**
Since this is not exactly an error, there are no logs

**Noice config**
```lua
    require('noice').setup {
        cmdline = {
            view = 'cmdline',
            view_search = 'cmdline',
            format = {
                inc_rename = { pattern = '^:%s*IncRename%s+', icon = ' ', ft = 'text' },
            },
        },
    }
```

**Comment by folke** [comment]
I just pushed an update that doesn;t hide mini messages when the ui is blocking. I already did the same for nvim-notify.

This probably fixes your issue. Can you test it?

**Comment by ranjithshegde** [comment]
@folke 
Works great now! 
Thanks

**Comment by gennaro-tedesco** [comment]
Sorry to comment on a closed issue, but somewhat related to `vim.fn.inputlist/input`. Invoking `vim.fn.input` I noticed that it does not fall under the formatting options provided for `cmdline` (or similar patterns): what is the right way to control the options of the vim prompts (like `vim.fn.confirm/input` and the like)?

To be more clear: if I set specific options for formatting certain cmdline patterns (say like in the [the README](https://github.com/folke/noice.nvim#%EF%B8%8F-configuration)) the prompts that display with input or confirm do not undergo the same behaviour (for instance they don't respect the highlight groups or titles that are set), thus I presume they need special format patterns to be included?

**Comment by folke** [comment]
For confirm, you can configure the `confirm` view. Check the [code](https://github.com/folke/noice.nvim/blob/927e7549efe9d3261311a2b0bd104d97d6aae7cd/lua/noice/config/views.lua#L184) for that.

Configure it with `config.views.confirm` to override any of the deafult settings.

As for `input` and the like, it's not that simple, since it comes in as an `event=msg_show`, `kind=`. You can add custom routes for that, but there's no way to know if a message is coming from `input` or trigered by let's say `:ls`.

You can submit a feature request to Neovim for that :)

**Comment by folke** [comment]
Wait, I'm wrong, apparently `input` comes in as a `cmdline`. Will see to make this configurable!

**Comment by folke** [comment]
@gennaro-tedesco just pushed an update that makes this configurable. Check the docs https://github.com/folke/noice.nvim/commit/b645e30dc228e75b64b28374aa72b6c8ebbbe977

Default config, adds `NoiceCmdlineInput` as hl group for the prompt, removes the icon and sets the title to `Input`

**Comment by gennaro-tedesco** [comment]
Ooops, I see that `confirm` is there, my bad. Thank you for looking into `input`, obviously this is just nitpicking on things, do dedicate the time to more urgent matters :)

**Comment by folke** [comment]
@gennaro-tedesco input is fixed. See my previous comment :)

**Comment by gennaro-tedesco** [comment]
Woow, you're faster than we can check :D 

Thank you for all the effort really.
