### ISSUE TITLE
Input popup draws over packer display

### ISSUE THREAD

**Issue by grimm26** [folke/noice.nvim#117]
**Describe the bug**
I run `:PackerSync` when there is a plugin that has been removed from my config. Packer displays a notification to show what is being removed then prompts for Y|N input. Noice puts the Input prompt over Packer's display of what is being removed.

Noice disabled:
![Screenshot from 2022-10-25 10-29-59](https://user-images.githubusercontent.com/127401/197816989-6ef2f4fa-e6fa-4e56-aaa4-a265079c53fc.png)

Noice enabled
![Screenshot from 2022-10-25 10-25-39](https://user-images.githubusercontent.com/127401/197817039-41aa2629-d5e4-4170-86e7-f0dc22e43487.png)

**Which version of Neovim are you using?**
nightly NVIM v0.9.0-dev-155+g771824128

**To Reproduce**
1. Use packer. Remove a previously installed plugin from your configuration.
2. Run `:PackerClean` or `"PackerSync` inside of nvim with Noice enabled.

**Expected Behavior**
The display and the input prompt do not cover each other. Either noice somehow picks up Packer's display so that it handles it or it detects that it is there so as not to overlay it. Or something else that keeps displays in view.

**Screenshots**
See above.

**Comment by folke** [comment]
Noice will now automatically move out of the way of existing floating windows
