### ISSUE TITLE
Warning window in C file that is persistent

### ISSUE THREAD

**Issue by InsigMath** [folke/noice.nvim#118]
**Describe the bug**
I open up a C file and I get a constant warning about improper encoding issue (look at image below).

**Which version of Neovim are you using?**
Nightly: 0.8.0

**To Reproduce**
1. Open up a .c file in neovim

**Expected Behavior**
Before noice I had this issue popup below but I had the following lua script to suppress it via vim.notify:
```lua
local notify = vim.notify
vim.notify = function(msg, ...)
  if msg:match("warning: multiple different client offset_encodings") then
    return
  end

  notify(msg, ...)
end
```
So I was expecting it to be suppressed, not sure if there is a way to supress warnings in noice.

**Screenshots**
![image](https://user-images.githubusercontent.com/2395535/197840916-8337585a-a826-4c8f-ab8a-fdda593b4cce.png)

**Comment by clason** [comment]
Wouldn't it be better to, you know, _fix_ the actual issue?

**Comment by InsigMath** [comment]
Oh I was just wondering if this was a bug from noice since I was able to suppress it before using vim.notify.

**Comment by InsigMath** [comment]
Thank you I will look into those suggestions!

**Comment by Spo0on** [comment]
I have same problem but the above solution didn't work for me. Plz help I love this plugin but I can't use it because of that bug
