### ISSUE TITLE
Control the 'time' of things on screen.

### ISSUE THREAD

**Issue by alphastrata** [folke/noice.nvim#119]
**Is your feature request related to a problem? Please describe.**
Despite the bugs etc, this is too awesome not to use! It would be nice to configure the 'time' that a popup stays up before fading --esp the ability to configure that popup based on the event that triggered it, i.e maybe you are happy to have successful things (saving, formatting etc) pass by within a second, but for warnings or errors, perhaps you want them to be on-screen longer, and configurable to be so.

**Describe the solution you'd like**
Dream configuration may look something like:
```lua
require("noice").setup({
	views = {
		cmdline_popup = {
			--...snipped for brevity
	},
	popup = {
		size = { width = 80, height = 40, focusable = true },
                **fade_time ={
                         error = 5,
                         warning = 3,
                         info = 1,**
	}
})
```

**Describe alternatives you've considered**
Had a quick look at the popup defaults within nui that the docs point to, `rg` for the usual suspects like 'time' 'fade' 'timer' etc failed to produce any results, perhaps this functionality is already there and just named in such way that I was unable to grep it :( in-which-case perhaps some docs would solve this.  

**Additional context**
As a user I think it'd be a powerful part of this framework in general if we could control the temoprality of how long stuff that pops into our field of view was going to stay there, and, based on what said popup is-- where appropriate, have **very** granular control, perhaps even on a language level.

**Comment by folke** [comment]
Are you refering to nvim-notify? For that you can configure it globlly with nootify setup, or set it on a route opts. (just added this)
