### ISSUE TITLE
lazy_exists a nil value

### ISSUE THREAD

**Issue by crivotz** [folke/noice.nvim#12]
Hi Folke,
after last_update I receive the following error:
`Error in packer_compiled: ...im/site/pack/packer/start/noice.nvim/lua/noice/hacks.lua:214: attempt to call field 'lazy_exists' (a nil value)`

**Comment by Shougo** [comment]
dup of https://github.com/folke/noice.nvim/issues/13.

**Comment by crivotz** [comment]
Thank you I close in favor of #13

**Comment by folke** [comment]
Fixed in https://github.com/folke/noice.nvim/commit/4d3b4964d15dc83448a486dfe1af97e5992fb590
