### ISSUE TITLE
Cmdline popup is off by two characters (prompt?)

### ISSUE THREAD

**Issue by pwntester** [folke/noice.nvim#122]
**Describe the bug**
The Cmdline and cmdline-popups seem to be off by two characters as shown in the image:
![image](https://user-images.githubusercontent.com/125701/197955526-0bb697c5-fc94-4938-89ba-076c70072f2f.png)

**Which version of Neovim are you using?**
Nightly

**To Reproduce**
```
          views = {
            cmdline_popup = {
              -- https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/popup
              position = {
                row = 15,
                col = "50%",
              },
              size = {
                width = 150,
                height = "auto",
              },
            },
            popupmenu = {
              relative = "editor",
              position = {
                row = 18,
                col = "50%",
              },
              size = {
                width = 150,
                height = 10,
              },
              border = {
                style = "rounded",
                padding = { 0, 1 },
              },
              win_options = {
                winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
              },
            },
          }
```

**Expected Behavior**
Both windows are aligned

**Comment by pwntester** [comment]
Even if I set the width of the cmdline to 148 chars, the two windows are shifted:

![image](https://user-images.githubusercontent.com/125701/197956626-d36d17d5-ea66-4f51-b9f6-05e28949ee34.png)

Also, is there anyway to trigger autocompletion as you write?

Thanks!

**Comment by folke** [comment]
I know what's causing this. Something on my end, and also something at Nui https://github.com/MunifTanjim/nui.nvim/pull/204

**Comment by folke** [comment]
Fixed, but you also need to update Nui

**Comment by pwntester** [comment]
Thanks!
