### ISSUE TITLE
Can't change winhighlight

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#126]
When i try to set new highlight group `FloatBorder`, it doesn't work. It must be like on second image.

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/198047810-e26cf584-f638-40a7-b1ee-4611b0108e45.png)

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/198047974-09382ca0-840f-4491-8b7e-9e806d015606.png)

**Comment by folke** [comment]
How do you set it?

**Comment by folke** [comment]
Sorry, I see it in the screenshot now

**Comment by mrjones2014** [comment]
Interestingly, changing the highlight group colors for the default highlight groups doesn't seem to work either 🤔

**Comment by folke** [comment]
That's because the routes for cmdline stuff are automatically generated.

You can override by adding the `opts` to each of the cmdline formats.

I will add a better way though, since that;s quite verbose

**Comment by kaiphat** [comment]
I would like to have opportunity set `Normal` and `FloatBorder` globally

**Comment by folke** [comment]
I changed it so that `config.cmdline.opts` overrides everything in the formats. So your initial code should work as expected now.

**Comment by folke** [comment]
Sorry, not your initial code.

Apply any settings to override in `config.cmdline.opts`
