### ISSUE TITLE
Strange behavior, when i press tab in empty cmd line

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#127]
![image](https://user-images.githubusercontent.com/53742299/198048384-47d62cf1-7247-4a35-bb35-5e953d79cbd5.png)

**Comment by folke** [comment]
Did you try this with the last version? I think I fixed that. That;s the code that goes out of the way of existing floats. But it shouldn't do that for Noice windows

**Comment by kaiphat** [comment]
Yes, it's the last version.

**Comment by folke** [comment]
Can you try now? If it still behaves weird, would be great if you could make a mini.lua

https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by kaiphat** [comment]
The same thing.
Why when i open cmd line it has `Cmdline` title, but when i press `Tab` the title changes to `Filter`? Mb it connects with error.

**Comment by folke** [comment]
That;s because you selected the first entry in the popumenu which is `!`, so your cmdline becomes `:!`

**Comment by folke** [comment]
Wait, I can reproduce it. Will look into it!

**Comment by kaiphat** [comment]
https://github.com/kaiphat/dotfiles/tree/master/nvim

**Comment by kaiphat** [comment]
```    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif require("luasnip").expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
      else
        fallback()
      end
    end, { "i", "s" }),
```

**Comment by kaiphat** [comment]
It's problem mb
```
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif require("luasnip").expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
      else
        fallback()
      end
    end, { "i", "s" }),
```

**Comment by kaiphat** [comment]
Good job! It's working.
