### ISSUE TITLE
Can't disable fidget settings

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#128]
![image](https://user-images.githubusercontent.com/53742299/198048735-02e3258f-e70d-4727-aef3-e89585ddab99.png)

**Comment by kaiphat** [comment]
Without noice
![image](https://user-images.githubusercontent.com/53742299/198049026-f7bea753-e528-4ba8-9ecd-27a714dd3375.png)

**Comment by kaiphat** [comment]
I think noice use fidget plugin. My bad, by why on screen there are two messages about sumneko_lua lsp?

**Comment by kaiphat** [comment]
And i whatever can't disable this:)

**Comment by folke** [comment]
`lsp_progress` shoudl be under the main key, not cmdline

**Comment by kaiphat** [comment]
Thank you so much!
