### ISSUE TITLE
Crash when `nvim-cmp` is  *not* lazy-loaded

### ISSUE THREAD

**Issue by jonatan-branting** [folke/noice.nvim#13]
It seems that `noice.nvim` fails to load due to: 
```
packer.nvim: Error running config for noice.nvim: ...im/site/pack/packer/start/noice.nvim/lua/noice/hacks.lua:214: attempt to call field 'lazy_exists' (a nil value)
```
Error was introduced with this commit: https://github.com/folke/noice.nvim/commit/0044d37d5ea364df787671247d72e21dba2578de

From a cursory glance at the code, it seems that this will always crash *unless* `nvim-cmp` is lazy loaded, as otherwise this method won't exist.

**Comment by folke** [comment]
Should be fixed now!

**Comment by folke** [comment]
Fixed in https://github.com/folke/noice.nvim/commit/4d3b4964d15dc83448a486dfe1af97e5992fb590
