### ISSUE TITLE
smartmove doesnt work well with cmp

### ISSUE THREAD

**Issue by folke** [folke/noice.nvim#130]
We should add an exlcude list of filetypes that are ok to overlap.

**Comment by folke** [comment]
@wangl-cc I can't repdoduce this. What do you do to trigger it?

**Comment by wangl-cc** [comment]
I trigger it when the cmdline change，like type :h or :lua.

**Comment by quantum-booty** [comment]
I can reproduce this too.

**Comment by folke** [comment]
Should be fixed. I've added the filetype exlcusions and also only do the smart move when the overlapping area is larger than 30%.

There's always windows without filetypes. Like the packer cofirm dialog, shade window, cmp scrollbars, ...

The area check should cover most of that
