### ISSUE TITLE
<80>kb character in notifications

### ISSUE THREAD

**Issue by pBorak** [folke/noice.nvim#131]
**Describe the bug**

Hey, I've noticed that [this](https://github.com/folke/noice.nvim/commit/8463b0b6b683b1d06730dc6a0977c81eb8dc092d) changes introduced weird behavior when interacting with vim-fugitive.
After doing a git commit within the nvim with the use of `vim-fugitive` there's an extra `<80>kb` character present in the notification. See screenshots below

**To Reproduce**
1. Open fugitive popup
2. Stage files
4. hit `cc` to open the commit window
3. write commit-msg and hit `wq`

**Expected Behavior**
There's no <80kb>

**Screenshots**
<img width="450" alt="Screenshot 2022-10-26 at 22 01 46" src="https://user-images.githubusercontent.com/45797239/198128265-aa44ef90-2c36-4b07-a41a-67b1416456db.png">

Before [8463b0](https://github.com/folke/noice.nvim/commit/8463b0b6b683b1d06730dc6a0977c81eb8dc092d) it looked this way
<img width="450" alt="Screenshot 2022-10-26 at 22 00 44" src="https://user-images.githubusercontent.com/45797239/198128480-a35e5464-25e2-4726-802b-d43e80b0cc10.png">

**Comment by Pheon-Dev** [comment]
@folke , can't seem to figure out why issue #142, this one kind of have some sort of similarity. I've been facing the same problem too whereby the [SHIFT] key seems to be already pressed then a notification appears whenever the key is actually pressed showing what would have been the the result of [SHIFT + ,] which is [<] as illustrated below. Note: No one pressed the [SHIFT] key, just the [,] key which in itself I mapped it to saving a file(wasn't really using it for [?] search next :-)
 
![image](https://user-images.githubusercontent.com/93865776/198388945-49740782-4e3c-4644-a9a0-24c751915390.jpeg)

**Comment by pBorak** [comment]
👍🏻  I have also noticed the issue with `<` notifications

**Comment by folke** [comment]
Check `:h shortmess`. `t` option. Standard Neovim behavior

**Comment by folke** [comment]
#142 is an nvin-notify problem, not Noice.
Your issue #99, is not an issue at all. Your issue #99 was because of a plugin.
All unrelated to this.

This is likely caused by my hack to make keys work in cmdline during substitute. But haven't yet found anything that could cause that.

**Comment by folke** [comment]
Just looked it up and `<80>kb` is indeed the internal code for `<backspace>`.
Which I here https://github.com/folke/noice.nvim/blob/ac29174bebeedb86983eea7436dabcf2b17dbc19/lua/noice/util/hacks.lua#L255

**Comment by Pheon-Dev** [comment]
Thanks for the explanation, it makes more sense now. I'll try to config my nvim-notify a bit better to avoid receiving unnecessary messages

**Comment by folke** [comment]
Once the upstream issue below is solved, this issue can be solved
- [ ] https://github.com/neovim/neovim/issues/20463

**Comment by folke** [comment]
I was able to work around the cursor issue by calling `update_screen` through **ffi**, so your issue should no longer happen
