### ISSUE TITLE
`:Notifiations` from vim-notify doesn't work as intended

### ISSUE THREAD

**Issue by msva** [folke/noice.nvim#132]
**Describe the bug**
`:Notifications` (from `vim-notify`) displays the listing within itself in notification popup, when using with noice.
As it can't fit all the possible content, and disappears after some time, and repeating calls pop in up with billios of duplicates, it is not useful to look for reading missed notifications.

It would be nice to show it in float (i prefer floats like with packer/mason/telescope) or at least split, like noice does for some other things.

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?

TUI, nightly (git head) v0.9.0-dev-69-g26c653718-dirty

**To Reproduce**
1. make some mistake in configuration, to get some tracebacks. Additionally, get some info notifications from other plugins
2. open neovim
3. wait few seconds, so notification floats disappear.
4. type `:Notifications`

**Expected Behavior**
I got float with notifications listing opened.
(without noice it opened with `print`/`echo`, so displayed similar to messages)

**Comment by msva** [comment]
Well,
`:Noice history` with `history = { view = "popup" }` in settings is **almost** what I'd like it look, but it contains both notifications and messages, and has no way (at least from what I found) to filter them...

**Comment by folke** [comment]
Notify just `prints` the notifications, so those `msg_show` events get picked up by Noice and shows them in whatever route you setup.

Would it be helpful if I add custom commands to `:Noice`?

Like you could configure for example `notifications = {event = ...}`

**Comment by folke** [comment]
You could also add a route to send messages with `min_height=20` for example to the `split` view

**Comment by msva** [comment]
> Would it be helpful if I add custom commands to `:Noice`?

it would be vary helpful, yes, thanks!

**Comment by folke** [comment]
Just pushed a new update. Check the docs https://github.com/folke/noice.nvim#%EF%B8%8F-configuration

Added deafult commands for `history`, `last` and `errors`
