### ISSUE TITLE
For those using sunjon/Shade.nvim

### ISSUE THREAD

**Issue by Pheon-Dev** [folke/noice.nvim#133]
**Describe the bug**
The prompt blips for a millisecond and defaults to top. Lualine's status line starts to misbehave upon window resizing and a message notification appears. 

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?
NVIM v0.8.0
Build Type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

**To Reproduce**
```
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "folke/noice.nvim",
        requires = {
          "MunifTanjim/nui.nvim",
          "rcarriga/nvim-notify",
        },
      },
      {
        "folke/tokyonight.nvim",
      },
      {
        "sunjon/Shade.nvim",
        config = function()
          require 'shade'.setup({
            overlay_opacity = 80,
            opacity_step = 2,
            keys = {
              brightness_up   = '<S-Up>',
              brightness_down = '<S-Down>',
            }
          })
        end
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end

_G.load_config = function()
  vim.opt.termguicolors = true
  vim.cmd([[colorscheme tokyonight]])
  require("noice").setup()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Noice and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Expected Behavior**
Prompt should only appear at the center of the screen unless it's blocking another action prompt.

**Screenshots**
![Picture_4](https://user-images.githubusercontent.com/93865776/198136819-59d3a5f5-1d3d-4809-941e-1a36f6b1855c.png)

**Noice Log**

Wed 26 Oct 2022 22:42:41 EAT
.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:226: Failed to delete line

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'nvim_buf_set_lines'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:226: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:244: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:222>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	...
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	...site/pack/packer/opt/noice.nvim/lua/noice/util/hacks.lua:92: in function 'cmd'
	...ack/packer/start/nvim-notify/lua/notify/service/init.lua:63: in function 'push'
	...site/pack/packer/opt/noice.nvim/lua/noice/util/hacks.lua:200: in function 'push'
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:223: in function 'notify'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/init.lua:204: in function 'notify'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/init.lua:248: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/init.lua:247>
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:122>

**Comment by folke** [comment]
I just pushed an update where you can add `config.smart_move.excluded_filetypes`. If shade sets an ft you can add it there. And let me know so I can add it to the defaults.

I've also made another change that now only moves out of the way, if there's more than 30% overlap of the windows, so that might actually already fix this.

**Comment by folke** [comment]
You can now also disable it with `config.smart_move.enabled = false`

**Comment by Pheon-Dev** [comment]
Cool thanks
