### ISSUE TITLE
Use vim keybindings inside rename window

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#137]
I don't know it's possible or not:)
When i want to rename something with lsp i open rename window. I would like to have opportunity use norm mode inside this window, because sometimes i want to change only one letter in the beginning of the long word and it would be useful if i can use `F{letter}` or `^` for example.

**Comment by folke** [comment]
Do you mean the inc-rename window? Or vim.ui.input window?

I'm thinking of adding vim.ui stuff to noice at some point.

**Comment by folke** [comment]
Oh wait. That's probably vim.fn.input. that can't work with normal commands, since it's basically the cmdline

**Comment by kaiphat** [comment]
Ok, if `vim.fn.input` can't do it, mb it's possible open new buffer on `lsp.rename` instead of `vim.ui.input`, like it works in harpoon plugin.

**Comment by kaiphat** [comment]
![Uploading image.png…]()

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/198269166-0ad8e354-e30e-4fff-a37a-8a954d81c6d8.png)

**Comment by folke** [comment]
Better to use https://github.com/smjonas/inc-rename.nvim

The setup for Noice on that page is outdated. Simple use `config.presets.inc_rename = true` in your Noice config

**Comment by kaiphat** [comment]
Thank you!

**Comment by igorlfs** [comment]
Hey, sorry to necrobump this issue, but was a solution ever implemented for having normal mode mappings inside `vim.ui.input`? It's what I'm missing the most, now that dressing.nvim was archived.

**Comment by kaiphat** [comment]
You can press `<C-f>` in command mode to edit text in normal mode.

**Comment by igorlfs** [comment]
> You can press `<C-f>` in command mode to edit text in normal mode. After edit press `Enter`.

Thanks! I wasn't aware it was possible to use this feature inside `vim.ui.input`. Nice catch! This suffices for my use case
