### ISSUE TITLE
Signature help covers current line

### ISSUE THREAD

**Issue by mrjones2014** [folke/noice.nvim#138]
**Describe the bug**
Signature help window covers current line (so I can't see what I'm typing), instead of being positioned one line below current line like I'd expect.

**Which version of Neovim are you using?**
Terminal, current stable (0.8.0).

**To Reproduce**

```lua
require('noice').setup({
  lsp = {
    signature = {
      enabled = true,
      opts = {
          border = { style = 'rounded' },
          win_options = {
            winhighlight = {
              Normal = 'LspFloat',
              FloatBorder = 'LspFloatBorder',
            },
          },
        },
    },
  },
})
```

**Expected Behavior**
Signature help window is placed one line _below_ the current line

**Screenshots**
![image](https://user-images.githubusercontent.com/8648891/198293548-d2262e32-6bf5-496a-9b29-34f0363a8685.png)

**Noice Log**
Nothing relevant.

**Comment by folke** [comment]
That's because you added a border. You need to also change the position

**Comment by mrjones2014** [comment]
Gotcha. This fixes it:

```lua
require('noice').setup({
  lsp = {
    signature = { enabled = true },
    hover = { enabled = true },
    documentation = {
      opts = {
        border = { style = 'rounded' },
        relative = 'cursor',
        position = {
          row = 2,
        },
        win_options = {
          concealcursor = 'n',
          conceallevel = 3,
          winhighlight = {
            Normal = 'LspFloat',
            FloatBorder = 'LspFloatBorder',
          },
        },
      },
    },
  },
})
```
