### ISSUE TITLE
Not compatible with CtrlSpace

### ISSUE THREAD

**Issue by losinggeneration** [folke/noice.nvim#140]
**Describe the bug**

When using CtrlSpace with Noice, there is an issue where when exiting out of CtrlSpace with either `Esc` or `q` something effectively runs `:resize 0`. It's possible this is an issue with CtrlSpace, however, I've been using it for years and very rarely saw this behavior. With CtrlSpace & Noice together, it happens consistently every time.

**Which version of Neovim are you using?**

```
NVIM v0.8.0-dev-1063-g2f385d17a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/harley/Source/vim/neovim/build/cmake.config -I/home/harley/Source/vim/neovim/src -I/home/harley/Source/vim/neovim/.deps/usr/include -I/usr/include -I/home/harley/Source/vim/neovim/build/src/nvim/auto -I/home/harley/Source/vim/neovim/build/include
Compiled by harley@dreamcast

Features: +acl +iconv +tui
```

**To Reproduce**

Use this config for init.lua
```lua
return require("packer").startup(function()
	use("wbthomason/packer.nvim")

	use({
		"szw/vim-ctrlspace",
		config = function()
			vim.keymap.set("n", "<c-space>", ":CtrlSpace<cr>")
			vim.opt.hidden = true
			vim.opt.termguicolors = true
			vim.opt.encoding = "utf-8"
			vim.opt.showtabline = 0
		end
	})

	use({
		"folke/noice.nvim", -- experimental UI overhaul
		event = "VimEnter",
		config = function()
			require("noice").setup()
		end,
		requires = {
			-- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
			"MunifTanjim/nui.nvim",
			-- OPTIONAL:
			--   `nvim-notify` is only needed, if you want to use the notification view.
			--   If not available, we use `mini` as the fallback
			"rcarriga/nvim-notify",
		},
	})

end)
```

1. Run the normal Packer install process
2. Open nvim
3. If there are any messages, wait for the notify window to close
4. Press `ctrl+space`
5. Press `q` or `Esc`
6. Observe that triggered something to effectively run `:resize 0`
7. From here you can reset with `:resize` but doing steps 4 & 5 will trigger it again.

**Expected Behavior**

I would expect it to keep the sizes the same.

**Screenshots**
step 2
![image](https://user-images.githubusercontent.com/5209/198363912-b41bee02-bd43-429c-b5b9-5b0d0a53d11f.png)

step 4
![image](https://user-images.githubusercontent.com/5209/198364081-27aa0591-e5bc-4205-ab7b-85a7a3cb0e29.png)

step 5
![image](https://user-images.githubusercontent.com/5209/198364156-cda06906-0e32-43bf-8aba-2ae9202c54eb.png)

**Noice Log**

No log messages

**Comment by folke** [comment]
I briefly had a look at ctrspace and they do a `:resize` in a couple of places.
It might be that Noice triggers this, since I can create windows/buffers outside of the normal neovim event loop. I could imagine situations where some plugins create windows/buffers, but dont use the buf/win number and instead always use 0. In those cases, they might do calculations on noice win/bufs.

Closing this

**Comment by losinggeneration** [comment]
Fair enough. May I suggest perhaps maintaining a place to document incompatible plugins? It could even be as simple an issue label.
