### ISSUE TITLE
notifications hijacks `q` key

### ISSUE THREAD

**Issue by msva** [folke/noice.nvim#142]
Hi there! I've faced strange situation, that if there is active notification, when I press `q` neovim closes, while normaly it just closes current buffer, and quits only if it is last buffer (I have it mapped to `Sayonara` from corresponding plugin).
Looks like it remaps `q`, but I can't confirm that, as even with active notification `:map q` returns my mapping :shrug: 

**Neovim**
TUI, nightly, v0.9.0-dev-69-g26c653718-dirty

**Comment by folke** [comment]
Only `popup` and `split` views have a default handler for `q`, but that should only close their own window.

What view do you mean?

**Comment by msva** [comment]
novermind, looks like somethng changed in [nvim-notify](https://github.com/rcarriga/nvim-notify).
I just tested without noice, but keeping only `nvim-notify`, and got same result.

Sorry for noise :grin:

**Comment by msva** [comment]
// I thought on `noice` because I saw something looked like mappings change (with `q` there too) in last commits, so didn't initially tested if it is not a nvim-notify issue, and that was my huge mistake, sorry

**Comment by folke** [comment]
I just did that after your comment here :)
Bad practice to map `<esc>` by default, so removed that one
