### ISSUE TITLE
Popup does not scroll text horizontally and "hides" it from users

### ISSUE THREAD

**Issue by bobrown101** [folke/noice.nvim#143]
**Describe the bug**
When opening a popup with long text, the popup does not go to the end of the text input and does not allow the user to scroll horizontally.

What it looks like in a popup:
<img width="1525" alt="Screen Shot 2022-10-27 at 8 28 16 PM" src="https://user-images.githubusercontent.com/2817648/198421774-218b879b-94d2-4f5b-8e2e-904a2940479e.png">

Whereas in a split it renders like:
<img width="1727" alt="Screen Shot 2022-10-27 at 8 29 40 PM" src="https://user-images.githubusercontent.com/2817648/198421904-05070d4a-9a12-4dfb-af75-c8a8cf95e85c.png">

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?
`NVIM v0.9.0-dev-183+gf44ad7538` - nightly compiled from source

**To Reproduce**
1. 
```lua
	-- Packer
        use({"MunifTanjim/nui.nvim"})
	use({
		"folke/noice.nvim",
		event = "VimEnter",
		config = function()
			require("noice").setup({
                                presets = {
                                  -- this does not redirect to split
                                  long_message_to_split = true, -- long messages will be sent to a split
                                },
                          })
		end,
                requires = {
                  "MunifTanjim/nui.nvim"
                }
	})
```
2. 
```lua
lua vim.fn.input({prompt = 'asdf', default = 'asdfadsfasdfasdfasdfadsfasdfasdfasdfadsfasdfasdfasdfadsfasdfasdfasdfadsfasdfasdfasdfadsfasdfasdfasdfadsfasdfasdfasdfadsfasdfasdf'})
```

**Expected Behavior**
The popup has a maximum width of the current window.
When the text gets too large, the popup sticks to the max width of the window, and the text scrolls.
The text of the input scrolls left and right. The cursor starts at the end of the text and the user can scroll within the existing text

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)
No logs outputted

**Comment by folke** [comment]
That window is the cmldine input window. It looks like you changed the configuration for that. It should have `size.max_width=auto`, as in the defaults. That way it will grow larger when needed.

**Comment by bobrown101** [comment]
Even if removing the configuration alltogether (using the raw defaults) this problem persists.

I think `size.max_width=auto` might be broken if the text of the input is too large.

**Comment by folke** [comment]
I was wrong. `width` should be `auto`. And `min_width` 60 or something
