### ISSUE TITLE
[ Feature Request ] Integrate scroll bar

### ISSUE THREAD

**Issue by NEX-S** [folke/noice.nvim#145]
Will noice integrate the Scrollbar like `scrollbar.nvim`?

https://github.com/petertriho/nvim-scrollbar

<img src="https://github.com/petertriho/nvim-scrollbar/raw/main/assets/search.gif" />

And maybe can add some `-` `=` to instruct the information like `diagnostics / search result` on the right side like gif above.

though noice.nvim is a fascinating plugin, if this feature can be implemented, it would be awsome :smile: !!!

**Comment by folke** [comment]
Noice already has a scrollbar implementation, but it's only used for noice windows.

I may make it opionally be used by all windows, but I'm not planning to build something like nvim-scrollbar. For that specific functionaliy, you should use that plugin ;)

**Comment by clason** [comment]
Except nothing less than https://github.com/lewis6991/satellite.nvim.

**Comment by folke** [comment]
> Accept nothing less than https://github.com/lewis6991/satellite.nvim.

Nice! Hadn't seen that one yet
