### ISSUE TITLE
Idea: hook into nvim-cmp and replace the documentation window

### ISSUE THREAD

**Issue by mrjones2014** [folke/noice.nvim#146]
**Is your feature request related to a problem? Please describe.**
The noice.nvim documentation window looks so much nicer than the nvim-cmp one, it would be awesome if we could replace it with the noice.nvim one, attached to the cmp entry window like the nvim-cmp documentation window does.

**Describe the solution you'd like**
Using nvim-cmp's event handler API you should be able to trigger noice.nvim to show/hide the documentation window whenever the cmp entry window pops open, and using the data from the callback, you should be able to position it relative to the entries window. Docs: https://github.com/hrsh7th/nvim-cmp/blob/cdb77665bbf23bd2717d424ddf4bf98057c30bb3/doc/cmp.txt#L221

**Describe alternatives you've considered**
Setting similar window settings on nvim-cmp's documentation window, unfortunately there isn't really an API to directly access that window or set options on it.

**Additional context**
nvim-cmp documentation window: \
![image](https://user-images.githubusercontent.com/8648891/198579996-3879a9de-04dc-4971-830f-9f37783ba56e.png)

vs. noice.nvim's, with collapsed/concealed markdown links etc. \
![image](https://user-images.githubusercontent.com/8648891/198580148-4a0d26e3-969b-4b36-bab8-bf8ebb0cdfbc.png)

**Comment by folke** [comment]
Great idea, but nit sure it's doable...

Also, I noticed in your screenshot that you're using an outdated version of Noice. I fixed those duplicate newlines :)

**Comment by mrjones2014** [comment]
Just updated this morning after taking the screenshot 🙂

I think it should be do-able using the event handler API that nvim-cmp provides (you can have a callback when the nvim-cmp menu opens, and the callback is passed some information about the window), but I don't have all the context about how exactly nvim-cmp or noice.nvim works.

It would likely require the end-user adding some small amount of configuration to their nvim-cmp config to hook it up to noice.nvim

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/198636682-47ca08a7-e655-4c9b-95d4-fc764a78301e.png)

Done!

```lua
  require("noice").setup({
    lsp = {
      hover = {
        enabled = true,
      },
      signature = {
        enabled = true,
      },
      message = {
        enabled = true,
      },
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
        ["cmp.entry.get_documentation"] = true,
      },
    },
    presets = {
      bottom_search = true,
      command_palette = true,
      long_message_to_split = true,
      inc_rename = true,
    },
  })
```

**Comment by mrjones2014** [comment]
Amazing, thanks! This is awesome!
