### ISSUE TITLE
`:file` doesn't print the name of the file

### ISSUE THREAD

**Issue by Integralist** [folke/noice.nvim#148]
**Describe the bug**
If I execute `:file` I'll see the Noice UI popup display `<` and no file name

<img width="428" alt="Screenshot 2022-10-28 at 17 17 51" src="https://user-images.githubusercontent.com/180050/198684860-7397feed-d020-4c49-930a-c340c79a8f50.png">

But if I do `:echo expand('%:p')` it works.

**Which version of Neovim are you using?**
0.8.0

**Comment by folke** [comment]
Check `:h shortmess` (`t` option)
