### ISSUE TITLE
disabling lsp.signature does not disable lsp.signature

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [folke/noice.nvim#149]
**Describe the bug**
Setting `lsp.signature.enabled` to false does not disable the LSP signature functionality. I also have to set `lsp.signature.auto_open.enabled` to false. e.g.:
```lua
    signature = {
      enabled = false,
      auto_open = { enabled = false },
    },
```
I assume that setting `lsp.signature.enabled` to false should completely turn off signature functionality.

**Which version of Neovim are you using?**
Nightly.
```
$ vim -v
NVIM v0.9.0-dev-162+g40791f8e8
...
```

**To Reproduce**
1. Set `lsp.signature.enabled` to false (and nothing else in the `lsp.signature` block)
2. Watch as signature details are displayed when interacting with an LSP server

**Expected Behavior**
I expected no signature behavior from Noice.

**Comment by folke** [comment]
Fixed!
