### ISSUE TITLE
Command mode keymaps are not preserved

### ISSUE THREAD

**Issue by mrjones2014** [folke/noice.nvim#15]
**Describe the bug**
I have a command-mode keymap so that when I press the up arrow, instead of normal cycling through history, it copies the current command into a Telescope `command_history` finder.

**To Reproduce**
```lua
vim.keymap.set('c', '<Up>', function()
  local search = vim.fn.getcmdline()
  vim.fn.setcmdline('') -- otherwise the command gets executed when opening the finder
  require('telescope.builtin').command_history({ default_text = search })
end)
```

Then, with `noice.nvim` replacing your cmdline with the popup window, type `:<Up>`. It will cycle through history normally instead of opening the Telescope finder.

**Expected behavior**
It respects command-mode keymaps, or alternatively, the plugin exposes a way to create custom keymaps for the cmdline popup.

**Screenshots**
N/A

**Noice log**
N/A

**Comment by folke** [comment]
I'll work on something that can be used as a work-around

**Comment by folke** [comment]
I just tested this and cmdline mappings work perfectly fine for me.

```lua
vim.keymap.set("c", "<Up>", function()
  vim.notify("Test from cmdline")
end)
```

**Comment by folke** [comment]
Your mapping also correctly opens Telescope for me.

**Comment by folke** [comment]
Make sure to update noice. Maybe there was another issue causing things to fail.

**Comment by mrjones2014** [comment]
Ah yeah. It was a bug in my config. Sorry.
