### ISSUE TITLE
Latest Noice plugin breaks the ability to get documentation window after entering one

### ISSUE THREAD

**Issue by InsigMath** [folke/noice.nvim#150]
**Describe the bug**
When I open up any type of file like a lua file if I push K I get the definiton with the new window but if I push K again to into the window and then exit and try to bring up the documentation again I get a vim/_meta:0: error where its expecting a lua string. 

**Which version of Neovim are you using?**
0.8.0 nvim nightly

**To Reproduce**
1. Open up a file, like a lua file.
2. Push K and then push K to get in the documentation popup window and then get out.
3. Push K again and you get that error notification, if you exit the file and go back it is normal.

**Expected Behavior**
You would expect the documentation window to popup again since that was the old behaviour.

**Screenshots**
![noice_hover_error](https://user-images.githubusercontent.com/2395535/198718947-c5a867f5-0812-4273-a423-aa295de20ab2.gif)

**Noice Log**
Fri Oct 28 15:42:01 2022

<details>
<summary>Noice log</summary>
<pre>
vim/_meta.lua:0: Expected lua string

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'nvim_get_option_info'
	vim/_meta.lua: in function '__index'
	vim/_meta.lua: in function ''
	vim/_meta.lua: in function '__index'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:260: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:251>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:123: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:115: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:74>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:145: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:130>
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/init.lua:104: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
</pre>
</details>

**Comment by folke** [comment]
I didn't experience that problem, but I probably fixed it. Let me know if it would still cause any issues

**Comment by InsigMath** [comment]
This works now thanks!
