### ISSUE TITLE
Weird behavior w/ nvchad

### ISSUE THREAD

**Issue by lucazz** [folke/noice.nvim#151]
**Describe the bug**
Hello there everyone, I'm having a weird error while trying to use noice.vim:
Whenever I open a file with neovim I get two distinct behaviours:

1. I'm greeted w/ 3 banner messages about`vim.lsp.handlers["textDocument/hover"]`, `vim.lsp.handlers["textDocu,ent/signatureHelp"]` and `vim.notify` being overwritten by another plugin
2. Poorly formated Workspace loading messages on the lower right side

**Which version of Neovim are you using?**
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

Here's my dotfiles: https://github.com/lucazz/dotfiles/tree/master/nvim/custom 

**To Reproduce**
1. Install nvchad
3. Install noice.vim
4. open any file with neovim

**Expected Behavior**
One should be able to use noice.vim alongside nvchard w/o issues

**Screenshots**
https://user-images.githubusercontent.com/6126301/198719312-09231736-75f6-423f-ba86-32c79b5d7ac7.mov

**Noice Log**
Here's my noice.log file: 
https://gist.github.com/lucazz/8788cb9cb322904a9910a28fdcdf3444

**Comment by folke** [comment]
The lsp progrsss is your colorscheme. Check the Noice docs on highlight groups.

the messages are there because Noice is configured to handle those, but it seems other plugins have taken over the handlers after Noice was started. Maybe lsp-saga?

So either disable those Noice components (check the docs), or disable those other plugins.

**Comment by ekokotov** [comment]
I have the same issue just with neovim + noice + ray-x/lsp_signature.nvim
<img width="948" alt="image" src="https://user-images.githubusercontent.com/11966000/199620197-c1db8cb2-c5ac-4b31-969f-f002103f4f5f.png">

**Comment by Integralist** [comment]
I've just noticed this and so I removed the lines where I was setting this in my own config to get nice rounded borders on some LSP ui things, but now I get these plain bordered hovers etc instead so not sure if Noice is supposed to be setting some nice styling for that or not, and if not, where is the appropriate place for me to put back that styling?

<img width="844" alt="Screenshot 2022-11-03 at 10 59 57" src="https://user-images.githubusercontent.com/180050/199704277-9d0e51ef-307b-48cb-b461-f8bd95681eff.png">

**Comment by Integralist** [comment]
For reference this is my configuration:
https://github.com/Integralist/dotfiles/blob/main/.config/nvim/init.lua

The initial setting of the `vim.lsp` settings happens here first:
https://github.com/Integralist/dotfiles/blob/main/.config/nvim/lua/settings/ui.lua#L7-L19

Then plugins get loaded here (files are loaded in sorted order):
https://github.com/Integralist/dotfiles/blob/main/.config/nvim/lua/plugins/init.lua#L44-L58

Then the Noice plugin (and other ui plugins are loaded here):
https://github.com/Integralist/dotfiles/blob/main/.config/nvim/lua/plugins/gui.lua

I'm not sure why this would cause the lsp hover (as per the above example) to lose styling?
