### ISSUE TITLE
Search spam

### ISSUE THREAD

**Issue by prgres** [folke/noice.nvim#152]
**Describe the bug**
After hitting multiple time n/N there is ton of the same error: `E486: Pattern not found:` and warning: `search hit BOTTOM, continuing at TOP`

**Which version of Neovim are you using?**
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

**To Reproduce**
1. `/sldkfnsdlfsdfk;`
2. nnnn

**Expected Behavior**
Only one of each notification appears

**Screenshots**
![image](https://user-images.githubusercontent.com/23465248/198730269-61e972f7-31d3-48f7-8f8f-6fdba5d30164.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

**Comment by folke** [comment]
You will get that message every ttime you do `n` when there's nothing found.
That's standard Neovim behavior. Noice doesnt do anything else. What did you expect it to do?
