### ISSUE TITLE
Command completion does not appear under cmdline view

### ISSUE THREAD

**Issue by prgres** [folke/noice.nvim#153]
**Describe the bug**
After applying recipe (https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#display-the-cmdline-and-popupmenu-together) command completion still appears as previous.

It only works when Tab is hit after colon `:` but navigation is broken ie Tab only moves one entry up and downjj

**Which version of Neovim are you using?**
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**To Reproduce**
1.
2.
3.

**Expected Behavior**
CmdLine completion menu appears like this
![image](https://user-images.githubusercontent.com/23465248/198730968-4487a246-eec0-4b53-b51e-3fec4411f9a8.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/23465248/198730479-9ec971b5-6362-4d76-8c50-231ae4dcf099.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

**Comment by folke** [comment]
That completion popup menu is not Noice.
Also, you can configure that command palette in Noice with a preset. `config.presets.command_palette = true`.

For that bar problem. Do you have `vim-sleuth` installed? That plugin messes up Nui buffers somehow.

**Comment by prgres** [comment]
Yeah, I have and disabling `vim-sleuth` resolved Tab issue. 

Back to menu, maybe I missunder something
I have this when hitting Tab after colon
![image](https://user-images.githubusercontent.com/23465248/198733221-3d861db9-c251-426a-9804-492bbd44a968.png)

But with any insertion I get this 
![image](https://user-images.githubusercontent.com/23465248/198733408-5eb8e5d3-42ad-4afa-9858-fd3ec6b3af78.png)

**Comment by folke** [comment]
The second popupmenu is **not** Noice. Do you have `cmp-cmdline`? or `wilder` installed?

**Comment by folke** [comment]
Noice is probably not what you think it is. The Noice cmdline **is the** cmdline. Not like other plugins that show a popup. Noice actually externalizes the Neovim cmdline.

So anything in the Noice cmdline is what you would have without Noice.

The popupmenu you see (the Noice one) is similar in that we **externalize** and as such replace the native pmenu.

But still as a normal cmdline, other plugins still work of course.

**Comment by prgres** [comment]
Ah okay, I get it know. The problem is with `cmp-cmdline`, thanks for your time
