### ISSUE TITLE
Some notes about the new paradigm

### ISSUE THREAD

**Issue by ranjithshegde** [folke/noice.nvim#154]
Hey Folke,

I was thinking, to avoid or redirect a lot of similar questions regarding "spam" and/or issues with other plugins, there could be some explanation about the message system and a list of known conflicting plugins

Maybe tomorrow I can write up a small post in the discussions about `:messages`, `shortmess`, `vim.notify` etc that send or control notifications to various places that are now being unified and popped up by `noice`. 

Several of these might be what people already know but pay no attention to as they show up in the message area when `cmdheight` is not 0. But now as noice pops them up, users are alarmed.

Maybe you could link it in the readme once I post it?

**Comment by folke** [comment]
That would be great!

The Wiki might also be a good place for that info.

**Comment by ranjithshegde** [comment]
Will close this issue to not take space from relevant stuff. 

Will write something up tomorrow

**Comment by folke** [comment]
Awesome, thanks!

**Comment by ranjithshegde** [comment]
I have a draft ready. 
Cant for the life of me figure out how to send a PR to wiki

So, I have just cloned the wiki, changed the `remote` and created branches+commits. 
Will figure out what to do later today. I am sure when I figure it out I will feel stupid for not knowing such a simple thing.

**Comment by folke** [comment]
I've never done that before myself, so no idea :)

Thank you for documenting this!

I've maed some changes to health checks earlier today.

When another plugin overrode something, we'll now show a message that mentions the plugin name, file and line. And also how to disable the functionality in Noice

**Comment by ranjithshegde** [comment]
@folke 
Here is the link to the first draft

https://github.com/ranjithshegde/noice.nvim/wiki/A-Guide-to-Messages

I found this answer on stack that explains what the owner of the repo needs to do to merge it

https://stackoverflow.com/a/56810747

**Comment by folke** [comment]
Looks really great!

Some notes:
- Your fork doesn't seem to have the original pages, so not sure how I can eventually merge that.
- For showmode, maybe also add the statusline component? https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages
- the section on LSP progress is not ideal, since that code snippet will override the Noice listener, so should be made very clear that they need to disable config.lsp.progress for that. Also worth mentioning that diagnostics config for update_on_insert. from that earlier issue.

Thanks again!

**Comment by ranjithshegde** [comment]
1. For some reason the forks dont pull in the wiki. Cant seem to understand how.
2. Will add showmode notes
3. Agree, it does override. I will make that explicit, and also add the diagnostics note

**Comment by ranjithshegde** [comment]
This link might be of interest
https://gist.github.com/larrybotha/10650410

**Comment by folke** [comment]
I think I was able to merge it all, but had some conflicts in the other wiki pages. Not sure I manged to get everything there.

Thanks again for doing this!

**Comment by folke** [comment]
I believe you need to
