### ISSUE TITLE
Error when save and quit buffer or tab

### ISSUE THREAD

**Issue by CRAG666** [folke/noice.nvim#155]
Your plugin is incredible.After some updates every time I close a buffer this error occurs, on other occasions noice does not work
![image](https://user-images.githubusercontent.com/34254373/198754408-f752870a-bdb3-4fb3-a84e-b86d0854f8ca.png)

**Comment by folke** [comment]
This should not happen. I can suppress the error, but that would just mask the problem.

Can you add some of the last logs? `:Noice log`

**Comment by CRAG666** [comment]
[noice.log](https://github.com/folke/noice.nvim/files/9894786/noice.txt)

**Comment by CRAG666** [comment]
![imagen](https://user-images.githubusercontent.com/34254373/199076159-0417cc16-30b6-4925-a4a0-d469e4949762.png)
other error

**Comment by folke** [comment]
Cant reproduce. Please create a minimal.lua https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

That last error should never happen. Unrelated to Noice. Some lsp server or plugin is submitting progress info without a client_id?

**Comment by CRAG666** [comment]
> Cant reproduce. Please create a minimal.lua https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue
> 
> That last error should never happen. Unrelated to Noice. Some lsp server or plugin is submitting progress info without a client_id?


Maybe it's null-ls but maybe I'm not sure

**Comment by gennaro-tedesco** [comment]
Interestingly enough I (sometimes) get the same behaviour (of the first screenshot: "invalid window id") when moving buffers around from floating windows. Let me explain: with modern fuzzy finders (I use `fzf-lua`) you can list your buffers (opening such list in a floating window) and associate actions upon them via keymaps, for instance opening it in a split window, editing it, deleting it and so forth. When doing so I sometimes get the many errors as in the original question, but I haven't been able to reproduce it consistently.

**Comment by CRAG666** [comment]
> Echo to @gennaro-tedesco message. Same issue here, but unable to reproduce. cry It happens usually when I start to split windows and open new tabs.

Is exactly my workflow

**Comment by folke** [comment]
Yesterday, I fixed an issue that seems related to this in https://github.com/folke/noice.nvim/commit/a8402e84c1923885896ee83eefb0f492a9f9b620

Please let me know if this issue still happens

**Comment by CRAG666** [comment]
![imagen](https://user-images.githubusercontent.com/34254373/201106812-020a6f65-f64d-463e-8204-af532b92e3b9.png)
@folke

**Comment by CRAG666** [comment]
![imagen](https://user-images.githubusercontent.com/34254373/201107103-b984f1d2-1b08-4379-a78f-e97b3eea2f38.png)
This only happens if I use noise
I am currently using Neovim 0.9.0

**Comment by folke** [comment]
@CRAG666 what is your Noice config?

**Comment by CRAG666** [comment]
@folke 
![imagen](https://user-images.githubusercontent.com/34254373/201365457-af0ffb8d-3558-4a61-b7de-92ee55ef537c.png)

**Comment by folke** [comment]
I would really need to have a way to reproduce this. I've never even once seen such an error.

**Comment by CRAG666** [comment]
I could try my configuration
@folke  this is my config
https://github.com/CRAG666/dotfiles/tree/master/config/nvim
