### ISSUE TITLE
Blank line at the top(or  bottom) of lsp window and no way remove it

### ISSUE THREAD

**Issue by leaxoy** [folke/noice.nvim#158]
### Hover
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/8556349/198812707-a6b2451c-fd2a-4dca-a899-05a031949a66.png">

### Signature
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/8556349/198812735-6adf74d3-32c0-4522-a9e0-be0dd0c9911c.png">

### Completion
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/8556349/198812762-639c6d49-b0cb-41d7-8666-8d81cbd46d76.png">

**Comment by pBorak** [comment]
I think those blank lines aren't that blank after all. Those are code blocks with language not visible in the markdown preview. Nevertheless, it would be good to get rid of them :D

<img width="378" alt="Screenshot 2022-10-29 at 09 22 05" src="https://user-images.githubusercontent.com/45797239/198819367-1909d72a-090d-4994-bf32-90dcbdac683c.png">

**Comment by leaxoy** [comment]
You are right, that makes sense.

**Comment by folke** [comment]
In the default Neovim lsp markdown renderer, we strip the begininig and end of code blocks and use `syn-region` to highlight the syntax.

The new Noice markdown renderer uses Treesitter under the hood, since it is by far superior in terms of highlighting and concealing, but the Treesitter highlighter currently doesn't support highlighting regions.

I'm planning to make a PR upstream to make this possible.

Once that's done, I can use that to strip those lines.

**Comment by leaxoy** [comment]
Another issue maybe also related to this.
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/8556349/198823970-48cb0752-5926-42d0-a92a-1f44ee7664f4.png">
The last row in this case is a markdown link. 
Window's width is not rendering correctly.
It's should same with the length second last row.

**Comment by folke** [comment]
There's no way to caculate the concealed str width as far as I know. So that's why the window width is wider

**Comment by leaxoy** [comment]
Indeed, it's a small problem, does't affecting the rest of the awesome features

**Comment by max397574** [comment]
couldn't this be done with injections @folke or have I missunderstood something?

**Comment by max397574** [comment]
I thought with the "highlight a region" you meant sth like injections

**Comment by TomLebeda** [comment]
Sorry to comment on an old issue, but what is the current state of this? 

Judging by the "Closed" status I guess it's solved somehow, but I can't seem to configure it properly. 

I've been trying to figure it out for several hours now, but I still get the empty (concealed) lines in the hover pop-ups (in Rust, with rustaceanvim) no matter what configuration I try. 

Right now I use the default config that is used in LazyVim.
