### ISSUE TITLE
"Breaking out Noice into new plugins"

### ISSUE THREAD

**Issue by barrett-ruth** [folke/noice.nvim#159]
I notice [here](https://www.reddit.com/r/neovim/comments/yfqtoi/comment/iu5dw4h/?utm_source=share&utm_medium=web2x&context=3) you mention considering to break out noice.nvim into several plugins.

This prospect is very appealing to me as currently I'd just use noice.nvim for the amazingly improved markdown rendering, which I definitely think is unique enough to warrant it being separated out into another plugin. Currently noice.nvim is just not worth the installation for me because I would be ignoring 99% of its functionality as I'd only use this feature.

So while you did make that comment only 10 hours ago (:D), how high is that on your priority list? If not too low, is there any way I can help jumpstart the process?

**Comment by folke** [comment]
Not planning to do this soon. As I mentioned I want the code Noice code base to settle a bit first.
