### ISSUE TITLE
Scroll in hover without enter

### ISSUE THREAD

**Issue by lvim-tech** [folke/noice.nvim#161]
How to scroll in lsp hover without enter? In lsp signature too. Thanks.

**Comment by folke** [comment]
Haven't documented this yet, but you can use something like the below:

```lua
  vim.keymap.set("n", "<c-f>", function()
    if not require("noice.source.lsp").scroll(4) then
      return "<c-f>"
    end
  end, { silent = true, expr = true })

  vim.keymap.set("n", "<c-b>", function()
    if not require("noice.source.lsp").scroll(-4) then
      return "<c-b>"
    end
  end, { silent = true, expr = true })
```

**Comment by lvim-tech** [comment]
`require("noice.source.lsp").scroll(4)` - is this defined?

**Comment by folke** [comment]
Damn, should be without source. Will fix the docs!

**Comment by folke** [comment]
https://github.com/folke/noice.nvim#lsp-hover-doc-scrolling

**Comment by gennaro-tedesco** [comment]
Excuse me for commenting on a closed issue: using the above I get "attempt to call a nil value (scroll)", which leads me to think the `scroll` method isn't exported out from `noice.lsp` (`init.lua`) module? Is this working for other users, am I making a silly mistake in the configuration?

**Comment by folke** [comment]
@gennaro-tedesco my bad. Did some refactoring on the lsp code and forgot to export the scroll function. Should be fixed now

**Comment by gennaro-tedesco** [comment]
While I no longer see the error now, I also do not get the scrolling motion in the hover. Is it working for you? Or perhaps I misunderstood: this is for the hover `K`, namely hover on function and scroll (not for the completion menu window, whose scrolling is working fine), is it not?

**Comment by folke** [comment]
@gennaro-tedesco please see https://github.com/folke/noice.nvim/issues/210
