### ISSUE TITLE
Optionally show lsp hover on mouse move

### ISSUE THREAD

**Issue by folke** [folke/noice.nvim#163]
We should make it possible to hover with the mouse for hover docs

**Comment by folke** [comment]
Not sure what I was thinking, but that's impossible :)

**Comment by seblj** [comment]
Still early, but if https://github.com/neovim/neovim/pull/21531 gets merged, then this should be possible :)

**Comment by ryo33** [comment]
I want to join in to implement this feature! If rich mouse hover experiences are realized in the Neovim community, I could recommend Neovim to someone who passively uses so-called IDEs.

**Comment by max397574** [comment]
you can just use the snippet from the linked pr
```lua
local util = require('vim.lsp.util')

local function make_position_param(window, offset_encoding)
    window = window or 0
    local buf = vim.api.nvim_win_get_buf(window)
    local row, col

    local mouse = vim.fn.getmousepos()
    row = mouse.line
    col = mouse.column

    offset_encoding = offset_encoding or util._get_offset_encoding(buf)
    row = row - 1
    local line = vim.api.nvim_buf_get_lines(buf, row, row + 1, true)[1]
    if not line then
        return { line = 0, character = 0 }
    end
    if #line < col then
        return { line = 0, character = 0 }
    end

    col = util._str_utfindex_enc(line, col, offset_encoding)

    return { line = row, character = col }
end

local make_params = function(window, offset_encoding)
    window = window or 0
    local buf = vim.api.nvim_win_get_buf(window)
    offset_encoding = offset_encoding or util._get_offset_encoding(buf)
    return {
        textDocument = util.make_text_document_params(buf),
        position = make_position_param(window, offset_encoding),
    }
end

local hover_timer = nil
vim.o.mousemoveevent = true

vim.keymap.set({ '', 'i' }, '<MouseMove>', function()
    if hover_timer then
        hover_timer:close()
    end
    hover_timer = vim.defer_fn(function()
        hover_timer = nil
        local params = make_params()
        vim.lsp.buf_request(
            0,
            'textDocument/hover',
            params,
            vim.lsp.with(vim.lsp.handlers.hover, {
                silent = true,
                focusable = false,
                relative = 'mouse',
            })
        )
    end, 500)
    return '<MouseMove>'
end, { expr = true })
```

I think there is no need to include this in this plugin
but in the end it's folkes decision

**Comment by seblj** [comment]
I think there may be some small issues with the snippet in the PR if I remember correctly (don't remember if I edited it), but it's a good starting point at least

**Comment by max397574** [comment]
quite sure it worked for me

**Comment by seblj** [comment]
> quite sure it worked for me

Yes it works okay, but I found some edge cases where it prompted an error, but I don't remember exactly when that happens, but nice to know that it worked for you🙌

**Comment by ryo33** [comment]
It might be good to have a unified interface for various plugins to improve performance through concentration and hover experience through a single configuration. I'm going to make a small prototype myself. I hope someone is interested.
