### ISSUE TITLE
Feature Request: Ability to render code blocks in hover and signature

### ISSUE THREAD

**Issue by quantum-booty** [folke/noice.nvim#169]
![image](https://user-images.githubusercontent.com/28958399/198829998-14d7dcec-5974-445a-8677-8eeb3404449e.png)

**Comment by folke** [comment]
Do you have the markdown and markdown_inline treesitter parser installed?

**Comment by quantum-booty** [comment]
> Do you have the markdown and markdown_inline treesitter parser installed?

I have markdown install but not markdown_inline, installing markdown_inline has fixed my issue!
