### ISSUE TITLE
Ability to render escaped underscore character

### ISSUE THREAD

**Issue by quantum-booty** [folke/noice.nvim#170]
![image](https://user-images.githubusercontent.com/28958399/198830655-c968f91a-f5ef-4777-93da-969ca3e7ec87.png)

I expect these \\_ characters to be displayed like this:
![image](https://user-images.githubusercontent.com/28958399/198830703-f3446e72-a05f-4d0a-a400-0d21f917c987.png)

**Comment by folke** [comment]
I'll see if I can fix that upstream https://github.com/nvim-treesitter/nvim-treesitter/blob/287ffdccc1dd7ed017d844a4fad069fd3340fa94/queries/markdown_inline/highlights.scm#L28
