### ISSUE TITLE
Bottom padding for `hover` when the server doesn't do it correctly

### ISSUE THREAD

**Issue by ofirgall** [folke/noice.nvim#171]
Some servers doesn't padding the bottom at `hover`.

No padding - [lua-language-server](https://github.com/sumneko/lua-language-server):
![nopad](https://user-images.githubusercontent.com/4954051/198831044-5241fdda-5f5e-499b-b1a9-1a6d70bdab6c.png)

Padding - [rust-analyzer](https://github.com/rust-lang/rust-analyzer)
![pad](https://user-images.githubusercontent.com/4954051/198831074-0fb89a9f-6b3f-428b-bdcd-801fff9e8886.png)

**Comment by folke** [comment]
We don't add any pdding by default. The empty line you see is a concealed code block

**Comment by folke** [comment]
See https://github.com/folke/noice.nvim/issues/158
