### ISSUE TITLE
[Bug] Don't show vim-sleuth issues popup, when popup menu disabled

### ISSUE THREAD

**Issue by Dimfred** [folke/noice.nvim#172]
Hey, it would be great if you could disable the vim-sleuth warning when the popup menu is disabled anyways :)

![image](https://user-images.githubusercontent.com/29997904/198832405-b37aa76a-8ea0-4a9a-94f7-44d3a7c7dd02.png)
I guess this will be it?

Btw I love your work! You're a monster! Keep it up

**Comment by folke** [comment]
I just removed the health check altogether and set `g:sleuth_noice_heuristics=0` to disable sleuth in Noice buffers
