### ISSUE TITLE
recommendation on how to handle "disable the other plugin" messages

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/noice.nvim#173]
[This commit](https://github.com/folke/noice.nvim/commit/84dcdf3bf453ae1bc4d05a2110e3202e1eb4eafa) introduced warning messages whenever we configure Noice to take over handlers from LSP or notify. In particular, the messages suggest along the lines of

>  Either disable the other plugin or set `config.<optiosn>= false` in your **Noice** config.

what is the intended behaviour here? Does this mean that whenever Noice is active (namely, if these options are active) one needs to disable the other plugins (notify, cmp, lsp) altogether? Wouldn't this however introduce a behaviour of Noice claiming to be explicitly incompatible with the plugins, so it is _either_ Noice _or_ the others (and they cannot be used together)? What is the suggested course of actions here?

(I find it a little strange to have to disable the other plugins or those handlers altogether, because they may be still needed for other custom functions that users defined or external plugins).

**Comment by folke** [comment]
If you tell noice to handle `vim.notify` for example, and later we see another plugin took that over, then obviously the noice handler wil no longer work.

Is up to the user to decide how to handle the situation.

I'm sure things like that happen frequently in other plugins, but they don't have any checks in place. And that can obviously lead to issues.

So again. Totally up to you. 

Out of curiosity what did you get this for?

**Comment by gennaro-tedesco** [comment]
> Out of curiosity what did you get this for?

I am getting this messages upon starting neovim, without even exacuting anything or opening any files. In particular I am using the configuration shown in the README
```
 override = {
      ["vim.lsp.util.convert_input_to_markdown_lines"] = false,
      ["vim.lsp.util.stylize_markdown"] = false,
      ["cmp.entry.get_documentation"] = false,
    },
```
which makes me puzzle: according to your comment above

> and later we see another plugin took that over, then obviously the noice handler wil no longer work.

does this mean that either lsp/cmp or noice must be enable, and not both of them at the same time? See screenshot below


https://user-images.githubusercontent.com/15387611/198841128-3bcf3cda-41ae-4917-be85-663c96aa3391.mov

(in particular about the `vim.lsp/cmp` handlers). So while I do agree that if one explicitly invokes a handler from another plugin to take over, warning messages must occur, I would like to better understand why these messages are generated upon start-up in the context of lsp/cmp.

**Comment by folke** [comment]
ok, so there was a bug in the healthcheck.
Apparently `plugged` doesn't use standard Neoivm pack site paths so detection went wrong. Should be fixed.

All those handlers are already Noice, so you should be good :)

**Comment by gennaro-tedesco** [comment]
I confirm it's fixed, thank you for looking into it!
