### ISSUE TITLE
LSP status stuck even though the LSP server is restarted

### ISSUE THREAD

**Issue by cenk1cenk2** [folke/noice.nvim#175]
Thank you @folke for your all work on many plugins that I dearly enjoy!

**Describe the bug**
LSP status gets stuck whenever there is a error coming from the language server, even though the language server has been restarted.

**Which version of Neovim are you using?**
Nightly

**To Reproduce**
1. On a golang project, manipulate the go.mod file to make the language server throw an error.
2. Tidy the vendor files.
3. Restart the LSP language server.

**Expected Behavior**
Language server should go away whenever the LSP is restarted.

**Screenshots**
![image](https://user-images.githubusercontent.com/26881592/198841244-7ed767a1-6ada-400b-a60f-2d06c1a088c5.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Nothing related, since everything works as expected in the UI form.
</pre>
</details>

**Comment by folke** [comment]
I'm not a Go developer, so you'll need to be more specific in how I can reproduce this error.

**Comment by cenk1cenk2** [comment]
That is totally okay.

As I understand it, the issue is compared to other language servers `gopls` sends out an exit code that is not 0 when `LspRestart` request comes in, it does not start in place the existing instance so neovim restarts manually.

![image](https://user-images.githubusercontent.com/26881592/200291503-5b94bdcd-34d4-4952-9c3d-5851e91c613f.png)

When the `go.mod` file is updated manually, there is an implicit error raised by the language server where it says that the mod file is out of date. Noice as expected propagates this issue to the user through the UI.
![image](https://user-images.githubusercontent.com/26881592/200292068-102d2744-3b04-415c-bb56-f49c2b733634.png)

But when the language server is explicitly reloaded to reflect the changes on the mod file, by tidying the mod file therefore reinstalling the dependencies, it does not pick this automatically so it needs to be restarted.

Even though the language server works properly after being restarted, Noice still picks up the error from the old instance indefinitely, causing the neovim to slow down and constantly show the given message. 

I do not think this issue affects many language servers, because this is not the usual flow.

**Comment by cenk1cenk2** [comment]
If you have golang installed, you can reproduce it as follows:

1. Please pull the repository: https://gitlab.kilic.dev/docker/seafile-cli
2. `make install` to get the dependencies first.
3. Open up file `go.mod`
4. Change version of `gitlab.kilic.dev/libraries/plumber/v4 v4.16.0` manually to `v4.15.0`
5. You should see the language server error now.
6. `make tidy` to tidy and install your overwritten version
7. `:LspRestart` to fix the language server.
8. The error should be stuck but the language server should now work properly.

**Comment by folke** [comment]
Should be fixed now. Let me know if you have any more issues.

**Comment by cenk1cenk2** [comment]
Thanks, @folke, I can confirm this fixes the related issue.
