### ISSUE TITLE
Dont omit snippet nodes in hover

### ISSUE THREAD

**Issue by ranjithshegde** [folke/noice.nvim#178]
**Describe the bug**
With the new (and incredible) `convert_lines_to_markdown` option, the hover information for snippet malfunctions.
Many snippets dont have the `description` key which means the actual snip definition with nodes and code is displayed in help.

With the above option set to true, its all hidden away. 
![noice](https://user-images.githubusercontent.com/10258296/198867244-b8a39a14-bea3-478d-9cac-f0889fe6e89a.png)

Perhaps it could use a similar parsing function concept as `noice.text.markdown.html_entities`?

**To Reproduce**
1. Configure noice lsp overrides (set to true)
2. use snippet engine + friendly snippets (just the best test case as it contains verbose snippets with descriptions to undocumented snippets)
3. type any snippet and hover

**Expected Behavior**
![snip](https://user-images.githubusercontent.com/10258296/198867318-edfc8bf0-ac63-454a-ac0f-92e0e36c17fd.png)

**Comment by folke** [comment]
Will be fixed soon :)

![image](https://user-images.githubusercontent.com/292349/200257750-e40b5e58-bb69-4504-8585-5ca96271397a.png)
