### ISSUE TITLE
Notification appears folded

### ISSUE THREAD

**Issue by nick4tech** [folke/noice.nvim#18]
**Describe the bug**
The stats notification will be folded unless I disable code folding with `set nofoldenable`.

**To Reproduce**
Enable code folding with `set foldenable`
Execute `Noice stats`

**Expected behavior**
I should see the stats in the notify window

**Screenshots**
![image](https://user-images.githubusercontent.com/6836442/193941280-799dcb54-7d76-4bdf-a0ab-3a0e657bb4db.png)

**Comment by Shougo** [comment]
Please create the minimal init.vim.
