### ISSUE TITLE
"max_width" and "max_height" support percentage string

### ISSUE THREAD

**Issue by adoyle-h** [folke/noice.nvim#184]
The size of view:

```
size = {
    max_height = '50%',
    max_width = '50%',
    width = 'auto',
    height = 'auto',
}
```

**Comment by max397574** [comment]
would perhaps make more sense to use a float number

**Comment by adoyle-h** [comment]
noice uses nui to [show popups](https://github.com/folke/noice.nvim#-views). The nui supports [`number` or `percentage string` or `table` for size](https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/layout#size).

**Comment by folke** [comment]
@adoyle-h the `max_width` and `max_height` options are added by Noice. Will see to upstream those and make it so we can have percentages as well

**Comment by adoyle-h** [comment]
@folke Noice calculate the width. `size.width = minmax(size.min_width, size.max_width, dim.width)`
https://github.com/folke/noice.nvim/blob/d0eea152566c1f7e15eb297959e4efbd1420a11c/lua/noice/util/nui.lua#L198-L201

**Comment by adoyle-h** [comment]
Remove stale label
