### ISSUE TITLE
Multiple possible "jump to defintion" tags preview is broken

### ISSUE THREAD

**Issue by Philwi** [folke/noice.nvim#185]
**Describe the bug**
There is the "jump to definition" feature, where I can jump to a ctag. When there are multiple ctags, there is a list of possible definition places. With noice the tag preview is broken:
![Screenshot_20221031_221959](https://user-images.githubusercontent.com/32922962/199114177-27d81b01-3edb-4e97-9274-7d4d9d0b88a9.png)

Sometimes there is a floating overlay with no text when I choose a tag. Sometimes if there is no tag available there is this overlay as well:
![image](https://user-images.githubusercontent.com/32922962/199114391-8c2283b1-aca7-4dc8-bc1a-3efb323a0229.png)

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?
```
❯ nvim -v
NVIM v0.8.0
```

**To Reproduce**
1. use jump to definition with multiple possible entries

**Expected Behavior**
well formatted output of the ctags entries

**Screenshots**

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

**Comment by folke** [comment]
Can't reproduce. please provide a minimal intit. https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by Philwi** [comment]
Hey I created a repository with the minimal dependencies to occur: https://github.com/Philwi/noice-tag-issue-setup
And there is the same issue:
![image](https://user-images.githubusercontent.com/32922962/200355993-9a5ad3e5-6b95-4ec2-a48a-30eebdcedbb5.png)

**Comment by folke** [comment]
That's not a minimal setup. I need one file, as the one on the wiki.

**Comment by doitian** [comment]
I can reproduce when noice has loaded nui.

<details><summary>Details</summary>
<p>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
  spec = {
    { "MunifTanjim/nui.nvim", lazy = true },
    {
      "folke/noice.nvim",
      event = "VeryLazy",
      opts = {},
    },
  },
})
```

</p>
</details>
