### ISSUE TITLE
Floating Status Line Showing Running Events

### ISSUE THREAD

**Issue by Pheon-Dev** [folke/noice.nvim#186]
**Is your feature request related to a problem? Please describe.**
Whenever one is using macros, it's hard to tell whether it is recording or for instance one starts a macro and forgets it's still recording.

**Describe the solution you'd like**
Heavily inspired solution from [incline](https://github.com/b0o/incline.nvim) would be noice.

**Describe alternatives you've considered**
Override [incline](https://github.com/b0o/incline.nvim) in an instance of a macro or show it in the mini, like a persistent fidget.

**Additional context**

**Comment by ranjithshegde** [comment]
I am not familiar with incline, but there are multiple solutions

Please check [this](https://github.com/folke/noice.nvim/wiki/A-Guide-to-Messages) page of the wiki, specifically `showmode` section. You can customize that snippet to show the output in any `view` you want

**Comment by Pheon-Dev** [comment]
Okay cool, will give it a try. Incline just hovers above the winbars, far right showing the file name

**Comment by Pheon-Dev** [comment]
Exactly what I was looking for, I should have done more research.  Thanks
```
require("lualine").setup({
  sections = {
    lualine_x = {
      {
        require("noice").api.statusline.mode.get,
        cond = require("noice").api.statusline.mode.has,
        color = { fg = "#ff9e64" },
      }
    },
  },
})
```
