### ISSUE TITLE
Hover not formatted correctly with `svelte-language-server`

### ISSUE THREAD

**Issue by vishalbalaji** [folke/noice.nvim#187]
**Describe the bug**
There are no closing triple-backticks in the content for the hover window for svelte-language-server, which messes with the formatting of the content. I encountered this when using Typescript with Sveltekit.

**Which version of Neovim are you using?**
v0.9.0-dev-155+g771824128

**To Reproduce**
1. Initialize a `svelte` or `sveltekit` app.
2. Make sure that the `svelte-language-server` is installed and running.
3. Open any `.svelte` file in the project, create a variable and run `lua vim.lsp.buf.hover()` with the cursor on the variable.

**Expected Behavior**
The code snippet within the hover window has closing triple-backticks and thus is formatted properly.

**Screenshots**
![2022-11-01_19:30:22_scrot](https://user-images.githubusercontent.com/36506250/199253796-5aa76e43-1a72-49b1-897a-75ea054bc0f7.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Noice log not included as it exceeds comment max length.
</pre>
</details>

**Comment by folke** [comment]
Works for me
![image](https://user-images.githubusercontent.com/292349/200261953-d02356a1-36bc-4362-b16c-d7e4748d6d63.png)

Are you sure that hover is Noice? Noice hovers don't have borders by default.

Please provide a minimal.lua https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by vishalbalaji** [comment]
Works now after updating. Sorry for the trouble.
