### ISSUE TITLE
Command line enabled = false, does not work.

### ISSUE THREAD

**Issue by MeiWagatsuma** [folke/noice.nvim#191]
**Describe the bug**
The noise command line keeps popping up even when "enable=false" is set.

**Which version of Neovim are you using?**
Nightly.

**To Reproduce**
```
-- init.lua
require('packer').startup(function(use)
  use { 'wbthomason/packer.nvim' }

  use { 'MunifTanjim/nui.nvim' }
  use { 'rcarriga/nvim-notify'  }
  use { 'folke/noice.nvim' }
end)

require("notify").setup()
require("noice").setup({
	cmdline = {
    enabled = false, -- Can't work this!!
  },
})
```

**Noice Log**
I tried reproducing the bug by deleting the log, but the :Noice log remained empty afterward.

**Comment by Gordin** [comment]
You can't disable the cmdline if you have messages enabled, you need to disable both if you don't want "cmdline". From the README:
```lua
  messages = {
    -- NOTE: If you enable messages, then the cmdline is enabled automatically.
    -- This is a current Neovim limitation.
    enabled = true
    ...
  },
```
You probably want this though: Set `cmdline.view` to `"cmdline"` instead of the default `"cmdline_popup"`, then you'll get the default command line 
```
cmdline = {
  view = "cmdline",
  enabled = true
},
```

**Comment by MeiWagatsuma** [comment]
I'm sorry. I missed that comment! I'm going to close this issue.

But I want to disable the command line while enabling messages. Because it conflicts with a [gelguy/wilder.nvim](https://github.com/gelguy/wilder.nvim)...
