### ISSUE TITLE
"Transparent" cmdline popup

### ISSUE THREAD

**Issue by Gordin** [folke/noice.nvim#192]
**Is your feature request related to a problem? Please describe.**
I would like to remove the background colors from all highlight groups for the cmdline popup, to only have a border and otherwise the backgroud color of whatever colorscheme I'm using. Kinda like in the screenshot, just with the icons in the popup also without background, I didn't figure out how to do that.

![WindowsTerminal_iXuX9ErKfC](https://user-images.githubusercontent.com/118403/199630047-a690697d-5611-4e67-87e6-bfe9073c29f4.png)

Right now it looks like this (with gruvbox theme): 
![image](https://user-images.githubusercontent.com/118403/199630308-2b838d2f-1dd2-479f-8b13-56836dc5510e.png)

I found this issue #126 about not being able to set `FloatBorder`, and I tried using your solution of overriding `config.cmdline.opts`. This works and I can set the highlight group to something without a background, but now all commandline popups also have the same foreground color too.

What I want is the foreground color to match with the mode (yellow for search, blue for command), but without background color.

**Describe the solution you'd like**
I would like to either have a `no_background` option under `cmdline_popup` that just turns off all background colors in the popup, OR
some way to set foreground and background colors (that can be `nil`) for each different type of cmdline popup (`/` or `:`) OR
some way to just set highlight groups directly for the different kinds of popups

**Describe alternatives you've considered**
I tried just setting different values to the used highlight groups, but this didn't work because they are generated, and I wasn't able to figure out what the groups were called in the end and figured it would be useless anyway, because noice might just reset them.

**Comment by 1612492** [comment]
I also want to have `no_background` option for mini view

**Comment by gennaro-tedesco** [comment]
> This works and I can set the highlight group to something without a background

From here it seems you have indeed succeeded in "removing" the colour for `FloatBorder` (namely setting the corresponding highlight group to your background colour).

> What I want is the foreground color to match with the mode (yellow for search, blue for command), but without background color.

Then you can just re-assign the highlight groups for the single commands: I do something along the lines of
```
local noice_hl = vim.api.nvim_create_augroup("NoiceHighlights", {})
local noice_cmd_types = {
	CmdLine = "Constant",
	Input = "Constant",
	Lua = "Constant",
	Filter = "Constant",
	Rename = "Constant",
	Substitute = "Define",
	Help = "helpVim",
}
vim.api.nvim_clear_autocmds({ group = noice_hl })
vim.api.nvim_create_autocmd("BufEnter", {
	group = noice_hl,
	callback = function()
		for type, hl in pairs(noice_cmd_types) do
			vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder" .. type, {})
			vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder" .. type, { link = hl })
		end
		vim.api.nvim_set_hl(0, "NoiceConfirmBorder", {})
		vim.api.nvim_set_hl(0, "NoiceConfirmBorder", { link = "Constant" })
	end,
})
```
(you can check my noice config [here](https://github.com/gennaro-tedesco/dotfiles/blob/master/nvim/lua/plugins/noice.lua))

As you can see from the screenshot below, each single mode has its own colours: is this what you are after?


https://user-images.githubusercontent.com/15387611/200088998-a51b7cfa-c58c-47e4-876d-d9475e3085f8.mov

**Comment by Gordin** [comment]
@gennaro-tedesco Yes, this is what I was looking for :) I added `Search` to your code and and also set the `NoiceCmdlineIcon...` group, because for me that had a wrong background as well. I also made 2 highlight groups based of stuff from my colorscheme, removed the background, and used those. 



```lua
local search = vim.api.nvim_get_hl_by_name("Search", true)
vim.api.nvim_set_hl(0, 'TransparentSearch', { fg = search.foreground })

local help = vim.api.nvim_get_hl_by_name("IncSearch", true)
vim.api.nvim_set_hl(0, 'TransparentHelp', { fg = help.foreground })

local cmdGroup = 'DevIconLua'
local noice_cmd_types = {
  CmdLine    = cmdGroup,
  Input      = cmdGroup,
  Lua        = cmdGroup,
  Filter     = cmdGroup,
  Rename     = cmdGroup,
  Substitute = "Define",
  Help       = "TransparentHelp",
  Search     = "TransparentSearch"
}

local noice_hl = vim.api.nvim_create_augroup("NoiceHighlights", {})
vim.api.nvim_clear_autocmds({ group = noice_hl })
vim.api.nvim_create_autocmd("BufEnter", {
  group = noice_hl,
  callback = function()
    for type, hl in pairs(noice_cmd_types) do
      vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder" .. type, { link = hl })
      vim.api.nvim_set_hl(0, "NoiceCmdlineIcon" .. type, { link = hl })
    end
    vim.api.nvim_set_hl(0, "NoiceConfirmBorder", { link = cmdGroup })
  end,
})
```

I still think it would be nice if we just could do something like this, then we wouldn't have to create our own autocommands, when Noice can just use the specific highlight groups in the first place.
```lua
local Cmdlines= {     
  Normal = "ABC",    
  FloatBorder = "XYZ"
}
local Searches= {     
  Normal = "OtherStuff",    
  FloatBorder = "OtherBorder"
}                   
...
require("noice").setup({
  cmdline = {
    format = {
      cmdline     = { pattern = "^:", winhighlight = Cmdlines, ... },
      search_down = { pattern = "^/", winhighlight = Searches, ... },
      search_up   = { pattern = "^%?", winhighlight = Searches, ... }
    },
    ...
  }
...
```

**Comment by gennaro-tedesco** [comment]
The autocommands are just to ensure that the groups are cleared up, should they have been assigned in other places of the configurations first. It should very well work without augroups if there is no other command/assignment taking precedence before up above (I just have a habit to assign highlight groups via autocommands because with old Vimscript it was unclear to me what was loaded before or after: I agree it's a bad habit, try and see if you get the same results by just assigning the highlight groups explicitly in the configs).

**Comment by Gordin** [comment]
Hm, seems like just doing this (same thing, but without setting the highlight groups in an autocommand)
```lua
local search = vim.api.nvim_get_hl_by_name("Search", true)
vim.api.nvim_set_hl(0, 'TransparentSearch', { fg = search.foreground })

local help = vim.api.nvim_get_hl_by_name("IncSearch", true)
vim.api.nvim_set_hl(0, 'TransparentHelp', { fg = help.foreground })

local cmdGroup = 'DevIconLua'
local noice_cmd_types = {
  CmdLine    = cmdGroup,
  Input      = cmdGroup,
  Lua        = cmdGroup,
  Filter     = cmdGroup,
  Rename     = cmdGroup,
  Substitute = "Define",
  Help       = "TransparentHelp",
  Search     = "TransparentSearch"
}

for type, hl in pairs(noice_cmd_types) do
  vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder" .. type, { link = hl })
  vim.api.nvim_set_hl(0, "NoiceCmdlineIcon" .. type,        { link = hl })
end
vim.api.nvim_set_hl(0, "NoiceConfirmBorder", { link = cmdGroup })
```
after `require("noice").setup({...})` has been called is enough, Noice doesn't seem to overwrite the highlight groups after the setup

**Comment by gennaro-tedesco** [comment]
Yes, in fact, this is the cleanest solution.

**Comment by folke** [comment]
Yep, that's exactly how you should do it. Noice sets `default=true` on the hl groups, so that's why they're not overriden by Noice.
