### ISSUE TITLE
When I scroll with enabled noice I get artifacts

### ISSUE THREAD

**Issue by ekokotov** [folke/noice.nvim#194]
**Describe the bug**

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?

**To Reproduce**
1. Just added noice.vim to neovim 0.8
2. Used default configuration from manual 
3. When scroll vertically I get artifacts (repeated lualine bar)
(without enabled noice I don't face this issue)
**Expected Behavior**
scroll should clear the screen
**Screenshots**
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/11966000/199802909-1d9244f3-03cf-4a1b-a510-d111bf104918.png">

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>

Sun Oct 23 01:29:59 2022
...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: invalid position.row

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:133: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:132>
	[C]: in function 'assert'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: in function 'calculate_window_position'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:185: in function 'update_layout_config'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:356: in function 'update_layout'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:129: in function 'init'
	.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:132: in function <.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:130>
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:53: in function 'create'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:148: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:142>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:121: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:118: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:77>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:67: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:47>

Sun Oct 23 01:30:02 2022
...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: invalid position.row

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:133: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:132>
	[C]: in function 'assert'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: in function 'calculate_window_position'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:185: in function 'update_layout_config'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:356: in function 'update_layout'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:129: in function 'init'
	.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:132: in function <.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:130>
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:53: in function 'create'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:148: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:142>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:121: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:118: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:77>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:67: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:47>

Sun Oct 23 01:30:36 2022
...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: invalid position.row

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:133: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:132>
	[C]: in function 'assert'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: in function 'calculate_window_position'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:185: in function 'update_layout_config'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:356: in function 'update_layout'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:129: in function 'init'
	.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:132: in function <.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:130>
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:53: in function 'create'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:148: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:142>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:121: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:118: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:77>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:67: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:47>

Sun Oct 23 01:30:50 2022
...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: invalid position.row

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:133: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:132>
	[C]: in function 'assert'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:38: in function 'calculate_window_position'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:185: in function 'update_layout_config'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:356: in function 'update_layout'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:129: in function 'init'
	.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:132: in function <.../site/pack/packer/start/nui.nvim/lua/nui/object/init.lua:130>
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:53: in function 'create'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:148: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:142>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:121: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:118: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:77>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:138: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:67: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:47>

Thu Nov  3 01:51:09 2022
...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:23: Invalid window id: 1010

stack traceback:
	[C]: in function 'pcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:140: in function <...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'nvim_win_get_width'
	...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:23: in function 'get_window_size'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:93: in function 'get_container_info'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:155: in function 'update_layout_config'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:357: in function 'update_layout'
	...
	[C]: in function 'xpcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	...ite/pack/packer/start/noice.nvim/lua/noice/view/init.lua:123: in function 'display'
	...ack/packer/start/noice.nvim/lua/noice/message/router.lua:115: in function <...ack/packer/start/noice.nvim/lua/noice/message/router.lua:74>
	[C]: in function 'xpcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:145: in function <...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:130>
	[C]: in function 'pcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/init.lua:104: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Thu Nov  3 01:51:20 2022
...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:23: Invalid window id: 1010

stack traceback:
	[C]: in function 'pcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:140: in function <...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'nvim_win_get_width'
	...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:23: in function 'get_window_size'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:93: in function 'get_container_info'
	...site/pack/packer/start/nui.nvim/lua/nui/layout/utils.lua:155: in function 'update_layout_config'
	...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:357: in function 'update_layout'
	...
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:145: in function 'try'
	...te/pack/packer/start/noice.nvim/lua/noice/util/hacks.lua:96: in function 'cmd'
	...m/site/pack/packer/start/nvim-cmp/lua/cmp/utils/misc.lua:246: in function <...m/site/pack/packer/start/nvim-cmp/lua/cmp/utils/misc.lua:244>
	[C]: in function 'wait'
	.../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:34: in function 'sync'
	...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:38: in function 'completion_visible'
	...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:93: in function 'virtual_hint'
	...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:281: in function 'handler'
	...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Thu Nov  3 19:53:01 2022
.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:6: module 'nui.object' not found:
	no field package.preload['nui.object']
	no file './nui/object.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/nui/object.lua'
	no file '/usr/local/share/lua/5.1/nui/object.lua'
	no file '/usr/local/share/lua/5.1/nui/object/init.lua'
	no file '/opt/homebrew/share/lua/5.1/nui/object.lua'
	no file '/opt/homebrew/share/lua/5.1/nui/object/init.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nui/object.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nui/object/init.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nui/object.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nui/object/init.lua'
	no file './nui/object.so'
	no file '/usr/local/lib/lua/5.1/nui/object.so'
	no file '/opt/homebrew/lib/lua/5.1/nui/object.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nui/object.so'
	no file './nui.so'
	no file '/usr/local/lib/lua/5.1/nui.so'
	no file '/opt/homebrew/lib/lua/5.1/nui.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nui.so'

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'require'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:6: in function 'load'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:22: in function 'Object'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:31: in main chunk
	[C]: in function 'require'
	...
	[C]: in function 'wait'
	.../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:126: in function '_wait'
	.../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:145: in function 'run'
	...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:136: in function 'load_project_status'
	...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:29: in function '_load'
	...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:23: in function 'new'
	...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/core.lua:15: in function 'init'
	...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:119: in function 'open'
	...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:272: in function 'on_enter'
	...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:790: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:789>

Thu Nov  3 19:53:24 2022
.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:6: module 'nui.object' not found:
	no field package.preload['nui.object']
	no file './nui/object.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/nui/object.lua'
	no file '/usr/local/share/lua/5.1/nui/object.lua'
	no file '/usr/local/share/lua/5.1/nui/object/init.lua'
	no file '/opt/homebrew/share/lua/5.1/nui/object.lua'
	no file '/opt/homebrew/share/lua/5.1/nui/object/init.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nui/object.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nui/object/init.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nui/object.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nui/object/init.lua'
	no file './nui/object.so'
	no file '/usr/local/lib/lua/5.1/nui/object.so'
	no file '/opt/homebrew/lib/lua/5.1/nui/object.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nui/object.so'
	no file './nui.so'
	no file '/usr/local/lib/lua/5.1/nui.so'
	no file '/opt/homebrew/lib/lua/5.1/nui.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nui.so'

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'require'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:6: in function 'load'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:22: in function 'Object'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:31: in main chunk
	[C]: in function 'require'
	...
	[C]: in function 'wait'
	.../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:126: in function '_wait'
	.../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:145: in function 'run'
	...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:136: in function 'load_project_status'
	...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:29: in function '_load'
	...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:23: in function 'new'
	...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/core.lua:15: in function 'init'
	...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:119: in function 'open'
	...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:272: in function 'on_enter'
	...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:790: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:789>

Thu Nov  3 19:53:26 2022
.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:6: module 'nui.object' not found:
	no field package.preload['nui.object']
	no file './nui/object.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/nui/object.lua'
	no file '/usr/local/share/lua/5.1/nui/object.lua'
	no file '/usr/local/share/lua/5.1/nui/object/init.lua'
	no file '/opt/homebrew/share/lua/5.1/nui/object.lua'
	no file '/opt/homebrew/share/lua/5.1/nui/object/init.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nui/object.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nui/object/init.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nui/object.lua'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nui/object/init.lua'
	no file './nui/object.so'
	no file '/usr/local/lib/lua/5.1/nui/object.so'
	no file '/opt/homebrew/lib/lua/5.1/nui/object.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nui/object.so'
	no file './nui.so'
	no file '/usr/local/lib/lua/5.1/nui.so'
	no file '/opt/homebrew/lib/lua/5.1/nui.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/${user}/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nui.so'

stack traceback:
	[C]: in function 'pcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:140: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:139>
	[C]: in function 'require'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:6: in function 'load'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/lazy.lua:22: in function 'Object'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:31: in main chunk
	[C]: in function 'require'
	...
	[C]: in function 'wait'
	.../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:126: in function '_wait'
	.../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:145: in function 'run'
	...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:136: in function 'load_project_status'
	...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:29: in function '_load'
	...cker/start/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:23: in function 'new'
	...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/core.lua:15: in function 'init'
	...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:119: in function 'open'
	...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:272: in function 'on_enter'
	...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:790: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:789>

</pre>
</details>

**Comment by folke** [comment]
This is a known issue that has been fixed upstream already

**Comment by steliyan** [comment]
Can you point to the upstream fix for this? Also, is it possible to workaround the issue with nvim 0.8.0?

**Comment by folke** [comment]
No idea. There's no workaround. Just use nightly or don't use Noice if the issue botters you

**Comment by ekokotov** [comment]
0.8.1 fixes this isse?
