### ISSUE TITLE
Noice hijacking window title

### ISSUE THREAD

**Issue by duarm** [folke/noice.nvim#197]
**Describe the bug**
When I open the cmdline with noice, the window title changes to `scrollbar (noice://N) - NVIM`, N being a number which increases each time I open the cmdline. If I open a file which triggers an LSP progress bar, I can see the number quickly increasing to 400.

**Which version of Neovim are you using?**
v0.9.0-dev-55-gedc8a1f046

**To Reproduce**
1. Open NVIM with noice, interact with noice once (e.g. opening the cmdline), and see the window title changing

**Expected Behavior**
ideally, the Window title should remain unchanged. But restoring the old window title would already help instead of permanently changing to `noice (noice://200) - NVIM`

**Comment by latipun7** [comment]
seems duplicate with #182

**Comment by duarm** [comment]
yeah, it's a duplicate, same problem

**Comment by latipun7** [comment]
@folke , after updating to https://github.com/folke/noice.nvim/commit/ea1079deb6ffdc326b3da0dc2e84371b330dfdae this problem seems not resolved. I still see the flashing when lsp mini view is updating. Using default setting.

https://user-images.githubusercontent.com/20012970/200270392-032b308b-8723-4c76-970f-9f4ffea47bda.mp4

**Comment by UtkarshVerma** [comment]
I am facing the same problem, any workarounds for this?

**Comment by folke** [comment]
This is Neovim behavior. You can ony fix it by disabling `vim.g.title`

**Comment by UtkarshVerma** [comment]
Oh, so I guess there's no functionality to blacklist mini windows for titles.

**Comment by aymanbagabas** [comment]
I'm facing the same issue here too. Related issue: https://github.com/neovim/neovim/issues/19380

**Comment by GiuseppeMP** [comment]
> As I mentioned way too many times before, **this can not be fixed**. That's standard Neovim behavior.
> 
> Disable `vim.g.title`, or disable Noice if it bothers you.

> 
Little fix typo, it's an **o**ption. 

`vim.o.title`
