### ISSUE TITLE
[Feature/Question] Integration with cmp-cmdline

### ISSUE THREAD

**Issue by akinsho** [folke/noice.nvim#2]
So this issue is a little unclear since I don't know where it should be, i.e. in cmp-cmdline's repo or here, but this seems like a good place to start.

When using https://github.com/hrsh7th/cmp-cmdline with this plugin enabled, the position of the cmp window is just above the cmdline and doesn't change. This makes sense since cmp-cmdline likely hardcoded the position of the window and has not adapted to `vim.ui_attach` so there is likely some change required there. Although something that made me think it could maybe be solved here was the addition of this change to cmp-cmdline that no longer constrains the source to just the cmdline
https://github.com/hrsh7th/cmp-cmdline/pull/61

Although I guess with `ui_attach` you are in cmdline mode, so maybe that would have to be disabled somehow and re-enabled as a source for your window. Not sure what/if there is a good solution or if the two plugins are just incompatible.

**Comment by folke** [comment]
So the way the popupmenu works is probably not as you think :)

We implement `ext_popupmenu` and get the list of items we should show in a popup together with information if an option is selected.

Right now, for this I use some of the internal views from `cmp`, but `cmp` isn't actually doing any completion for this.
`cmp-cmdline` isn't involved at all with rendering the popupmenu in Noice.

I was just lazy and haven't yet implemetented a simple popup view.

You're right about the cmp popup position durting cmdlline mode, but I fix (hack) that in https://github.com/folke/noice.nvim/blob/dee23c21c3ff52119d8452b77814e6be75dd23bb/lua/noice/ui/popupmenu.lua#L16

**Comment by folke** [comment]
This can probably also be closed now?

**Comment by akinsho** [comment]
I'm still seeing the cmp-cmdline window located just above the old cmdline position, e.g.

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/22454918/193302689-0489a426-e427-46f9-8c50-2ec8cfbac6e0.png">

**Comment by akinsho** [comment]
Yeah, I think the cmp-cmdline issue here is separate since a solution to that will probably be some sort of mixture of a change to cmp-cmdline to allow changing the position of the window through some sort of API and maybe that being incorporated here, so maybe best to move this issue there at least to raise the request for such an API.

Regarding the other issue of positioning, that still recurs without cmp cmdline enabled seems to be a different window with other sources (e.g. my spell and rg source) where the cursor would otherwise be

**Comment by Shougo** [comment]
Hi, `ddc-cmdline` has the same problem.
It seems `screenpos()` result is wrong.
I think it is from fake cursor.

https://github.com/folke/noice.nvim#-known-issues

**Comment by folke** [comment]
This should be fixed now in the latest version. Things I changed:

- I made a [proper fix](https://github.com/folke/noice.nvim/blob/e1d93f1f49657d996c330bee1f560cee8790bcf8/lua/noice/hacks.lua#L170) to the existing **cmp** api functions to get the position, screen position and line of the cmdline when **Noice** is active. Will see to make a PR to cmp that exposes an API to set the cmdline position from other plugins, but this works for now.
- I implemented a proper **cmp** source **noice_popupmenu** that is automatically added when no other cmdline sources have been configured.

With these changes, things should work as expected:
- cmp popupmenu should always be positioned correctly
- pmenu items (the ones I get from `ui_attach/ext_popupmenu` will be used for completion if no other cmp cmdline sources were configured
- if you're using `cmp-cmdline`, then that will work as it did before

Let me know if you encounter any more issues!

**Comment by folke** [comment]
@Shougo yes, you're correct. 

I made some changes so that `cmp` can properly work with fake cursors.

Once we have a proper Neovim api to work with the cursor, it should work for other usages without these *hacks*

**Comment by Shougo** [comment]
Thanks.  I will try it later.

**Comment by folke** [comment]
Closing this issue since the fake cursor issue is tracked in the tracking issue.

**Comment by miversen33** [comment]
Ya, it looks like [popupmenu.lua](https://github.com/folke/noice.nvim/blob/main/lua/noice/ui/popupmenu.lua) has a hard dependency on both [cmp](https://github.com/hrsh7th/nvim-cmp) now. This seems wrong @folke ?

**Comment by folke** [comment]
@Shougo @miversen33 I've removed the hard dependency on cmp. In your config you can set `popupmenu.enabled = false`.

I'll also add a native implementation for regular cmdline completions.

**Comment by Shougo** [comment]
Thank you.

**Comment by Shougo** [comment]
Well, `nvim-cmp` is loaded yet.

![スクリーンショット_2022-10-04_16-16-16](https://user-images.githubusercontent.com/41495/193757870-afbcdbba-c0f5-4cb7-8d23-1788737bc3d5.png)

**Comment by Shougo** [comment]
My config

```lua
  require'noice'.setup {
    cmdline = {
      enabled = true,
      menu = 'popup',
      icons = {
        ['/'] = { icon = '/', hl_group = 'DiagnosticWarn' },
        ['?'] = { icon = '?', hl_group = 'DiagnosticWarn' },
        [':'] = { icon = ':', hl_group = 'DiagnosticInfo', firstc = false },
      },
    },
    popupmenu = {
      enabled = false,
    },
  }
```

**Comment by folke** [comment]
@Shougo my bad. I use a lazy-require and while I had a pcall to check if cmp exists, it never failed due to the lazy loading. Should be fixed now.

**Comment by folke** [comment]
In order to fix the position of the menu for `ddc.vim`, you'll have to somehow tell it the correct position of the cmdline cursor.

You can retrieve it with
```lua
---@type {win: window, buf: buffer, win_cursor:number[], screen_cursor:number[]}?
require("noice.util.cursor").get_cmdline_cursor()
```

Positions are (1,0) indexed

**Comment by Shougo** [comment]
Thank you!  It works.

**Comment by Shougo** [comment]
I want to check `noice.nvim` is installed in vim script...

**Comment by Shougo** [comment]
I have added `noice.nvim` support in `pum.vim`.

**Comment by folke** [comment]
@Shougo that's awesome!

**Comment by Shougo** [comment]
![スクリーンショット_2022-10-04_19-56-55](https://user-images.githubusercontent.com/41495/193802088-dc0dbced-1845-4b04-b187-40d9d1708c67.png)

**Comment by akinsho** [comment]
@folke what do you think about allowing the user to position the completion menu themselves, specifically what I'm thinking is that rather than have it overlapping with the bottom of the float it might be nicer to have it appear just below the window.

I'm going for something that looks a bit more like

<img width="740" alt="image" src="https://user-images.githubusercontent.com/22454918/193806799-8200a2bc-9def-4d7d-975d-3e8e10dd86fb.png">

(obvs that's a GUI I just meant the positioning)

But I think rather than you specifically hard coding any values that what you pass to the positioning function be configurable defaulting to how you currently have it but with the user having an option to move it.

Just an idea as always, no pressure if it will make things complex

**Comment by folke** [comment]
@akinsho and done :)
<img src="https://user-images.githubusercontent.com/292349/193823421-05ca391a-aa31-4ede-b3e0-f27bc74cec7e.png" alt="image"/>

See https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#display-the-cmdline-and-popupmenu-together

**Comment by Shougo** [comment]
I have added offset_row support.

![スクリーンショット_2022-10-04_22-06-04](https://user-images.githubusercontent.com/41495/193826884-f1b2a7b3-e7e2-4eec-9832-2895b80e09d0.png)

**Comment by folke** [comment]
@Shougo great :)

I forgot to mention that I fixed some issues with the cmdline position. There were some off by ones (sometimes) that are now fixed.

**Comment by akinsho** [comment]
@folke that looks great, very *noice* 😆.

I'm noticing that using `<Tab>` in the native popup menu doesn't cycle the options correctly, though. It seems to get stuck after moving to the second item and doesn't continue cycling through them.

Also, I'm wondering if customization regarding positioning would work for cmp as well since I prefer that it autocompletes the cmdline completions versus manually triggering the completion

**Comment by folke** [comment]
@Shougo hi! I just refactored a lot of the code and also the part for the cmdline cursors.

The existing function no longer exists, but you now have `require("noice").api.get_cmdline_position()` instead.

```lua
---@class CmdlinePosition
---@field win number Window containing the cmdline
---@field buf number Buffer containing the cmdline
---@field bufpos {row:number, col:number} (1-0)-indexed position of the cmdline in the buffer
---@field screenpos {row:number, col:number} (1-0)-indexed screen position of the cmdline
```

This no longer returns the cursor position, but the position where the cmdline starts.

You can then use `vim.fn.getcmdpos` to get the cursor if needed.

The reason I changed it is because working with the cursor position itself was difficult in situations where completion ran before the cursor was updated. Usingt the actual position of the cmdline makes things much easier.

**Comment by Shougo** [comment]
Oh, thanks.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.

**Comment by AndreM222** [comment]
Is it possible to have this UI running as I'm typing like cmp-cmdline?
