### ISSUE TITLE
lualine sometimes disappears under cmdline

### ISSUE THREAD

**Issue by jinzhongjia** [folke/noice.nvim#206]
**Describe the bug**
lualine sometimes disappears under cmdline, and I use the default configuration.

Now the trigger condition is to enter multiple letters

**Which version of Neovim are you using?**
Version: Nightly

**Screen**
![Peek 2022-11-07 23-14](https://user-images.githubusercontent.com/41784264/200346247-4823686f-3bf5-4dc0-905f-5aa28c2b523c.gif)

**Comment by folke** [comment]
Can't reproduce. Please provide a https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by jinzhongjia** [comment]
> https://gist.github.com/jinzhongjia/9474de837f6a04676f1555ca0fa3fd4b I have stored `minimal.lua` on the gist, and this file can restore the situation, I suspect it is caused by my lualine configuration

And my system is Arch Linux, and mu neovim(nightly) is from repo called `archlinuxcn`

**Comment by folke** [comment]
I know what change is causing this, but strangely enough I don;t have it with my config. So I'm looking into what is different in my config, so I can properly fix it
