### ISSUE TITLE
Problem with `clojure-lsp` / too many errors.

### ISSUE THREAD

**Issue by ribelo** [folke/noice.nvim#207]
**Describe the bug**
![2022-11-07-233930_grim](https://user-images.githubusercontent.com/1815898/200430783-f72cdcda-307e-4a73-9269-c1ccdba7d3a0.png)
![2022-11-07-233942_grim](https://user-images.githubusercontent.com/1815898/200430796-6f60bf6a-d7e4-4694-a182-b30f0d9c19db.png)

**Which version of Neovim are you using?**
nightly

**To Reproduce**
1. install `clojure-lsp`
2. open clj file

Perhaps the problem lies with `clojure-lsp`, but I can't tell.

**Comment by folke** [comment]
This could only happen if the lsp server died already when processing the lsp progress. I've changed it so it no longer errors
