### ISSUE TITLE
error notice when using hot key

### ISSUE THREAD

**Issue by fan-xing** [folke/noice.nvim#208]
**Describe the bug**
when i use hot key to save my file,i get an error notice and the command was executed

**Which version of Neovim are you using?**
Nightly

**To Reproduce**
hot key like this
```
noremap <C-s> :<C-U><C-R>=printf("w")<CR><CR>
```
if i use the cmdline to input `:w`, there's no error

**Config**
```
lua << EOF
local noice = require("noice")
noice.setup({
  cmdline = {
    format = {
      cmdline = { pattern = "^:", icon = "💬 ", lang = "vim" },
      search_down = { kind = "search", pattern = "^/", icon = "🔍 ", lang = "regex" },
      search_up = { kind = "search", pattern = "^%?", icon = "🔍 ", lang = "regex" },
    }
  },
})
EOF
```

**Screenshots**

![image](https://user-images.githubusercontent.com/31067312/200804489-adeef009-058d-44b1-b1fb-0c33dfc14278.png)

**Noice Log**
![image](https://user-images.githubusercontent.com/31067312/200798898-7de92858-9930-4c3b-a691-e71528f5b366.png)

**Comment by folke** [comment]
The issue was cause by quickly opening and closing the cmdline. It's fixed now, but better to use the following mappings instead:

```lua
vim.keymap.set("i", "<C-s>", "<cmd>:w<cr><esc>")
vim.keymap.set("n", "<C-s>", "<cmd>:w<cr><esc>")
```

The `<cmd>` is specially made to prevent opening the cmdline

**Comment by fan-xing** [comment]
Thank you, i'll try it
