### ISSUE TITLE
Persist Tree-Sitter info panels

### ISSUE THREAD

**Issue by adrian5** [folke/noice.nvim#218]
It appears that output from `:TSConfigInfo` and `:TSInstallInfo` gets placed into transient panels. As their information takes time to read, I think it would be better if they behaved more classically (vsplit, new buffer, float), requiring manual closure.

**Comment by folke** [comment]
You can always show all messages in a split after running the command with `:Noice`.

I've also just added a new feature that makes it straightforward to redirect commands or functions to a different view (like a popup).

Please refer to the section on [command redirection](https://github.com/folke/noice.nvim#%EF%B8%8F-command-redirection)
