### ISSUE TITLE
Lsp progress title only for done state

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#223]
Have a nice day!
I have two problems.
1. If i open typescript file i see lsp progress message after several seconds only for done state.
![image](https://user-images.githubusercontent.com/53742299/201689966-91a778ad-b5e5-4374-b641-6a12b396187c.png)
2. For sumneko_lua i can't see lsp progress message.
Mb it's connected with mason plugin...

**Comment by folke** [comment]
That's odd. I use Mason myself, so that's not the issue.

What does `:checkhealth noice` say?

**Comment by folke** [comment]
Your config? Any logs?

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/201984217-4b4a2903-a860-4b3f-a235-b270ddc010d1.png)

**Comment by kaiphat** [comment]
My config: https://github.com/kaiphat/dotfiles/tree/master/nvim

**Comment by folke** [comment]
Can't reproduce. Please provide a https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue
