### ISSUE TITLE
attempt to call field 'syntax' (a nil value)

### ISSUE THREAD

**Issue by mhanberg** [folke/noice.nvim#224]
**Describe the bug**
I assume an error is occuring when attempting to display the signature help

**Which version of Neovim are you using?**

```
NVIM v0.9.0-dev-312+gc4fcde506
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1668402625487.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**To Reproduce**

This is specific to how i can reproduce, and I'll note that this is using [ElixirLS](https://github.com/elixir-lsp/elixir-ls) v0.12
1. In elixir code
2. Type `|> IO.inspect`
3. observe no errors
4. type `(`
5. observer error and no signature help

**Expected Behavior**

Signature help and no error

**Screenshots**

Work code, so unfortunately no screenshot.

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Mon Nov 14 09:50:39 2022
...pack/packer/start/noice.nvim/lua/noice/text/markdown.lua:162: attempt to call field 'syntax' (a nil value)

stack traceback:
	[C]: in function 'pcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:140: in function 'syntax'
	...pack/packer/start/noice.nvim/lua/noice/text/markdown.lua:162: in function 'emit_md'
	...pack/packer/start/noice.nvim/lua/noice/text/markdown.lua:170: in function 'format'
	...te/pack/packer/start/noice.nvim/lua/noice/lsp/format.lua:44: in function 'format'
	...pack/packer/start/noice.nvim/lua/noice/lsp/signature.lua:163: in function 'format_signature'
	...pack/packer/start/noice.nvim/lua/noice/lsp/signature.lua:169: in function 'format'
	...site/pack/packer/start/noice.nvim/lua/noice/lsp/init.lua:193: in function <...site/pack/packer/start/noice.nvim/lua/noice/lsp/init.lua:179>
	[C]: in function 'xpcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:145: in function 'signature'
	...pack/packer/start/noice.nvim/lua/noice/lsp/signature.lua:91: in function 'handler'
	...stalls/neovim/nightly/share/nvim/runtime/lua/vim/lsp.lua:1388: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

</pre>
</details>

**Comment by mhanberg** [comment]
Can you clarify what you mean by "git of the noice plugin directory"

**Comment by folke** [comment]
I meant, did you make any manual changes to those files which prevents updating them properly?

Can you check if that specific line exists in the local plugin repo?

**Comment by folke** [comment]
Are you using something like https://github.com/lewis6991/impatient.nvim?
