### ISSUE TITLE
Macro recording (q) not working with noice

### ISSUE THREAD

**Issue by slai-nick** [folke/noice.nvim#225]
**Describe the bug**
Macros (`q`) not working anymore - nothing happens when pressing `q`.

**Which version of Neovim are you using?**
0.8.0 - TUI - MacOs - iTerm 2

**To Reproduce**
1. Use noice with default setup

**Expected Behavior**
Macros should start recording when pressing `q`, noice should inform the user so.

**Noice Log**
Empty

**Comment by folke** [comment]
https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages
