### ISSUE TITLE
Question: views/mini-backend - transparent background?

### ISSUE THREAD

**Issue by baahrens** [folke/noice.nvim#226]
How would I go about changing the background of popup-messages (lsp-progress in the screenshot) to be `transparent`? I tried all the highlight groups and options.

![Bildschirmfoto 2022-11-15 um 14 42 38](https://user-images.githubusercontent.com/9726718/201937081-a4aee732-f95a-4fa0-8a8b-49e4a22586b5.png)

**Comment by folke** [comment]
Did you try setting `config.views.mini.win_options.winblend = 100`?
There's also `NoiceMini` the `Normal` hl group for mini.

**Comment by baahrens** [comment]
Both didn't seem to work, but I'll try again with a minimal setup and report back.

**Comment by cpea2506** [comment]
> ```lua
> winblend = 100
>         }
>       },
> ```

I'm here to say that winblend must be set to 0 to make it totally transparent.

**Comment by cpea2506** [comment]
> I have the same problem.
> I tried with `winblend = 0` but the background still exists.

Just make sure you run `:PackerCompile` if your setup is in packer config.

**Comment by ilias777** [comment]
My config is outside from the `packer.startup()` function.

**Comment by m-h-san** [comment]
The following addition to init.lua may work:
  
![image](https://user-images.githubusercontent.com/85449119/206145240-83b3f8bc-9617-416a-bbec-5d721e307c3e.png)
If it works, it will look something like this:
  
![image](https://user-images.githubusercontent.com/85449119/206145435-87a419f4-b1c9-4996-9e6b-8daede029166.png)
![image](https://user-images.githubusercontent.com/85449119/206145512-01a777a1-95e8-49da-8095-e3b66c565612.png)
I hope this is helpful.

**Comment by baahrens** [comment]
```lua
mini = {
  win_options = {
    winblend = 0
  }
}
```
does indeed work. Thanks @cpea2506

**Comment by ilias777** [comment]
For me `winblend = 0` doesn't work. And I need `NormalFloat` to have a background for my *SignatureHelp - Completion*. I think this is a colorscheme setting. Unfortunately *mini* doesn't have his own highlighting group, as mentioned and uses the *NormalFloat* highlighting.
I leave it as is! It's ok.
Thank you for your advices.
Have a good day.

**Comment by folke** [comment]
@ilias777 you can easily change the `winhighlight` settings as well with the win_options?

**Comment by ilias777** [comment]
Hi @folke, I tried with `winhighlight`, but unfortunately without success. 
Can you tell me what I am doing wrong?
```lua
require('noice').setup({
    ...
    mini = {
        win_options = {
            winhighlight = {
                NormalFloat = '???', -- I tried here with different highlighting groups
                -- or
                Normal = '???' -- and I tried also to set Normal to a different highlighting group
            }
        }
    }
    ...
})
```
🤷🏻

**Comment by m-h-san** [comment]
You may be able to use [nvim-transparent.nvim](https://github.com/xiyaowong/nvim-transparent).

**Comment by ilias777** [comment]
Thank you for your suggestion. I tried now with nvim-transparent.nvim, but it doesn't work. I have to use the `winhighlight` in the `win_options` setting and I don't know how to do this. I read the documentation and I don't get it 😅

**Comment by davidsierradz** [comment]
> Thank you for your suggestion. I tried now with nvim-transparent.nvim, but it doesn't work. I have to use the `winhighlight` in the `win_options` setting and I don't know how to do this. I read the documentation and I don't get it sweat_smile

@ilias777 You are almost there:

```lua
require('noice').setup({
  views = {
    mini = {
      winhighlight = {},
    },
  },
})
```
