### ISSUE TITLE
Allow normal/visual/replace modes in cmdline

### ISSUE THREAD

**Issue by mrjones2014** [folke/noice.nvim#227]
**Is your feature request related to a problem? Please describe.**
I use vi-bindings in my shell. I'd like to be able to use vim motions/actions to edit the current command line text.

**Describe the solution you'd like**
Add a configuration option that allows me to enter normal/visual/replace/etc. modes without closing the cmdline (currently pressing `<ESC>` just closes it and pressing `jk` which I've mapped to `<ESC>` does nothing).

**Describe alternatives you've considered**
Not using vim actions/motions to edit command line 😭

**Additional context**

**Comment by folke** [comment]
Not possible. I've been answering multiple related issues already, so please check the closed issues
