### ISSUE TITLE
Compatibility with Neogit

### ISSUE THREAD

**Issue by jamestrew** [folke/noice.nvim#232]
**Describe the bug**
I'm running into some compatibility issues with [Neogit](https://github.com/TimUntersberger/neogit), specifically around this message/input when making a commit.

```
Are you sure you want to commit?
[Y]es, (N)o:
```

With `noice`, I get a blank input box.
![image](https://user-images.githubusercontent.com/66286082/202833882-623d173c-6203-4d31-a3b7-aae0e147a3a6.png)

**Which version of Neovim are you using?**
NVIM v0.9.0-dev-348+gf2b30b4d6
latest commit as of this issue

**To Reproduce**

First without `noice` to understand expected behavior
1. get my [noice_minimal.lua](https://gist.github.com/jamestrew/7301215517044732d56cbd4dbd014347#file-noice_minimal-lua) and comment out the `setup` call for `noice`
2. `nvim . -u noice_minimal.lua`
3. after everything has installed, edit some file to commit
4. `:Neogit`, navigate over a file and `s` to stage, `cc` to make a commit, enter some commit message and `:wq`
5. should see the "Are you sure you want to commit? [Y]es, (N)o:" message, hitting either `y` or `<cr>` will make the commit.
6. `git reset --soft HEAD~` to undo the last commit

Next with `noice`
1. uncomment the `setup` call for `noice` in `noice_minimal.lua`
2. repeat steps 2-4 from above
3. a box appears (as shown in ss above), hitting `y` or `<cr>` will confirm the commit but the box will remain until to `:q` out of the `neogit` buffer.

**Expected Behavior**
The "Confirm" input box should show the message correctly and disappear after an appropriate input. The strange thing is this behavior seems to work with discarding files (hitting `x` over a file in the `neogit` buffer).

![image](https://user-images.githubusercontent.com/66286082/202834406-d01b5902-2b8f-45ce-9d3b-25e3f3783ae7.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Fri 18 Nov 2022 11:25:18 PM EST
vim/_meta.lua:0: Expected lua string

stack traceback:
	[C]: in function 'pcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:144: in function <...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:143>
	[C]: in function 'nvim_get_option_info'
	vim/_meta.lua: in function '__index'
	vim/_meta.lua: in function ''
	vim/_meta.lua: in function '__index'
	...site/pack/packer/start/noice.nvim/lua/noice/view/nui.lua:269: in function <...site/pack/packer/start/noice.nvim/lua/noice/view/nui.lua:256>
	[C]: in function 'xpcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:152: in function 'try'
	...ite/pack/packer/start/noice.nvim/lua/noice/view/init.lua:136: in function 'display'
	...ack/packer/start/noice.nvim/lua/noice/message/router.lua:200: in function <...ack/packer/start/noice.nvim/lua/noice/message/router.lua:144>
	[C]: in function 'xpcall'
	...ite/pack/packer/start/noice.nvim/lua/noice/util/call.lua:149: in function 'try'
	.../site/pack/packer/start/noice.nvim/lua/noice/ui/init.lua:93: in function <.../site/pack/packer/start/noice.nvim/lua/noice/ui/init.lua:73>
	[C]: in function 'confirm'
	...m/site/pack/packer/start/neogit/lua/neogit/lib/input.lua:64: in function 'get_confirmation'
	...r/start/neogit/lua/neogit/buffers/commit_editor/init.lua:50: in function <...r/start/neogit/lua/neogit/buffers/commit_editor/init.lua:46>
	[string ":lua"]:1: in main chunk
</pre>
</details>

**Comment by c3n21** [comment]
Do you experience crashes when making a second commit in the same editing session like #337 

setting `disable_commit_confirmation = true` seems to work this issue around so maybe the issue lies in Neogit...

**Comment by abusch** [comment]
What I suspect is happening is:

* `neogit` calls `vim.fn.confirm()` for its confirmation dialogs
* the commit confirmation dialog is called from a `BufUnload` event handler
* the doc for `BufUnload` says `Do not switch buffers or windows!`
* `Noice` uses an `nui` popup to display `confirm` messages, which does create a new buffer/window, causing issues

I have no idea if that makes any sense and I could be completely wrong though 😅 (or what the fix would be)

**Comment by tobealive** [comment]
You can check if the linked PR works for you. 
Initially I wanted clean up the commit editor just a bit, but hopefully improving the compatibility with noice could be done along the way.

**Comment by abusch** [comment]
@tobealive I can confirm this fixes the issue for me. Nice one!

**Comment by tobealive** [comment]
Well, it couldn't stay like that because it would interfere with other functionalities. I had to rework the PR. Should be a proper solution now :+1: .

**Comment by folke** [comment]
@tobealive that's awesome, thank you for looking into this!

**Comment by jamestrew** [comment]
Thanks everyone. I'm good to close this issue.

**Comment by metalelf0** [comment]
I'm still seeing this issue with latest neovim HEAD, noice and neogit versions.

**Comment by abusch** [comment]
Yes, the neogit PR that fixes it hasn't been merged yet, unfortunately: https://github.com/TimUntersberger/neogit/pull/441

The workaround for now is to disable commit confirmation in neogit.
