### ISSUE TITLE
Goneovim: messages are printed into stdout

### ISSUE THREAD

**Issue by przepompownia** [folke/noice.nvim#236]
**Which version of Neovim are you using?**
Upstream fbce9f421ad1ad466126a24524ade9df978486d5 merged into `fix_multigrid_lua_ui_attach` (https://github.com/neovim/neovim/pull/21080), Goneovim nightly https://github.com/akiyosi/goneovim/commit/508947cce2042dc3fa9cd546dfa497830072d339

Gui(specify which GUI client you are using)? Nightly? Version?

**To Reproduce**
1. Run Goneovim with minimal Noice config, e.g.  `goneovim --nvim ~/tmp/nvim-from-src/bin/nvim -- -u /tmp/noice-minimal.lua 2>/dev/null` 
2. Wait for loading Noice 
3. Press`n` in Normal mode and see displayed messages
4. Look at the console from which goneovim was started. 

**Expected Behavior**
Messages are not printed into stdout. 

**Screenshots**

https://user-images.githubusercontent.com/11404453/202935530-dd48480c-4804-4bb3-8c73-a63cdcd9394a.mp4

**Noice Log**
Empty.

**Comment by folke** [comment]
This is likely just debugging output from Goneovim? Not coming from Noice...
