### ISSUE TITLE
Wiping all the buffers cause noice to stop working

### ISSUE THREAD

**Issue by lourenci** [folke/noice.nvim#244]
**Describe the bug**
Executing the command `:%bw` causes Noice to stop working.

![image](https://user-images.githubusercontent.com/2339362/204429870-a257654e-ff7c-4a4d-a159-b36bcc9e96e3.png)

**Which version of Neovim are you using?**
Nightly

**To Reproduce**
1. Open nvim
2. Execute `:%bw`

**Comment by folke** [comment]
you shouldn't do that and expect everything to keep working. wont fix

**Comment by lourenci** [comment]
Out of curiosity: why should I not use a native vim command to wipe all buffers? Thanks for your plugin anyway.
