### ISSUE TITLE
rapidly change between normal and operator-pending mode when entering OP mode

### ISSUE THREAD

**Issue by WilliamHsieh** [folke/noice.nvim#247]
**Describe the bug**
When entering operator-pending mode, noice is causing mode changing rapidly. It is also causing my current mode on statusline flickering.

**Which version of Neovim are you using?**
0.8.1

**To Reproduce**
1. nvim -nu /tmp/min.lua
2. press any OP key (ex: d, =)
3. rapid mode-changing message will appear

/tmp/min.lua:
```lua
-- install packer && setup path
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end

-- plugins
require("packer").startup {
  {
    "wbthomason/packer.nvim",
    {
      "folke/noice.nvim",
      requires = {
        "MunifTanjim/nui.nvim",
        "rcarriga/nvim-notify",
      },
      config = function()
        require("noice").setup()
      end,
    },
  },
  config = {
    package_root = package_root,
    compile_path = install_path .. "/plugin/packer_compiled.lua",
  },
}
require("packer").sync()

-- reproduce the problem
vim.api.nvim_create_autocmd("ModeChanged", {
  pattern = "*",
  callback = function()
    local msg = string.format("Switched from %s mode to %s mode", vim.v.event["old_mode"], vim.v.event["new_mode"])
    print(vim.fn.strftime("%T") .. " " .. msg)
  end
})
```

**Expected Behavior**
The mode should stay on OP mode instead of flickering.

**Comment by folke** [comment]
I can reproduce this in the same way without using Noice, so seems like a Neovim issue

**Comment by vimpostor** [comment]
Are you sure about this? I can't reproduce this with a clean neovim config without this plugin:
```bash
nvim -Nu <(cat<<EOF
au ModeChanged * call append(0, printf("Switched from %s mode to %s mode", v:event["old_mode"], v:event["new_mode"]))
EOF
```

Even if I take the less minimal config from above, I can only reproduce this if and only if `noice.nvim` is present.

**Comment by folke** [comment]
The problem seems to be triggered by nvim-notify, not noice.

If you execute the code below and then do `:lua = _G.modes` you can see total mode changes.

If you disable the notify, mode changes does not increase. Otherwise it does.

Test it with noice disabled of course.

```lua
_G.modes = 0
vim.api.nvim_create_autocmd("ModeChanged", {
  pattern = "*",
  callback = function(event)
	  require("notify").notify("fooo")
	  _G.modes = _G.modes + 1
  end,
})
```

**Comment by folke** [comment]
Might also be a neovim thing related to floating windows.

**Comment by vimpostor** [comment]
The upstream issue is tracked at https://github.com/neovim/neovim/issues/22263

**Comment by vimpostor** [comment]
The problem has been resolved upstream: https://github.com/neovim/neovim/pull/23288
