### ISSUE TITLE
Support vigoux/notifier.nvim

### ISSUE THREAD

**Issue by clason** [folke/noice.nvim#25]
Would it be possible to add https://github.com/vigoux/notifier.nvim as a backend alternative to `nvim-notify`?

**Comment by folke** [comment]
Yes! I actually submitted a PR there that got merged so I can integrate :)

**Comment by folke** [comment]
https://github.com/vigoux/notifier.nvim/issues/19

**Comment by folke** [comment]
I'm still planning to integarte notifer.nvim, but I've also added a new `mini` view to Noice. I basically had all the components already to make something like this :)

See https://github.com/folke/noice.nvim/blob/main/lua/noice/view/mini.lua

Replace routes with anything that you want. Like for any route, view, you can use custom formatters and position the lines anywhere you would like. Bottom-right is the default.

Example:

```lua
  local noice = require("noice")
  noice.setup({
    routes = {
      {
        view = "mini",
        filter = {
          any = {
            { event = "msg_show", kind = { "", "echo" } },
          },
        },
      },
    },
  })
```

**Comment by folke** [comment]
Integration doesn't seem possible for now. If that would change in the future, I can revsist this or someone else can submit a PR.

**Comment by clason** [comment]
Pity. Looking forward to the `mini` LSP progress component then!

**Comment by folke** [comment]
@clason it already exists, I just didn't find the time to document it.

By default it's a bit flashy though, with spinners **AND** a progress bar 😄 


https://user-images.githubusercontent.com/292349/196055721-9f3de915-414f-4937-bbed-f17b459b1cc6.mp4

But you can easily customize the format like this:
```lua
noice.setup({
  debug = false,
  lsp_progress = {
    enabled = true,
    format = {
      { "{data.progress.message} " },
      "({data.progress.percentage}%) ",
      { "{data.progress.title} ", hl_group = "NoiceLspProgressTitle" },
      { "{data.progress.client} ", hl_group = "NoiceLspProgressClient" },
    },
  },
})

```

That config is a bit less flashy:
![image](https://user-images.githubusercontent.com/292349/196055804-8b9a3d85-9eab-4212-96eb-5895a331f00d.png)

**Comment by clason** [comment]
I saw the commit, but I took "disabled and non-documented" seriously ;)

Thanks! I love how configurable everything is.

**Comment by ranjithshegde** [comment]
@folke With the `mini` module in place, and the example above, is `nvim-notify` still a hard dependency? Or can it be optional?

**Comment by folke** [comment]
@ranjithshegde yep, you're right. Can be made optional. I'll make some changes tomorrow, so one can specify the default backend. That way you dont need to override all the existing routes.

**Comment by ranjithshegde** [comment]
Fantastic!
Thank you for your excellent work! Cheers
