### ISSUE TITLE
Infinite recursive if packer used

### ISSUE THREAD

**Issue by TwIStOy** [folke/noice.nvim#253]
**Describe the bug**
If packer.nvim is loaded, packer will insert a new loader at the first of `package.loaders`. Then `util.hacks.on_module` will cause a infinite recursive.

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?
TUI, branch master

**To Reproduce**
1.
2.
3.

**Expected Behavior**

**Screenshots**

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

**Comment by folke** [comment]
Packer should insert itself as the second loader, but I fixed it anyway. Would be great if you could confirm, since I no longer use Packer myself
