### ISSUE TITLE
Handle empty documentation for variables

### ISSUE THREAD

**Issue by igorlfs** [folke/noice.nvim#258]
**Describe the bug**
Trying to hover variables without documentation throws the following error:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1636: 'width' key must be a positive Integer
stack traceback:
[C]: in function 'nvim_open_win'
/usr/share/nvim/runtime/lua/vim/lsp/util.lua:1636: in function 'handler'
/usr/share/nvim/runtime/lua/vim/lsp.lua:1387: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Which version of Neovim are you using?**
No Gui / Nightly / NVIM v0.9.0-dev-432+g8f1ef36875

**To Reproduce**
1. Create a sample (python) file:
```py
class foo:
    def __init__(self):
        self.x = 0


bar = foo()
```
2. Try to inspect `bar` with LSP's hover
3. Aforementioned error is thrown

**Expected Behavior**
No error should be thrown.

**Noice Log**
Log file is empty, though I only have tested with default verbosity settings.

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/205452022-a97924c2-8a38-4c76-8c45-09014312374b.png)

Works for me.
Also, that stack trace is not Noice?

You don't seem to be using the Noice hover?

**Comment by igorlfs** [comment]
> You don't seem to be using the Noice hover?

That's odd, Noice's checkhealth shows
```
- OK `vim.lsp.handlers["textDocument/hover"]` is set to **Noice**
```
Am I missing something? My config is
```lua
    messages = {
        view_search = false,
    },
    lsp = {
        override = {
            ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
            ["vim.lsp.util.stylize_markdown"] = true,
            ["cmp.entry.get_documentation"] = true,
        },
    },
    presets = {
        lsp_doc_border = true, -- add a border to hover docs and signature help
    },
```

**Comment by folke** [comment]
What LSP are you using? I'm using pyright for python

**Comment by folke** [comment]
How do you trigger the hover? Which command?

**Comment by igorlfs** [comment]
I'm using `pylsp`, which should support hover. Testing with `pyright` works, though! 

Any tips on where should I report the issue, then? Pylsp's repo or neovim's?

**Comment by folke** [comment]
I still don't understand that code path. how do you trigger the hover?

**Comment by igorlfs** [comment]
Using `vim.lsp.buf.hover`, triggered with a keymap

**Comment by folke** [comment]
Can you try with `require("noice.lsp").hover()` instead and see if the issue is still there?

It really seems like the Noice handler is not invoked

**Comment by igorlfs** [comment]
Using `require("noice.lsp").hover()` works!

**Comment by folke** [comment]
ok, are you setting handlers on your lsp config? Those would be used instead of the default ones. Do you use any other lsp specific plugins like lsp saga? One of those things is messing up your handlers

**Comment by igorlfs** [comment]
> ok, are you setting handlers on your lsp config? 
Yup! That was the culprit! Sorry for the mess 😅
