### ISSUE TITLE
bug: `:nmap` output is having wrong linebreaks

### ISSUE THREAD

**Issue by pysan3** [folke/noice.nvim#259]
**Describe the bug**

Hi, thank you for an amazing plugin!

The output of listing the defined mappings seems to be quite weird.
For example in my case, I have multiple keybinds that start from `<leader>f`. When I execute `:nmap <leader>f` to list all of them, the alignment seems to go wrong as posted in the **Screenshots** section.

The expected behavior is to have a linebreak on each keybind and the line should be like this.
(Default behavior without noice plugin is shown in **Expected Behavior** section.)
```txt
n   <Space>fa  *  <function>
                  Description
n   <Space>fb  *  <function>
                  Description
```

**Screenshots**

I have a route that routes `msg_show` with more than 5 lines to `messages` but it seems to not matter because it happens even without it.

- w/ route
![Screenshot_20221205_035121](https://user-images.githubusercontent.com/41065736/205509877-80f6c06c-d070-4a99-9a74-ec14d08a4389.png)
- w/o route
![Screenshot_20221205_040408](https://user-images.githubusercontent.com/41065736/205510167-040d6f5d-caaa-4bd6-8d75-c80c159a46ce.png)

**Which version of Neovim are you using?**

Stable, compiled on my machine.
On Linux / Manjaro / Alacritty
```txt
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**To Reproduce**
1. `:nmap <leader>f`
  \* `<leader>f` could be anything

**Expected Behavior**

Each keybind description should be printed in new line.
![Screenshot_20221205_034933](https://user-images.githubusercontent.com/41065736/205509865-9311bfe4-8f52-4f25-9f41-2c367d306c51.png)

**My noice setup**
```lua
require("noice").setup({
  messages = {
    enabled = true,
    view = "notify", -- default view for messages
    view_error = "notify", -- view for errors
    view_warn = "notify", -- view for warnings
    view_history = "messages", -- view for :messages
  },
  health = { checker = false },
  lsp = {
    progress = { enabled = false },
    override = {},
    hover = { enabled = false },
    signature = { enabled = false },
    message = { enabled = false },
  },
  presets = {
    bottom_search = false, -- use a classic bottom cmdline for search
    command_palette = true, -- position the cmdline and popupmenu together
    long_message_to_split = false, -- long messages will be sent to a split
    inc_rename = false, -- enables an input dialog for inc-rename.nvim
    lsp_doc_border = false, -- add a border to hover docs and signature help
  },
  routes = {
    { -- route long messages to split
      filter = { event = "msg_show", any = { { min_height = 5 }, { min_length = 200 } } },
      view = "messages",
      opts = { stop = true },
    },
  },
  views = {
    split = {
      win_options = { wrap = false },
      size = 16,
      close = { keys = { "q", "<CR>", "<Esc>" } },
    },
  },
})

vim.api.nvim_set_keymap("n", "<Leader>n", "<Cmd>Noice<CR>", {})
```

**Noice Log**

- No noticeable output to `:Noice log`.
- Sorry if I'd missed it but is there smtg like a `trace = true` setting?

**Comment by folke** [comment]
It does indeed https://github.com/neovim/neovim/issues/20715

**Comment by pysan3** [comment]
Oh, I somehow missed it. Sorry.

Thanks for linking.

**Comment by pysan3** [comment]
For those who came across this issue, I've implemented a workaround in the `init` function here.

https://github.com/pysan3/dotfiles/blob/8b57c9965aabe3a0ed0de932c1653a389c0b666d/nvim/lua/plugins/20-noice.lua

It defines commands `:NMap` for `:nmap`, `:IMap` for `:imap` and so on.

Feel free to ping me if it breaks ;)

### Usage

`:NMap <filter>` (normal map)

- e.g. `:NMap <Leader>k`
![image](https://github.com/folke/noice.nvim/assets/41065736/351f518d-da3b-49f0-9343-87bd2e8981f0)

All other modes are also available; `:IMap`, `:VMap` ...

If you don't pass `<filter>` it will print all keybinds.
