### ISSUE TITLE
Plugin error when starting Neovim on WSL2

### ISSUE THREAD

**Issue by marcfyk** [folke/noice.nvim#26]
**Describe the bug**
Starting neovim on WSL2 Ubuntu with noice.nvim installed with packer and received an error:

Currently using the default packer snippet to manage the plugin:
```
-- Packer
use({
  "folke/noice.nvim",
  event = "VimEnter",
  config = function()
    require("noice").setup()
  end,
  requires = {
    -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
    "MunifTanjim/nui.nvim",
    "rcarriga/nvim-notify",
    }
})
```

**What version of Nevoim are you using?**
neovim version: 0.8.0
![image](https://user-images.githubusercontent.com/39775611/194083440-debd8d2a-f3e1-4d52-a26f-f628d258a795.png)

**To Reproduce**
Start neovim in WSL2 Ubuntu

**Expected behavior**
Expected to have no error message on starting neovim

**Screenshots**
errors:
![image](https://user-images.githubusercontent.com/39775611/194082731-c910ca3d-fec3-4428-a551-6a041416b751.png)
![image](https://user-images.githubusercontent.com/39775611/194092548-3af79aa6-ac79-4e7b-a1e3-c91bef6d61b8.png)

**Noice log**
output from running  `:Noice log`
![image](https://user-images.githubusercontent.com/39775611/194092765-6bbb5363-612d-4590-9079-007ca53c92e3.png)

**Comment by folke** [comment]
That's odd. Please report an issue upstream for this.

**Comment by folke** [comment]
It really seems you're not on 0.8.0.

`vim.ui_attach` does not exist in 0.7 and `vim.cmd.whatever` neighter.

Both are new additions to 0.8.0

**Comment by folke** [comment]
Can you do `:version` inside Neovim?

**Comment by marcfyk** [comment]
Hi, I tried building neovim from source to use the latest version and it works now. It seems that 0.8.0-dev is behind 0.8.0? Either way, thanks for the help!
