### ISSUE TITLE
query.lua:219: query: invalid node type at position 2765 for language vim

### ISSUE THREAD

**Issue by yofriadi** [folke/noice.nvim#260]
**Describe the bug**
../nvim/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

**Which version of Neovim are you using?**
neovim v0.8.1

**To Reproduce**
1. install
2. press :
3. after typing error shown

**Expected Behavior**
no error

**Other details**
I am on WSL, this doesn't happen though on macOS

**Comment by folke** [comment]
That's treesitter. Try running `TSUpdate` and if that doesn't help check further in the nvim-treesitter docs. Not caused by Noice

**Comment by yofriadi** [comment]
for future reference https://github.com/nvim-treesitter/nvim-treesitter/issues/3934

in short, remove your `../lib/nvim/parser`
