### ISSUE TITLE
avoid hijacking messages for `:recover`

### ISSUE THREAD

**Issue by msva** [folke/noice.nvim#262]
Hi!

Can you advice me how to set up `noice` to not hijack (to notifications) messages output from `:recover` command, please?
Without that it is impossible to recover file if there is multiple swap files :-/
(it is even impossible to see the recover message until pressing `Esc` to cancel it (it is only goes to notificatons after that).

**Comment by folke** [comment]
That will have to wait till https://github.com/neovim/neovim/pull/18375 gets merged

**Comment by msva** [comment]
btw, @folke, can you, please, advice, is it possible to map some key to, for example, _somee noice function_ (or whatever), to clean all the notifications out of the screen? maybe even on noice config?

Or should I dig in the direction of nvim-notify itself?

**Comment by folke** [comment]
check nvim-notify docs
