### ISSUE TITLE
Could you support shadow border?

### ISSUE THREAD

**Issue by nyngwang** [folke/noice.nvim#266]

**Comment by folke** [comment]
It is supported? Have you checked the docs? Nui docs?

**Comment by nyngwang** [comment]
I got this error:

<img src="https://user-images.githubusercontent.com/24765272/208059947-88805149-7d25-488b-ada7-c21055d4bdfa.png" width="400">

**Comment by folke** [comment]
Read the error message. You cant have a shadow border with a text, so you need to remove the text.

**Comment by folke** [comment]
Also, as you can see this is Nui, so if you feel that a shadow border should support text, you'd have to ask it there

**Comment by MunifTanjim** [comment]
I see that the built-in `nvim_open_win()` now also supports border text. And text with shadow border is not supported there as well. Since shadow doesn't really have any border to put the text on.

**Comment by nyngwang** [comment]
@folke: This is my full `setup`. I didn't use anything related to `text` so I don't understand the error message. SOrry

```lua
config = function ()
  local win_info = vim.fn.getwininfo()[1]
  local center_pos = {
    position = {
      row = math.floor(win_info.height/3),
      col = '45%',
    },
    size = { width = '50%' },
    border = { style = 'shadow' },
  }
  require('noice').setup {
    views = {
      cmdline_popup = center_pos,
      popupmenu = center_pos,
    },
    lsp = {
      -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
      override = {
        ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
        ['vim.lsp.util.stylize_markdown'] = true,
        ['cmp.entry.get_documentation'] = true,
      },
    },
  }
  -- vim.keymap.set('n', '<Leader>ar', function () vim.cmd('CellularAutomaton make_it_rain') end, NOREF_NOERR_TRUNC)
end

```

**Comment by folke** [comment]
@nyngwang I just made a new release so that `shadow` should work, without needing to make adjustments to the border title. https://github.com/folke/noice.nvim/releases/tag/v1.4.2

@MunifTanjim fyi: popup padding messes up the layout when border is set to `shadow`. As a work-around I now set `padding=nil` when the border style is set to `shadow`

**Comment by nyngwang** [comment]
Thanks for your helps :) Now I can make noice.nvim more beautiful. (I will form a better issue the next time... sorry if it might cause any misunderstood...)

**Comment by MunifTanjim** [comment]
@folke `border.padding` should now work with `border.style=shadow`:
- https://github.com/MunifTanjim/nui.nvim/pull/219
- https://github.com/MunifTanjim/nui.nvim/pull/220

**Comment by folke** [comment]
@MunifTanjim thanks! Removed the work-around.
