### ISSUE TITLE
Delay When Typing in Cmdline

### ISSUE THREAD

**Issue by UnrealApex** [folke/noice.nvim#27]
**Describe the bug**
There is latency between pressing a key and the output appearing in the cmdline. This is probably because the cmdline window is "fake". Perhaps instead of emulating a cursorline and displaying text typed, have an actual window you can type text in and send the input to `vim.cmd`? Take my suggestion with a grain of salt, I have not looked at how you implemented this and you are far more experienced than I am creating lua plugins.

**What version of Nevoim are you using?**
Gui

**To Reproduce**
1. Open the cmdline with `:`
2. Type anything
**Expected behavior**
Typed text would appear almost immediately.

**Noice log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>

10/4/2022 9:33:43 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>
	[C]: in function 'nvim_err_writeln'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\install.lua:169: in function 'cb'
	vim/_editor.lua:262: in function <vim/_editor.lua:261>

10/4/2022 9:53:47 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:200: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 9:53:52 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:200: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 9:57:08 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:195: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 10:49:06 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: Vim(append):Error executing lua callback: ...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: Keyboard interrupt
stack traceback:
	[C]: in function 'nvim_buf_set_option'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: in function 'enable_syntax'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:175: in function 'detach'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:490: in function 'detach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:499: in function 'reattach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:108: in function <...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:107>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 10:50:17 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: Vim(append):Error executing lua callback: ...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: Keyboard interrupt
stack traceback:
	[C]: in function 'nvim_buf_set_option'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:151: in function 'enable_syntax'
	...lugged\nvim-treesitter/lua\nvim-treesitter\highlight.lua:169: in function 'attach'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:477: in function 'attach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:500: in function 'reattach_module'
	...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:108: in function <...\plugged\nvim-treesitter/lua\nvim-treesitter\configs.lua:107>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:97: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:96>
	[C]: in function 'nvim_buf_set_option'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\utils\init.lua:129: in function 'set_buf_options'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:142: in function 'render'
	...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:137: in function <...ers\Aaron\.vim\plugged\noice.nvim/lua\noice\view\nui.lua:126>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

10/4/2022 10:53:21 PM
C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: end_col value outside range

stack traceback:
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:102: in function <...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:101>
	[C]: in function 'nvim_buf_set_extmark'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\text\init.lua:67: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\nui.nvim/lua\nui\line\init.lua:55: in function 'highlight'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\block.lua:72: in function 'highlight'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:151: in function 'render'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:57: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:48>
	...
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\hacks.lua:195: in function 'push'
	C:\Users\Aaron\.vim\plugged\nvim-notify/lua\notify\init.lua:214: in function 'notify'
	...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:102: in function <...\Aaron\.vim\plugged\noice.nvim/lua\noice\view\notify.lua:74>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:107: in function 'try'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\view\init.lua:81: in function 'display'
	C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:91: in function <C:\Users\Aaron\.vim\plugged\noice.nvim/lua\noice\router.lua:75>
	[C]: in function 'xpcall'
	...rs\Aaron\.vim\plugged\noice.nvim/lua\noice\util\call.lua:107: in function 'try'
	...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:29: in function <...sers\Aaron\.vim\plugged\noice.nvim/lua\noice\ui\init.lua:22>

</pre>
</details>
sidenote: I noticed you started using details element to conceal the log output in issue templates, thanks for taking my issue as inspiration!

**Comment by folke** [comment]
I experimented with native cursors, but that leads to a whole lot of issues due to autocmds that are triggered when entering the cmdline window. But even with the native cursors, you're still only looking at a view of the cmdline.

I simply receive events from Neovim, that tell me what the cmdline is and where the position should be for the cursor.

Thinking about it, native cursors would have a similar delay.

I honestly don't notice any delays. Is it very noticable for you?

And yes, great idea to use details for the logs!

**Comment by Shougo** [comment]
I think you should create the minimal init.vim.

**Comment by UnrealApex** [comment]
> I experimented with native cursors, but that leads to a whole lot of issues due to autocmds that are triggered when entering the cmdline window. But even with the native cursors, you're still only looking at a view of the cmdline.
> 
> I simply receive events from Neovim, that tell me what the cmdline is and where the position should be for the cursor.

> 
> Thinking about it, native cursors would have a similar delay.

I understand.

> I honestly don't notice any delays. Is it very noticable for you?

Yep, the delay is around a second. This is unlikely but perhaps inputting keys too fast might be the problem?

**Comment by UnrealApex** [comment]
> I think you should create the minimal init.vim.

Clarify how this would improve Noice's performance. What do you think I would need to do to make it more minimal? Have you checked my Neovim [config](https://github.com/UnrealApex/dotfiles)?

**Comment by Shougo** [comment]
If it is noice.nvim problem, it must be reproduced by other people.
Your configuration is too long to test.

**Comment by folke** [comment]
@UnrealApex it should be less than a ms at least. Can you post your config?

As @Shougo mentioned, a minimal init.lua would be great to be able to reproduce.

**Comment by UnrealApex** [comment]
Hmm, it seems that the delay is probably coming from one of the plugins I have installed. Any ideas of what plugin might be causing this?

**Comment by Shougo** [comment]
Oh, the list is too long.  You should disable plugins one by one...

**Comment by UnrealApex** [comment]
Good idea! I was considering doing this but did not out of laziness.

**Comment by UnrealApex** [comment]
Oddly enough, it appears that treesitter is causing a majority of the delay.

**Comment by Shougo** [comment]
It means vim treesitter highlight?
It should be disabled in noice.nvim cmdline.

**Comment by folke** [comment]
@UnrealApex do you have any more information on why treesitter is causing this? Or does the delay just disappear without treesitter?

Treesitter is good to be enabled for highlighting, since it supports language injections, which means typing `:lua ...` will highlight the part after lua as lua.

**Comment by UnrealApex** [comment]
I am not sure the about the exact cause of the delay. As you suggested, it just disappears when treesitter is disabled. If it helps, here is my treesitter config:
```lua
local configs = require("nvim-treesitter.configs")
configs.setup {
  ensure_installed = "all",
  sync_install = false, 
  ignore_install = { "" }, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { "" }, -- list of language that will be disabled
    additional_vim_regex_highlighting = true,

  },
  indent = { enable = true, disable = { "yaml" } },
}

```

**Comment by folke** [comment]
`additional_vim_regex_highlighting` is really bad. It honestly should not be an option in treesitter. Disable it and test again.

**Comment by folke** [comment]
Indent also causes performance issue in Treesitter, so might also be the culprit

**Comment by Shougo** [comment]
It seems your configuration issue.  Close?

**Comment by UnrealApex** [comment]
Setting `additional_vim_regex_highlighting` and `indent` both caused the problem. Thank you!
