### ISSUE TITLE
nvim-cmp integration breaks lazy-loading with lazy.nvim

### ISSUE THREAD

**Issue by mrjones2014** [folke/noice.nvim#272]
**Describe the bug**
Hi, this morning I am trying out your new plugin manager, `lazy.nvim`. It's really really impressive, it cut my startup time literally in half, more actually. So thanks for that.

When running `:Lazy profile` I noticed that the `VeryLazy` event is loading `nvim-cmp` because I have `VeryLazy` loading `noice.nvim`, and `noice.nvim` in turn `require`s `nvim-cmp` to patch the documentation window. This should be done in a manner compatible with lazy loading if possible.

**Which version of Neovim are you using?**
Neovim nightly

**To Reproduce**
1. Enable the `nvim-cmp` integration of `noice.nvim`
2. Lazy load `noice.nvim` with `lazy.nvim` on the `VeryLazy` event
3. `nvim-cmp` is loaded with `noice.nvim`

**Expected Behavior**
`nvim-cmp` is not loaded until it would normally be loaded otherwise, without the `noice.nvim` integration.

---

Is there a way to not load `nvim-cmp` to apply the patch until it would normally otherwise be loaded? perhaps you could offer a function that applies the patch, that I could call in my `nvim-cmp` config?

**Comment by folke** [comment]
I actually fixed that in noice a couple of days ago. Did you maybe set `version=...` for noice?

**Comment by mrjones2014** [comment]
Ah, I think actually I was using a local version of `noice.nvim` I had on disk that I hadn't updated in a few days, since I was messing with some config stuff. Deleting the local repo/making `lazy.nvim` not use the local repo fixed it. Thanks, and really amazing work on `lazy.nvim`!
