### ISSUE TITLE
Allow customizing icons for `mini` view

### ISSUE THREAD

**Issue by clason** [folke/noice.nvim#274]
If one is not using a nerdfont, it's possible to customize the icons for the `cmdline`. However, this is not possible for the `mini` view, so, e.g., `Error`s  are prefixed with a "broken font" symbol.

An easier (and possibly preferable) approach would be to allow disabling icons altogether (`icons = false`).

**Comment by folke** [comment]
I don't think I added any special icons to error messages etc. Are these messages coming from `vim.notify?`

**Comment by folke** [comment]
Oh, neremind. I do add icons :)

**Comment by clason** [comment]
Note to self: don't set `icons = false`; this will freeze Neovim _hard_ ...

**Comment by clason** [comment]
Hmm, this doesn't seem to work?

**Comment by clason** [comment]
Hmm, I can't seem to get this to work. Would you mind telling me the exact line I need to put in the `setup` call?

**Comment by clason** [comment]
Works, thank you!
