### ISSUE TITLE
Provide `quickfix` list support

### ISSUE THREAD

**Issue by utilyre** [folke/noice.nvim#279]
**Is your feature request related to a problem? Please describe.**

I've always hated the way `quickfix` is designed in vim. It doesn't provide any preview and it is, in fact, just another horizontally split window that clutters my workflow.

**Describe the solution you'd like**

So I'd like to (optionally) have a floating window that displays each item nicely (I mean with highlighting and stuff for better distinction) and shows a preview of the item in the corresponding buffer inside another window. Long story short, something like nvim-telescope.

In addition, I'd like an API/keymap to toggle the last/current `quickfix`.

**Describe alternatives you've considered**

I guess, an alternative would be just overriding `quickfix` API (not sure if it's even a thing) with nvim-telescope.

**Additional context**

I think [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) would be a great inspiration.

https://user-images.githubusercontent.com/17562139/137736502-91d32251-96a2-4c3f-ba74-65cfd336473e.mp4

**Comment by folke** [comment]
Not going to add this
