### ISSUE TITLE
Command window support

### ISSUE THREAD

**Issue by musjj** [folke/noice.nvim#283]
**Is your feature request related to a problem? Please describe.**
I wanted to route the command window (`q:`) to the `popup` view, but it seems that it's not a part of the supported events.
It would also be nice if treesitter highlighting is supported, since treesitter for some reason doesn't work with the default command window.

**Describe the solution you'd like**
Support overriding the command window.

**Comment by folke** [comment]
That's not possible. The command window is a very special window in Neovim, and can't be touched by any other code.
