### ISSUE TITLE
Noice hijacks code actions and other innocent popups

### ISSUE THREAD

**Issue by paveloom** [folke/noice.nvim#284]
**Describe the bug**
Noice presents options from a popup as a message. It also doesn't display the message again when called right after. 

**Which version of Neovim are you using?**
NVIM v0.9.0-dev-535+gec1738a6e
Build type: Release
LuaJIT 2.1.0-beta3

**To Reproduce**
1. Here's a minimal configuration file for Neovim:
	```lua
	-- Define the local root path
	local root = vim.fn.fnamemodify("./.repro", ":p")
	
	-- Set standard paths to use the local root path
	for _, name in ipairs({ "config", "data", "state", "cache" }) do
	  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
	end
	
	-- Bootstrap Lazy
	local lazypath = root .. "/plugins/lazy.nvim"
	if not vim.loop.fs_stat(lazypath) then
	  vim.fn.system({
	    "git",
	    "clone",
	    "--filter=blob:none",
	    "--single-branch",
	    "https://github.com/folke/lazy.nvim.git",
	    lazypath,
	  })
	end
	vim.opt.runtimepath:prepend(lazypath)
	
	-- Install plugins
	local plugins = {
	  "folke/tokyonight.nvim",
	  {
	    "folke/noice.nvim",
	    dependencies = {
	      "MunifTanjim/nui.nvim",
	      "rcarriga/nvim-notify",
	    },
	  },
	  "neovim/nvim-lspconfig",
	}
	require("lazy").setup(plugins, {
	  root = root .. "/plugins",
	})
	
	-- Setup the theme
	vim.opt.termguicolors = true
	vim.cmd([[colorscheme tokyonight]])
	
	-- Setup the plugins
	require("noice").setup()
	require("lspconfig").sumneko_lua.setup({
	  single_file_support = true,
	  on_attach = function(_, bufnr)
	    -- Show code actions
	    vim.keymap.set("n", "ga", vim.lsp.buf.code_action, {
	      noremap = true,
	      silent = true,
	      buffer = bufnr,
	    })
	  end,
	  settings = {
	    Lua = {
	      hint = {
	        enable = true,
	        setType = true,
	      },
	      runtime = {
	        version = "LuaJIT",
	      },
	      diagnostics = {
	        globals = { "vim" },
	      },
	      workspace = {
	        checkThirdParty = false,
	        library = vim.api.nvim_get_runtime_file("", true),
	      },
	      telemetry = {
	        enable = false,
	      },
	    },
	  },
	})
	
	-- Try pressing `ga` a couple of times 
	-- on the diagnostic location
	local hey = 0
	```
    Save it as `init.lua` and run with `nvim -u init.lua init.lua`.
2) Try pressing `ga` a couple of times on the unused variable at the bottom of the file.

**Expected Behavior**
Perhaps, something similar to what [`dressing.nvim`](https://github.com/stevearc/dressing.nvim) does. Just a small list near the cursor.

**Screenshots**
![image](https://user-images.githubusercontent.com/49961859/209814287-d0949fa7-7305-4a99-a1f6-37856f44e06b.png)

Here's also me pressing `<C-f>` when using [Mason](https://github.com/williamboman/mason.nvim) in my config:

![image](https://user-images.githubusercontent.com/49961859/209814716-3bf7ba25-5599-4d69-8a79-f709490366a5.png)

**Noice Log**
There is no log.

**Comment by folke** [comment]
Noice doesn't hijack `vim.ui`. It's just that default for vim.ui uses nvim_echo, which will be captured by noice as part of `ext_messages`. No way around that. 

I use dressing.nvim myself.
