### ISSUE TITLE
Hiding write notifications based on the recipe depends on shortmess not having the w or a flag set

### ISSUE THREAD

**Issue by hermitmaster** [folke/noice.nvim#290]
**Describe the bug**
The [recipe](https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#hide-written-messages) does not work if `shortmess` has the `w`, and by extension `a`, flag enabled.

**Which version of Neovim are you using?**
```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info 
```

**To Reproduce**
1. Copy the config from the above referenced recipe
2. `:set shortmess+=a`
3. Write a buffer

**Expected Behavior**
No notifications for writes.

**Screenshots**
<img width="1550" alt="Screen Shot 2022-12-29 at 5 26 04 PM" src="https://user-images.githubusercontent.com/68909555/210020588-af6a0770-373b-4f81-8fbc-28ee0a116507.png">

**Noice Log**
No log, not really an "error"

**Comment by hermitmaster** [comment]
BTW, thanks for the fantastic plugins!

**Comment by folke** [comment]
You are right, so just change the code? I can't possibly provide a recipe for every different Neovim config.

**Comment by hermitmaster** [comment]
I did change my shortmess settings, just thought it might be worth noting in the wiki. Thanks again!
