### ISSUE TITLE
Auto open cmdline suggestions

### ISSUE THREAD

**Issue by mosheavni** [folke/noice.nvim#294]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
When on the command window, if I hit `<Tab>`, it suggests completion in a popup window, is there an option to auto open the suggestion completions popup when I'm typing?

![image](https://user-images.githubusercontent.com/17252601/210135066-90821c39-716f-44c3-9427-f557daf5766f.png)

**Comment by folke** [comment]
that's not possible as I answered multiple times before. The noice popupmenu **IS** the native popupmenu. That behavior does not exist for the NEovim popupmenu

**Comment by Shougo** [comment]
If you need the feature, you need to install auto completion plugins.

**Comment by farzadmf** [comment]
Hey @Shougo , sorry if this is a stupid question, but when you say

> you need to install auto completion plugins

does it mean it's possible to get completion in, say, noice's cmdline menu, while typing (using `nvim-cmp` for example)? If so, are there any resources/pointers to know more?

**Comment by Shougo** [comment]
> does it mean it's possible to get completion in, say, noice's cmdline menu, while typing (using nvim-cmp for example)? If so, are there any resources/pointers to know more?

I don't know `nvim-cmp` supports noice.nvim command line.
`ddc.vim` + `pum.vim` supports it.

**Comment by farzadmf** [comment]
Thank you @Shougo , are there any docs/resources somewhere on how to connect them together?

**Comment by Shougo** [comment]
You need to enable command line auto completion like this.

```
Q: I want to enable command line completion by ddc.vim.

A: Note: "pum.vim" is required.

https://github.com/Shougo/pum.vim
https://github.com/Shougo/ddc-ui-pum
>
	call ddc#custom#patch_global('ui', 'pum')
	call ddc#custom#patch_global('autoCompleteEvents',
	\ ['InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineChanged'])
	nnoremap :       <Cmd>call CommandlinePre()<CR>:
	
	function! CommandlinePre() abort
	  cnoremap <Tab>   <Cmd>call pum#map#insert_relative(+1)<CR>
	  cnoremap <S-Tab> <Cmd>call pum#map#insert_relative(-1)<CR>
	  cnoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
	  cnoremap <C-p>   <Cmd>call pum#map#insert_relative(-1)<CR>
	  cnoremap <C-y>   <Cmd>call pum#map#confirm()<CR>
	  cnoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
	
	  " Overwrite sources
	  if !exists('b:prev_buffer_config')
	    let b:prev_buffer_config = ddc#custom#get_buffer()
	  endif
	  call ddc#custom#patch_buffer('cmdlineSources',
	  \ ['necovim', 'around'])
	
	  autocmd User DDCCmdlineLeave ++once call CommandlinePost()
	  autocmd InsertEnter <buffer> ++once call CommandlinePost()
	
	  " Enable command line completion
	  call ddc#enable_cmdline_completion()
	endfunction
	function! CommandlinePost() abort
	  silent! cunmap <Tab>
	  silent! cunmap <S-Tab>
	  silent! cunmap <C-n>
	  silent! cunmap <C-p>
	  silent! cunmap <C-y>
	  silent! cunmap <C-e>
	
	  " Restore sources
	  if exists('b:prev_buffer_config')
	    call ddc#custom#set_buffer(b:prev_buffer_config)
	    unlet b:prev_buffer_config
	  else
	    call ddc#custom#set_buffer({})
	  endif
	endfunction
```

**Comment by farzadmf** [comment]
Thank you @Shougo for the answer, I guess it doesn't have a Lua equivalent, does it?

**Comment by Shougo** [comment]
Yes.  It is Vim script plugin.

**Comment by shelper** [comment]
@Shougo  newbie here, could you explain a little bit more on how to setup this so the autocompletion works as mentioned in @mosheavni  's suggestion?

I can install cmp-cmdline but i found it mixes up with noice. i can disable noice, but i dont get the UI that moves the cmd input to the top center of my window.  see below, there are two popups, one from cmp-cmdline, one from noice....

![image](https://user-images.githubusercontent.com/546163/216161673-2d193e62-87ab-4fb5-9b8b-84990eff001c.png)

**Comment by farzadmf** [comment]
Hey @shelper , question: the one being covered, is it appearing without pressing `TAB`? If so, how do you set it up to appear?

I think that's the one from `noice` that only appears with `TAB`?

**Comment by shelper** [comment]
That's right I pressed tab and that shows up

**Comment by Shougo** [comment]
@shelper Sorry.  I have tested it but noice.nvim does not work in minimal init.vim.

```vim
set rtp+=~/src/nvim-cmp
set rtp+=~/src/cmp-buffer
set rtp+=~/src/cmp-cmdline
set rtp+=~/src/noice.nvim
set rtp+=~/src/nui.nvim

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    mapping = {
      ['<CR>'] = cmp.mapping.confirm {
        behavior = cmp.ConfirmBehavior.Replace,
        select = true,
      },
      ['<tab>'] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', 'c' }),
      ['<C-p>'] = cmp.mapping.select_prev_item(),
      ['<C-n>'] = cmp.mapping.select_next_item(),
    },
    sources = {
      { name = 'buffer' },
    },
    completion = {
      autocomplete = {
        cmp.TriggerEvent.TextChanged,
        cmp.TriggerEvent.InsertEnter,
      },
      completeopt = 'menu,menuone,noselect'
    }
  })
  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'cmdline' }
    }
  })

  require'noice'.setup {
    cmdline = {
      enabled = true,
      format = {
        cmdline = { pattern = "^:", icon = ":", lang = "vim" },
        search_down = { kind = "search", pattern = "^/", icon = "/", lang = "regex" },
        search_up = { kind = "search", pattern = "^%?", icon = "?", lang = "regex" },
        filter = { pattern = "^:%s*!", icon = "$", lang = "bash" },
        lua = { pattern = "^:%s*lua%s+", icon = "", lang = "lua" },
        help = { pattern = "^:%s*he?l?p?%s+", icon = "" },
        input = {}, -- Used by input()
        -- lua = false, -- to disable a format, set to `false`
      },
    },
    popupmenu = {
      enabled = false,
    },
    messages = {
      enabled = true,
    },
    routes = {
      {
        view = "mini",
        filter = {
          event = { "msg_show", "msg_showmode" },
          ["not"] = {
            kind = { "confirm", "confirm_sub" },
          },
        },
      },
      {
        filter = {
          event = "cmdline",
          find = "^%s*[/?]",
        },
        view = "cmdline",
      },
    },
  }

EOF

runtime! after/plugin/*.lua
```

I don't know why.  And `noice.nvim` works when my vimrc with ddc.vim.

**Comment by Shougo** [comment]
![2023-02-02_09-02-1675298711](https://user-images.githubusercontent.com/41495/216202988-6d6d66db-e0fc-4528-9dd8-eccdb946a2d4.png)

Hm.  `nvim-cmp` + `noice.nvim` works for me.  What is the problem?

**Comment by shelper** [comment]
I tried your config and it works but it does not select the first item by default, has to tab then enter....
> Hm. `nvim-cmp` + `noice.nvim` works for me. What is the problem?
