### ISSUE TITLE
is it possible now to make command mode as in default novim (under statusline), and displaying a colon at the beginning of commands?

### ISSUE THREAD

**Issue by brxxlstxrs** [folke/noice.nvim#295]
is it possible to turn off the UI design for the command line, leaving the distance
under the statusline, and keeping the original experience? (in general, and that's what I wrote in the title)

**Comment by folke** [comment]
If you want to disable the command line then yes that's possible. Check the docs. I don't get why people dont simply read the documentation.

**Comment by brxxlstxrs** [comment]
> If you want to disable the command line then yes that's possible. Check the docs. I don't get why people dont simply read the documentation.

but if i disable it i cant see it, or if I set cmdline mode - only status line or cmdline only is shown

**Comment by folke** [comment]
What do you mean?

**Comment by brxxlstxrs** [comment]
> What do you mean?

I mean, the cmdline view is not like that and it is not under statusline

**Comment by folke** [comment]
Did you set cmdheight=0? You should set it to 1 if you want both statusline and cmdline. And of course disable it in noice too then.

**Comment by brxxlstxrs** [comment]
but cmdheight = 1 and I have and still not working
```lua
local opts = {
  cmdline = {
    enabled = false,
  },
}

noice.setup(opts)
vim.opt.cmdheight = 1
```

**Comment by folke** [comment]
Did you read this part?
![image](https://user-images.githubusercontent.com/292349/210141085-135ec9a4-1b17-483c-b37c-8924950f1e22.png)

Is that what you mean?

You need to disable messages too

**Comment by brxxlstxrs** [comment]
Oh thanks!

**Comment by UnrealApex** [comment]
> Did you set cmdheight=0? You should set it to 1 if you want both statusline and cmdline. And of course disable it in noice too then.

@folke I am experiencing this issue too. I have my cmdheight set to 1.

**Comment by folke** [comment]
As I said before, you also need to disable noice messages. This is a Neovim limitation, not noice

**Comment by UnrealApex** [comment]
I also have messages disabled:
```lua
require('noice').setup({
  cmdline = {
    view = "cmdline",
  },
  messages {
    enabled = false
  }
})
```

**Comment by folke** [comment]
@UnrealApex what is the issue you are having? As i mentioned before, cmdheight can not work if you enable noice cmdline.

**Comment by UnrealApex** [comment]
Noice hijacks my statusbar(lualine).


> @UnrealApex what is the issue you are having? As i mentioned before, cmdheight can not work if you enable noice cmdline.

I see. I was a little confused because in one of your [previous](https://github.com/folke/noice.nvim/issues/295#issuecomment-1368231383) comments on this issue , you stated that it would work. I assumed by cmdline you meant Noice's cmdline UI, not the actual command line mode.
