### ISSUE TITLE
Neovim crashes when trying to enter command line

### ISSUE THREAD

**Issue by sugiura-hiromichi** [folke/noice.nvim#297]
**Describe the bug**
I can't enter cmdline mode because if I type `:`, neovim quickly end.

**Which version of Neovim are you using?**
```zsh
nvim -v
NVIM v0.9.0-dev-590+g6ba34e21f-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by r@rR.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-6ba34e2/share/nvim"

Run :checkhealth for more info
```

**To Reproduce**
1. here is neovim setting
```lua
	use {
		'folke/noice.nvim',
		event = 'VimEnter',
		config = function()
			require('noice').setup {}
		end,
	}
-- dependencies are installed
```
2. enter neovim normally
3. type `:`

**Expected Behavior**
enter cmdline mode, appear popup.

**Noice Log**
can't execute `:Noice log` because I can't enter cmdline mode.

**Comment by folke** [comment]
Noice can't crash Neovim. This is most likely a Neovim issue. You should create a minimal init.lua as explained in the wiki. Also refer to the Neovim docs on how to get a stacktrace. Once you have that, you can report an issue for Neovim https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#reporting-problems
