### ISSUE TITLE
[bug] highlight flicker in search window

### ISSUE THREAD

**Issue by max397574** [folke/noice.nvim#3]
https://user-images.githubusercontent.com/81827001/193349030-a0b12d75-6306-4996-b76e-74578becbc6e.mov

**Comment by folke** [comment]
Some flickering during search is to be expected for now, since we have to redraw the ui while in blocking mode.

Related to https://github.com/neovim/neovim/issues/17810

Although, for me the flickering is almost invisible.

Can you see if the latest version still flickers as much as in your recording?

**Comment by max397574** [comment]
it's better
you can decide if you want to leave this issue open or close it

**Comment by folke** [comment]
I'll close it for now. The incsearch issue is linked in the traking issue.

**Comment by max397574** [comment]
would it be possible to disable noice for `/` ?

**Comment by folke** [comment]
@max397574 that's not possible unfortunately.

However, I did fix an issue that caused more flickering than needed, so check the latest version and see if it's better there.

**Comment by Meow-2** [comment]
@folke is there a way to disable 'incsearch' highlight in cmdline?

**Comment by Shougo** [comment]
@Meow-2 `:help hl-IncSearch`

**Comment by folke** [comment]
@Meow-2 fixed in the latest version!

**Comment by nfwyst** [comment]
> @max397574 that's not possible unfortunately.
> 
> However, I did fix an issue that caused more flickering than needed, so check the latest version and see if it's better there.

yeah, maybe offer an option to disable fix_incsearch is better

**Comment by max397574** [comment]
it could very well be (and also that's how I understood that) that it's not possible to add such a thing since this is part of ext_cmdline and you can't just disable parts of it
