### ISSUE TITLE
Ugly notification with `which-key`

### ISSUE THREAD

**Issue by kuntau** [folke/noice.nvim#301]
**Is your feature request related to a problem? Please describe.**
Default which-key options which have `show_help=true` and `show_keys=true` give very long notification with `nvim-notify` because which-key try show nice `messages` with padding from for `<BS> to go back ... `

It get worse if you get multiple of that notification which can block most of the screen. 

**Describe the solution you'd like**
If possible remove those extra middle padding would be nice. 

**Describe alternatives you've considered**
Have `show_help` & `show_keys` disabled 

**Additional context**

**Comment by folke** [comment]
That padding is needed if you do not use Noice. You can disable help and keys as you already know.

**Comment by kuntau** [comment]
![Screen Shot 2023-01-03 at 19 22 08](https://user-images.githubusercontent.com/327489/210348082-57935ade-d28e-4ce3-bfa9-e3b8455f4069.png)
Even with `show_help=false` but `show_keys=true` it's still unnecessarily long.

**Comment by folke** [comment]
thats why you shoul set `show_keys=false`

**Comment by folke** [comment]
I've fixed this in the meantime in the which-key repo.

When cmdheight=0 (or when using noice), then help and keys will be shown at the bottom of the floating window instead. You can of course still disable it.

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/210604334-9b732319-3e39-46fb-b7a2-d047b439e32a.png)

**Comment by kuntau** [comment]
Amazing. Thank you.
