### ISSUE TITLE
bug: confirm dialog is duplicated in :cdo substitute

### ISSUE THREAD

**Issue by eyev0** [folke/noice.nvim#302]
**Describe the bug**
confirm dialog `replace with <replacement> (y/n/a/q/l/^E/^Y)?` is duplicated every time neovim is switching buffers when iterating over quickfix entries during `:cdo s/<pattern>/<replacement>/c`
**Which version of Neovim are you using?**
0.8.2

**To Reproduce**
minimal.lua
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/noice.nvim",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
vim.cmd([[colorscheme tokyonight]])

vim.keymap.set("n", "<C-q><C-o>", ":copen<CR>", { noremap = true })
vim.keymap.set("n", "<C-q><C-j>", ":cnext<CR>", { noremap = true })
vim.keymap.set("n", "<C-q><C-k>", ":cprev<CR>", { noremap = true })

require("noice").setup()

```
1. grep over two buffers with some common data, e.g. `:vimgrep /something/ buffer1 buffer2`
2. run substitute for each quickfix entry: `:cdo s/something/else/c`
3. press q or Esc
4. confirm dialog will be duplicated inside cmdline popup

**Expected Behavior**
confirm dialog is shown once, pressing l/q/Esc stops substitution

**Screenshots**
![image](https://user-images.githubusercontent.com/22837926/210569193-b0193fb4-1443-42f4-8dbc-eec08f92e2f0.png)

**Comment by edementyev** [comment]
fyi this behaviour remains on nightly neovim and latest noice as of now

**Comment by RayGuo-ergou** [comment]
Hi @folke I can confirm this still an issue, any chance you can look into it?
![image](https://github.com/folke/noice.nvim/assets/33137074/5da29b35-a720-44b4-aa34-46ca742185a6)

```
nvim -v
Found existing alias for "nvim". You should use: "vim"
NVIM v0.11.0-dev-251+g4faad4a95
Build type: RelWithDebInfo
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

noice.nvim is up to date
