### ISSUE TITLE
bug: remaps that invoke commands show for a split of a second as a popup

### ISSUE THREAD

**Issue by luisiacc** [folke/noice.nvim#304]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-621+g39d70fcaf

### Operating system/version

WSL 2 Ubuntu 20.04

### Describe the bug

I have a mapping like:

```vim
nnoremap <leader>gg :echo "asd"<CR>
```

Whenever I use the remap, the popup of cmdline shows for a split second.

https://user-images.githubusercontent.com/31720261/210926603-17d8185d-06e1-48b6-9841-370e0dd4f892.mp4

### Steps To Reproduce

Just press `<leader>gg`

### Expected Behavior

The popup cmdline should not show for a split second, at all.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  "MunifTanjim/nui.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

require("noice").setup({})
vim.cmd([[
let mapleader = " "
nnoremap <leader>gg :echo "asd"<CR>
]])
```

**Comment by folke** [comment]
That's normal Neovim behavior. Make the keymap silent and/or check `:h <cmd>` which has been created specifically to avoid this

**Comment by dragonofdeath** [comment]
Is there a way to silence mappings defined in library you are using other that doing contribution to it? As an example I'm having issue with unimpaired vim mappings, for example these are defined as non silent https://github.com/tpope/vim-unimpaired/blob/master/plugin/unimpaired.vim#L314

**Comment by folke** [comment]
I use the code below, but that would only work for lua keymaps. I don't think you can do something similar for vimscript keymaps.

```lua
  -- make all keymaps silent by default
  local keymap_set = vim.keymap.set
  ---@diagnostic disable-next-line: duplicate-set-field
  vim.keymap.set = function(mode, lhs, rhs, opts)
    opts = opts or {}
    opts.silent = opts.silent ~= false
    return keymap_set(mode, lhs, rhs, opts)
  end
````
