### ISSUE TITLE
feature: instant preview-as-you-type completion

### ISSUE THREAD

**Issue by yingzhu146** [folke/noice.nvim#309]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Discoverability is solved very well in the helix editor. 

<img width="2056" alt="20230110-230504" src="https://user-images.githubusercontent.com/59233975/211715601-1cda2f62-8ff5-40ec-9ad9-bd902d13aa76.png">

Instantly as you start typing, options are shown in a grid, even before first character is typed. This greatly helps discoverability.

### Describe the solution you'd like

Solutions should be shown as you type, ideally in grid/or list below window

### Describe alternatives you've considered

`Telescope command_history` comes pretty close but I can't get the edit shortcut to work reliably

**Comment by folke** [comment]
As I mentioned multiple times before, this is not possible. Check the other issues
