### ISSUE TITLE
bug: `<` notification when I trying to save the file

### ISSUE THREAD

**Issue by jeeeem** [folke/noice.nvim#314]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-647+g1df2db0bc

### Operating system/version

Windows 11

### Describe the bug

Context: Updated to latest commit and using lunarvim.

![image](https://user-images.githubusercontent.com/51053482/212475581-6a92bdbf-4979-4719-b08c-e29ec42fd172.png)

### Steps To Reproduce

Just saving the file will reproduce this notification.

### Expected Behavior

Should show the normal message when saving the buffer file.
`"config.lua" [unix] 49L, 1032B written`

**Comment by folke** [comment]
Should be fixed upstream 4 days ago. See https://github.com/neovim/neovim/pull/21709

**Comment by jeeeem** [comment]
> Should be fixed upstream 4 days ago. See [neovim/neovim#21709](https://github.com/neovim/neovim/pull/21709)

Fixed. thanks.
