### ISSUE TITLE
feature: statuscolumn 

### ISSUE THREAD

**Issue by Astrantia** [folke/noice.nvim#316]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

new status column customisations are now possible

### Describe the solution you'd like

noice could add a good looking status column with gitsigns, conceals, etc supported ootb

### Describe alternatives you've considered

this doesn't have to be in noice, but it would be noice if it was supported

**Comment by folke** [comment]
Probably makes more sense to have this functionality in the statusline plugins. It's also very easy to setup your own statuscolumn.
