### ISSUE TITLE
bug: E591: 'winheight' cannot be smaller than 'winminheight'

### ISSUE THREAD

**Issue by xorander00** [folke/noice.nvim#319]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

FreeBSD 13.1-STABLE

### Describe the bug

When opening the vim-clap window via ':Clap<CR>', the following error is thrown...  
```
Error detected while processing function clap#[46]..clap#for[41]..clap#floating_win#open:
line    4:
E591: 'winheight' cannot be smaller than 'winminheight'
```  

':verbose set winheight' and ':verbose set winminheight' didn't produce any useful information, just said that it was set by vim-clap.  
    
I tried disabling other plugins that I suspected might be messing with related options, but to no avail. What did work was commenting out line vim-clap/autoload/clap/floating_win.vim:451

```
let s:save_winheight = &winheight
" let &winheight = 1
```

Then the window popped up and worked as expected without throwing any errors.  
  
I'm not sure how else to further diagnose if this is something that I should work-around in another plugin or whether it's something that vim-clap should guard for maybe? Figured I'd post here to get any further tips/feedback. Wish I could provide a bit more context, but currently still exploring. Feel free to ask me for whatever further info you might need. Thanks! 

### Steps To Reproduce

1. Open vim-clap via ':Clap<CR>'

### Expected Behavior

Open clap window without error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
No idea, but looks to be an issue in the vim clap code. It probably does something with the existing current window? Really no idea. Better to check in the vim clap repo. Closing this

**Comment by xorander00** [comment]
Hahaha oops, my bad. I meant to create this in the vim-clap repo. Sorry!
