### ISSUE TITLE
Is it possible to have cmdline_popup at the top?

### ISSUE THREAD

**Issue by MordechaiHadad** [folke/noice.nvim#32]
**Describe the solution you'd like**
Basically be able to have the cmdline_popup at the top instead of the center like vscode:
![](https://p0rn.pro/ADeadAndRedundantCat)

**Comment by folke** [comment]
```lua
  noice.setup({
    views = {
      cmdline_popup = {
        position = {
          row = 2,
          col = "50%",
        },
      },
    },
  })

```

**Comment by folke** [comment]
If you want the dropdown positioned like that as well, check
https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#display-the-cmdline-and-popupmenu-together

**Comment by MordechaiHadad** [comment]
Oh fascinating, thanks!
