### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by fan-xing** [folke/noice.nvim#321]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-701+g34b973b1d

### Operating system/version

macOS ProductVersion: 12.4

### Describe the bug

- When i use `so $MYVIMRC`, i get an error like this
```
E5108: Error executing lua .../zhangboyang/.vim/bundle/noice.nvim/lua/noice/health.lua:211: bad argument #1 to 'getinfo' (function or level expected)
stack traceback:
	[C]: in function 'getinfo'
	.../zhangboyang/.vim/bundle/noice.nvim/lua/noice/health.lua:211: in function 'get_source'
	.../zhangboyang/.vim/bundle/noice.nvim/lua/noice/health.lua:189: in function 'check'
	...rs/zhangboyang/.vim/bundle/noice.nvim/lua/noice/init.lua:14: in function 'setup'
	[string ":lua"]:1: in main chunk

```
- Config
```lua
require("noice").setup({
  messages = {
    -- NOTE: If you enable messages, then the cmdline is enabled automatically.
    -- This is a current Neovim limitation.
    enabled = true, -- enables the Noice messages UI
    view = "notify", -- default view for messages
    view_error = "notify", -- view for errors
    view_warn = "notify", -- view for warnings
    view_history = "messages", -- view for :messages
    view_search = "mini", -- view for search count messages. Set to `false` to disable
  },
  lsp = {
    progress = {
      enabled = false,
    },
  },
  routes = {
    {
        view = 'mini',
        filter = { event = 'msg_showmode' },
    },
  }
})
```

### Steps To Reproduce

1.Open a file
2.Whatever i do, noice looks all right
3.Input `so $MYVIMRC`
4.My config was reload, but get an error
![image](https://user-images.githubusercontent.com/31067312/212802549-43a51f31-eaab-4488-b881-17d21da08353.png)

### Expected Behavior

Just reload config

**Comment by max397574** [comment]
just want to tell you that you can't reload your config like this
most lua stuff is cached and won't be reloaded
much more stuff would be required to do this

I don't know how this is related to the error though

**Comment by folke** [comment]
As @max397574 said. Noice can't be reloaded.
The error you're getting is exactly the reason why this can't work. You cleared loaded modules that are expected to exist.
Won't fix.

**Comment by fan-xing** [comment]
> As @max397574 said. Noice can't be reloaded. The error you're getting is exactly the reason why this can't work. You cleared loaded modules that are expected to exist. Won't fix.

Tks
