### ISSUE TITLE
Can I add a border to the document display.

### ISSUE THREAD

**Issue by FZZkill** [folke/noice.nvim#324]
if the document is displayed in this way, it is difficult to separate it from the editor:
![图片](https://user-images.githubusercontent.com/76607157/213618565-68d7eb2d-3917-486d-8cc5-c1539ea1de5b.png)
and hints for functions:
![图片](https://user-images.githubusercontent.com/76607157/213618707-2ba3ad47-8ade-475d-90a3-795ce6ecd49d.png)
if you can add a bezel, it can be much better like CMP

**Comment by folke** [comment]
`config.presets.lsp_doc_border = true`
