### ISSUE TITLE
Indicator when recording or finishing a macro

### ISSUE THREAD

**Issue by EthanJWright** [folke/noice.nvim#34]
**Is your feature request related to a problem? Please describe.**
With this plugin, I am no longer able to see a clear indicator when I begin recording a macro or finish a macro. (i.e. when I press q<a-z> in normal mode, or q a second time after.

**Describe the solution you'd like**
I would love to get a notification for macro-related messages.

**Describe alternatives you've considered**
Tried to fiddle with the settings but it doesn't appear to currently be supported

**Comment by folke** [comment]
Alternatively, you can also show `showmode` as a message with:

```lua
  local noice = require("noice")
  noice.setup({
    routes = {
      {
        view = "notify",
        filter = { event = "msg_showmode" },
      },
    },
  })

```

**Comment by folke** [comment]
See also https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages

**Comment by rodhash** [comment]
> See also https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages

Can I enable this only for 'Recording' and ignore the other notifications for Insert, Visual, etc?
