### ISSUE TITLE
bug: invalid utf-8 string is sent on redraw event on Windows

### ISSUE THREAD

**Issue by SilverMira** [folke/noice.nvim#340]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-763+ge86d2734a

### Operating system/version

Windows 11 22621.1105

### Describe the bug

Came across this strange bug while writing a GUI implementation. On Windows, when `:` is used to enter command mode, invalid UTF-8 string bytes is sent through RPC notify with the `cmdline_show` redraw event, this happens no matter the method of establishing the RPC channel (stdio / TCP), as long as nvim is running on a Windows host. Might be the root cause for https://github.com/folke/noice.nvim/issues/17#issuecomment-1356808783 or similar comments on Windows on that issue?

On Linux (tested in WSL2), the same string is sent with a `\u0000` however.

msgpack is unable to decode the bytes coming from RPC

Have no idea whether this is an upstream bug from neovim or not.

<details>
<summary>Windows</summary>

```
Bytes in question
[147, 2, 166, 114, 101, 100, 114, 97, 119, 220, 0, 2, 220, 0, 2, 172, 99, 109, 100, 108, 105, 110, 101, 95, 115, 104, 111, 119, 150, 144, 0, 161, 208, 160, 0, 1, 220, 0, 2, 165, 102, 108, 117, 115, 104, 144]
```

The malformed UTF-8 bytes is [161, 208], (msgpack fixstr length 1, char code 208), which isn't valid

```json
[
  2,
  "redraw",
  [
    [
      "cmdline_show",
      [
        [],
        0,
        "X", <-- malformed UTF-8 string bytes, 
        "",
        0,
        1
      ]
    ],
    [
      "flush",
      []
    ]
  ]
]

```
</details>

<details>
<summary>Linux</summary>

```
Bytes in question
[147, 2, 166, 114, 101, 100, 114, 97, 119, 220, 0, 2, 220, 0, 2, 172, 99, 109, 100, 108, 105, 110, 101, 95, 115, 104, 111, 119, 150, 144, 0, 161, 0, 160, 0, 1, 220, 0, 2, 165, 102, 108, 117, 115, 104, 144]
```

Byte sequence [161, 0] which results in `"\u0000"`

```json
[
  2,
  "redraw",
  [
    [
      "cmdline_show",
      [
        [],
        0,
        "\u0000",
        "",
        0,
        1
      ]
    ],
    [
      "flush",
      []
    ]
  ]
]
```
</details>

### Steps To Reproduce

1. Use the attached `init.lua`
2. Clone a minimal rust GUI attach and `:` repro https://github.com/SilverMira/reproduce-noice-windows
3. `cargo run` on Windows / Linux and notice the err

### Expected Behavior

Behavior across operating system should be consistent, valid UTF-8 string should be sent.

### Repro

```Lua
-- bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "folke/noice.nvim",
    opts = {},
    dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" },
  },
})
```

**Comment by folke** [comment]
This is not a Noice bug
