### ISSUE TITLE
feature: ability to manually close signature help window in insert mode

### ISSUE THREAD

**Issue by matthewsia98** [folke/noice.nvim#341]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

When I type `print(`, signature help is auto triggered and window opens.
This covers some number of lines either above or below cursor.

### Describe the solution you'd like

I want to be able to map something like `<C-c>` in insert mode to close signature help.

### Describe alternatives you've considered

Tried mapping `<C-c>` to `require("noice.lsp.docs").on_close()` but did not work well.

**Comment by shabaev** [comment]
guys, you would not believe...

```lua
vim.keymap.set("i", "<M-c>", function()
  local nldocs = require("noice.lsp.docs")
  local message = nldocs.get("signature")
  nldocs.hide(message)
end)
```
