### ISSUE TITLE
bug: pylsp signature help vs cmp documentation

### ISSUE THREAD

**Issue by matthewsia98** [folke/noice.nvim#345]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-825+g843c9025a

### Operating system/version

6.1.8-arch1-1

### Describe the bug

Enabling `rope_completion` plugin causes cmp docs to lose highlighting.
In both cases signature help has proper highlighting.
Let me know if this is a pylsp/nvim-cmp issue and I can open an issue there instead.

Signature help
![image](https://user-images.githubusercontent.com/71731492/216017679-82a13202-a9cc-45b0-843e-59625b624b65.png)

Cmp documentation with `rope_completion` disabled
![image](https://user-images.githubusercontent.com/71731492/216016256-b47adbd2-3b05-4b10-b97f-9d7e78e63452.png)

Cmp documentation with `rope_completion` enabled
![image](https://user-images.githubusercontent.com/71731492/216016447-eca5299a-c1d0-462a-92ff-8218ea7f37e4.png)

### Steps To Reproduce

1. Go to line 102 in minimal config
2. Toggle `enabled` and see different behavior

### Expected Behavior

Highlighting in cmp documentation

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- options
vim.opt.termguicolors = true
vim.opt.completeopt = ""
vim.opt.wildmenu = false

-- install plugins
local plugins = {
    "nvim-lua/plenary.nvim",
    "folke/tokyonight.nvim",
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        event = "BufReadPost",
        config = function()
            require("nvim-treesitter.configs").setup({})
        end,
    },
    {
        "hrsh7th/nvim-cmp",
        dependencies = {
            "hrsh7th/cmp-nvim-lsp",
        },
        event = { "InsertEnter", "CmdlineEnter" },
        config = function()
            local cmp = require("cmp")
            cmp.setup({
                completion = {
                    completeopt = "menu,menuone,noselect",
                },
                sources = {
                    { name = "nvim_lsp" },
                },
                mapping = {
                    ["<C-p>"] = cmp.mapping.select_prev_item(),
                    ["<C-n>"] = cmp.mapping.select_next_item(),
                },
            })
        end,
    },
    {
        "neovim/nvim-lspconfig",
        dependencies = {
            "williamboman/mason.nvim",
            "williamboman/mason-lspconfig.nvim",
        },
        event = "BufReadPre",
        config = function()
            require("mason").setup()

            -- install mason packages
            local show_ui = true
            local packages = {
                "python-lsp-server",
            }
            for _, package_name in ipairs(packages) do
                local package = require("mason-registry").get_package(package_name)
                if not package:is_installed() then
                    if show_ui then
                        vim.cmd("Mason")
                        show_ui = false
                    end
                    package:install()
                end
            end

            require("mason-lspconfig").setup()

            require("lspconfig").pylsp.setup({
                on_attach = function(client, bufnr)
                    -- Disable semantic highlighting by server
                    -- sumneko lua highlights comments when toggling
                    local servers_disable_semantic_highlighting = { "sumneko_lua" }
                    if vim.tbl_contains(servers_disable_semantic_highlighting, client.name) then
                        client.server_capabilities.semanticTokensProvider = nil
                    end

                    vim.keymap.set("i", "<C-s>", function()
                        vim.lsp.buf.signature_help()
                    end, { buffer = bufnr })
                end,
                capabilities = require("cmp_nvim_lsp").default_capabilities(),
                handlers = {},
                flags = { allow_incremental_sync = true, debounce_text_changes = 150 },
                settings = {
                    pylsp = {
                        plugins = {
                            rope_completion = {
                                enabled = true,
                                eager = true,
                            },
                        },
                    },
                },
            })
        end,
    },
    {
        "folke/noice.nvim",
        dependencies = {
            "MunifTanjim/nui.nvim",
            {
                "rcarriga/nvim-notify",
                lazy = false,
                config = function()
                    local notify = require("notify")
                    notify.setup({
                        timeout = 3000,
                    })
                    vim.notify = notify
                end,
            },
        },
        event = "BufReadPost",
        config = function()
            require("noice").setup({
                notify = { enabled = true },
                cmdline = { enabled = true },
                messages = { enabled = true },
                lsp = {
                    progress = {
                        enabled = true,
                        -- view = "mini",
                    },
                    documentation = {
                        opts = {
                            border = { style = "rounded" },
                            position = { row = 2 },
                        },
                    },
                    signature = { enabled = true },
                    hover = { enabled = true },
                    override = {
                        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
                        ["vim.lsp.util.stylize_markdown"] = true,
                        ["cmp.entry.get_documentation"] = true,
                    },
                },
            })
        end,
    },
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
    defaults = { lazy = true },
    ui = { border = "rounded" },
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I'm not 100% I understand what's missing and I don't know pylsp that well.

But if it's the type thing on top you're missing, then you might set `["cmp.entry.get_documentation"] = false` and see if that fixes what you think should be fixed.

Most lsp servers add a redundant title to the doc and setting that to `true` removes that title. But that might not always be the case

**Comment by matthewsia98** [comment]
Not what I was referring to but I think it may be a pylsp issue.
If you look at the last picture, the documentation window lacks highlighting compared to the 2 others above.
I get highlighting when using pyright.

**Comment by folke** [comment]
The only difference between the two screenshots that I can see is the title line right?

The part below that has the same highlighting.

**Comment by matthewsia98** [comment]
There are 3 screenshots. The last one is the different one.

**Comment by folke** [comment]
Please read what I mentioned and look closely at your screenshots. The third screenshot has the exact same highlighting as your second one, but is missing the first `print(` statement.

**Comment by matthewsia98** [comment]
I was talking about this highlighting. 
But I just realized that the documentations aren't even the same, thanks for pointing that out.
Anyways  not a noice issue I think.

![image](https://user-images.githubusercontent.com/71731492/217096737-b600f929-9eac-456a-8291-84f3174c3423.png)

**Comment by folke** [comment]
Come on. Just look at the contents of the two screenshots you just posted??

The `'print(` in your second screenshot is also not hightligted in your first screenshot.

Your first screenshot has an **extra** `print(` statement.

**Comment by folke** [comment]
Your first screenshot has **two** print functions. the second one only **one**

**Comment by folke** [comment]
Set `["cmp.entry.get_documentation"] = false`

**Comment by matthewsia98** [comment]
Ah ok I see what you mean now.
In the first two the lines that have highlighting is the function signature.
In the third one the function signature is not included in the documentation.
Below is with `["cmp.entry.get_documentation"] = false`. Unfortunately still missing the function signature.

![image](https://user-images.githubusercontent.com/71731492/217100388-b0ddbd1e-e658-4437-9b8a-8a14d57ca29d.png)

**Comment by folke** [comment]
ok, then that's just pylsp that's not returning that. Nothing Noice nor cmp can do about that
