### ISSUE TITLE
bug: `cmdline_popup` view is not compatible with mini.align plugin

### ISSUE THREAD

**Issue by Fau818** [folke/noice.nvim#346]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

MacOS 13.2

### Describe the bug

I use [mini.align](https://github.com/echasnovski/mini.align) plugin to align my code, but it does not display the characters when I enter the `Split Pattern`(mini.align) via `cmdline_popup` view. However, it works if I use `hover` view.

We can see it in the following video.

https://user-images.githubusercontent.com/75115028/216084879-196650f7-7d60-4ed6-ab0e-d4feb1a63ad9.mov

### Steps To Reproduce

Shown in the above video.

### Expected Behavior

I can see the entered text in real time for `cmdline_popup` view, just like in the `hover` view.

**Comment by Fau818** [comment]
I've figured out the reason, I need to set `enter = true` manually.

Thanks for providing such a great plugin!

**Comment by Fau818** [comment]
Sorry, I still found some problems, and I've to reopen this.

If I don't set `enter = true` and use the **adaptive size**, it can display the entered text in real time.

Example from [noice.config.views](https://github.com/folke/noice.nvim/blob/main/lua/noice/config/views.lua)
```lua
hover = {
	view = "popup",
	relative = "cursor",
	zindex = 45,
	enter = false,
	anchor = "auto",
	size = {  -- important
		width = "auto",
		height = "auto",
		max_height = 20,
		max_width = 120,
	},
	border = {
		style = "rounded",
		padding = { 0, 1 },
	},
	position = { row = 1, col = 0 },
	win_options = {
		wrap = true,
		linebreak = false,
	},
},
```

---

But if I use a **fixed size**, it can't display the entered text in real time.

For example, use the following code to replace the size part.

```lua
size = {
	width = 60,
	height = "auto"
}
```

---

Is it possible to display the entered text in real time even at a fixed size?

**Comment by folke** [comment]
This should be fixed now. Let me know if the problem would still perssist with the latest version!

**Comment by farzadmf** [comment]
Tried with the latest version, and it's working

Once, it stopped typing characters once I entered a couple, but I'm hoping that was a one-off thing. Will update here if I see an issue
