### ISSUE TITLE
bug: Keys are not showed during `vim.fn.input()` when called from Visual mode

### ISSUE THREAD

**Issue by echasnovski** [folke/noice.nvim#347]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-857+g2c5906b55

### Operating system/version

EndeavourOS Linux x86_64 (6.1.8-arch1-1)

### Describe the bug

When `vim.fn.input()` is called during Visual mode, it doesn't show user's pressed keys while still processing them correctly.

### Steps To Reproduce

1. Create the following mappings:
```lua
-- Doesn't show input characters, but registers them (`_G.input_result` is as expected)
-- Doesn't work even if `vim.o.showmode = false`
-- Without 'noice.nvim' works as expected in command line
vim.keymap.set('x', '<M-x>', [[<Cmd>lua _G.input_result = vim.fn.input({ prompt = 'Enter: ' })<CR>]])
vim.keymap.set('x', '<M-f>', function() _G.input_result = vim.fn.input({ prompt = 'Enter: ' }) end)

-- Works as expected
vim.keymap.set('n', '<M-n>', [[<Cmd>lua _G.input_result = vim.fn.input({ prompt = 'Enter: ' })<CR>]])
```
2. In Visual mode press `<M-x>`. Type `abcd`. It doesn't appear in popup window.
    Press `<CR>`. All key presses do appear for a brief moment.
    Type `:lua print(_G.input_result)`. It should show `abcd`, as expected.
3. In Visual mode press `<M-f>`. Type `efgh`. The result is the same with updated value of `_G.input_result`.
4. In Normal mode press `<M-n>`. Type `ijkl`. It **does** appear in popup window and value of `_G.input_result` is updated.

### Expected Behavior

Any user's key press should immediately be shown in popup window (as when in command line without 'noice.nvim').

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

-- Doesn't show input characters, but registers them (`_G.input_result` is as expected)
-- Doesn't work even if `vim.o.showmode = false`
-- Without 'noice.nvim' works as expected in command line
vim.keymap.set('x', '<M-x>', [[<Cmd>lua _G.input_result = vim.fn.input({ prompt = 'Enter:' })<CR>]])
vim.keymap.set('x', '<M-f>', function() _G.input_result = vim.fn.input({ prompt = 'Enter:' }) end)

-- Works as expected
vim.keymap.set('n', '<M-n>', [[<Cmd>lua _G.input_result = vim.fn.input({ prompt = 'Enter:' })<CR>]])
```

**Comment by echasnovski** [comment]
It *might be* the reason behind #346.

**Comment by folke** [comment]
Sorry for the late reply.

The issue was that `mode()` returns `V` when `vim.fn.input` is called when in visual mode. And there's no `vc` special mode for this case.

Should be fixed now. Whenever the cmdline is open, Noice will always assume blocking mode.

Thank you for the detailed bug report!
