### ISSUE TITLE
bug: respect cursor's shape

### ISSUE THREAD

**Issue by tmpm697** [folke/noice.nvim#348]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Operating system/version

archlinux latest

### Describe the bug

Whenever i use this plugin, my cursor shape change from `_` to block, i force set cursor shape from `alacritty` and not set it on nvim.

how to preserve the cursor shape?

### Steps To Reproduce

just use this plugin

### Expected Behavior

cursor shape not change when using this plugin

**Comment by folke** [comment]
Noice uses your Neovim cursor settings, not sure how that works with Alacritty. Noice supports Neovim cursors.

**Comment by tmpm697** [comment]
@folke : there's something that reset cursor shape to `block`, like:
```
1. map / to :silent! /
2. nvim
3. press /
4. press <esc>
5. :qa
6. now nvim exit and user dropped to shell with a block cursor shape
```

**Comment by navxio** [comment]
Is there a way to get insert mode cursor shape in the fine cmdline box?

**Comment by nullptr-yxw** [comment]
> @folke : there's something that reset cursor shape to `block`, like:
> 
> ```
> 1. map / to :silent! /
> 2. nvim
> 3. press /
> 4. press <esc>
> 5. :qa
> 6. now nvim exit and user dropped to shell with a block cursor shape
> ```

It's possible to write a script to avoid it.

**Comment by folke** [comment]
https://github.com/folke/noice.nvim/issues/552

**Comment by nullptr-yxw** [comment]
> #552

So isn't there any way to set the cursor shape? so the only thing I can to avoid from changing the cursor shape of the shell might be write a script like `echo -n $'\e[0 q'`
