### ISSUE TITLE
Delay of statusbar "mode" change after popup use

### ISSUE THREAD

**Issue by adrian5** [folke/noice.nvim#353]
I'm not sure if this is related to how noice interacts with lualine, but after I use popups there's a noticeable delay in the mode indicator. This makes my brain think something (else) happened at the bottom, which is distracting. It doesn't seem to be affected by the values of `timeoutlen` or `updatetime`.

![mode-delay](https://user-images.githubusercontent.com/5426924/217982492-4815d351-dc2a-47ca-8d79-98cd68f6f498.gif)

Is this normal?

**Comment by folke** [comment]
`config.lualine.refresh.statusline = 1000`
Defaults to one second. Not related to Noice. Check the lualine docs
