### ISSUE TITLE
bug:  floating window overlays quickfix list

### ISSUE THREAD

**Issue by unendlicherPing** [folke/noice.nvim#354]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-912+gfe1e6b82f

### Operating system/version

Windows 10

### Describe the bug

If I want to filter the lsp servers in the mason.nvim menu by language, the selection screen appears behind the floating window. 
![image](https://user-images.githubusercontent.com/65238661/218225719-7520e13f-1a99-4909-8d30-8ac6d5c8896b.png)

### Steps To Reproduce

1. type in :Mason
2. press \<c-f\>

### Expected Behavior

Without noice.nvim a full sized window appears.
![image](https://user-images.githubusercontent.com/65238661/218225977-9d83899e-6a7f-4405-ac63-ea3075db1de5.png)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
  { "williamboman/mason.nvim", config = true }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You can try setting the `zindex` option to the view that is being used there, but better to use something like `dressing.nvim`

![image](https://user-images.githubusercontent.com/292349/218247694-ea14cc2f-1b04-4d33-a460-bccaaac8b204.png)
