### ISSUE TITLE
bug: overwritten by another plugin

### ISSUE THREAD

**Issue by jeeeem** [folke/noice.nvim#355]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-920+gc9b0fe1f4

### Operating system/version

Windows 11

### Describe the bug

I do not have this error before I updated Lunarvim to its latest commits, I am just confused that I have to disable the two config that shown in the error. Is this normal? Do I really need to disable those? I did that and there's no error anymore but I am not sure if this is consider a bug or not.

![image](https://user-images.githubusercontent.com/51053482/218294004-4c6572ba-78b5-4866-8379-5090a622b077.png)

### Steps To Reproduce

nan

### Expected Behavior

Should have no error

**Comment by max397574** [comment]
the error exactly tells you what's the problem and how to fix it
and the fix works
here everything works as expected

perhaps lunarvim did add lspsaga or something similar that overwrites this so you didn't get the error before

**Comment by folke** [comment]
@max397574 is right. Either fix the conflicting plugin, or disable the functionality in noice.

**Comment by cshuaimin** [comment]
LunarVim overrides these handlers at https://github.com/LunarVim/LunarVim/blob/732fd6fc2b840eb5ecb5f7ba5931363d3c3dafab/lua/lvim/lsp/handlers.lua#L15-L16

**Comment by max397574** [comment]
then open an issue there
if lunarvim sets those config values to true but overwrites the handlers themself it's a lunarvim issue
