### ISSUE TITLE
feature: level icon (INFO, WARN, ...) & Pango markup with notify_send backend

### ISSUE THREAD

**Issue by mochaaP** [folke/noice.nvim#357]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

The `notify_send` backend currently uses the same icon (nvim) for every notification. Moreover, the highlight color isn't carried over and it looks a little plain.

### Describe the solution you'd like

Somehow convert the highlight in Neovim to Pango markup (is reading the highlight even possible?)

### Describe alternatives you've considered

Only change the text color / font / icon so we don't have to mess with the highlight tree

### Additional context

<https://docs.gtk.org/Pango/pango_markup.html#convenience-tags>

**Comment by folke** [comment]
Thank you for the suggestion, but that's out of scope for this project
