### ISSUE TITLE
bug: status messages aren't cleared with `:mes clear`

### ISSUE THREAD

**Issue by boltlessengineer** [folke/noice.nvim#365]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-2198+gf905ab045-dirty

### Operating system/version

MacOS 13.1

### Describe the bug

When I do `:mes clear` to clear all messages, even I did cleared them all (checked with `:mes`), ` require("noice").api.status.message.get_hl()` still shows last message.

### Steps To Reproduce

1. Open neovim and make some messages. (like `:echom 'test'`)
2. Clear them all with `:mes clear`
3. See `require("noice").api.status.message.has()` says there are still messages left.

### Expected Behavior

messages in Noice api should be cleared with `:mes clear` vim command.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
  'rcarriga/nvim-notify',
  "MunifTanjim/nui.nvim",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

require('noice').setup()
```

**Comment by folke** [comment]
Message clear doesn't work with noice. I'm not planning to change this. I honestly wouldn't even know how that should work and don't think this is useful

**Comment by darksinge** [comment]
@boltlessengineer I was hoping for this functionality too. Noice can act as a replacement to `:messages`, so I think it makes sense to support a `:messages clear` behavior. 

I created the following user command to "clear" the message history for noice, but like folke eluded to, I don't think it's possible to override/intercept the builtin `:message` command. Hope this helps.
```lua
local Manager = require("noice.message.manager")

vim.api.nvim_create_user_command('Noice-clear', function()
  local messages = Manager.get({ has = true }, { history = true })
  for _, msg in ipairs(messages) do
    Manager.remove(msg)
  end
end, { desc = 'Noice clear' })
```
