### ISSUE TITLE
feature: confirm exit on `xall`

### ISSUE THREAD

**Issue by jrnxf** [folke/noice.nvim#366]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Not related to any problem.

### Describe the solution you'd like

I find myself accidentally editing no name buffers often. I'd love it if there was a way that when I try to exit neovim with `xall` if the same confirm dialog was presented to me as it is with `qall`. Given the confirm option doesn't seem to do anything for xall I'm not sure there is anything that can be done here though.

### Describe alternatives you've considered

n/a

**Comment by folke** [comment]
This isn't a Noice issue. Just don't use `:xall`?
