### ISSUE TITLE
feature: Only show `cmdline_popup` when entering ex mode manually ":"

### ISSUE THREAD

**Issue by liam-ngy** [folke/noice.nvim#368]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Hello! I hope you're doing well. I'm reaching out because I noticed that every time I execute a command using a keybinding, such as '<leader>0' for 'NvimTreeToggle', the command-line view pops up and executes the command. Although this is the natural behaviour of the built-in command-line, I find it a bit distracting to have the command-line pop up every time I execute a command. I understand that 'Noice' is actually modifying the user interface of the command-line so therefore expected, but I was wondering if there is any way to suppress the command-line from opening when I execute commands via keybindings. It would be amazing if I could seamlessly execute commands without being interrupted by the command-line interface. Thank you so much for your time and consideration, and let me know if you have any questions or suggestions!"

https://user-images.githubusercontent.com/8395044/220348848-69c90525-76dc-40b9-93e2-6f5a815e5db3.mov

### Describe the solution you'd like

I'm not entirely sure if this is possible, but I thought it might be worth asking. Currently, we're using the built-in command-line, but with a different view. My question is whether it's possible to show only the popup menu when we manually execute a command using ':', and suppress the command-line popup window or change the view to the classic command-line whenever we run a command using a keybinding.

### Describe alternatives you've considered

I read the documentation but couldn't find any related options to fix it. But feel free to point me in the right direction. :)

Thanks for creating all these amazing plugins!!

**Comment by max397574** [comment]
use `silent` in your mappings?
