### ISSUE TITLE
extra keymaps in `["vim.lsp.util.stylize_markdown"] = true`

### ISSUE THREAD

**Issue by Fau818** [folke/noice.nvim#369]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

MacOS 13.2.1

### Describe the bug

If I set `["vim.lsp.util.stylize_markdown"] = true`, two additional keymaps will be gotten.

I checked the source code and found the following statement in lines 228 to 229 of the `lua/noice/text/markdown.lua` file.

```lua
map("gx")
map("K")
```

In fact, only the `K` mapping bothers me because I usually map `K` to `5k`.

So, can there be a way to modify or remove such a default mapping?

### Steps To Reproduce

...

### Expected Behavior

...

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This is a very specific thing, so I'm not going to make this configurable.

You can write an autocmd that sets `vim.b.markdown_keys = true` for new buffers. With that set, the keymaps won't be added
