### ISSUE TITLE
bug: vim.lsp.handlers["textDocument/signatureHelp"] has been overwritten by another plugin?

### ISSUE THREAD

**Issue by mamaraddio** [folke/noice.nvim#370]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [x] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

ArchLinux

### Describe the bug

On LunarVim installation the following error pops up every time a new instance of LunarVim is spawned
![image](https://user-images.githubusercontent.com/82162277/221522311-3ff9ad09-1ad4-4d5a-92c5-cca038942358.png)

The signature help works correctly although.

Setting `config.lsp.signature = false` as shown in the error message doesn't solve the issue
```lua
require("noice").setup({
  lsp = {
    signature = {
      enabled = false,
    },
  },
})
```
Setting
```lua
require("noice").setup({
  lsp = {
    signature = {
      enabled = false,
      auto_open = {
        enabled = false,
        trigger = true, -- Automatically show signature help when typing a trigger character from the LSP
        luasnip = true, -- Will open signature help when jumping to Luasnip insert nodes
        throttle = 50, -- Debounce lsp signature help request by 50ms
      },
   },
 },
})
```
solves the problem but signature help lose the noice feature

### Steps To Reproduce

1. Install NeoVim from system package manager
2. Install LunarVim (v 1.2/stabe)
3. Add the following to `lvim.plugins`
```lua
{
  "folke/noice.nvim",
  config = function()
    require("noice").setup({
      lsp = {
        -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
        override = {
          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
          ["vim.lsp.util.stylize_markdown"] = true,
          ["cmp.entry.get_documentation"] = true,
        },
      },
      -- you can enable a preset for easier configuration
      presets = {
        bottom_search = false, -- use a classic bottom cmdline for search
        command_palette = true, -- position the cmdline and popupmenu together
        long_message_to_split = true, -- long messages will be sent to a split
        inc_rename = true, -- enables an input dialog for inc-rename.nvim
        lsp_doc_border = true, -- add a border to hover docs and signature help
      },
    })
  end
},
```

### Expected Behavior

Not showing the error message at any launch, especially because it is working

**Comment by folke** [comment]
You'll have to adress this problem on the LunarVim side. The code that interfers is here https://github.com/LunarVim/LunarVim/blob/a7e7f28639a70ac56d77867c283c3666cae8ab4d/lua/lvim/lsp/handlers.lua#L16

**Comment by rodhash** [comment]
It seems that disabling  lsp signature on noice config worked for me.

First I tried disabling on my lsp config but didn't work.. something was still overwritting this config, which was weird.

> vim.lsp.handlers["textDocument/publishDiagnostics"] = ...

This seems to have worked for me:

```lua
require("noice").setup({
  lsp = {
    signature = {
      enabled = false,
    },
  },
})
```
