### ISSUE TITLE
bug: nvim breaks after treesitter auto install, needs to rerun nvim 

### ISSUE THREAD

**Issue by akriese** [folke/noice.nvim#372]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-1028+gd422fc827

### Operating system/version

Ubuntu 22.04; also happens on my Win11 build

### Describe the bug

When nvim-treesitter installs a new parser upon nvim startup, nvim crashes with the message:
"...neovim/src/nvim/message.c:2413: msg_scroll_flush: Assertion `to_scroll >= 0` failed"
A similar message was shown in #53.

### Steps To Reproduce

1. Backup nvim data directory (e.g. rename `$HOME/.local/share/nvim` to `...nvim_bak`.
2. Use attached `repro.lua` which is only using lazy.nvim, nvim-treesitter and noice.nvim. (`nvim -u repro.lua`)
3. Everything should work fine, lazy should be installed and the `c.so` parser installed correctly.
4. Now, remove the parser like `rm $HOME/.local/share/nvim/lazy/nvim-tressitter/parser/c.so`.
5. Run `nvim -u repro.lua` again. Treesitter will install the parser again, but nvim will crash (with the above error message) after that has happened.

### Expected Behavior

At step 5, no crash should happen.

### Repro

```Lua
local lazypath = os.getenv("HOME") .. "/test_lazy/lazy.nvim"
print(lazypath)
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            require 'nvim-treesitter.install'.compilers = { "clang", "gcc", "cc" }
            require 'nvim-treesitter.configs'.setup {
                ensure_installed = { "c" },
                sync_install = true,
            }
        end
    },
    {
        "folke/noice.nvim",
        config = function()
            require("noice").setup({
                lsp = {
                    progress = {
                        enabled = false
                    },
                    -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
                    override = {
                        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
                        ["vim.lsp.util.stylize_markdown"] = true,
                        ["cmp.entry.get_documentation"] = true,
                    },
                },
                -- you can enable a preset for easier configuration
                presets = {
                    bottom_search = false, -- use a classic bottom cmdline for search
                    command_palette = true, -- position the cmdline and popupmenu together
                    long_message_to_split = true, -- long messages will be sent to a split
                    inc_rename = false, -- enables an input dialog for inc-rename.nvim
                    lsp_doc_border = true, -- add a border to hover docs and signature help
                },
            })
        end,
        dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" }
    },
}

require("lazy").setup(plugins)
```

**Comment by folke** [comment]
I can reproduce this. You should try to get a stacktrace for this. Check the Neovim wiki for that and post an issue there.

**Comment by Magicrafter13** [comment]
This also happens with [mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim) when `automatic_installation` is set to `true`.
