### ISSUE TITLE
feature: Mapping does not need to display the command line

### ISSUE THREAD

**Issue by 1538379200** [folke/noice.nvim#373]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I want to filter some of the mapped keys. Displaying the command line causes very slow execution

![image](https://user-images.githubusercontent.com/42434762/221858832-92fb8c82-cb57-4e58-9701-b7e81827a76a.png)

### Describe the solution you'd like

Have a configuration that can be filtered

### Describe alternatives you've considered

Filter all commands that are not started through ```:```

**Comment by max397574** [comment]
silent=true?

**Comment by 1538379200** [comment]
I don't want this ```:bn``` to show up.
What I want to hide is command itself,not the echo.
Does vim itself have the configuration to do that?

![image](https://user-images.githubusercontent.com/42434762/222022217-067a60e0-166b-4f5c-ab4d-70294085278c.png)

**Comment by folke** [comment]
`:h <cmd>`
