### ISSUE TITLE
bug: treesitter markdown highlight

### ISSUE THREAD

**Issue by seblj** [folke/noice.nvim#378]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1023+g649742821

### Operating system/version

MacOS Ventura 13.1

## Bug:

After the new PR by lewis with `vim.treesitter.language.add()` (Not sure if this was the case before that), this line here may break highlighting in the buffer: https://github.com/folke/noice.nvim/blob/f148923300b9fc4609d76867f1f95410ab1442e8/lua/noice/text/init.lua#L66

https://user-images.githubusercontent.com/5160701/222781643-35d5b664-90b7-4cc9-8dd5-cc164c9058c3.mov

There are two reasons for this I believe. The first one is that it uses the filetype to check for a parser when the argument should really be the parsername. For example in this case, when I backspace and get a signature help it will call that function with `typescriptreact`, and that is not the parser name. I think it ideally should use `vim.treesitter.language.get_lang` which would give the correct parsername `tsx`.

The other reason is probably that I am not sure `vim.treesitter.language.require_language` is the correct way to check if a parser is available. I think it ideally should use something like `has_parser` either from upstream or nvim-treesitter (would then need to add it as a required dependency which is not the best even though there are probably a minority who are not using it).

## Follow up question while I am here

While I am at it, I also noticed that the language server from rust for example returns a code block without specifying the language only when sending signature results. On hover it does it correctly. I am not sure if this applies to others as well. This will make the hover look like this:
<img width="984" alt="Screenshot 2023-03-03 at 18 00 17" src="https://user-images.githubusercontent.com/5160701/222781249-da88b063-1a4e-4482-8cc9-3d1d265b23e3.png">

While signature looks like this:
<img width="881" alt="Screenshot 2023-03-03 at 18 00 32" src="https://user-images.githubusercontent.com/5160701/222781286-b5f5838d-7b06-4d69-ac6d-f618e99342e4.png">

This is because of the fallback to `text` here: https://github.com/folke/noice.nvim/blob/f148923300b9fc4609d76867f1f95410ab1442e8/lua/noice/text/markdown.lua#L88

Would it make sense to fallback to the filetype here instead maybe?

### Steps To Reproduce

Sorry for not being able to have an easier replication of the bug.

1. Clone this: https://github.com/seblj/noice-bug
2. Run `npm install`
3. Go into `App.tsx` and do as I did in the video

### Expected Behavior

It would not remove treesitter highlighting from the buffer when doing `:e`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{ "folke/tokyonight.nvim" },
	{
		"folke/noice.nvim",
		config = function()
			require("noice").setup({
				lsp = {
					-- override markdown rendering so that **cmp** and other plugins use **Treesitter**
					override = {
						["vim.lsp.util.convert_input_to_markdown_lines"] = true,
						["vim.lsp.util.stylize_markdown"] = true,
						["cmp.entry.get_documentation"] = true,
					},
				},
				-- you can enable a preset for easier configuration
				presets = {
					bottom_search = true, -- use a classic bottom cmdline for search
					command_palette = true, -- position the cmdline and popupmenu together
					long_message_to_split = true, -- long messages will be sent to a split
					inc_rename = false, -- enables an input dialog for inc-rename.nvim
					lsp_doc_border = false, -- add a border to hover docs and signature help
				},
			})
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by max397574** [comment]
also noticed the signature help thing before

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/222792823-e30acca4-fd35-4ca0-9593-8cb61aa6d701.png)

This is how it looks like for me with the latest nightly and updated nvim-treesitter.

What am I missing?

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/222793295-3798f59b-b910-49ae-8934-f30a514eaadc.png)

Got it. It was using syntax hl. Fixing it

**Comment by seblj** [comment]
> ![image](https://user-images.githubusercontent.com/292349/222793295-3798f59b-b910-49ae-8934-f30a514eaadc.png)
> 
> Got it. It was using syntax hl. Fixing it

Thanks! What do you think about my suggestion to fallback to the filetype if no language is provided for the codeblock?

**Comment by folke** [comment]
Yep, makes sense!

Coming up :)

![image](https://user-images.githubusercontent.com/292349/222802162-b9f0104a-6975-4961-9a87-8746c81063b7.png)
