### ISSUE TITLE
Noice <> nvim-notify settings

### ISSUE THREAD

**Issue by entropitor** [folke/noice.nvim#38]
**Describe the bug**
When I set nvim-notify settings through `require('notify').setup({...})` the vim.notify messages don't appear in `:Noice` 

I use packer, in case that's relevant

**Which version of Neovim are you using?**
Nightly

**Expected Behavior**
There is a way to configure nvim-notify settings by calling notify.setup or by passing it through noice settings

**Comment by Shougo** [comment]
Please upload your `nvim-notify` config.  I will test it later.

**Comment by entropitor** [comment]
```lua
  use({
    "rcarriga/nvim-notify",
    config = function()
      local notify = require("notify")
      notify.setup({
        render = "minimal",
        stages = "static",
        timeout = 1000,
      })
    end,
  })
```

**Comment by Shougo** [comment]
I have tested it and I don't reproduce the problem.

**Comment by folke** [comment]
I know what's happenig here. When we're in blovking mode, we use a separate notify instance that renders without animations. Otherwise, you would not see the notificaiton.

Will fix it so that for that instance we use the user settings as well.

**Comment by folke** [comment]
Actually, everything should already work as expected.

Are you still settting `vim.notify = require('notify')` anywhere in your `init.lua`? 

You shouldn't do that, since that would prevent Noice from picking up Notifications

**Comment by Shougo** [comment]
I think `noice.nvim` should check `vim.notify` is overwritten.

**Comment by entropitor** [comment]
Don't seem to be able to reproduce anymore 👍
