### ISSUE TITLE
How to view the substitute dialog in the cmdline instead of the static mid-screen popup?

### ISSUE THREAD

**Issue by serhez** [folke/noice.nvim#384]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

nightly (>0.9)

### Operating system/version

MacOS 13.1

### Describe the bug

The current substitute popup displaying the `y/n/...` options when performing `%s/...` is quite unusable, as it has a fixed position in the middle of the screen which often results in the popup being on top of the substitution instance, hence reading the code instance is impossible.

### Steps To Reproduce

Simply perform substitution with a vanilla config of Noice.

### Expected Behavior

It would be great to have the popup's position being dependent on the code substitution instance's position. However, that may be a lot of work. The easiest solution I think would be to be able to have the dialog in the cmdline instead of the popup. I have not being able to figure out by reading the docs how this could be achieved.

Thanks for the help!

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
check the recommended presets in the docs. especially bottom search

**Comment by serhez** [comment]
> check the recommended presets in the docs. especially bottom search

@folke this applies to bottom- and up-search, not to the substitution (`:%s/[...]/[...]/gc`) popup, i.e., when setting the `bottom_search` preset, I still get this:

![Screenshot 2023-03-04 at 19 27 46](https://user-images.githubusercontent.com/18057093/222920204-757f5036-2faa-4586-b908-16571d297dbe.jpg)

Do you think it's possible to have this dialog on the bottom cmdline by tweaking the config in `setup()` somehow?

Thanks for the help!

**Comment by folke** [comment]
I'm sure you can do that. Check the code on how the bottom_search preset works and adapt it to what you need

**Comment by serhez** [comment]
I got it, here is the snippet that achieves this:

``` lua
routes = {
  {
    view = "cmdline",
    filter = {
      any = {
        { event = "msg_show", kind = "confirm_sub" },
      },
    },
  },
},
```
