### ISSUE TITLE
bug: `NoiceCursor` renders incorrently

### ISSUE THREAD

**Issue by mrtnvgr** [folke/noice.nvim#386]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Operating system/version

Linux

### Describe the bug

`NoiceCursor` uses `guibg` instead of `guifg` for rendering.

**Highlight groups**
![](https://user-images.githubusercontent.com/48406064/223334558-46384dc9-7bed-40d4-ae0d-c64f79939fa4.png)
![](https://user-images.githubusercontent.com/48406064/223334572-d46dd657-2eff-4f21-adc7-da3488795207.png)

**Cursor**
![](https://user-images.githubusercontent.com/48406064/223334066-c209bf4d-974c-45f4-8e1c-4cff5d74dd2d.png)

**NoiceCursor**
![](https://user-images.githubusercontent.com/48406064/223334179-c89df81f-17c6-4832-9a2d-3cccc7b85250.png)

`NoiceCursor` disappears completely on colorschemes without `guibg` in `Cursor`. (see ellisonleao/gruvbox.nvim#217)

### Steps To Reproduce

1. Install [rose-pine](https://github.com/rose-pine/neovim) colorscheme

### Expected Behavior

`NoiceCursor` looks like `Cursor`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "rose-pine/neovim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("rose-pine")
-- add anything else here
```

**Comment by folke** [comment]
Why would this be a Noice issue? Colorschemes should make sure they correctly style the `Cursor` hl.

It should be styled the same as the real terminal cursor. (yes, those are not the same)

**Comment by mrtnvgr** [comment]
> Why would this be a Noice issue? Colorschemes should make sure they correctly style the `Cursor` hl.

Neovim uses `guibg` for cursor, why does Noice use the opposite?

**Comment by folke** [comment]
NoiceCursor links to Cursor. Your colorscheme is responsible to assign a proper highlight to that group. The actual colors used to remnder the actual cursor are chosen by your terminal, not your colorscheme.

So again, this needs to be fixed on those colorschemes. Not a noice issue
