### ISSUE TITLE
`:digraphs` doesn't work well

### ISSUE THREAD

**Issue by p00f** [folke/noice.nvim#39]
**Describe the bug**
`:digraphs` just shows a wide notification at the top of the screen

**Which version of Neovim are you using?**
https://github.com/neovim/neovim/commit/cfdb4cbada8c65aa57e69776bcc0f7b8b298317a

**To Reproduce**
`:digraphs`

**Expected Behavior**
Digraphs in a new buffer (as described in readme: "no more more-prompt")

**Screenshots**
![image](https://user-images.githubusercontent.com/36493671/194600379-205afdca-c6a7-4872-b04e-08145d4f95eb.png)

**Noice Log**
Log file is empty

**Comment by folke** [comment]
This is a current limitation of nvim-notify. See https://github.com/rcarriga/nvim-notify/issues/137

**Comment by p00f** [comment]
Shouldn't this use a split instead of nvim-notify? It's too big to fit in a float notification, even if it occupies the whole screen

**Comment by Shougo** [comment]
Hm...  If the messages are too long, it should be outputted in buffer.
But it takes to time to implement it.

**Comment by Shougo** [comment]
> Digraphs in a new buffer (as described in readme: "no more more-prompt")

I think it does not mean "it outputs the buffer automatically".
`noice.nvim` is not magic.

**Comment by folke** [comment]
You can adda route for this using the min_width filter:
```lua
  local noice = require("noice")
  noice.setup({
    routes = {
      {
        view = "split",
        filter = { min_width = 500 },
      },
    },
  })
```

This will send messages wider than 500 characters to the split window

**Comment by folke** [comment]
Will think about changing some of the default routes to handle this by default, but the config above fixes it

**Comment by p00f** [comment]
Thanks!

**Comment by p00f** [comment]
Doing this skips the space after the number though:
noice with split filter:

![image](https://user-images.githubusercontent.com/36493671/208520900-e4054cd1-af8d-44ac-909c-aa6941d0a5ab.png)


vanilla nvim:
![image](https://user-images.githubusercontent.com/36493671/208520704-e81a8ed0-df82-4080-b605-6d44e7b480ee.png)

(this means the alignment of the "table" is wrong too)

**Comment by folke** [comment]
@p00f that's a Neovim issue. There's other commands right now that also display wrong like `:map`. I opened an issue about the map one already
