### ISSUE TITLE
bug: Noice doesn't trigger `ModeChanged` when exiting command-line mode.

### ISSUE THREAD

**Issue by mawkler** [folke/noice.nvim#390]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-1184+g0ecb4d725

### Operating system/version

Arch Linux

### Describe the bug

Noice doesn't trigger `ModeChanged` when exiting command-line mode.

### Steps To Reproduce

1. Enter command-line mode (`:`)
2. Message: "mode changed: c"
3. Leave command-line mode (`<Esc>`)
4. No message

### Expected Behavior

Message "mode changed: n" appears when leaving command-line mode.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  'folke/tokyonight.nvim',
  {
    'folke/noice.nvim',
    config = function()
      require('noice').setup({})
    end,
    dependencies = {
      'MunifTanjim/nui.nvim',
      'rcarriga/nvim-notify',
    }
  }
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')

vim.api.nvim_create_augroup('NoiceTest', {})
vim.api.nvim_create_autocmd('ModeChanged', {
  callback = function()
    local mode = vim.api.nvim_get_mode().mode
    print('mode changed: ' .. mode)
  end,
  group = 'NoiceTest'
})
```

**Comment by folke** [comment]
I looked into this, and unfortunately this is not possible to fix.

When the cmdline is displayed, I need to make sure the cursor is always visible. I do this using `vim.cmd([[noautocmd silent! normal! ze]])`.

It seems that that sets the mode to normal internally, so when exiting the cmdline, the ModeChanged is not triggered.

**Comment by mawkler** [comment]
@folke Hmm ok. Is it possible to raise a custom event like `NoiceCmdLineLeave` when leaving command-line mode that I can subscribe to?

**Comment by folke** [comment]
I was able to work-around this issue by not using a normal command to horizontally align the cursor. ModeChanged triggers as expected now

**Comment by mawkler** [comment]
Thank you! Works great!
