### ISSUE TITLE
Splitting a long message into a table.

### ISSUE THREAD

**Issue by pawelurbanski** [folke/noice.nvim#393]
Hi,
I've spent this weekend digging into internals of your plugin. I am in the need of replacing the `:redir` pattern for commands output.
Since my use case is rather nitch I cannot use your great plugin apart from picking ideas here and there.
I unfortunatelly hit hte wall, which can be easy to solve but not for someone who is still learning how Neovim and Lua play together.

I need to split the long message into lines. The example of such message can be output of running: `:! ls` or `:buffers`.

What I do is:

* Replace all the \r\n to \n to normalize the string,
* Tried to use: `vim.fn.split(contents, '\\n') - with no results.

I found posts on Stackoverflow or jists on Github telling how ot split the string but they seem to fall through the cracks.

When I log to file the contents htat was normalized it is cleaned correctly. I would appriciate any hints in a good direction.

Thank you in advance,
Pawel

**Comment by folke** [comment]
I dont really understand what you're asking here tbh, but it doesn't seem to be a Noice issue. So closing this. sorry
