### ISSUE TITLE
Missing highlight group

### ISSUE THREAD

**Issue by sho-87** [folke/noice.nvim#394]
I'm not sure if the HL group is missing, or I just can't find it in [the list](https://github.com/folke/noice.nvim#-highlight-groups), but theres some text in the LSP area of mini that doesn't seem to be responding to setting of bg colour:

![vlcsnap-2023-03-13-08h14m22s455](https://user-images.githubusercontent.com/5199715/224745471-68ddbe2b-ab92-40cc-bd5a-00af3aaa237a.png)

It's hard to see (light purple area), but the text says `black`, which is the formatter I'm using for python files, installed via mason

I've tried setting it using the following but none seem to work:
```
NoiceMini = { fg = colors.palette.sumiInk0, bg = colors.theme.ui.bg },
NoiceLspProgressSpinner = { bg = colors.theme.ui.bg },
NoiceLspProgressClient = { bg = colors.theme.ui.bg },
NoiceLspProgressTitle = { bg = colors.theme.ui.bg },
```
What is the correct HL group to use for this?

**Comment by folke** [comment]
the mini view has `win_options.winblend=30` set, so that's probably the reason.

Check the docs/code to see how to change it
