### ISSUE TITLE
bug: Search count virtual text not show when screen was scrolled by mini.animate

### ISSUE THREAD

**Issue by lkhphuc** [folke/noice.nvim#395]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-2388+g46d4d420e-dirty

### Operating system/version

MacOS 13.2.1

### Describe the bug

Search_count virtual text does not show up when the screen was scrolled by `mini.animate`.
Jumping to the next and previous still shows search count if the screen isn't scrolled.

### Steps To Reproduce

1. Use LazyVim
2. Enable mini-animate preset with ` { import = "lazyvim.plugins.extras.ui.mini-animate" }`
3. Jump to next search that is outside of current screen.

### Expected Behavior

search_count virtual text always shows. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{ "folke/noice.nvim", opts = {}, 
	dependencies = {
		{ "MunifTanjim/nui.nvim" },
		{ "rcarriga/nvim-notify" },
	},
},
	-- add any other plugins here
	{ "echasnovski/mini.animate",
	event = "VeryLazy",
	config = function() require("mini.animate").setup() end,
	}, 
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
The virtual text view shows the given text at the cursor. In case you are using mini.animate, that will indeed change your cursor to make it smoothly go to the new location. So depending on timing, the virtual text might be displayed on a different position.

I personally don't see this as a big issue tbh.

Won't fix (and not really easy to fix if at all possible)

**Comment by lkhphuc** [comment]
Got it thank you. Not a big deal really. I just added a a search count to status bar.

**Comment by AndreasNasman** [comment]
Thanks for discussing this issue and mentioning a fix.

I applied the same workaround by adding `searchcount` to lualine:

```lua
-- lualine.lua (setup with LazyVim)
return {
  "nvim-lualine/lualine.nvim",
  opts = {
    sections = {
      lualine_a = {
        { "mode" }, -- Default value. Needs to be added here to as nested `opts` values are overwritten. https://www.lazyvim.org/plugins/ui#lualinenvim
        { "searchcount" }, 
      },
    },
  },
}
```

`maxcount = 999` and `timeout = 500`, [mentioned in the lualine README](https://github.com/nvim-lualine/lualine.nvim#searchcount-component-options), are the default values (see [the source code](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/searchcount.lua#L3)) so can be omitted if desired.
