### ISSUE TITLE
border display is a bit jagged?

### ISSUE THREAD

**Issue by Integralist** [folke/noice.nvim#40]
**Describe the bug**
With no setting changes, when I invoke the Ex command line the UI box look like this (notice also the quickfix window also looks a bit broken with additional lines visible?)...

<img width="1232" alt="Screenshot 2022-10-07 at 17 38 38" src="https://user-images.githubusercontent.com/180050/194605079-2a520923-864e-4dc7-baaf-e2c2ece9bf81.png">

If I use the configuration from:
https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#display-the-cmdline-and-popupmenu-together

Then the quickfix window issues clear up, but the Ex command line is still _jagged_:

<img width="1248" alt="Screenshot 2022-10-07 at 17 41 06" src="https://user-images.githubusercontent.com/180050/194605220-6c90ebc1-2593-455b-967b-51db7ce76a7b.png">

**Which version of Neovim are you using?**
v0.8.0

**Expected Behavior**
I expect there to be no extra lines displayed.

**Extra comments**
I don't know if there's something in my config causing this?

For example, I set borders on some LSP UI elements here:
https://github.com/Integralist/dotfiles/blob/main/.config/nvim/lua/settings/options.lua#L42-L55

**Comment by folke** [comment]
What happens when you do `<c-l>` after this?

**Comment by Integralist** [comment]
If I type `:` and then press `<Ctrl-l>` nothing happens (from what I can tell)

**Comment by folke** [comment]
Do you get the issue with the minimal `init.lua`? https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by Integralist** [comment]
Aha, OK so there's something wrong with the colorscheme https://github.com/sainnhe/gruvbox-material 🤔 all other colorschemes seem OK?

**Comment by Integralist** [comment]
If you randomly happen to know why this might be then I'd love to hear any thoughts/suggestions, otherwise I've opened an issue on the relevant GitHub repo: https://github.com/sainnhe/gruvbox-material/issues/148

**Comment by folke** [comment]
I know what's causing this. For the border, we use `DiagnosticInfo` in the default `cmdline_popup` view. That group probably has an underline in that colorscheme. You can change it to something else by:

```lua
  local noice = require("noice")
  noice.setup({
    views = {
      cmdline_popup = {
        win_options = {
          winhighlight = {
            Normal = "Normal",
            FloatBorder = "DiagnosticInfo",
            IncSearch = "",
            Search = "",
          },
        },
      },
    },
  })

```

**Comment by Integralist** [comment]
Thanks! I tried that config but it doesn't look to fix it...

<img width="1197" alt="Screenshot 2022-10-09 at 11 54 39" src="https://user-images.githubusercontent.com/180050/194752854-db3ca5e7-913c-4667-bde0-fde459d2a523.png">

**Comment by folke** [comment]
Well, obviously  you need to rplace the `DiagnosticInfo` by another group, since that's the one causing the issue ;)

**Comment by folke** [comment]
Try `DiagnosticSignInfo` instead. Looks like a better option than `DiagnosticInfo` for gruvbox-material

**Comment by Integralist** [comment]
> Well, obviously you need to rplace the DiagnosticInfo by another group, since that's the one causing the issue ;)

Oh dear what a plonker I am, sorry 🤦🏻 

Yes, `DiagnosticSignInfo` fixed it 👍🏻

**Comment by Integralist** [comment]
@folke So I just realised this issue happens when typing `/` as well, even though I've fixed the `:` scenario using `DiagnosticSignInfo`. I tried assigning that same highlight group to `IncSearch` and `Search` but that didn't affect it at all.

```
            cmdline_popup = {
              win_options = {
                winhighlight = {
                  Normal = "Normal",
                  FloatBorder = "DiagnosticSignInfo",
                  IncSearch = "DiagnosticSignInfo",
                  Search = "DiagnosticSignInfo",
                },
              },
            },
```
