### ISSUE TITLE
Question: Don't automatically open messages view

### ISSUE THREAD

**Issue by harrisoncramer** [folke/noice.nvim#403]
Hey, thanks for the great plugin.

I've set the default view for messages to be the messages buffer, and for errors and warnings to be handled by notify.

However, I don't want the messages buffer open all of the time, I'd like it to be hidden by default. Right now it pops back open (and grabs focus) which is aggravating. This happens whenever a new message (such as a writefile message) occurs. Is there a way to hide the messages buffer by default?

**Comment by folke** [comment]
nope
