### ISSUE TITLE
feature: configure lsp hover handler to use `silent = true`

### ISSUE THREAD

**Issue by igorlfs** [folke/noice.nvim#412]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Having the ability to not display anything on hover would be nice, specially when using multiple LSP servers attached to the same buffer, where some may not provide hover capabilities. Overall, it feels cleaner than "No information available".

### Describe the solution you'd like

Having an option (a preset?) to control whether to use `silent = true`. I don't think this should be the default, as some users may get confused thinking the hover isn't working.

### Describe alternatives you've considered

Since manually setting the handlers with noice is a no-go, I haven't looked into any alternatives.

**Comment by jisensee** [comment]
I was too looking for a way to get rid of that annoying notification and found that as a workaround you can add a custom route to stop that message being processed. Just needed to add this to the routes list in the plugin opts:
````
{
  filter = { find = 'No information available' },
  opts = { stop = true },
},
````
Not the best solution but does the job for now.

**Comment by igorlfs** [comment]
Hey @jisensee, thanks for the workaround!

**Comment by igorlfs** [comment]
Thanks folke!
