### ISSUE TITLE
bug: can't use `popupmenu` view in `routes` 

### ISSUE THREAD

**Issue by TheSafdarAwan** [folke/noice.nvim#413]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1259+g434f3d6a0

### Operating system/version

5.15.94-1-MANJARO x86_64 GNU/Linux

### Describe the bug

I am not able to use the `popupmenu`. in the `routes`. I looked into source code and found out that `popupmenu` view doesn't have backend module which is causing the problem. 
I don't know if i am making some mistake but the `popupmenu` view was listed in views why can i use it.
I am trying to replace the select menu option with the `popupmenu`.
This is the error
```
    

...local/share/nvim/lazy/noice.nvim/lua/noice/util/lazy.lua:6: module 'noice.view.backend.popupmenu' not found:
	no field package.preload['noice.view.backend.popupmenu']
cache_loader: module noice.view.backend.popupmenu not found
cache_loader_lib: module noice.view.backend.popupmenu not found
	no file './noice/view/backend/popupmenu.lua'
	no file '/home/safdar/.local/temp/builds/neovim/.deps/usr/share/luajit-2.1.0-beta3/noice/view/backend/popupmenu.lua'
	no file '/usr/local/share/lua/5.1/noice/view/backend/popupmenu.lua'
	no file '/usr/local/share/lua/5.1/noice/view/backend/popupmenu/init.lua'
	no file '/home/safdar/.local/temp/builds/neovim/.deps/usr/share/lua/5.1/noice/view/backend/popupmenu.lua'
	no file '/home/safdar/.local/temp/builds/neovim/.deps/usr/share/lua/5.1/noice/view/backend/popupmenu/init.lua'
	no file './noice/view/backend/popupmenu.so'
	no file '/usr/local/lib/lua/5.1/noice/view/backend/popupmenu.so'
	no file '/home/safdar/.local/temp/builds/neovim/.deps/usr/lib/lua/5.1/noice/view/backend/popupmenu.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './noice.so'
	no file '/usr/local/lib/lua/5.1/noice.so'
	no file '/home/safdar/.local/temp/builds/neovim/.deps/usr/lib/lua/5.1/noice.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

```

### Steps To Reproduce

1. add `popupmenu` view to the routes.
2. you will get the error as soon as you open another instance of the neovim.

### Expected Behavior

to show a popup menu for selection.

### Repro

```Lua
This is the route config.


routes = {
	{
		view = "popupmenu",
		filter = { event = "msg_show", find = "Select a command" }, -- select menu
	},
} --- @see section on routes
```

**Comment by folke** [comment]
The popupmenu view is only use for the native popupmenu (`:h pmenu`)
