### ISSUE TITLE
[Feature request]: Allow the dismissal of 'mini' view

### ISSUE THREAD

**Issue by lmburns** [folke/noice.nvim#417]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I'd like to be able to dismiss the `mini` view notification windows.

### Describe the solution you'd like

Would it be possible to get something like [`nvim-notify`'s `dismiss` function](https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/init.lua#L115)?

### Describe alternatives you've considered

Setting a lower timeout on the window. However, this isn't favorable all of them time. Sometimes I would like to have windows open longer than others, and when they are in the way and I want them to be closed, I'd like to close them.

I have a function like the following, that allows me to focus floating windows and I can close them if I'd like, but that involves having to press the keybinding for the function, followed by `:q`, when I can just have a single builtin keybinding to close the window.

<details>
<summary>Function</summary>

```lua
---Focus the floating window
M.focus_floating_win = function()
    if D.is_floating_window(fn.win_getid()) then
        cmd.wincmd("p")
        return
    end
    for _, winnr in ipairs(fn.range(1, fn.winnr("$"))) do
        local winid = fn.win_getid(winnr)
        local conf = api.nvim_win_get_config(winid)
        if conf.focusable and conf.relative ~= "" then
            fn.win_gotoid(winid)
            return
        end
    end
end
```
</details>

### Additional context

I see that there is `MiniView:hide`, but the function is empty.
I tried calling `require('noice.view.backend.mini'):hide()` and it doesn't do anything.

**Comment by bennypowers** [comment]
I tried this, with `:NoiceDisable` and `:NoiceEnable`. I suppose it works, but it clears the nvim window for a few frames and that's annoying

```lua
command('ClearNotifications', function()
  local has_notify, notify = pcall(require, 'notify')
  if has_notify then
    notify.dismiss { silent = true }
  elseif pcall(require, 'notifier') then
    vim.cmd[[:NotifierClear]]
  elseif pcall(require, 'noice') then
    -- vim.cmd[[:NoiceDisable]]
    -- vim.cmd[[:NoiceEnable]]
  end
  vim.cmd[[nohlsearch|diffupdate|normal! <C-L><CR>]]
end, {
  bang = true,
})
```
