### ISSUE TITLE
bug: preset.lua:12 attempt to index nil value

### ISSUE THREAD

**Issue by ghostbuster91** [folke/noice.nvim#418]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-d1e0f74

### Operating system/version

 Ubuntu 20.04.6 LTS

### Describe the bug

Hi, first of all thank you very much for this awesome plugin. 

I am not familiar with lazy (I use another plugin manager), so please forgive me if that is a rookie mistake. I read the docs and afaik this is the way to configure plugins. When trying to write a reproducible example for another bug I encountered following issue. When I open nvim with attached config noice fails with `preset.lua:12 attempt to index local 'options' a nil value`

### Steps To Reproduce

1. `nvim -u repro.lua`

### Expected Behavior

There should be no errors.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "folke/noice.nvim",
        tag = "v1.9.5", -- tested other versions as well
        config = function()
            require("noice").setup()
        end,
        dependencies = {
            -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
            "MunifTanjim/nui.nvim",
            -- OPTIONAL:
            --   `nvim-notify` is only needed, if you want to use the notification view.
            --   If not available, we use `mini` as the fallback
        }
    }
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})



vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by ghostbuster91** [comment]
Hi @folke thanks for taking a look at it. It is weird because I am able to reproduce it each time with the attached config.

After looking at some other issues I realized that I am missing one option that others have been using `event = "BufReadPost",` in plugin configuration.

After adding that option the issue disappeared. Maybe it is worth adding that into the minimal reproduction template?

**Comment by folke** [comment]
As I said, there is simply no code path that can trigger that issue with the latest version.

Don't use that `tag=` thing. IT may have been broken at some point, but I'm obviously not going to look into bugs in older versions.

**Comment by folke** [comment]
You get the error for `options` being `nil` at this line here:
https://github.com/folke/noice.nvim/blob/1da4edfba3e9278e98fc9723d7235d9ab3889744/lua/noice/config/preset.lua#L12

That function is called here https://github.com/folke/noice.nvim/blob/1da4edfba3e9278e98fc9723d7235d9ab3889744/lua/noice/config/init.lua#L243

Options is **ALWAYS** set
https://github.com/folke/noice.nvim/blob/1da4edfba3e9278e98fc9723d7235d9ab3889744/lua/noice/config/init.lua#L224

So as you can see the error you get is simply **not possible**. 

I also tested your repro and as I figured, I don't get an error.

So whatever you're doing, you're doing something very wrong.

**Comment by ghostbuster91** [comment]
just fyi: I found the culprit. In nix neovim is wrapped with a script that modifies the runtime path. Even though lazy was pulling the newest version the old one from the nix store was taking precedence. 

I didn't know about it until now, sorry for bothering you.
