### ISSUE TITLE
feature: Do not close notification until I type another command

### ISSUE THREAD

**Issue by TroySigX** [folke/noice.nvim#419]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

As title suggests

### Describe the solution you'd like

Like in conventional Neovim cmdline bar, it doesn't delete the message until I type a new command

### Describe alternatives you've considered

Not yet

**Comment by folke** [comment]
You can always show the output of the last command with `:Noice last`

**Comment by TroySigX** [comment]
I typed the setup command for copilot, and noice shows the message (in the bottom left corner): 
![image](https://user-images.githubusercontent.com/88051085/229174585-122288cc-d7d2-40e7-8a16-2779a010e740.png)

When I typed `:Noice last`, it shows nothing:
![image](https://user-images.githubusercontent.com/88051085/229174770-77b121a0-8d7b-47f4-aa56-1a199aacdf89.png)

**Comment by TroySigX** [comment]
It's not a lsp progress message. It's just a message from the GitHub Copilot plugin. 
Here's how the message shows without `noice`:
![image](https://user-images.githubusercontent.com/88051085/229175858-9a049413-1248-4364-b17f-e406feae6f47.png)

`:Noice all` didn't work as well.

**Comment by folke** [comment]
`all` is not a default command. Add the below to your noice options and try again:

```lua
    commands = {
      all = {
        -- options for the message history that you get with `:Noice`
        view = "split",
        opts = { enter = true, format = "details" },
        filter = {},
      },
    },
```

**Comment by TroySigX** [comment]
Thank you, it works now! But what if I just want to see the last message?

**Comment by folke** [comment]
below `filter`, add `filter_opts  = {count = 1}`.

It's all in the readme. Search for `commands`

**Comment by TroySigX** [comment]
Thank you very much @folke!
