### ISSUE TITLE
Empty Buffer is created with rmagatti/auto-session plugin

### ISSUE THREAD

**Issue by ariel-frischer** [folke/noice.nvim#42]
**Describe the bug**
Not sure why but when using https://github.com/rmagatti/auto-session with this plugin I keep getting an extra empty buffer window when I open a new session. Just calling `nvim` in a previously used directory (it saves a session after quitting) after opening some files. 

**Which version of Neovim are you using?**
I'm using packer and nvchad with Neovim v0.8.0

**To Reproduce**
Open up a new session and you start having an extra new empty buffer. I also am using nvim-tree and bunch of other plugins so idk if maybe something else is interfering with this plugin.

**Expected Behavior**
No extra buffer window when new session is opened.

**Comment by folke** [comment]
You proably have `blank` in your `sessionoptions`?

I use https://github.com/folke/persistence.nvim instead where I don't add `blank` (empty windows)

**Comment by ariel-frischer** [comment]
Yes I did, I removed it and that seemed to work thank you!
