### ISSUE TITLE
bug: html tag not removed in treesitter lsp markdown hover

### ISSUE THREAD

**Issue by seblj** [folke/noice.nvim#424]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-1324+ge30cc8be1

### Operating system/version

MacOs 13.1

### Describe the bug

It doesn't properly remove all html tags for the markdown render of lsp docs

Neovim:

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/5160701/230508090-f1ca5838-e070-4ab4-b79a-4960d28b9e7f.png">

VsCode:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/5160701/230508205-ed7998bf-a472-405b-85c1-0ca9fc518bf8.png">

Note the `<code>Option\<String\></code>` in the neovim popup. I would expect something like in vscode where the tags are not included

### Steps To Reproduce

Use this Rust file:

```rs
fn main() {
    let foo = Some("foo");
    foo.map(|_| "bar");
}
```

Try to hover the docs on `map` and notice the tags being there

### Expected Behavior

I would expect something like this where the `<code></code> is gone:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/5160701/230508596-cb522a87-4baf-4f90-9547-494540c80089.png">

Note I just `set modifiable` and removed the tags to make it look like it ideally should. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by seblj** [comment]
It seems like something like this could work for the escape character:

```diff
diff --git a/lua/noice/text/markdown.lua b/lua/noice/text/markdown.lua
index cef6b13..bb84214 100644
--- a/lua/noice/text/markdown.lua
+++ b/lua/noice/text/markdown.lua
@@ -63,7 +63,7 @@ end
 function M.parse(text, opts)
   opts = opts or {}
   ---@type string
-  text = text:gsub("</?pre>", "```"):gsub("\r", "")
+  text = text:gsub("</?pre>", "```"):gsub("\r", ""):gsub("(\\)(%p)", "%2")
   text = M.html_entities(text)
 
   ---@type Markdown
```

 However, I am not too sure about how we should deal with the `<code>` tag. Because if we change it for a backtick, then all the text inside will be interpreted as a literal string, and the conceal won't work for the url which makes it a bit ugly. So I think maybe just doing `:gsub("</?code>", "")` could work okay. If you have a better idea, let me know!

**Comment by seblj** [comment]
Another potential expected behaviour is to have it all be wrapped in backticks, but that would probably require some changes to queries in `nvim-treesitter` for concealing or something like that. It seems like helix does it like this:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/5160701/230616084-59a1c7a6-f25f-4c10-a2b3-ce0272df18ca.png">

**Comment by seblj** [comment]
@folke that won't work correctly, because now the links will not be concealed properly:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/5160701/232294221-6499f222-7eb2-4cd5-80e2-92b210127853.png">

**Comment by seblj** [comment]
Something like this seems to work good:

```diff
diff --git a/lua/noice/text/markdown.lua b/lua/noice/text/markdown.lua
index b14a2c0..1078679 100644
--- a/lua/noice/text/markdown.lua
+++ b/lua/noice/text/markdown.lua
@@ -64,7 +64,7 @@ end
 function M.parse(text, opts)
   opts = opts or {}
   ---@type string
-  text = text:gsub("</?pre>", "```"):gsub("\r", ""):gsub("</?code>", "`")
+  text = text:gsub("</?pre>", "```"):gsub("\r", ""):gsub("</?code>", ""):gsub("(\\)(%p)", "%2")
   text = M.html_entities(text)
 
   ---@type Markdown
```

**Comment by folke** [comment]
I've reverted my changes. This should be fixed in the treesitter markdown parser. `\\` should probably be concealed when inside `<code>` tags

**Comment by folke** [comment]
Your suggested changes may work for rust, but will very likley break a lot of other markdown code

**Comment by seblj** [comment]
I don't think it will very likely break a lot of other markdown code. This fix has been suggested to upstream as well:

https://github.com/neovim/neovim/pull/13803
https://github.com/neovim/neovim/pull/14069

It looks like the reason they didn't go this route is because they wanted users to have more general control over syntax rules: https://github.com/neovim/neovim/pull/14073

I agree with mjlbach on this: `I'm betting the frequency of unintended rendered \ >> frequency of intended \`

And by replacing `<code>` with a backtick will always break the concealing of url since then it isn't parsed as a url anymore. Fixing this would probably require a lot of change in the `markdown_inline` parser
