### ISSUE TITLE
feature: Showmode doesn't differentiate between Macro recording and visual/insert mode

### ISSUE THREAD

**Issue by AdityaRoot** [folke/noice.nvim#425]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

As per [this documentation](https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages), I have been using showmode on my lualine statusbar to show the macro recording messages:

```lua
require('lualine').setup {
    options = {
        theme = 'kanagawa'
    },
    sections = {
        lualine_a = { 'mode' },
        lualine_b = { 'encoding', 'branch', 'diff', 'diagnostics', {
            require("noice").api.statusline.mode.get,
            cond = require("noice").api.statusline.mode.has,
            color = { fg = "#ff9e64" },
        } },
        lualine_c = { 'filename',
        },
        lualine_x = { 'filetype' },
        lualine_y = { 'progress' },
        lualine_z = { 'location' }
    },
}
```

However this has the issue that it not only shows when I am recording a macro, but also when I go into insert or visual mode:
![image](https://user-images.githubusercontent.com/66115252/230729073-91b5c3bd-17b6-4733-8670-a30805c8615f.png)

### Describe the solution you'd like

Hoping for any way to allow only showing the recording messages and ignoring the mode changes. 

### Describe alternatives you've considered

I have gone through the :h showmode and other relevant Noice/NeoVim documentation - however I am rather new and still have a lot to learn - so I apologize if this has an easy fix noted somewhere that I overlooked. 

Currently I'm just dealing with the extra pop-up, though it would be fabulous to have a way to filter it!

**Comment by yingmanwumen** [comment]
Hello, you can add the following simple codes to avoid that:

```lua
local function macro_recording()
	local mode = require("noice").api.statusline.mode.get()
	if mode then
		return string.match(mode, "^recording @.*") or ""
	end
	return ""
end
require("lualine").setup({
  -- ...
  sections = {
    lualine_c = {
       -- ....
       macro_recording,
    }
  }
})
```

 I've tested it, and it works.

**Comment by AdityaRoot** [comment]
It does indeed, thank you so much for the work-around!

**Comment by MariaSolOs** [comment]
@folke do you have another workaround for this? I'm afraid that by hardcoding the regex I might end up missing other messages.

**Comment by folke** [comment]
That's really odd, I don't see the other modes in my lualine.

```lua
{
  function() return require("noice").api.status.mode.get() end,
  cond = function() return package.loaded["noice"] and require("noice").api.status.mode.has() end
},
```

You probably should set `vim.opt.showmode = false`

**Comment by folke** [comment]
Can confirm, just set `vim.opt.showmode = false`. That's not needed since you use lualine. That way noice will only report recording mode.

**Comment by MariaSolOs** [comment]
@folke as always, thank you <3
