### ISSUE TITLE
feature: More customisation for notify: duration and render style

### ISSUE THREAD

**Issue by oyarsa** [folke/noice.nvim#426]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I'd like to change how long the messages are displayed on the screen and which render style is used globally (e.g. always use the `compact` style). 

### Describe the solution you'd like

Add `render_style` and `duration` keys to the `notify` options.

### Describe alternatives you've considered

I went through the documentation and the code, but I didn't find anything that could be used for this.

**Comment by gennaro-tedesco** [comment]
Have you tried changing the `nvim-notify` defaults? Such properties belong to the notify plugin, what `noice` does is only to invoke it (with whichever default properties you have set).

**Comment by oyarsa** [comment]
That worked! Thank you. For reference, it was as easy as adding the following lines after `noice`'s setup:

```lua
require("notify").setup({
	render = "compact",
	timeout = 2000,
	stages = "static",
})
```
