### ISSUE TITLE
feature: change location of notifications

### ISSUE THREAD

**Issue by Ahwxorg** [folke/noice.nvim#427]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

when writing code, notifications show up in front of code which bugs me, so i was wondering if i could move the notifications to another area of the screen, but could not find it in the docs.

### Describe the solution you'd like

some configuration settings to move the notifications

### Describe alternatives you've considered

ive considered switching to another plugins since this gives me quite anoyance

### Additional context

this is a very bad github issue thingy but you get the idea...

**Comment by gennaro-tedesco** [comment]
Have you tried using different [views](https://github.com/folke/noice.nvim#-views) for notifications? For instance `mini` is minimally invasive, you could use it to redirect most of your notification using filters.

**Comment by Ahwxorg** [comment]
Not yet, I will soon.
