### ISSUE TITLE
bug: Two statuslines when opening multiple files 

### ISSUE THREAD

**Issue by Dosx001** [folke/noice.nvim#429]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Arch Linux

### Describe the bug

When opening multiple files using `-p`, all tabs minus the first one will have two statuslines when using `view="cmdline"`.

Note, if you resize your window, the extra statusline will be removed for the current tab.

I wasn't able to recreate this issue using `nvim -u repro.lua` so my Steps To Reproduce will include a docker container.

![image](https://user-images.githubusercontent.com/62494922/231319464-02e86579-d0e9-45c4-9a7a-69c331f969a7.png)

### Steps To Reproduce

1. docker pull archlinux
2. docker run -it archlinux
3. pacman -Sy
4. pacman -S neovim git
5. nvim init.lua # Paste config from Repro section
7. nvim init.lua init.lua -p

### Expected Behavior

Have one single statueline for each tab.

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({
                "git",
                "clone",
                "--filter=blob:none",
                "https://github.com/folke/lazy.nvim.git",
                "--branch=stable",
                lazypath,
        })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
        "folke/noice.nvim",
        config = function()
                require("noice").setup({
                        cmdline = {
                                view = "cmdline",
                        },
                })
        end,
        dependencies = {
                "MunifTanjim/nui.nvim",
                "rcarriga/nvim-notify",
        },
})
```

**Comment by folke** [comment]
not a noice issue. Check if this still happens on nightly. If so, submit a Neovim issue
