### ISSUE TITLE
Cannot disable History/message/notify part

### ISSUE THREAD

**Issue by BerkeleyTrue** [folke/noice.nvim#43]
**Describe the bug**

I'm would love to just use the cmdline popup by itself, but I can't figure out how to disable the notify component. 

**Which version of Neovim are you using?**
Gui? Nightly? Version?
0.8
**To Reproduce**
Enable noice, set history, notify to { enabled = false}

**Expected Behavior**
messages to work as normal vim.

**Screenshots**
![image](https://user-images.githubusercontent.com/6775919/194675884-386bafeb-6ad5-4dc0-9c16-7aa0e75fcf32.png)

**Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
Log comes here
</pre>
</details>

**Comment by Shougo** [comment]
Well, it is hard coded.

```lua
  vim.ui_attach(Config.ns, {
    ext_messages = true,
    ext_cmdline = true,
    ext_popupmenu = Config.options.popupmenu.enabled,
  }, function(event, ...)
    -- dont process any messages during redraw, since redraw triggers last messages
    if not Hacks.inside_redraw then
      safe_handle(event, ...)

      -- check if we need to update the ui
      if Util.is_blocking() then
        Util.try(Router.update)
      end
    end
  end)
```

**Comment by Shougo** [comment]
Please test #44.

**Comment by folke** [comment]
I merged @Shougo changes. You can disable the messages with:

```lua
  local noice = require("noice")
  noice.setup({
    messages = {
      enabled = false,
    }
  })
```
