### ISSUE TITLE
How to change position of notification messages

### ISSUE THREAD

**Issue by kaykhan** [folke/noice.nvim#440]
I do not like to use [notify.nvim](https://github.com/rcarriga/nvim-notify) so im using the default notification. However the postion of the notifications seems to conflict with an existing plugin i use `j-hui/fidget.nvim`.

is there a way reposition the notifications?

- Without noice, the notification message when searching for a phrase that does not exists appears in the bottom left.
![image](https://user-images.githubusercontent.com/5202527/233830476-6104bee9-35cd-4a27-b7a1-89dbcf792017.png)

- With noice it appears in the bottom right ( conflicting with what i have with fidget, although i was not able to capture it this time )
![image](https://user-images.githubusercontent.com/5202527/233830606-c8c759ac-2c90-43b7-99fe-50f6ccc86dee.png)

**How do i change the position/location of these messages?**

**Comment by folke** [comment]
Noice includes progress notifications as well, so you dont really need fidget.
If you want to change the position of anything, check the readme for views
