### ISSUE TITLE
bug: A annoying warning.

### ISSUE THREAD

**Issue by buddhiko1** [folke/noice.nvim#444]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

gentoo linux

### Describe the bug

![last](https://user-images.githubusercontent.com/8435488/235032442-a95377f2-d923-442a-94a9-e8b14c875cf3.png)

### Steps To Reproduce

Sometimes it appears, sometimes it doesn't appear.

### Expected Behavior

None

### Repro

```
M.config = function()
  local noice = load("noice")
  local options = {
    messages = {
      view_search = false
    },
    lsp = {
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
        ["cmp.entry.get_documentation"] = true,
      },
      progress = {
        enabled = false,
      },
      signature = {
        enabled = false,
      },
    },
  }
  noice.setup(options)
end
```

**Comment by folke** [comment]
That's not noice, but nvim-notify

**Comment by buddhiko1** [comment]
> 

Sorry, I was too careless.
