### ISSUE TITLE
bug: Shows &emsp; instead of actual space in markdown

### ISSUE THREAD

**Issue by Jomik** [folke/noice.nvim#447]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

macOS 13.1

### Describe the bug

`yamlls` hover is filled with `&emsp;`, which shouldn't be there.
![image](https://user-images.githubusercontent.com/699655/235475500-91572d0f-7ccd-4135-8426-3a0153b6992e.png)
Issue happens for me when overriding lsp stylize_markdown with `noice` implementation.

Similar issue has been fixed in https://github.com/neovim/neovim/issues/22757
Related issue https://github.com/folke/noice.nvim/issues/424

### Steps To Reproduce

1. Install the `repro.lua` given.
2. Create `.gitlab-ci.yaml` with content
```yaml
stages:
  - hello
```
3. Run `nvim -u repro.lua .gitlab-ci.yaml`, wait for mason to install `yamlls`.
4. Quit and reopen file.
5. Hover (`K`) on `hello`, observe above issue.

### Expected Behavior

I would expect not to see `&emsp;` as it should be fixed in neovim 0.9.
We still need https://github.com/redhat-developer/yaml-language-server/pull/863 to get rid of the additional `&emsp;`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"LazyVim/LazyVim",
	-- add any other plugins here
	{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
	{
		"neovim/nvim-lspconfig",
		opts = {
			servers = {
				yamlls = {
					settings = {
						yaml = {
							schemas = {
								["https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json"] = ".gitlab-ci.y*l",
							},
							hover = true,
						},
					},
				},
			},
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Feel free to submit a PR
