### ISSUE TITLE
Allow user configuration for positioning `nvim-cmp` popup 

### ISSUE THREAD

**Issue by akinsho** [folke/noice.nvim#45]
**Is your feature request related to a problem? Please describe.**
This request is pulled out of https://github.com/folke/noice.nvim/issues/2#issuecomment-1267007942, so it would be easier to track. I appreciate there's been quite a lot of activity so no pressure on this one, but given it was just a comment in an issue with a different focus thought I'd split it out.

**Describe the solution you'd like**
So as I mentioned in that issue, I think it would be nice for the use to be able to decide where the cmp popup window opens, similar to how the nui popupmenu's position is configurable. This way a user could have the cmp window open beneath the cmdline popup entirely so they don't overlap (or wherever else they think it would be best)

**Describe alternatives you've considered**
A sort of alternative would be using the builtin popup, but this is ultimately not really the same as using cmp which works differently i.e. it's a pluggable autocompletion engine and it's functionality isn't the same as the wildmenu

**Comment by folke** [comment]
Hi!

This should probably be a feature request for `cmp`, where you can specify the position and size of the cmp popup for the cmdline.

Currently, when you have `cmp-cmdline` enabled, Noice is only patching the cmp code so it gets the correct position of the cmdline.

**Comment by akinsho** [comment]
Thanks for the response @folke that's fair enough. I'll open the issue over in nvim-cmp
