### ISSUE TITLE
feature:  Allow configuration of the `inputlist` prompts

### ISSUE THREAD

**Issue by akinsho** [folke/noice.nvim#456]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Currently when input is requested using `inputlist` it is shown using an `nvim-notify` popup and I'm unable to change it's appearance at all. This was previously mentioned in https://github.com/folke/noice.nvim/issues/115 and the issue that that points too and you kindly added the change for the `input` but not the `inputlist` I'm not sure if there is any complexity there or blocker.

### Describe the solution you'd like

Tbh I'd ideally want one of two outcomes I can configure things as closely to how they appear natively i.e. natively the commandline area expands and the content appears there. It takes up a good portion of the screen and is hard to avoid or I could put it into a popup menu like nui's but I guess the information isn't sent as clearly as that via the api 🤷🏾‍♂️. Currently with noice it appears in a small box and it's easy to not notice that your input is being requested. 

### Describe alternatives you've considered

I'm not sure there are any good alternatives i.e. allow the user to configure it with whatever constraints that might entail seems the best option unless this is technically blocked

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/236692937-23f77a5d-66b6-4a6a-a5cd-1994db9cb6ba.png)

Inputlist is coming in as a regular msg_show, so there's not much I can do about that.

Where do you use that? As the default vim.ui.input? Better to use something like dressing.nvim for that.

As an alternative, you could manually override `vim.fn.inputlist`, but that will only work for lua code that calls that function

**Comment by akinsho** [comment]
No worries @folke I thought it might be the case, inputlist is used heavily by `orgmode.nvim` 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/22454918/236695135-424cd7fe-f5bf-49e2-b9ca-59b4a5b74583.png">

in native nvim it opens in the commandline area and very clearly takes over the bottom half of your screen whereas with noice it appears like

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/22454918/236695192-164ace3f-a942-45f7-bddf-21f911df51de.png">

On a big enough monitor it doesn't really feel like a blocking input and is easy to mistake for a random notification, but I figured there might be some technical issues working around it.
