### ISSUE TITLE
signature window should close previous ones before to open a new one

### ISSUE THREAD

**Issue by Thanatermesis** [folke/noice.nvim#460]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

Linux

### Describe the bug

I noticed that sometimes cmp re-draws it changing the direction / position of the popup (to-bottom or to-top), if there's signature popup opened by noice it looks like it redraws it again in the other direction but leaving the old one opened too, having 2 same signature popups showing up

I think that the issue is simply that noice should simply close any existing noice popup before to draw a new one 

### Steps To Reproduce

mentioned before

### Expected Behavior

mentioned before

**Comment by folke** [comment]
Noice's signature window and cmp completion window are two different things. In my setup they also dont interfer with each other. Closing since this is a non issue. Open a discussion if you want to ask other people.
