### ISSUE TITLE
Avoid blankline rendering tabs in the progress messages 

### ISSUE THREAD

**Issue by Thanatermesis** [folke/noice.nvim#462]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

Linux

### Describe the bug

The plugin blankline, which is https://github.com/lukas-reineke/indent-blankline.nvim , draws some tab lines in the noice progress messages, maybe noice should should include a conf (filetype-exclude or buffertype-exclude?) to avoid blankline to draw on these messages, or set the filetype/buffertype to a value that is already excluded (like lspinfo, nofile, or just "" _empty_)

Maybe I'm wrong and this issue should be reported to blankline instead, or maybe the issue is on my side where I just need to put the desired conf myself, I was just thinking to report it because IMHO noice should have it nicely show by default when installed

_example:_

![image](https://github.com/folke/noice.nvim/assets/1181626/a88b18e9-be4a-42e2-9b87-25c723e281bc)

### Steps To Reproduce

having blankline plugin installed

### Expected Behavior

to not have visual artifacts

**Comment by Thanatermesis** [comment]
Note: this bug is resolved in the blankline entry conf:

```lua
  buftype_exclude = { "terminal", "noice", },
```
as mentioned before, I don't know if this should be considered an issue in noice (in order to improve the rendering by default) but if its only on the user's side or blankline, this issue can be closed, having the previous line as solution for other affected users

**Comment by folke** [comment]
This is not a noice issue and should be fixed as you mentioned
