### ISSUE TITLE
Search count virtual text gets stuck on the line

### ISSUE THREAD

**Issue by Galicarnax** [folke/noice.nvim#464]
### Did you check docs and existing issues?

- [x] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Arch Linux

### Describe the bug

I have `view_search = "virtualtext"` in the config, and most of the time that works smoothly. But once in a while, one of the virtual texts (showing the number of current match and total search count) gets stuck at the end of the line. I still can loop over matches, and at each line, virtual text is shown normally, disappearring when I move to the next match. But the one which is stuck keeps hanging on its line. When I move to that match, a second virtual text is shown normally after the stuck one. The stuck one does not go away with hitting `<Esc>` or anything else.

### Steps To Reproduce

Unfortunately, I haven't been able yet to detect exact triggers for this behaviour. It happens not very often (say, one in ten searches). I guess, some combintation of triggers is involved (e.g., deleting the current search and moving to a different buffer and back).

### Expected Behavior

Search count virtual text follows cursor, without getting stuck on the line.

**Comment by rkulla** [comment]
I even get multiple stuck lines:

![noice](https://github.com/folke/noice.nvim/assets/244283/ce577375-0abf-47c0-a2c0-e3886f7a7255)

If i were to then `:set nohlsearch` (even multiple times) just the _unstuck_ ones would go away (in this case `/timestamp     [3/31]` would be the only one to go away).  nvim 0.9 with latest version of noice.

**Comment by folke** [comment]
right, the switching buffers does it indeed. Will fix
