### ISSUE TITLE
Search highlight using a specific color

### ISSUE THREAD

**Issue by Thanatermesis** [folke/noice.nvim#468]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I just found that Noice includes a feature that shows a virtual text while searching, this is very good because then I can see more clearly "where is my cursor from the multiple search results", I have before used the plugin vim-bling which blinks on the cursor-position when pressing "n" (next) of a search result, but this plugin bugs when using with Noice

Unfortunately the virtualtext showing search_result is not very visible, so I tried to change it to something much more visual when doing a search:

```lua
  DiagnosticVirtualTextInfo = { fg = colors.black, bg = colors.teal },
```

It worked good, except that then I found that the results in LSP diagnostics started to show like this too

Could be possible to add a specific HL name for it?

----

Examples:

Before:

![image](https://github.com/folke/noice.nvim/assets/1181626/a8e98ddb-1688-4f6c-8fff-69df1c347be7)

After:

![image](https://github.com/folke/noice.nvim/assets/1181626/d582a97c-579b-461e-8528-26a1160c2250)

As we can see in the example, is much more easy to know "on which result is my cursor" when doing a search, and gets rid of needing external plugins since Noice features this nice search_result :) 

### Describe the solution you'd like

A specific HL name for it

### Describe alternatives you've considered

Using extra plugins, unneeded thanks to this feature (and some are bugged)

**Comment by folke** [comment]
Check the docs. It's `NoiceVirtualText`

**Comment by Thanatermesis** [comment]
Ah sorry, I was confused by this line: https://github.com/folke/noice.nvim/blob/main/doc/noice.nvim.txt#L524

Thank you!
