### ISSUE TITLE
Autocomplete with Noice messes up indentation in some cases

### ISSUE THREAD

**Issue by debugloop** [folke/noice.nvim#47]
**Describe the bug**
When installing Noice (empty `.setup()`), any completion done without an LSP is de-indented by a single space. I have tried with `-u NORC` to no avial, and I've also uninstalled all other plugins temporarily to no avail. Having `popupmenu` disabled is also without effect on this issue. I am testing this on Lua files, as I don't regularly have sumneko installed.

If I leave everything in my RC, I can:
- C-x C-f to complete path names without deindent
- C-x C-o to produce a complaint about no omnifunc in lua files *and* deindent by one space
- C-x C-n to complete without deindent

I'd appreciate any pointers on how to go about debugging this, I realise that this report does almost nothing to narrow this down yet, and that the actual issue could even be unrelated to Noice, even though I only notice it with Noice installed.

**Which version of Neovim are you using?**
v0.8.0 in kitty

**To Reproduce**
1. install Noice as suggested by README
2. enjoy all Noice features
3. suffer completion breaking indentation

**Expected Behavior**
Not messing with completion results.

**Screenshots**
https://paste.selfnet.de/index.php/Lwfw/ (<200kB mp4)

**Noice Log**
None is produced

**Comment by folke** [comment]
I cant reproduce this. Can you create a [minimal.lua](https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue) that reproduces this?

**Comment by debugloop** [comment]
I've narrowed it down to some conflict with the `mini.nvim`'s `mini.complete` module. I'm not sure how this issue persisted through `vim.o.loadplugins = false` on yesterdays attempt... See the attached minimal config. To reproduce:

1. set `XDG_CONFIG_HOME=./test.config` and `XDG_DATA_HOME=./test.local`
2. put attached config in `.test.config/nvim/`
3. ensure nvim has installed packer and all plugins and do a clean launch
4. `4jol<BS>l` -> the second attempt at autocompleting the word "local" deindents (no <C-n> or anything required)

Might be this actually is an issue for @echasnovski's mini.nvim.

```lua
vim.o.termguicolors = true
vim.o.expandtab = true 
vim.o.shiftwidth = 2 

local ensure_packer = function()
  local fn = vim.fn
  local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd [[packadd packer.nvim]]
    return true
  end
  return false
end

local packer_bootstrap = ensure_packer()

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  -- My plugins here
  -- use 'foo1/bar1.nvim'
  -- use 'foo2/bar2.nvim'
  use({
    "folke/noice.nvim",
    event = "VimEnter",
    config = function()
      require("noice").setup()
    end,
    requires = {
       -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
       "MunifTanjim/nui.nvim",
       "rcarriga/nvim-notify",
    }
  })

  use({ -- mini plugin suite
    'echasnovski/mini.nvim',
    config = function()
      require('mini.completion').setup({})
    end
  })

  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end)

```

**Comment by echasnovski** [comment]
I think I managed to reproduce this without 'mini.completion'. It doesn't deindent, but rather... swaps second to last character to be last after completion?

It is not an issue with 'mini.completion' per se, but with using `<C-n>` builtin completion (imitated by 'mini.completion' with default fallback completion). It seems to be doing so because of a notify window with message "Scanning tags" (usually displayed in command line).

Here is config:
```lua
-- Replace `packadd` arguments to actual plugin names in your 'pack' directory
vim.cmd('packadd nui')
vim.cmd('packadd nvim-notify')
vim.cmd('packadd noice')
require('noice').setup()
```

Here is demo with stable Neovim 0.8 release:

https://user-images.githubusercontent.com/24854248/195148443-6dffd507-8c69-4ff0-b9c3-e871b2d0fbe9.mp4

**Comment by folke** [comment]
@echasnovski thank you for the repro!

The problem is that Neovim shows `scanning` messages. And since `cmdheight=0`, a **more-prompt** gets triggered. To bypass that we `nvim_input` a `<CR>`. That `<CR>` apparently messes with the indentation.

Seems related to https://github.com/echasnovski/mini.nvim/issues/5 :)

**Comment by folke** [comment]
I was able to fix @echasnovski 's issue.
@debugloop can you check that yours is also fixed? I'm pretty sure it's the same issue

**Comment by debugloop** [comment]
Thanks for your quick diagnosis, both of you 👍🏻 I can confirm the original issue is resolved in my own as well as in the minimal setup.

However, Noice is reporting a loop now and shutting down after about 50 of these "Scanning" messages. This is not reproducible with the minimal setup though, so I'll investigate and open a new issue if necessary.

**Comment by folke** [comment]
@debugloop you can try setting `config.hacks.skip_duplicate_messages = true`. Should resolve the shutting down

**Comment by echasnovski** [comment]
> The problem is that Neovim shows `scanning` messages. And since `cmdheight=0`, a **more-prompt** gets triggered. To bypass that we `nvim_input` a `<CR>`. That `<CR>` apparently messes with the indentation.

Yeah, but this prompt doesn't need `<CR>`. But you seem to know that already :)
 
> Seems related to [echasnovski/mini.nvim#5](https://github.com/echasnovski/mini.nvim/issues/5) :)

Well, yes, that was the reason of this issue, but not the underlying problem. I couldn't get rid of those "Scanning" messages, no matter how much I've tried. Those are the result of how `<C-n>` works. It feels like it should be possible to disable via some 'shortmess' value, but it doesn't seem like. I am yet to find time and try to fix this in Vim source code.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/20633

For scanning messages, please see this.

**Comment by echasnovski** [comment]
> [neovim/neovim#20633](https://github.com/neovim/neovim/pull/20633)
> 
> For scanning messages, please see this.

Thanks for bringing this up. And @bfredl for making initial patch! And yet back again to using nightly :)

**Comment by folke** [comment]
That's awesome :)
