### ISSUE TITLE
feature: LSP doc borders doesn't look right when there is line wrapping

### ISSUE THREAD

**Issue by musjj** [folke/noice.nvim#470]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

The border added by `presets.lsp_doc_border` doesn't work well when the lines are wrapping.

How it looks like in narrow windows (the left, right and bottom borders are basically missing):

![image](https://github.com/folke/noice.nvim/assets/72612857/c85ba696-c9bd-442f-8ca4-e2aaab2dc157)

How it looks normally:

![image](https://github.com/folke/noice.nvim/assets/72612857/97b9f307-7f35-48c4-9031-f6f18d81a879)

### Describe the solution you'd like

Handle wrapping better so that the borders don't get cut off.

### Describe alternatives you've considered

I guess the only alternative is to turn off the borders.

**Comment by musjj** [comment]
![2023-07-05T06:47:52](https://github.com/folke/noice.nvim/assets/72612857/fa9485ca-346c-4c02-b891-2e681699ce03)
It seems that this is caused by the borders getting wrapped for some reason. I tried to reproduce the issue with the native API: 

```lua
vim.api.nvim_open_win(0, false, {relative='win', row=3, col=3, width=100, height=3, border="rounded"})
```

I also tried the nui.nvim API that noice is using: https://github.com/MunifTanjim/nui.nvim#popup

But I can't reproduce the issue there.

**Comment by chrisgrieser** [comment]
I also noticed this issue, and apparently it arises because the `hover` view does not have a max width. Instead of the preset, I set this, and it fixed the issue for me:

```lua
opts = {
		views = {
			hover = {
				border = { style = "rounded" },
				size = { max_width = 80 },
			},
		},
},
```

**Comment by musjj** [comment]
This stopgap probably works, but the real cause of the issue is somewhere else. If you try spawning a floating window (+borders) with either nui.nvim or the native API, you'll see that it doesn't suffer from tihs issue.

I suspect that this is caused by noice.nvim injecting scrollbars into the window.

**Comment by zuqini** [comment]
> I suspect that this is caused by noice.nvim injecting scrollbars into the window.

The option to disable scrollbars has since been added by https://github.com/folke/noice.nvim/issues/471, but unfortunately disabling the scrollbar doesn't seem to fix the border wrapping issue.

Since this issue is closed due to lack of activity, I wonder if there's any expectations/etiquettes surrounding re-opening stale issues like this one?
