### ISSUE TITLE
feature: disable scrollbar

### ISSUE THREAD

**Issue by igorlfs** [folke/noice.nvim#471]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Hey! As always, thanks for the plugin! I've read through the docs but haven't found a way to disable the scrollbar that pops up when hovering documentation. My main motivation to do that is that I find its behavior a little inconsistent. For instance: in the screenshot, I'm at the bottom, but the bar isn't:

![image](https://github.com/folke/noice.nvim/assets/84649544/3caea3d0-7734-46e0-8a72-bbd32b9b63e6)

From my understanding, the bar seems to be tracking the cursor when inside the window and the top when scrolling from outside. That is, when I focus the hover, I can get the "expected behavior":

![image](https://github.com/folke/noice.nvim/assets/84649544/e4e187ea-e077-438e-971d-84b85dc232d1)

Fixing that would be nice, but if that's the intended behavior, that's also ok. What I would like to do instead is to have an option to disable the scrollbar entirely.

### Describe the solution you'd like

Either fixing the underlying issue or provide an option to disable the scrollbar (or both)

### Describe alternatives you've considered

I went in-depth in the first section

**Comment by carlobonandriniunimi** [comment]
Looking for a solution as well, tried putting the highlight groups PmenuSbar and PmenuThumb, and while it works in the hover window, it messes up with the color of the scrollbar inside the cmdline_popup

**Comment by musjj** [comment]
I also suspect that the scrollbars are the cause of the weird border wrapping issue in LSP popups: https://github.com/folke/noice.nvim/issues/470

The same issue does not happen with vanilla nui.nvim floating windows, which does not have scrollbars.

**Comment by igorlfs** [comment]
Closed by #603

**Comment by zuqini** [comment]
> I also suspect that the scrollbars are the cause of the weird border wrapping issue in LSP popups: #470
> 
> The same issue does not happen with vanilla nui.nvim floating windows, which does not have scrollbars.

Hmm, unfortunately disabling the scrollbar doesn't seem to fix the border wrapping issue, and the original issue is closed due to lack of activity. I wonder what the proper etiquette is for re-opening stale issues.
