### ISSUE TITLE
bug: Error with showing `vim.tbl_deep_extend` 

### ISSUE THREAD

**Issue by dpetka2001** [folke/noice.nvim#473]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-357+g4c05b1a6a

### Operating system/version

Linux Mint 21.1

### Describe the bug

When trying to complete options of either `vim.tbl_deep_extend` or `vim.tbl_extend` an error pops up `...share/nvim/lazy/noice.nvim/lua/noice/text/treesitter.lua:91: Invalid 'end_col': out of range`. When trying to complete `list_extend` or `nvim_set_keymap` for example the preview window shows correctly the docs and what each option should be.

### Steps To Reproduce

1. Open a file
2. Type `vim.list_extend` and see that preview window opens up showing options correctly
3. Type `vim.tbl_deep_extend` and the error pops up after accepting the entry from the completion menu. Before selecting the entry from the completion menu the preview window shows correctly information. After selecting the entry the error pops up and no info is shown.

### Expected Behavior

After selecting the entry from the completion menu and the cursor gets positioned inside the parentheses to complete the parameters, the preview documentation should be shown correctly.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I'm not able to replicate this.  Can you provide a minimal repro.lua with the exact steps that lead to this issue?

**Comment by dpetka2001** [comment]
Strange, just cloned a new Lazyvim instance to another directory and run Neovim with NVIM_APPNAME and the issue is not reproduced. I have not made any configuration for `noice.nvim`. How could I narrow down what causes this? Maybe a treesitter option according to the error?

**Comment by folke** [comment]
Make sure you have all plugins up to date and run `TSUpdate` to make sure no parsers are outdated

**Comment by dpetka2001** [comment]
Everything is updated. Still the error persists. What exactly does the error mean? Maybe that will help me dissect this further.

**Comment by folke** [comment]
That's just the highlighter. It uses a treesitter query and then adds extmarks for the highlights.

Can you check if the issue is solved with commit c2a745a26ae562f1faecbf6177ac53377d2658d5 ?

**Comment by folke** [comment]
Also, are you using custom treesitter queries?

**Comment by dpetka2001** [comment]
It's strange that it only happens in `vim.tbl_deep_extend` and `vim.tbl_extend` and not in `vim.list_extend` or `nvim_set_keymap` or other `vim.tbl_*` commands that i tried.

**Comment by folke** [comment]
Are you using any plugins that remove ending whitespace or something similar?

**Comment by folke** [comment]
I just pushed a change to skips `bufload`, which wasn't needed anyway and I don't remember why I added it. Can you check if it works now without errors?

**Comment by dpetka2001** [comment]
I just commented out every spec in my plugins configuration and the problem goes away. I'm enabling them one by one to see where the error starts occuring. I will report back and try the recent change you suggested as well.

**Comment by folke** [comment]
I just pushed a change that just pcalls those extmarks. Can you check if everything works as expected now?

**Comment by dpetka2001** [comment]
Sorry it took me a while to reply. I was still trying things but didn't manage to narrow it down to a specific spec. With the latest push it seems to be working as expected now and I even uncommented all my specs in the configuration. I know I won't understand much, but could you explain what exactly happened? And why only for these specific commands and all others worked fine? Really appreciate your effort and patience. Thank you very much.

**Comment by folke** [comment]
I have really no idea, but I just encountered the same error. But only once and couldn't get it to reproduce. I just ignore those errors in Noice when they happen. Should be fine
