### ISSUE TITLE
feature: Remove some notifications

### ISSUE THREAD

**Issue by SingularisArt** [folke/noice.nvim#477]
### Did you check the docs?

- [x] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

When I use ultisnips, I keep getting the following notification:

https://github.com/folke/noice.nvim/assets/57925294/4b44e3f4-b0ef-4775-8433-2d1b5d8a75b2

Can I disable some notifications from popping up?

### Describe the solution you'd like

I would like something like this:
```lua
require("noice").setup({
  disable_notifications = {
    "UltiSnips#JumpForwads()",
    ...
  }
})
```

### Describe alternatives you've considered

I disable `noice.nvim` when I'm editing a `latex` file since that's where I use all the ultisnips.

**Comment by igorlfs** [comment]
You can filter notifications, take a look at https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#hide-written-messages, for example

**Comment by janbaer** [comment]
I'm trying to follow your documentation to hide some notifications, but it won't work for me. Any idea, what is wrong with the filter?

```lua
      {
        filter = {
          event = "msg_showmode",
          any = {
            { kind = "", find = "INSERT" },
            { kind = "", find = "VISUAL" },
          }
        },
        opts = { skip = true },
      }
```
