### ISSUE TITLE
Spell suggestions cannot be selected

### ISSUE THREAD

**Issue by kierun** [folke/noice.nvim#48]
**Describe the bug**

Spell suggestion cannot be selected by pressing number keys.

**Which version of Neovim are you using?**

```bash
√ ; nvim --version
NVIM v0.8.0-v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**To Reproduce**
1. Open a file.
2. Write some garbage.
3. Enable spelling.
4. Get a suggestion for any badly spelled word via command `z=`
5. Try selection a replacement.

**Expected Behavior**

A press of a number key should select the suggested spelling and replace it within the text.

This is the default behaviour.

**Screenshots**

https://user-images.githubusercontent.com/3079575/194830655-8c866bdd-64bc-4af1-8810-9e675ed9c54d.mp4

Sadly, the key presses are not shown…

**Noice Log**

<details>
<summary>Noice log</summary>
<pre>
Nothing shown…
</pre>
</details>

**Comment by folke** [comment]
It works for me. Did you press `[enter]` after entering the number?

**Comment by kierun** [comment]
Ah, pressing `[enter]`… No, I did not. Now that I do, it works fine.

However, I got this via `nvim-qt`:

```bash
√ ; gvim ook
√ ; Received unexpected redraw arguments, expecting list QVariant(qulonglong, 54)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 1)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 54)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 1)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 54)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 1)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 55)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 7)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 55)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 7)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 55)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 7)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 58)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 58)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(qulonglong, 58)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
Received unexpected redraw arguments, expecting list QVariant(Invalid)
```

Tried with console `nvim` and got nothing… I guess a `nvim-qt` bug.

I am going to close this as I do not think there is much more you can do.

Just to add: Thank you for your plugin! It's ace and I have been immensely enjoying it. :heart:

**Comment by folke** [comment]
Thanks!

**Comment by folke** [comment]
btw, if you also use `which-key`, you can enable `plugins.spelling.enabled = true` and you'll get a nicer way of picking spelling corrections. It's disabled by deafult.

**Comment by kierun** [comment]
[Found it!](https://github.com/folke/dot/blob/b82b90b14da12b43a00f22d557fc5913ce776fe3/config/nvim/lua/config/mappings.lua#L11)

Yes, this is a much nicer experience. Again, you have my thanks.

**Comment by lee-shun** [comment]
Hello! Also, I install the `which-key`, but I still got the `noice` version spell selection???

**Comment by lee-shun** [comment]
Any updates? @folke @kierun @

**Comment by folke** [comment]
@lee-shun check the which-key docs on how to enable spelling. It's not enabled by default.

**Comment by lee-shun** [comment]
thanks, but I think I have the proper settings for which key. Cause before I install noice.nvim, which key works normally as expected.

**Comment by folke** [comment]
@lee-shun did you check? You need to explicitely enable the spelling widget.

OR just update which-key. I just puhed an update there to enable that by default

**Comment by lee-shun** [comment]
![Screenshot_20230301-163402_Chrome](https://user-images.githubusercontent.com/46647235/222269912-5224311c-ce50-423a-8b0e-ca97a8667a9c.jpg)
something like this?

**Comment by folke** [comment]
Yep, that enables it indeed.

**Comment by lee-shun** [comment]
https://github.com/folke/noice.nvim/issues/48#issuecomment-1449046052

I pasted my config for.the 2 plugins.

I guess if it is because the lazy load which makes noice take the spell suggestion back?

**Comment by folke** [comment]
Noice does not take the spelling suggestions. That's not how noice works. Noice just renders messages received by Neovim.

```lua
config = function()
        require("config.mappings")
    end
```

That is wrong.

If you provide a config function then you need to run setup yourself.

**Comment by lee-shun** [comment]
It works! You are my hero!

**Comment by kierun** [comment]
> It works! You are my hero!

@folke does make fantastic plugins. :100: recommended!
