### ISSUE TITLE
bug: messages from fugitive are not split correctly

### ISSUE THREAD

**Issue by Shatur** [folke/noice.nvim#483]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

ArchLinux

### Describe the bug

https://github.com/tpope/vim-fugitive tends to produce big messages when using `:G push`. They looks look normal without noice.nvim, but with noice.nvim it looks like this:
![изображение](https://github.com/folke/noice.nvim/assets/22453358/38d27ba7-b688-494f-87a9-45f8e1dd2335)
I have ultra-wide display and it takes all horizontal space :smile: 

### Steps To Reproduce

1. Install noice
2. Install vim-fugitive
3. Open a repo with unpushed commits or create a new one.
4. Call `:G push`

### Expected Behavior

The output is the same as in CLI.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  "tpope/vim-fugitive",
  "rcarriga/nvim-notify",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
require('notify').setup({
  top_down = false,
})
require('noice').setup({})
```

**Comment by folke** [comment]
I just pushed an update that now should properly deal with `\r` characters. Would be great if you could confirm it's fixed. Thanks!

**Comment by Shatur** [comment]
Now works like a charm, thanks!
