### ISSUE TITLE
bug: Not able to write M in commandline

### ISSUE THREAD

**Issue by abhilash26** [folke/noice.nvim#489]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Arch Linux  6.3.4-arch1-1

### Describe the bug

Pressing :M clears the line and removes the commandline argument. 
I am even not able to write capital M on the command line.
Not sure what the reason is. I have tried to replicate the problem in repro but was not able to.

https://github.com/folke/noice.nvim/assets/28080925/8a443bd9-ac88-4daa-8e56-a10103a31767

Reverting noice to release 1.14.0  tends to fix the issue. Also removing noice altogether too solves the issue.

### Steps To Reproduce

Write :M on the command line or try to write capital M

### Expected Behavior

I should be able to write M (capital m) in commandline.

**Comment by folke** [comment]
I can't reproduce this. `:M` works fine for me, both on Neovim stable and on nightly. Are you using something like cmp cmdline? Or do you have anything mapped to `M`? Check with `:verbose cmap M`

**Comment by abhilash26** [comment]
Hello @folke Sir, 

I have removed every plugin except for lazy and noice with no remaps and no settings / options change. 
The problem is still here. 
However I too wasn't able to replicate the problem. Even tried to create a repro

## What seems to fix the problem
- Downgrading from current release to 1.14.0 commit id (1478f7295806d354e7689edc2a58f3bc2e697f78)
- Removing noice altogether

I know as a developer myself that not able to replicate the problem will not help, maybe someone else have the same issue with new commits of noice.

**Comment by folke** [comment]
Right, i know what's causing this. I've fixed this yesterday

**Comment by abhilash26** [comment]
Correct, the issue is not present in the latest commit.
I am using ee24b36743b18e53bdc6b49bbfa426fc18ea337a commit id use latest one instead of 1.4.1 release.

Thank you folke, I am big fan of you and your creations.
