### ISSUE TITLE
Disable virtual text

### ISSUE THREAD

**Issue by kassio** [folke/noice.nvim#49]
### Context
I use the commands and messages in my statusline, therefore the virtual text sometimes is redundant. 

### Proposed solution

Add a configuration to disable the virtual text altogether:

```lua
require('noice').setup({
  views = {
    virtualtext = {
     enabled = false,
    }
  },
})
```

**Comment by folke** [comment]
Already possible. See https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#hide-search-virtual-text

**Comment by folke** [comment]
It's also mentioned in the README
