### ISSUE TITLE
tab on cmdline not working correctly.

### ISSUE THREAD

**Issue by peter-lyr** [folke/noice.nvim#492]
https://github.com/folke/noice.nvim/assets/55801796/680efd1a-49cd-4ec4-aa56-890a7f86d683

I type `<Tab>` key every single time, but it seems not working well.

**Comment by peter-lyr** [comment]
It's ok on clean startup. Let me see see.

**Comment by nottyl** [comment]
Hi! I'm having the same issue, did any of you find out why?

**Comment by niksingh710** [comment]
@peter-lyr was you able to dig down what was causing this type of behaviour?

**Comment by niksingh710** [comment]
For me this was happening because of transparent.nvim (If someone stumbles)

**Comment by nottyl** [comment]
> Hi! I'm having the same issue, did any of you find out why?

My issue was resolved by modifying my `lualine.nvim` config, so I think this could be some kind of conflict between plugins?
