### ISSUE TITLE
feature: tail -f like view of :messages

### ISSUE THREAD

**Issue by graftholders-admin** [folke/noice.nvim#493]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Noice is really very n~o~ice. I'm using it with lazyvim. Keep up the good work!

While developing plugins it would be helpful to view a live debug log for :messages in a split. Especially if for any reason (e.g. visual problems) the notifications are too fast/many/long to read, having a stream where you can scroll back and pause the flow would be very useful.

I'm not sure the functionality is there already, or maybe it can be added using other plugins.

### Describe the solution you'd like

It would be helpful to view a live debug log for :messages in a split. It would show new messages flowing like tail -f on a log file. I.e. I would be able to set an option to "follow" :messages. 
Would be perfect if automatic scrolling to the the end of the buffer could be toggled.

### Describe alternatives you've considered

Re launching the :messages command all the time. But it is frustrating.

**Comment by chrisgrieser** [comment]
I also like the idea. 

Alternatively, the log could be reversed (new messaged prepended at the top, rather than appended at the bottom), which would also remove the need for scrolling & the need to press `G` to see the last message

**Comment by pysan3** [comment]
+1

**Comment by b0ae989c** [comment]
A comment will do. The bot will remove stale label next time it runs.

**Comment by opzap** [comment]
+1

Would love to see this

**Comment by devrajneupane** [comment]
+1

**Comment by sassanh** [comment]
Really sorry you are receiving a notification about a comment with no value in its content. Unfortunately the only way to stop stale marker bots is posting comments.
