### ISSUE TITLE
feature: Expand "No Nerd Font" part of the docs

### ISSUE THREAD

**Issue by TimDeve** [folke/noice.nvim#494]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I do not use a Nerd Font, I have the _mini_ view enabled and the icons there are shown as _tofu_. 
I have used the configuration in the docs for when not using a Nerd Font but this does not seem to be enough to fix the icons in the mini view.

### Describe the solution you'd like

I would like for the "No Nerd Font" part of the docs to explain how to fix this problem.

### Describe alternatives you've considered

It feels like I should be able to override the Formatting for each log type but I'm not actually sure if this is the right place for changing icons.

**Comment by folke** [comment]
Just check the code and configure any icons you want to change. I'm not going to do this for you. If you don't want to use a nerd font, then that's fine, but at least do the work yourself to change/update all the icons.

**Comment by TimDeve** [comment]
I guess what I was trying to say is that it isn't clear where I should be doing that.

**Comment by folke** [comment]
you want to change `config.lsp.progress.format_done`.

This is the builtin:

```lua
{
    { "✔ ", hl_group = "NoiceLspProgressSpinner" },
    { "{data.progress.title} ", hl_group = "NoiceLspProgressTitle" },
    { "{data.progress.client} ", hl_group = "NoiceLspProgressClient" },
  }
```

You can also change the spinner, if that's not working properly. `config.format.spinner.name = "..."`. Check the codebase for `spinner.lua` to see all the options.

**Comment by TimDeve** [comment]
Ah thank you kindly, this is what I was looking for.

Would you be open to me making a PR to update this part of the doc once I've figured it out?

**Comment by folke** [comment]
yep, sure. thanks
