### ISSUE TITLE
noice.nvim defaults last active window number to 3 instead of 1.

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/noice.nvim#50]
**Describe the bug**
`noice.nvim` defaults last active window number to 3 instead of 1.

**Which version of Neovim are you using?**
```
NVIM v0.9.0-dev-1228-ga93ff5fc6-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```
(nightly, I have not tested on stable - do you think this makes a difference?).

**To Reproduce**
Tested using `minimal.lua`, see attached video. 

- with `noice.nvim` `vim.fn.winnr('$')` returns 3
- without `noice.nvim` `vim.fn.winnr('$')` correctly returns 1

https://user-images.githubusercontent.com/15387611/194870259-148e5255-6788-4b6f-80c3-81a23c612036.mov

I realised it because all configuration toggling functions that check if a certain window/buffer is the last one before quitting stopped working correctly (debugging, I realised that the condition `vim.fn.winnr('$')` no longer held).

**Expected Behavior**

`vim.fn.winnr('$')` to always return 1

**Comment by folke** [comment]
I don't think this can be fixed. When you have the cmdline open, you get two additional windows. One for the buffer containing the cmdline and one for the border.

Be aware, that this would be the same if you'd have an nvim-notify, figet, incline, ... window open.

Can you give a real-world example of what fails?

**Comment by gennaro-tedesco** [comment]
> Can you give a real-world example of what fails?

In my case I was submitting a patch to [symbols-outline](https://github.com/simrat39/symbols-outline.nvim) to auto-close the symbols menu when last buffers/windows are wiped (therefore one needs to check `winnr('$')==1`); Similar cases are the ones of plugins like file explorers/tree views/git diff and such that implement similar conditions to quit if there is no window associated to the buffer that invoked the plugin.

Whilst of course each single case can be probably solved with its own specifics, I thought I would mention this behaviour since in my experience it is quite common to have user-defined and plugin-defined functions that perform this sort of mechanical checks on window numbers to avoid pending splits when closing the main windows.

**Comment by folke** [comment]
I could close the windows when closing the cmdline, but then the windows need to be recreated every time.
They don't have hard-coded ids.

The check for number of windows seems flawed. There's a lot of plugins out there that have hidden windows.

You should check on the number of visible widows.

Also, be aware that your `print` statement also opens a new window (nvim-notify)

**Comment by folke** [comment]
So, a better check would be to simply check for listed buffers?

**Comment by folke** [comment]
```vim
:lua print(#vim.tbl_filter(function(buf)
  return vim.api.nvim_buf_get_option(buf, "buflisted")
end, vim.api.nvim_list_bufs()))
```

This will be `0`

**Comment by gennaro-tedesco** [comment]
You are right, checking listed buffers is the robust way to handle this!
