### ISSUE TITLE
bug: The input method cursor position is not updated.

### ISSUE THREAD

**Issue by hanxi** [folke/noice.nvim#500]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

win10

### Describe the bug

When entering Chinese in the search input box, the input method does not follow the input box position.

![4S6UFRU7UTLDXO YNQ7 $V(2)](https://github.com/folke/noice.nvim/assets/1185757/70fa88d2-b1b8-45de-8283-66b846f37b44)

### Steps To Reproduce

1. type / to search
2. change to chinese input method
3. input worlds

### Expected Behavior

The cursor should be at the input box position.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
          "folke/noice.nvim",
          event = "VeryLazy",
          opts = {
                  -- add any options here
          },
          dependencies = {
                  -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
                  "MunifTanjim/nui.nvim",
                  -- OPTIONAL:
                  -- `nvim-notify` is only needed, if you want to use the notification view.
                  -- If not available, we use `mini` as the fallback
                  "rcarriga/nvim-notify",
          }
  }

  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Can you clarify what is wrong here? Does it have to do with LTR? Can you show me what is wrong and what it should look like?

**Comment by hanxi** [comment]
Like telescope, input method candidate box is below the input box. 
![0MQ0@BKVJGGCR(7{I`ON2BC](https://github.com/folke/noice.nvim/assets/1185757/cb1c3918-3886-4138-8ad7-22af0b2c9a04)

**Comment by hanxi** [comment]
![66fa1f02fd306049](https://github.com/folke/noice.nvim/assets/1185757/2a6d5e21-3bef-47e9-981c-7da258afd06d)

**Comment by hanxi** [comment]
I try nui input, it's run ok.

https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/input

![K4OK3I~8T`DXHI_L{C5X9TM](https://github.com/folke/noice.nvim/assets/1185757/35c8d6f3-f56e-444f-9afe-006b60936044)

**Comment by folke** [comment]
ok, I understand now. That;s not something I can fix, since the noice cmdline that you see is just a representation.
That's not the actual input field.

As far as noice is concerned, there is no input field.

Neovim simply tells noice, to render the cmdline with a certain input string.

Noice doesn't handle the input.

Closing as can't fix.
