### ISSUE TITLE
feature:  do not hide `=` by default in lua prompt

### ISSUE THREAD

**Issue by danielo515** [folke/noice.nvim#502]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I am used a lot to use `:lua =` to quickly print values. When I started using noice, I typed `=` until I started seeing  it in the prompt, and I was getting errors. After a lot of frustration I realised that maybe the cause is that it was being hidden, and indeed that is the cause.
I find this confusing for a default behaviour and I think leaving the `=` in place will be much more user friendly

### Describe the solution you'd like

To not hide the `=` in the lua prompt

### Describe alternatives you've considered

I'm not sure if this is achievable modifying the lua pattern. I don't know if it is just for detecting or for prompt recognition, as it is not extensively documented.

**Comment by folke** [comment]
Then just change the config?

`config.cmdline.format.lua`
