### ISSUE TITLE
Latest nui.nvim update broke noice.nvim

### ISSUE THREAD

**Issue by TroySigX** [folke/noice.nvim#503]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

6.3.6-arch1-1

### Describe the bug

I have the following config: 
``` lua
require('noice').setup({
  cmdline = {
    view = 'cmdline',
  },
})
```

The `cmdline` bar is supposed to be placed at the bottom of the screen (like that in Neovim), but it's not.

### Steps To Reproduce

1. Type some command, e.g `:Noice`, this time, the `cmdline` is shown at the bottom, as expected.
2. After the first command, try to type another command, this time, the `cmdline` bar is shown on the top.

### Expected Behavior

The `cmdline` bar should always be shown at the bottom of the screen. But except the first time it is correctly displayed, the bar thereafter is placed on the top.

**Comment by folke** [comment]
I just pushed a work-around to fix the nui issue, but needs to be properly fixed upstream

https://github.com/folke/noice.nvim/commit/4db3c8f14302273b842f73a8facf1999169c1e41

**Comment by folke** [comment]
https://github.com/MunifTanjim/nui.nvim/issues/270

**Comment by TroySigX** [comment]
Thanks @folke
