### ISSUE TITLE
feature: Finer control over filtered LSP messages

### ISSUE THREAD

**Issue by MariaSolOs** [folke/noice.nvim#511]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I find mini LSP notifications useful, but I would like to filter out some clients or some particular messages while still using the UI that this plugin provides.

### Describe the solution you'd like

Extra options in `lsp.progress` or more options in `routes`.

### Describe alternatives you've considered

I tried using the snippet given in the [wiki](https://github.com/folke/noice.nvim/wiki/A-Guide-to-Messages#lsp-messages), but this results in a bunch of unformatted notifications (I want to keep the formatting from the `mini` view):
<img width="676" alt="image" src="https://github.com/folke/noice.nvim/assets/62502207/47326a8a-649f-454e-82c3-8749bec4fac9">

The other issue is that such snippet wouldn't allow me to continue using the `mini` view to display these filtered notifications...

### Additional context

That being said, I love this plugin! <3

**Comment by folke** [comment]
You can use something like the below:

```lua
    table.insert(opts.routes, {
      filter = {
        event = "notify",
        find = "No information available",
      },
      opts = { skip = true },
    })
```

Please open a discussion instead of an issue next time for questions.

**Comment by folke** [comment]
You can skip specific lsp progress messages like this:

```lua
    table.insert(opts.routes, {
      filter = {
        event = "lsp",
        kind = "progress",
        find = "workspace", -- skip all lsp progress containing the word workspace
      },
      opts = { skip = true },
    })
```

**Comment by MariaSolOs** [comment]
> You can skip specific lsp progress messages like this:
> 
> 
> 
> ```lua
> 
>     table.insert(opts.routes, {
> 
>       filter = {
> 
>         event = "lsp",
> 
>         kind = "progress",
> 
>         find = "workspace", -- skip all lsp progress containing the word workspace
> 
>       },
> 
>       opts = { skip = true },
> 
>     })
> 
> ```

Thanks for the quick response! However, I'm the most interested in filtering by client, which I haven't been able to do because it seems that the highlights prevent the string match (?)

**Comment by MariaSolOs** [comment]
Ohh, is this because the client name isn't part of the message's content but part of the title? @folke

**Comment by folke** [comment]
To exclude a client you can use:

```lua
    table.insert(opts.routes, {
      filter = {
        event = "lsp",
        kind = "progress",
        cond = function(message)
          local client = vim.tbl_get(message.opts, "progress", "client")
          return client == "lua_ls" -- skip lua-ls progress
        end,
      },
      opts = { skip = true },
    })
```

**Comment by MariaSolOs** [comment]
That worked perfectly, thanks a lot @folke!
Is this filter setting documented? I couldn't find it...

**Comment by MariaSolOs** [comment]
Also thanks again for all your amazing plugins. I truly admire your work!

**Comment by folke** [comment]
Noice is a bit too configurable tbh. Even I need to dive in the code all the time to check how I can achieve something :)

There's definitely a lot of documentation missing as well. 

And thank you for the kind words!

**Comment by sherubthakur** [comment]
This was super helpful. I bet you did it because of null_ls. That thing is too noisy when it comes to these progress messages.

**Comment by MariaSolOs** [comment]
> This was super helpful. I bet you did it because of null_ls. That thing is too noisy when it comes to these progress messages.

Yep. I also find the "code action" messages a bit too noisy since I'm using the gitsigns builtin and there's a code action for blaming a line, which is applicable to pretty much any line lol.
