### ISSUE TITLE
bug: Command line not shown if used together with Bekaboo/dropbar.nvim

### ISSUE THREAD

**Issue by Jendker** [folke/noice.nvim#516]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-528+g1f8fb7c00

### Operating system/version

Ubuntu 20.04

### Describe the bug

The `:` or `/` does not show command line if used together with `Bekaboo/dropbar.nvim`. There was a workaround necessary in the mentioned repo as described in https://github.com/Bekaboo/dropbar.nvim/issues/38. I thought that is something worth bringing up here to avoid similar issues with other plugins.

### Steps To Reproduce

1. Save the configuration as repro.lua
2. Run `nvim -u repro.lua repro.lua`
3. Press `:`
4. Command line is not shown

### Expected Behavior

Command line is shown.

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Indent Settings
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.smartindent = true

require("lazy").setup({
  { 'Bekaboo/dropbar.nvim',
    commit = '190dcc1',
    opts = {
      bar = {
        sources = function(_, _)
          local sources = require('dropbar.sources')
          return {
            {
              get_symbols = function(buf, win, cursor)
                if vim.bo[buf].ft == 'markdown' then
                  return sources.markdown.get_symbols(buf, win, cursor)
                end
                for _, source in ipairs({
                  sources.lsp,
                  sources.treesitter,
                }) do
                  local symbols = source.get_symbols(buf, win, cursor)
                  if not vim.tbl_isempty(symbols) then
                    return symbols
                  end
                end
                return {}
              end,
            },
          }
        end,
      },
    }
  },
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    opts = {
      -- add any options here
    },
    dependencies = {
      -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
      "MunifTanjim/nui.nvim",
    }
  }
})
```

**Comment by folke** [comment]
I recently made a change to noice so that you can use custom winbars. Previously noice would always override any winbars that were set, but that's not ideal. The user and other plugins should be able to override that.

**Comment by Jendker** [comment]
Hello Folke 👋

I am not sure if there wasn’t a misunderstanding. There is no issue with winbar not being shown, but rather that the command line is not appearing.

**Comment by folke** [comment]
Yes, not appearing because a winbar was added and height of the cmdline is 1. This means only the winbar would be shown.
