### ISSUE TITLE
`lazyredraw = true` causes constantly increasing RAM usage

### ISSUE THREAD

**Issue by echasnovski** [folke/noice.nvim#52]
**Describe the bug**
When `lazyredraw` is set to `true`, typing `:` leads to constantly increasing RAM usage and constant unexpectedly high CPU usage.

**Which version of Neovim are you using?**
Neovim 0.8 (stable release) in xfce4-terminal. Same issue can be reproduced in `NVIM v0.9.0-dev-55-gedc8a1f04` (one of the recent nightly) and kitty terminal.

**To Reproduce**
1. Create minimal init file (called, for example, 'noice_minimal.lua'):
```lua
-- Replace `packadd` arguments to actual plugin names in your 'pack' directory
vim.cmd('packadd nui')
vim.cmd('packadd nvim-notify')
vim.cmd('packadd noice')
require('noice').setup()
vim.o.termguicolors = true

vim.o.lazyredraw = true
```
2. Open Neovim with `nvim -u noice_minimal.lua noice_minimal.lua`.
3. Type `:`.

**Expected Behavior**
RAM usage and CPU is identical to hitting `:` without 'noice.nvim' set up.

**Screenshots**
Demo:

https://user-images.githubusercontent.com/24854248/195154839-9f06f341-b5de-4d00-bf30-e53199a87ba0.mp4

Couple of notes:
- It might be an issue with 'nui.nvim', I am not sure.
- I remember having same behavior when accidentally was setting **a lot** of extmarks over each other in buffer (so that effect was invisible) without cleaning its namespace.

**Noice Log**
`:Noice log` is empty.

**Comment by pBorak** [comment]
There was already a discussion about `lazyredraw`, and how this setting is not compatible with `noice`.
https://github.com/folke/noice.nvim/issues/24#issuecomment-1269721094

**Comment by echasnovski** [comment]
> There was already a discussion about `lazyredraw`, and how this setting is not compatible with `noice`. [#24 (comment)](https://github.com/folke/noice.nvim/issues/24#issuecomment-1269721094)

I see, thanks. It was so deep inside comments, that I didn't notice during search.

Still, didn't see a notification message about it being set. Probably, because it was set after setting up this plugin. Otherwise, don't mind this closed.

**Comment by folke** [comment]
@echasnovski yep, must be the order. Closing this...
