### ISSUE TITLE
Possible to stay locked into a command line mode?

### ISSUE THREAD

**Issue by EmreDogann** [folke/noice.nvim#524]
I'm using inc-rename and have set preset `inc-rename = true`. Inc-rename config:

```lua
{
	"smjonas/inc-rename.nvim",
	keys = {
		{
			"<F2>",
			function()
				return ":IncRename " .. vim.fn.expand("<cword>")
			end,
			expr = true,
			desc = "Rename Signature",
		},
	},
	config = function()
		require("inc_rename").setup()
	end,
},
```

When I press F2, It shows the rename menu like so:

![image](https://github.com/folke/noice.nvim/assets/48212096/3837d8ee-b42d-4f33-b78b-c54bb4e068d5)

If I delete all the characters, it will bring me back to the default command view:

![image](https://github.com/folke/noice.nvim/assets/48212096/6150a9b2-bdb4-4578-9d31-4ae94a48b289)

I understand why this happens, but is it possible to stay locked in the IncRename mode? Maybe is it possible to prevent the last backspace so you stay locked into the rename popup? Then maybe \<Esc> for quitting/cancelling the rename?
I ask this because, for certain popups like renaming, I find it annoying when accidentally pressing backspace too many times and being brought back into the default cmdline format.

**Comment by folke** [comment]
no, because that's the regular cmdline.

You could implement something like this yourself by creating an autocmd on `CmdlineChanged` and then revert it back to `IncRename` when you start deleting part of the cmd.

I would not recommend this though.
