### ISSUE TITLE
Can i format message for macros?

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#526]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

For example:
`start @j recording`
`@j recording finished`

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by folke** [comment]
what do you mean exactly? format it where?

**Comment by kaiphat** [comment]
If i add this one to my config
![image](https://github.com/folke/noice.nvim/assets/53742299/562c935c-11bc-4a0f-9edd-39f7d582b3bf)
I get this notify
![image](https://github.com/folke/noice.nvim/assets/53742299/b4603460-805e-440f-a557-7abc1a4d2423)
1 - Can i modify this message?
2 - Can i get message not only about start macros, but also about finish? Mb, you know some method how i can do this with mapping in my config.

**Comment by folke** [comment]
best to add it to your statusline instead. see the docs on how to do that
