### ISSUE TITLE
Using `vim.pretty_print` and `print` on plugin config load - crashes neovim

### ISSUE THREAD

**Issue by dlvhdr** [folke/noice.nvim#53]
**Describe the bug**
If I put any `print` statement in the config file of a plugin, neovim crashes with 
```
hi!Assertion failed: (to_scroll >= 0), function msg_scroll_flush, file message.c, line 2414.
                                                                                            fish: Job 1, 'nvim' terminated by signal SIGABRT (Abort)
                                                                                                                                                    ⏎
```

**Which version of Neovim are you using?**
NVIM v0.8.0-1-g9e784a53b
Build type: RelWithDebInfo

**To Reproduce**
1. In your `plugins.lua`, where packer is used, paste:
```
  use({
    "rcarriga/nvim-notify",
    config = function()
      require("notify").setup({})
    end,
  })

  use({
    "folke/noice.nvim",
    event = "VimEnter",
    config = function()
      require("noice").setup({})
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    },
  })

  print("hi!")
```
2. Restart nvim
3. Get error message

**Expected Behavior**
Message is printed using notify or printed to regular messages.

**Comment by folke** [comment]
Can't reproduce this with https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by folke** [comment]
Might be a Neovim bug. Either way, you'll have to make it reproducible with a minimal init.lua

**Comment by dlvhdr** [comment]
I can't reproduce with the minimal config, and now I can't even do it with mine.
