### ISSUE TITLE
bug: message output is unexpectedly broken when message created with echon

### ISSUE THREAD

**Issue by lervag** [folke/noice.nvim#532]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-633+g8a788e2daa

### Operating system/version

Arch Linux

### Describe the bug

Given the following function:

```vim
function! Test() abort
  echon "test"
  echo " tested"
endfunction
```

The expected output when `:call Test()` would be to have echoed `test tested` on a single line. Instead, we get something like this:

![image](https://github.com/folke/noice.nvim/assets/998898/d70cdef1-38ef-4061-9753-67291b2c22ea)

This feature, i.e. `echon`, allows to write formatted status messages. I know that this is somewhat "old fashioned" today. But for my now quite old plugins like VimTeX and wiki.vim I've relied on this.

So: is it possible for Noice to distinguish between `echo` and `echon`?

I've also built some simple selection utilities around this functionality where I use `echo` and `echon` to print candidates and then use `getchar()` to make the selection more smooth (don't need to press `<cr>`). I've failed to figure out how to route this kind of content into another view. This is a sidenote, though; let's focus on the above part first.

### Steps To Reproduce

1. Use Noice with standard configuration.
2. Run `:echon "test" | echo " tested"` (or use a function like mentioned and run `:call Test()`).

### Expected Behavior

The output shod not include a line break.

### Repro

If it becomes relevant to create a minimal lua file, I will create it. I don't think it is necessary in this specific case.

**Comment by folke** [comment]
there's no way to disambiguate between the two from ui_attach

**Comment by lervag** [comment]
> there's no way to disambiguate between the two from ui_attach

But should there be; I mean, would it make sense to open this discussion at the neovim issue tracker?
