### ISSUE TITLE
feature: Expose API for LSP progress statusline components

### ISSUE THREAD

**Issue by MariaSolOs** [folke/noice.nvim#537]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

There's no problem per se, I just find the amount of LSP progress `mini` notifications a bit overwhelming sometimes. I don't want to disable them entirely though, instead I would like to display them in my `lualine` as a single message.

### Describe the solution you'd like

An LSP statusline component that I could easily access to configure my `lualine`.

### Describe alternatives you've considered

I apologize in advance if I'm missing something 🙈 

Here are the things I've tried:
1. Use an existing component. However, after reading the docs it seems like there's no statusline component for LSP progress (the `message` component is for `event=msg_show` and I'm interested in `event=lsp`), and the other ones are clearly non-applicable here.
2. Configure a new statusline component. I looked at [these](https://github.com/folke/noice.nvim/blob/26394ed09d47160a493d4e9e754f5f78d4556a6b/lua/noice/config/status.lua) for inspiration, but there's no LSP event in `M.events`, so I got lost there.
3. Use another plugin for this like https://github.com/linrongbin16/lsp-progress.nvim, but I don't really want to add another plugin for something Noice is already handling.

**Comment by folke** [comment]
I'm pretty sure it can be done already with the status line component, but I'll have to look into the code to check how that works again :)

Will look into it tomorrow.

**Comment by folke** [comment]
So it's indeed already possible.

In your noice config, add a new statusline component:

```lua
    opts.status = { lsp_progress = { event = "lsp", kind = "progress" } }
```

Skip all lsp progress messages, so they won't be displayed with the default view:

```lua
    table.insert(opts.routes, {
      filter = {
        event = "lsp",
        kind = "progress",
      },
      opts = { skip = true },
    })
```

Then add the following to lualine:

```lua
  {
    function()
      return require("noice").api.status.lsp_progress.get_hl()
    end,
    cond = function()
      return package.loaded["noice"] and require("noice").api.status.lsp_progress.has()
    end,
  },
```
Result should look lke this:

![image](https://github.com/folke/noice.nvim/assets/292349/9b369646-108c-44fa-a349-da06fe9afd03)

**Comment by folke** [comment]
To properly update lualine on progress, you can also add the autocmd below:

```lua
    autocmd LspProgress * redrawstatus
```

Not required, but will update the statusline component as soon as new lsp progress was received

**Comment by folke** [comment]
Be aware that only the most recent lsp progress message wil be displayed this way. so if there's two or more, only the most recent one will be shown.

**Comment by MariaSolOs** [comment]
Thank you sooo much!
Just a quick follow-up: When I was trying this earlier, I disabled `opts.lsp.progress`. It sounds like I shouldn't do that but instead skip all messages with the filter right?

**Comment by folke** [comment]
Yes, don't disable that or lsp progress messages would not be generated. You still want to process those, just not routed to the default view

**Comment by MariaSolOs** [comment]
Awesome. Thanks again for looking into it! ❤️

**Comment by burgessa23** [comment]
> To properly update lualine on progress, you can also add the autocmd below:
> 
> ```viml
>     autocmd LspProgress * redrawstatus
> ```
> 
> Not required, but will update the statusline component as soon as new lsp progress was received

Where should the autocmd go?

**Comment by max397574** [comment]
anywhere were it gets loaded
