### ISSUE TITLE
bug: tree-sitter get_query deprecated on nvim 0.10.0 + 

### ISSUE THREAD

**Issue by WillEhrendreich** [folke/noice.nvim#539]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-579+gcd6458123

### Operating system/version

Windows 10

### Describe the bug

   Warn  1:23:29 PM notify.warn vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. :help deprecated
This feature will be removed in Nvim version 0.10
   Warn  1:23:30 PM notify.warn stack traceback:
	C:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:200: in function 'get_query'
	.../nvim-data/lazy/noice.nvim/lua/noice/text/treesitter.lua:26: in function 'get_query'
	.../nvim-data/lazy/noice.nvim/lua/noice/text/treesitter.lua:68: in function 'fn'
	...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:385: in function 'for_each_tree'
	.../nvim-data/lazy/noice.nvim/lua/noice/text/treesitter.lua:64: in function 'highlight'
	.../share/nvim-data/lazy/noice.nvim/lua/noice/text/init.lua:67: in function 'highlight'
	...ocal/share/nvim-data/lazy/nui.nvim/lua/nui/line/init.lua:58: in function 'highlight'
	...ocal/share/nvim-data/lazy/nui.nvim/lua/nui/line/init.lua:73: in function 'render'
	...share/nvim-data/lazy/noice.nvim/lua/noice/text/block.lua:98: in function 'render'
	...are/nvim-data/lazy/noice.nvim/lua/noice/lsp/override.lua:48: in function 'stylize_markdown'
	...local/share/nvim-data/lazy/hover.nvim/lua/hover/util.lua:295: in function 'open_floating_preview'
	...al/share/nvim-data/lazy/hover.nvim/lua/hover/actions.lua:133: in function 'show_hover'
	...al/share/nvim-data/lazy/hover.nvim/lua/hover/actions.lua:156: in function 'run_provider'
	...al/share/nvim-data/lazy/hover.nvim/lua/hover/actions.lua:181: in function <...al/share/nvim-data/lazy/hover.nvim/lua/hover/actions.lua:176>

### Steps To Reproduce

just got it off of a hover request, but anything that calls vim.treesitter.query.get_query() should do it, if noice is overriding stylize markdown. 

### Expected Behavior

shouldn't use the older function call on newer nvim. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by WillEhrendreich** [comment]
well.. fine... then.. jus... just.. be all speedy and helpful like that.. lol. thanks.

**Comment by folke** [comment]
I already added code to skip the deprecated functions, but the code was wrong :)
