### ISSUE TITLE
How to disalbe notify for `:w`?

### ISSUE THREAD

**Issue by xbladesub** [folke/noice.nvim#549]
I have an issue with my keymap to `:w`. If I trigger it several times (<C-s> in my case) - I got 1 message that buffer is written and errors. If I use `:w` without keymap - all good.

<img width="298" alt="image" src="https://github.com/folke/noice.nvim/assets/45129790/a062aa13-568d-4165-b80f-a38810bd92cc">

**Comment by folke** [comment]
check the LazyVim noice setup
