### ISSUE TITLE
Left/Right arrow keys don't work well in Cmdline UI with Substitution

### ISSUE THREAD

**Issue by Integralist** [folke/noice.nvim#55]
**Describe the bug**
I type `:` and enter a substitution pattern (e.g. `%s/foo/bar/`) but I find the UI gets very laggy and confused about where new characters are to be inserted.

**Which version of Neovim are you using?**
0.8

**To Reproduce**
After entering a substitution like `%s/foo/` then use the arrow keys to move around and type in a change to `foo` and you'll see the UI gets laggy and then the inserting of new text gets confused as if the cursor position has changed.

I've also just noticed that if I press `:` and then the up arrow to go back to my substitution, I now can't move the cursor to the left. Well, it LOOKS like the cursor isn't moving, but if I press the left arrow 3 times and then press the delete key then the expected character is deleted. So it's _visually_ the cursor looks like it isn't moving.

**Expected Behavior**
No lag, and to be able to freely move my left/right arrow keys to a position to start typing.

**Noice Log**
Not sure if this is related, but the following is in the log from me playing around with substitution patterns in the :Ex Cmdline UI...

<details>
<summary>Noice log</summary>
<pre>
Sun  9 Oct 11:19:58 2022
...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:165: module 'notify.stages.static' not found:
	no field package.preload['notify.stages.static']
	no file './notify/stages/static.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/notify/stages/static.lua'
	no file '/usr/local/share/lua/5.1/notify/stages/static.lua'
	no file '/usr/local/share/lua/5.1/notify/stages/static/init.lua'
	no file '/opt/homebrew/share/lua/5.1/notify/stages/static.lua'
	no file '/opt/homebrew/share/lua/5.1/notify/stages/static/init.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/notify/stages/static.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/notify/stages/static/init.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/notify/stages/static.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/notify/stages/static/init.lua'
	no file './notify/stages/static.so'
	no file '/usr/local/lib/lua/5.1/notify/stages/static.so'
	no file '/opt/homebrew/lib/lua/5.1/notify/stages/static.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/notify/stages/static.so'
	no file './notify.so'
	no file '/usr/local/lib/lua/5.1/notify.so'
	no file '/opt/homebrew/lib/lua/5.1/notify.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/notify.so'

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:119: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:118>
	[C]: in function '__index'
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:165: in function 'instance'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:35: in function 'instance'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:107: in function '_notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:157: in function <...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:135>
	[C]: in function 'xpcall'
	...
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:157: in function <...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:135>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:84: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:34: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Sun  9 Oct 11:31:37 2022
.../start/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'notify' extension doesn't exist or isn't installed: ...r/start/nvim-notify/lua/telescope/_extensions/notify.lua:8: module 'telescope.previewers' not found:
	no field package.preload['telescope.previewers']
	no file './telescope/previewers.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/telescope/previewers.lua'
	no file '/usr/local/share/lua/5.1/telescope/previewers.lua'
	no file '/usr/local/share/lua/5.1/telescope/previewers/init.lua'
	no file '/opt/homebrew/share/lua/5.1/telescope/previewers.lua'
	no file '/opt/homebrew/share/lua/5.1/telescope/previewers/init.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/previewers.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/previewers/init.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/previewers.lua'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/previewers/init.lua'
	no file './telescope/previewers.so'
	no file '/usr/local/lib/lua/5.1/telescope/previewers.so'
	no file '/opt/homebrew/lib/lua/5.1/telescope/previewers.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope/previewers.so'
	no file './telescope.so'
	no file '/usr/local/lib/lua/5.1/telescope.so'
	no file '/opt/homebrew/lib/lua/5.1/telescope.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/integralist/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope.so'

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:119: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:118>
	[C]: in function 'error'
	.../start/telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
	.../start/telescope.nvim/lua/telescope/_extensions/init.lua:62: in function 'load_extension'
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:33: in function 'setup'
	...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:82: in function 'notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:132: in function '_notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:157: in function <...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:135>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:84: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:34: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Mon 10 Oct 09:19:30 2022
...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:132: Invalid window id: 1212

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:119: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:118>
	[C]: in function 'nvim_win_call'
	...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:132: in function '_open_window'
	...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:210: in function 'mount'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:162: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:156>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:84: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Mon 10 Oct 11:17:22 2022
...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:129: Vim(append):Error executing lua callback: vim/keymap.lua:0: E31: No such mapping
stack traceback:
	[C]: in function 'nvim_buf_del_keymap'
	vim/keymap.lua: in function 'del'
	...r-textobjects/lua/nvim-treesitter/textobjects/attach.lua:57: in function 'detach'
	...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:490: in function 'detach_module'
	...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:499: in function 'reattach_module'
	...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:108: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:107>
	[C]: in function 'nvim_buf_set_option'
	...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:158: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:170: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:156>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:84: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:119: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:118>
	[C]: in function 'nvim_buf_set_option'
	...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:158: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:170: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:156>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:84: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>
</pre>
</details>

**Comment by folke** [comment]
See https://github.com/folke/noice.nvim/issues/6

Neovim issue

**Comment by folke** [comment]
https://github.com/neovim/neovim/issues/20463
