### ISSUE TITLE
bug: `vim.opt.guicursor` is ignored when in the cmdline

### ISSUE THREAD

**Issue by chrisgrieser** [folke/noice.nvim#552]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

neovim 0.9.1, Neovide 0.10.4

### Operating system/version

macOS 13.4.1 (M1)

### Describe the bug

`vim.opt.guicursor` is ignored in the cmdline. `guicursor` seems to be respected fine in the buffer and in the different modes, but in the cmdline, it stays a (non-blinking) block cursor.

I use `vim.opt.guicursor = { "ci-c:ver25" }`, which normally creates a beam cursor in the cmdline, but as soon as noice is enabled, that gets ignored.

---

As far as I can tell, from the only related issue (#84), it might be related to some upstream issue with nvim? However, when running `:set guicursor` shows me that as output `guicursor=a:NoiceHiddenCursor`, so noice at least touches the `guicursor` option somehow.

My guess is [noice is using some workaround](https://github.com/folke/noice.nvim/blob/894db25ec726d32047799d4d0a982b701bec453b/lua/noice/util/hacks.lua#L266) which requires disabling `guicursor`?

However, the docs or wiki do not mention anything about `guicursor` restrictions, so just to make sure, this issue is an unintended bug, I am opening this issue.

If the restriction of `guicursor` is intentional, is there any way to get around that? (Or is that rather a FR?)

### Steps To Reproduce

1. Use minimal repro config below.
2. `neovide -- -u repro.lua`
3. Run `:` to enter cmdline

### Expected Behavior

`vim.opt.guicursor = { "ci-c:ver25" }` should result in a beam cursor in the cmdline.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim" },
		opts = {}
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

----------------------------------------------------------

vim.opt.guicursor = { "ci-c:ver25" }
```

**Comment by kaem-e** [comment]
is there a way to change the cursor noice displays despite this? I usually set it to a horizontal cursor to match my terminal's cursor since it persists after leaving vim via `:q`, but with noice it remains as the block cursor which is incredibly annoying.

**Comment by edafonseca** [comment]
Hi @kaem-e , not an expert here, but I found this autocmd that can reset your cursor to this vertical line when quitting neovim.

```lua
vim.api.nvim_create_autocmd("ExitPre", {
	group = vim.api.nvim_create_augroup("Exit", { clear = true }),
	command = "set guicursor=a:ver90",
	desc = "Set cursor back to beam when leaving Neovim."
})
```

The `ver90` is the cursor shape. You can know more about it in :h guicursor.

That said, the cmdline change the cursor to block until you restard neovim.

**Comment by kaem-e** [comment]
@edafonseca this works wonderfully! ty
