### ISSUE TITLE
feature: Colorscheme adaption for noice.

### ISSUE THREAD

**Issue by quantumfate** [folke/noice.nvim#553]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

Noice is great for super enhanced looks! It would be even better if it was possible to integrate themes/colorschemes into the overall appearance of noice, with highlightgroups etc.

### Describe the solution you'd like

Lualine has something similar and maybe telescop as well, if I'm not mistaken. Lualine has some presets for themes where it loads fg and bg color into the overall appearance. I personally use the colorscheme "Catppuccin" and I even adapted it for Lualine, would be willing to do the same for Noice.

My point is: While red and green are useful to display info and error messages, unfortunately tho, they stand out of the rest of my color configuration. I obviously still want to signal error messages with a "warn" color, but many color schemes have there own representation of signaling colors. It would be great if noice had a way to quickly adapt existing colorschemes, with the help of contributors, such as myself.

### Describe alternatives you've considered

The alternative would be to override existing highlighting groups, but I think that can be done simpler.

**Comment by folke** [comment]
https://github.com/folke/noice.nvim#-highlight-groups
