### ISSUE TITLE
bug: certain notifications ignore `merge = false` and `replace = false`

### ISSUE THREAD

**Issue by chrisgrieser** [folke/noice.nvim#556]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

neovim 0.9.1 (homebrew)

### Operating system/version

macOS 13.4.1 (M1)

### Describe the bug
Essentially, `print()` seems to ignore `merge = false` and `replace = false`, while `vim.notify` does not. 

This quite troublesome, since when debugging with `print`, some messages are not displayed, when noice is enabled. Not knowing that it was noice "swallowing" my print messages has cost me 2+ hours, searching for a bug that wasn't actually there.

[The default view config](https://github.com/folke/noice.nvim/blob/main/lua/noice/config/views.lua#L70) already sets both, `replace` and `merge`, to `false`.

### Steps To Reproduce

1. Use the repro config below
2. Create a file with the following content:
```lua
print("hello")
```

3. run `:source` two times. Result: only one `hello` notification.

4. Now create this file:
```lua
vim.notify("hello")
```
5. run `:source` two times. Result: two `hello` notifications

### Expected Behavior

- `print` output should respect `merge = false` and `replace = false`
- `print` and `vim.notify` should behave consistently, since they both use the same view

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins with minimal LSP setup
local plugins = {
	"folke/tokyonight.nvim",
	{
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" },
		opts = true,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by chrisgrieser** [comment]
Bug is still there with nvim 0.10 and latest commit of noice (f278f273e9c9a43bd18ac293b0c36d39b7deec89)

I edited the original bug report for some added clarity.

**Comment by folke** [comment]
merge and replace is for notify only.

`print` is generating `msg_show` events with `msg_clear`, or with the flag `replace_last`.
So nothing much I can do about this...

**Comment by chrisgrieser** [comment]
Wouldn't something like overriding `print` work?

**Comment by folke** [comment]
ok, I was partially wrong with my anwser.
You're referring to printing exactly the same twice?
If so, then that currently doesn't work due to some Neovim issues with `ext_messages`.
The problem is that noice gets spammed repeatedly with the same `msg_show` (and other) events due to redraws that may  happen outside of Noice's control.

So I had to implement a mechanism where I drop messages if they're the same.

That's probably what you mean.

You can check with `:Noice stats` (the `skipped` events)
