### ISSUE TITLE
bug: Disabling cmdline doesn't seem to restore default neovim cmdline behavior

### ISSUE THREAD

**Issue by nerdo** [folke/noice.nvim#560]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-741+g996dd36c7-Homebrew

### Operating system/version

MacOS 13.5

### Describe the bug

I'm trying to disable the Noice cmdline because I prefer the default behavior, but I can't seem to get it back.

```
noice.setup({ cmdline = { enabled = false }})
```

This does indeed disable noice's cmdline, but the normal neovim commandline is gone and I can't seem to get it back even if I `:set cmdheight=1`.

BTW, I know I'm running nightly, but I had the same issue with the stable version.

### Steps To Reproduce

noice.setup({ cmdline = { enabled = false }})

### Expected Behavior

Neovim cmdline should be unaffected

**Comment by akbng** [comment]
You need to disable the `messages` as well otherwise the `cmdline` will be enabled by default.
## Set this in your config:
```lua
cmdline = {
  enabled = false,
},
messages = {
  enabled = false,
},
```
### check the docs for more details:
![image](https://github.com/folke/noice.nvim/assets/91788199/648c3967-bee9-4029-b9b9-4da8fa4d1766)
