### ISSUE TITLE
Errors on write buffer (nvim-notify strange behavior)

### ISSUE THREAD

**Issue by xbladesub** [folke/noice.nvim#561]
I have strange behavior on write buffer. I mapped `:w` to `<C-S>`

```lua
map("n", "<C-s>", ":w<CR>", { silent = true, desc = "Save" })
```

When I trigger `ctrl+s` several times this error alerts are being shown. 
But all good if I manually enter `:w` command (only 1 successful alert).

<img width="301" alt="image" src="https://github.com/folke/noice.nvim/assets/45129790/9225541f-e5e3-43e0-8177-4224f39a1b3c">

What could be wrong?

**Comment by lyjpy2005** [comment]
the same error happens on me. But I find that there is no error when I save the file first time.

**Comment by MariaSolOs** [comment]
Looking at the docs for `:w`, it seems like this might happen if you're saving a read-only file or the location doesn't exist:
<img width="630" alt="image" src="https://github.com/folke/noice.nvim/assets/62502207/626514ab-2b8d-4f2c-8dcd-dc12066f1fcd">

It's weird that they're showing up as error messages though. What do you have configured for `shortmess`?

**Comment by xbladesub** [comment]
found it
```lua
  require("noice").setup({
    routes = {
      {
        filter = {
          event = "msg_show",
          kind = "",
          find = "written",
        },
        opts = { skip = true },
      },
    },
  })
  ```

**Comment by elC0mpa** [comment]
Any update about this?
