### ISSUE TITLE
bug: replace first line to empty

### ISSUE THREAD

**Issue by y1rn** [folke/noice.nvim#578]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev 617fd5bdc6ab9a82bfc6136f549fc31dcf442ed7

### Operating system/version

linux

### Describe the bug

replace first line to empty while load `noice`.

### Steps To Reproduce

1. load file
2. open popup cmdline

### Expected Behavior

load file normally

**Comment by lervag** [comment]
Can confirm that this issue also affects me. As others, it took a while to bisect it to this plugin. I last updated my plugins 5 or 6 days ago, so the bug was introduced within the last week.

**Comment by folke** [comment]
Caused by this? https://github.com/neovim/neovim/issues/24897

Does the problem disappear with Neovim versions before https://github.com/neovim/neovim/commit/008154954791001efcc46c28146e21403f3a698b ?

**Comment by lervag** [comment]
I won't have time to check that explicitly myself, but that seems very related. I also updated neovim today, so I would not be surprised if this is due to the neovim update.

**Comment by MariaSolOs** [comment]
I just tested the current `master` branch and it seems like https://github.com/neovim/neovim/pull/24913 fixed this.

**Comment by SteveWolligandt** [comment]
I just updated my plugins in hope that it is fixed now but at least on windows the bug is still present. When hitting `"` the first line gets empty.

**Comment by MariaSolOs** [comment]
> @MariaSolOs, I just updated my plugins in hope that it is fixed now but at least on windows the bug is still present. When hitting `:` the first line gets empty.

Did you update `nvim` as well?
