### ISSUE TITLE
feature: More faithful `api.status.command`

### ISSUE THREAD

**Issue by Delta-official** [folke/noice.nvim#579]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I've switched over to noice with lualine recently and everything is perfect, except for the fact that `api.status.command` doesn't perfectly follow the behavior of the vanilla `showcmd`.

Here's a table that shows what gets displayed for each character typed in the sequence:
Sequence | `showcmd` | `api.status.command`
---|---|---
`cib` | `c`, `ci`, [clear] | `c`, [no-op], `cib`
`:w` | [nothing] | `:`, [no-op]
`j` | [nothing] | `j`

### Describe the solution you'd like

Ideally, `api.status.commandline` would follow the behavior of `showcmd`, but a good compromise would be to at least ignore the same commands as in `showcmd` (https://github.com/neovim/neovim/blob/7c4d317a660c9d241a817faddc28ec6f36e753ad/src/nvim/normal.c#L1939-L1948).

### Describe alternatives you've considered

Alternatively, noice should expose an api that would allow the user to replicate `showcmd` behavior.

### Additional context

P.S. There might be more inconsistencies in the behavior.

**Comment by folke** [comment]
Noice shows the exact showcmd from Neovim.
What Noice shows is triggerd in the `display_showcmd()` function you can find in the code you shared.

The difference probably stems from when lualine is drawn (redrawn).

Noice can trigger more redraws when needed (like when the cmdline is open)

**Comment by 4rgc** [comment]
I was able to work around this by replacing the `noice.nvim` lualine component with `'%S'`, and setting the `showcmdloc` option to `statusline`.
It is a little inconvenient that you can't see the command as you type with the provided component.
