### ISSUE TITLE
feature: do not showing `echom:` before showing messages

### ISSUE THREAD

**Issue by cxwx** [folke/noice.nvim#583]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

it always show a frame of `echom a:message` instantly before showing the main messages.
I known that it the command `echom` is used to show the message later.

### Describe the solution you'd like

supress the `echom a:message` info

### Describe alternatives you've considered

no

**Comment by folke** [comment]
not sure what you're asking here. You probably have a keyma triggering the message, that doesn't set `silent=true`?
