### ISSUE TITLE
feature: route option to delegate to built-in view

### ISSUE THREAD

**Issue by MariaSolOs** [folke/noice.nvim#587]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to use the built-in views for some commands, such as `z=`. Is there a way I can configure a route such that `noice` just delegates to the builtin view?

### Describe the solution you'd like

Having a `route` option such as `builtin` that just delegates to the ugly, vanilla Neovim experience.

### Describe alternatives you've considered

Cry :(
Seriously though, I guess I could create a custom `noice` view that's as similar as the builtin one but that feels wrong...

**Comment by folke** [comment]
You mean the builtin messages view? If that's what you're asking, then that is not possible. Since Noice uses ui_attach and from that point Noice **IS** the builtin messages view.

**Comment by MariaSolOs** [comment]
@folke yep that's what I meant. I was mostly interested in the `-- More --` prompt, since dealing with the special keymaps in that mode becomes kind of awkward with `nui`. I understand that this isn't possible though so I'll close this :)
