### ISSUE TITLE
bug: nvim crashing on Ubuntu - fixed by removing noice

### ISSUE THREAD

**Issue by Mithrandir2k18** [folke/noice.nvim#588]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Ubuntu 20.04, Linux mypc 5.11.0-42-generic #46~20.04.1-Ubuntu x86_64 GNU/Linux

### Describe the bug

<details>
<summary>Full build info</summary>
nvim --version
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/nvim/parts/nvim/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
</details>

Just recently added noice to my config and it has been working great on archlinux. I just now pulled my config to my Ubuntu 20.04 laptop and nvim would instantly crash after installing noice and then also at launch. It would only extremely briefly show this message (or print it out if I pipe neovims output to a file):

`nvim: /build/nvim/parts/nvim/build/src/nvim/message.c:2418: msg_scroll_flush: Assertion `to_scroll >= 0' failed.`

Removing noice from lazy fixes the issue, so I am pretty sure it is related. I run the default noice config

### Steps To Reproduce

I was able to reproduce it within the latest ubuntu:20.04 docker image:

1. `docker run -it ubuntu:20.04 bash
2. Install latest neovim from unstable branch (as stable is v0.7): https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu
3. clone my [dotfiles](https://github.com/Mithrandir2k18/dotfiles.git) to `$HOME/dotfiles` and run `$HOME/dotfiles/neovim/init`
4. run `nvim`. It should install all plugins, then crash. relaunching also crashes
5. to get the error message on stdout run `nvim > /dev/null`, it'll crash and print out: `nvim: /build/nvim/parts/nvim/build/src/nvim/message.c:2418: msg_scroll_flush: Assertion 'to_scroll >= 0' failed.`

### Expected Behavior

Run neovim normally, not crash instantly

### Repro

```Lua
I tried to narrow it down to a minimal init.lua, but sadly failed to reproduce it this way. It must therefore be my seemingly weird combination of plugins+running on Ubuntu 20.04, as I could not reproduce the issue on the debian:latest dockerimage, and also don't have this issue on my archlinux install at home.
```

**Comment by Mithrandir2k18** [comment]
> it would be really helpfull if you could try removing plugins and like this figure out which are needed to reproduce the issue

I know, tried to do this a few times, but was unable to find the culprit. Since I'm at work currently, I just removed noice locally and will try to find the culprit again later. Maybe I'll write a script to automate it.

**Comment by max397574** [comment]
well just comment out half of your plugins
if it then works comment out the other half because then the "breaking" plugin won't be in there
if it then doesn't work you continue to comment out half of the rest of the plugins
even with dozens of plugins you should be able to find it quite quickly like this

**Comment by MariaSolOs** [comment]
@Mithrandir2k18 `noice` uses experimental, actively-being-developed features, and so you should _*really*_ be using nightly Neovim. This might be an upstream issue that's already fixed.

**Comment by Mithrandir2k18** [comment]
I am now on 
```
$nvim --version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

And the problematic plugin seems to be [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim), at least deleting it solves the issue. I am on branch v1 but the same happens on v2 and v3 on my machine, so it seems there's an issue between these two plugins - but only on ubuntu 20.04 it seems, at least I don't have the issue on my other devices.

**Comment by folke** [comment]
Whenever Neovim crashes, it's a Neovim bug.
Make sure to use nightly for Noice since as @MariaSolOs said already, most of these bugs are likely already fixed upstream.

If you still have segfaults, then you need to get a proper stacktrace (see the Neovim wiki) and report an issue there with a minimal repro.

**Comment by kierun** [comment]
[Could this be linked to this issue?](https://github.com/neovim/neovim/issues/25446#issuecomment-1742785634)
