### ISSUE TITLE
Cmdline own plugin

### ISSUE THREAD

**Issue by rebelot** [folke/noice.nvim#59]
Hi @folke, I've always been a fan of your plugins! Please don't get me wrong, this is just my willing to share thoughts.

Perhaps the most interesting feature of `noice` is the floating commandline, popupmenu and notify don't really need to be "bundled" in this plugin. Most likely, the user base of noice is already using cmp and cmp-cmdline. Notify integration could be just shipped as a wrapper function. So my two cents are just to "focus" on the commandline feature. I am saying this because I am worried about the burden of a 'one size fits all' approach and the dev-time overhead needed to make three somewhat distinct feature go nice together. Besides, wouldn't a new "command-line" buffer type be worthy of a PR in core?

**Comment by max397574** [comment]
I think that there are quite a lot of people who want all the things together in one plugin.

And I think this wouldn't go into core.
For two reasons: `q:` exists (which is cmdline as a buffer) and they implemented `vim.ui_attach` exactly so **plugins** like this can be created

**Comment by folke** [comment]
Other reasons:
- cmdline, popupmenu and messages are all using the same `vim.ui_attach` api, so all code should process events in a similar way
- right now listening for `ext_messages` also implicily activates `ext_cmdline`, so you can't have messages without cmdline
- the fact that noice is extremely customziable is also used by all components.

I could think of putting some things in noice plugins, similar to what `cmp` does, but will keep it as is for now.

**Comment by rebelot** [comment]
Thanks for the clarifications :) keep it up!
