### ISSUE TITLE
bug: Crashes when running lazy.nvim or checkhealth

### ISSUE THREAD

**Issue by grighq** [folke/noice.nvim#598]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1240+g9afbfb4d6

### Operating system/version

Fedora Linux 38 (Workstation Edition)

### Describe the bug

Crashes when launching lazy.nvim and leaves artifacts: 
![Screenshot from 2023-09-29 09-24-38](https://github.com/folke/noice.nvim/assets/112962683/d1afc5b2-82a2-4eff-9eb4-8e85882e97ed)
Crashes when running checkhealth:
![Screenshot from 2023-09-29 08-58-12](https://github.com/folke/noice.nvim/assets/112962683/e77a1df5-65c4-4eb7-89cf-2308b5bce49a)
When I disable noise.nvim everything works fine.

### Steps To Reproduce

This behavior started after one of the latest neovim updates, I can’t say exactly after which one. If I run the stable version everything works fine. 

### Expected Behavior

No crashes. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
If NEovim segfaults, then that is always a Neovim issue.

Try with the lastest nightly. If the issue persists, get a stacktrace (see the Neovim wiki) and report upstream
