### ISSUE TITLE
bug: hide written message will hide the confirm message as well

### ISSUE THREAD

**Issue by XXiaoA** [folke/noice.nvim#599]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

nightly

### Operating system/version

Arch linux

### Describe the bug

Having hided written message as what wiki do, I find that the `confirm` window will be hided as well, which is provided by `confirm` option

### Steps To Reproduce

1. open a file and modify something
2. type`:q`

### Expected Behavior

Hide written messages and show `confirm` message

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/noice.nvim",
            routes = {
            {
                filter = {
                    event = "msg_show",
                    find = "written",
                },
                opts = { skip = true },
            },
       }
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.opt.confirm = true
```

**Comment by folke** [comment]
Then filter them out in another way?
Just add `W` to `shortmess`
