### ISSUE TITLE
Noice breaks when entering the command-line window from the cmdline popup

### ISSUE THREAD

**Issue by 0xAdk** [folke/noice.nvim#60]
**Describe the bug**
Opening the command-line window from Noice's cmdline popup cause it to error out

**Which version of Neovim are you using?**
nightly: `v0.9.0-dev-89-geb123b565e` (just built it)

**To Reproduce**
1. open Noice's cmdline with `:`
2. press `<c-f>` to transition into the command-line window
3. wait a second for a bunch of error messages followed by Noice disabling itself (if you close the command-line window quickly it wont break)

<details>
<summary>mini config if required</summary>

```lua
local plug_dir = vim.env.HOME .. '/.local/share/nvim/site/pack/packer/start'

vim.opt.rtp:append {
	plug_dir .. '/nvim-notify',
	plug_dir .. '/nui.nvim',
	plug_dir .. '/noice.nvim',
}

require 'noice'.setup {}
```
</details>

**Expected Behavior**
no errors

**Noice Log**
Nothing is added to the log

**Comment by folke** [comment]
Should be fixed now. Thank you for reporting!

**Comment by 0xAdk** [comment]
yup that fixed it! 
that's the fastest turn round I've seen on a bug :p
