### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by lipppchen** [folke/noice.nvim#602]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

windows10 wsl2

### Describe the bug

![image](https://github.com/folke/noice.nvim/assets/49047439/eddd4555-5b09-4ff9-8dd7-532a31981ce8)

### Steps To Reproduce

nvim into lazyvim
l
U (update plugins)
failed.

### Expected Behavior

you guys can told me what should I do?

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by max397574** [comment]
well you have local changes for noice it seems
either go into the local folder and do `git restore .`, just delete it or uninstall the plugin with lazy first
