### ISSUE TITLE
bug: Opening a buffer shows INSERT in lualine when its in normal mode. Goes away after entering and exiting insert mode once.

### ISSUE THREAD

**Issue by sameer1612** [folke/noice.nvim#605]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

MacOS Sonoma

### Describe the bug

Opening a buffer shows INSERT in lualine when its in normal mode. Goes away after entering and exiting insert mode once.

![ezgif com-video-to-gif](https://github.com/folke/noice.nvim/assets/39580073/08a67567-02c9-4007-a277-78f01dfe8259)

```lua
return {
  "nvim-lualine/lualine.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    local lualine = require("lualine")
    lualine.setup({
      options = {
        theme = "tokyonight",
      },
      sections = {
        lualine_x = {
          { "datetime" },
          { "filetype" },
          {
            require("noice").api.status.mode.get,
            cond = require("noice").api.status.mode.has,
            color = { fg = "#ff9e64" },
          },
          {
            require("noice").api.status.search.get,
            cond = require("noice").api.status.search.has,
            color = { fg = "#ff9e64" },
          },
        },
      },
    })
  end,
}
```

### Steps To Reproduce

1. Open any file using telescope.
2. Notice the mode value in status line.
3. By default it shows --INSERT-- 
4. Becomes normal after entering and exiting insert mode once.

### Expected Behavior

Opening a buffer should show not show that it is in insert mode. 

For reference notice the mode indicator in extreme left provided by lualine which shows correct state.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by max397574** [comment]
please provide a minimal repro

**Comment by folke** [comment]
Can't reproduce. Either way, mode is what Neovim tells Noice the mode should be. We're just routing the info.

You probably have some weird shortmess option active.
