### ISSUE TITLE
text not supported for type none

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/noice.nvim#61]
**Describe the bug**
Invoking the command line (press `:`) generates an error
```
text not supported for type none
```
This happens after one of the most recent commits: perhaps [this one](https://github.com/folke/noice.nvim/commit/da51d3596fa7e09ef7f5f9d3dc9d64a463aee76e)
```
  if opts.border and opts.border.style == "none" then
    opts.border.text = nil
  end
  ```
  then the `opts.border.text` is passed on to other calls that fail upon `nil`?

**Which version of Neovim are you using?**
```
nvim --version
NVIM v0.9.0-dev-1228-ga93ff5fc6-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

**To Reproduce**
1. use the `minimal.lua` 
2. add the [clean cmdline_popup](https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#clean-cmdline_popup) as per in the wiki
3. invoke command prompt (`:`)

See video below: commenting in/out the option `style="none"`)

https://user-images.githubusercontent.com/15387611/195632998-33fa7913-8cc2-48a6-902b-38ccf625284e.mov

**Comment by folke** [comment]
Fixed. Thank you for reporting!
