### ISSUE TITLE
Feature request: ability to check if noice is loaded

### ISSUE THREAD

**Issue by mawkler** [folke/noice.nvim#610]
### Discussed in https://github.com/folke/noice.nvim/discussions/591

<div type='discussions-op-text'>

<sup>Originally posted by **mawkler** September  7, 2023</sup>
I want a conditional depending on if I have noice.nvim loaded. Is there any build-in way to check that? Neovide sets the variable `vim.g.neovide` to `true`. Does noice.nvim have an equivalent? `vim.g.noice` doesn't seem to work.</div>

It would be sweet if noice had a `vim.g.noice` feature or similar to see if noice has been loaded.

**Comment by folke** [comment]
`require("noice.config")._running`

**Comment by mawkler** [comment]
@folke Thank you!
