### ISSUE TITLE
cmdline: Hitting backspace with empty command closes the popup

### ISSUE THREAD

**Issue by mhanberg** [folke/noice.nvim#62]
**Describe the bug**

When you hit backspace and there is no text entered, the cmdline_pop closes. This is surprising when you are spamming backspace to clear out the cmdline when making a spelling mistake. I would expect that `enter` and `esc` are the only keys that would exit the popup.

**Which version of Neovim are you using?**

NVIM v0.8.0-dev-1093-g982fef601

**To Reproduce**

1. type `:`
2. hit `Backspace`

**Expected Behavior**

Popup remains open

**Screenshots**

![noice-backspace](https://user-images.githubusercontent.com/5523984/195873103-d290e329-9458-4eec-a819-257efe4545f5.gif)

**Comment by folke** [comment]
That's standard Neovim behavior. Try the same without Noice. Cmdline closes when you hit backspace

**Comment by mhanberg** [comment]
Wow, you are right 😅. Sorry about that. I am not sure why felt like I had not experienced that before.
