### ISSUE TITLE
bug: disable signature help in favor of ray-x/lsp-signature.nvim doesn't work

### ISSUE THREAD

**Issue by Delice0** [folke/noice.nvim#620]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

latest

### Operating system/version

mac latest

### Describe the bug

I tried disabling signature help:

```
return {
  "folke/noice.nvim",
  opts = function(_, opts)
    table.insert(opts.routes, {
      filter = {
        event = "notify",
        find = "No information available",
      },
      opts = { skip = true },
    })

    -- opts.presets = {
    -- bottom_search = true, -- use a classic bottom cmdline for search
    -- command_palette = true, -- position the cmdline and popupmenu together
    -- long_message_to_split = true, -- long messages will be sent to a split
    -- inc_rename = false, -- enables an input dialog for inc-rename.nvim
    -- lsp_doc_border = true, -- add a border to hover docs and signature help
    -- }
    table.insert(opts.lsp, {
      signature = {
        enabled = false,
      },
    })
  end,
}
```
But it didnt work. I still get signature help + an error telling me to disabling it because I use another plugin.

### Steps To Reproduce

1. use giving config for noice
2. use ray-x/lsp-signature.nvim

### Expected Behavior

I expect that noice signature help is disabled and no error

**Comment by folke** [comment]
```lua
 table.insert(opts.lsp, {
      signature = {
        enabled = false,
      },
    })
```

That;s not correct. please refer to the noice docs.

Also please use github discussions for user questions

**Comment by Delice0** [comment]
> ```lua
>  table.insert(opts.lsp, {
>       signature = {
>         enabled = false,
>       },
>     })
> ```
> 
> That;s not correct. please refer to the noice docs.
> 
> Also please use github discussions for user questions

I did look at the noice docs and the other option i tried was:

```
opts.lsp.signature.enabled = false
```
which didn't work either.

How should I approach this?

**Comment by max397574** [comment]
perhaps return opts from the function?
and don't use table.insert
this will create something like `opts.lsp={{signature={enabled=false}}}`

**Comment by Delice0** [comment]
And this which didn't work

```
    require("noice").setup({
      lsp = {
        signature = {
          enabled = false,
        },
      },
    })
```

**Comment by folke** [comment]
`opts.lsp.signature = {enabled = false}`
Also, don't call setup yourself

**Comment by folke** [comment]
You should have gotten an error by lazy that your spec was incorrect, no? You have a lua error

**Comment by Delice0** [comment]
> `opts.lsp.signature = {enabled = false}` Also, don't call setup yourself

This did the trick.

I still wonder why this didn't work:
`opts.lsp.signature.enabled = false` but this is probably because of my poor lua knowledge

**Comment by folke** [comment]
`opts.lsp.signature` is not defined, so that would raise an error.
