### ISSUE TITLE
bug: `%s/foo/bar/` visual feedback falls behind (visual desync)

### ISSUE THREAD

**Issue by Zeioth** [folke/noice.nvim#622]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1352+g85ddd0074b

### Operating system/version

arch

### Describe the bug

When typing `:%s/foo/bar/`, what you see in the command bar do not correspond with what you are typing. 

* The artifact starts after typing `:%s/`
* After typing the first `/` the visual feedback will always be one character behind what you are actually writing.

This doesn't happen anymore if I disable noice.nvim

![screenshot_2023-10-16_15-18-42_646571766](https://github.com/folke/noice.nvim/assets/3357792/d1251a2b-ca28-4ad0-b949-3862952628e3)

### Steps To Reproduce

1. Write `:%s/foo/bar`
2. After writing the first `/`, whe glitch will manifest

### Expected Behavior

The same using `:%s/foo/bar` without noice.nvim has.

### Repro

```Lua
-- NOTE: It can be reproduced by default
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That was fixed yesterday. Did you update?

**Comment by Zeioth** [comment]
In the first place, you have no right to be so awesome.

In the second place YES that fixed it.
Thank you very much.
