### ISSUE TITLE
feature: Ability to style command line results seperate to the popup

### ISSUE THREAD

**Issue by Taaqif** [folke/noice.nvim#623]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

No problem

### Describe the solution you'd like

Highlight groups that allow configuring the results seperate from the popup
![image](https://github.com/folke/noice.nvim/assets/1954204/19947ada-5088-4c52-8f3a-d9cb015b1b40)

I have tried overriding a few highlight groups but none seem to override the results **only** 

The end goal is something similar to what Telescope allows but like this for the cmdline 
![image](https://github.com/folke/noice.nvim/assets/1954204/7b7ee48a-47e1-4554-844c-1f37eec50f4f)

### Describe alternatives you've considered

NA

**Comment by folke** [comment]
https://github.com/folke/noice.nvim#-highlight-groups
`NoicePopupmenu...`

Please use github discuttions next time for user questions

**Comment by Taaqif** [comment]
Thanks @folke

That didn't work, what did work was overriding the `winoptions.winhighlight` for the `cmdline_popupmenu` view. 
Setting the Normal and FloatBorder to another hl group I can override. 
By default its set to Normal. 
I might submit a PR to add these HL groups as it could benefit others

```lua
views = {
  cmdline_popupmenu = {
    win_options = {
      winhighlight = { Normal = "NoiceCmdlinePopupResults", FloatBorder = "NoiceCmdlinePopupResultsBorder" },
    },
  },
},
```

With this config I can get my cmd prompt to look perfect 
![image](https://github.com/folke/noice.nvim/assets/1954204/41ae0111-6740-4689-be5b-04bb81cc4b5a)
