### ISSUE TITLE
Need a workaround to avoid nvim crash at the start

### ISSUE THREAD

**Issue by przepompownia** [folke/noice.nvim#628]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

I described the problem in https://github.com/neovim/neovim/issues/25100. In short, nvim crashes at the start when multiline messages comes through Noice.

### Describe the solution you'd like

If the issue is hard to resolve on the nvim side, maybe it would be easier to work around it here?

### Describe alternatives you've considered

The first alternative for me is to disable Noice if nvim crashes at startup. In most cases it turns out that it crashes at displaying messages.

**Comment by folke** [comment]
I don't have this issue and have zero interest in creating a work-around specially for you.
Disable Noice or wait for a proper fix in core.

**Comment by przepompownia** [comment]
> I don't have this issue and have zero interest in creating a work-around specially for you. Disable Noice or wait for a proper fix in core.

Thanks for helpful answer. Disabling it seems to be good idea at the moment, at least before `UIEnter`: https://github.com/neovim/neovim/issues/25100#issuecomment-1772727478
