### ISSUE TITLE
bug: Noice interferes with cmp suggestion documentation pop up

### ISSUE THREAD

**Issue by MarcoCamilo** [folke/noice.nvim#632]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

MacOS 13.6

### Describe the bug

Cmp autocomplete documentation sometimes does not show when noice.nvim is on. Given the problem is solved when deactivating noice.nvim, it's the plugin that is interfering somehow, but I can't find how.

Noice activated.
<img width="1410" alt="Screenshot 2023-10-21 at 06 00 32" src="https://github.com/folke/noice.nvim/assets/72537451/04dd9dc5-1238-4103-a272-a9fc445c7e04">

Noice _not_ activated.
<img width="1410" alt="Screenshot 2023-10-21 at 06 01 42" src="https://github.com/folke/noice.nvim/assets/72537451/e0dbf074-24c9-4f7d-8df5-c2dbf452ebe5">

### Steps To Reproduce

1. Have cmp and noice installed
2. Write a command such as "vim.cmd()" and allow cmp to suggest options
3. Choose an option to attempt to see documentation.

### Expected Behavior

Cmp documentation is shown for suggestions when noice is on.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Your treesitter install is messed up. Check the nvim-treesitter docs. Probably need to run `:TSUpdate`
