### ISSUE TITLE
bug: `:Noice` return invalid window id 

### ISSUE THREAD

**Issue by AnhQuanTrl** [folke/noice.nvim#633]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-594ff34

### Operating system/version

WSL2

### Describe the bug

I sometimes got this error `...r/.local/share/nvim/lazy/nui.nvim/lua/nui/split/init.lua:168: Invalid window id: 1001` during using Noice. After I got this error, `:Noice` no longer works.

### Steps To Reproduce

1. Make sure `:Noice` previously works and populate a message history at the bottom.
![image](https://github.com/folke/noice.nvim/assets/36561860/7d0b9c94-da49-4fb2-a75b-8d00dd51eaba)

3. Instead of closing the message history window, navigate to the "code window" that we were just before typing `:Noice`
4. Close that window instead.
5. Now we finally close the message history window.
6. Navigate to any file and type `:Noice` again.
7. An error appeared: `...r/.local/share/nvim/lazy/nui.nvim/lua/nui/split/init.lua:168: Invalid window id: 1001`

### Expected Behavior

The error `invalid window id` should not occur and `:Noice` still works as expected.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" },
		opts = true,
	},
  {
      'nvim-tree/nvim-tree.lua',
      keys = {
        { '<leader>fe', '<cmd>NvimTreeFindFileToggle<cr>', desc = '[F]ile [E]xplorer' },
      },
      config = function(_, opts)
          local nvimtree = require 'nvim-tree'
          nvimtree.setup(opts)
      end,
  }
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by jackielii** [comment]
dup of #636. Or the other one is the dup one

**Comment by AnhQuanTrl** [comment]
Let's close this issue to focus on the other one.
