### ISSUE TITLE
bug: Repeated display “nui.nvim: Invalid window id” error

### ISSUE THREAD

**Issue by nanozuki** [folke/noice.nvim#636]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

I found some "Invalid window id" issue. It looks a little different, I'm not quite sure if it's a duplicate, and if it is, I'm sorry!

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1693350652

### Operating system/version

MacOS 14.0

### Describe the bug

![telegram-cloud-photo-size-1-5021882462535527376-y](https://github.com/folke/noice.nvim/assets/4208028/32971f5e-f2e8-4134-bf06-c21b3ee8d4f1)

After I closed a windows which I used noice, every time I use noice, this error will be display.

### Steps To Reproduce

1. `nvim -u repro.lua` to open minimal config, and use `<Ctrl>W V` to vsplit window.
2. Close this window by `:q` (use noice, and close window)
3. type `:` to open noice's cmdline popup window, and the error comes.

### Expected Behavior

No error message.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ 'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git', lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  'folke/tokyonight.nvim',
  {
    'folke/noice.nvim',
    event = 'VeryLazy',
    opts = {
      views = {
        cmdline_popup = {
          position = { row = 0, col = -2 },
          relative = 'cursor',
        },
      },
      lsp = {
        override = {
          ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
          ['vim.lsp.util.stylize_markdown'] = true,
          ['cmp.entry.get_documentation'] = true,
        },
      },
      presets = {
        bottom_search = true, -- use a classic bottom cmdline for search
        command_palette = true, -- position the cmdline and popupmenu together
        long_message_to_split = true, -- long messages will be sent to a split
        inc_rename = false, -- enables an input dialog for inc-rename.nvim
        lsp_doc_border = false, -- add a border to hover docs and signature help
      },
    },
    dependencies = {
      'MunifTanjim/nui.nvim',
      'rcarriga/nvim-notify',
    },
  },
  -- add any other plugins here
}
require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

vim.opt.background = 'dark'
vim.cmd.colorscheme('tokyonight')
-- add anything else here
```

**Comment by jackielii** [comment]
I get this very often. I have habit of using `<C-w>c` to close a window. If I do this on a noice split window, I get this error, once. The following ones seems to be swallowed by router deduplication.

Floating window doesn't seem to have this issue...

**Comment by pysan3** [comment]
We need this fix. 

https://github.com/MunifTanjim/nui.nvim/discussions/335

**Comment by Thesola10** [comment]
this seems to be related to reusing the same widget instance? Like, when a new split is created, its window ID is updated but the split being deleted means the instance is now linked to a nonexistent window ID? That's the way I understand it since I'm using (or trying to use) `relative = "win"` on `cmdline_popup`, it opens over the last opened window, except when changing types (e.g. with `:lua` or `:!`) the "new" popup appears over the _actual_ current window.

Maybe the `nui` widget needs to be discarded and re-created every time?

**Comment by Thesola10** [comment]
okay, then is there a way to discard the widget every time, so I can have `cmdline_popup` open over the currently focused window every time?

**Comment by pysan3** [comment]
I don't think your question belongs to this issue. 

Theoretically it would be `opts.cmdline_popup.relative = "win"`, but I doubt noice supports relative = "win" in the first place since I don't see it mentioned anywhere in the docs or code. 

That'll be a separate feature request (or a bug report), to support relative = "win" in the first place.

**Comment by pysan3** [comment]
A theoretical fix would be to add 
```lua
-- ...
-- `self` = NuiSplit or NuiPopup somewhere in the code.

self:layout_update({ relative = opts.<view>.relative, win = vim.api.nvim_get_current_win() })

-- ...
-- before self:mount() and self:show()
```

To force the window follow the current window.
But this will add additional unnecessary computation for all users using `relative = "editor"` which is the default option, so I don't know if it is worth supporting `relative = "win"` option.

**Comment by pysan3** [comment]
- https://github.com/MunifTanjim/nui.nvim/pull/337

**Comment by nanozuki** [comment]
I can still reproduce this issue, after I update the latest "nui.nvim". Should I change my config in noice?

**Comment by pysan3** [comment]
You might be right. I'll look into it once again. Thanks for testing @nanozuki

**Comment by nanozuki** [comment]
@pysan3 I saw the PR has merged. I tried the latest version of "nui.nvim," and this bug is fixed! Thanks!
