### ISSUE TITLE
Callback that is run when user types command

### ISSUE THREAD

**Issue by smjonas** [folke/noice.nvim#64]
**Is your feature request related to a problem? Please describe.**
I wonder if you'd consider adding a callback that is run when the user types in the command line window. This callback can be used to transform the text that the user typed before running the command / preview callback. Here's a scenario that shows how this could be used:
- for my plugin [inc-rename.nvim](https://github.com/smjonas/inc-rename.nvim), I'd like users to be able to simply type the new name for an identifier. Currently, you need to type out the full command, like `:IncRename new_name`.

**Describe the solution you'd like**
It would be awesome if something like this was possible (which you could then use in a mapping):
```lua
require("noice").command_line {
  title = "Enter new name:",
  callback = function(input)
    return "IncRename " .. input
  end,
}
```

**Describe alternatives you've considered**
Can't really think of any

**Comment by folke** [comment]
Great suggestion! I'll look into it.

**Comment by folke** [comment]
I just pushed a big update for formatting/concealing the cmdline. See this comment here https://github.com/folke/noice.nvim/issues/84#issuecomment-1285724444

It has an example to setup `IncRename`. Nothing to be done on your end :)
Feel free to add the snippet to your docs.

**Comment by smjonas** [comment]
Thank you very much for adding this feature, I'll check it out soon!

**Comment by folke** [comment]
Extended example with the input dialog at cursor position.

![image](https://user-images.githubusercontent.com/292349/197055719-8bc57c52-0051-451f-b8f3-b1b145467ced.png)

```lua
	local noice = require("noice")
	noice.setup({
		debug = false,
		cmdline = {
			format = {
				IncRename = {
					pattern = "^:%s*IncRename%s+",
					icon = " ",
					conceal = true,
					opts = {
						relative = "cursor",
						size = {
							min_width = 20,
						},
						position = {
							row = -3,
							col = 0,
						},
						buf_options = { filetype = "text" },
					},
				},
			},
		},
	})
```

**Comment by smjonas** [comment]
Just tested it and it works great! I added a `noice.nvim support` section to the `inc_rename.nvim` readme. Thanks again!
