### ISSUE TITLE
Issue using :Git push from fugitive-nvim in cmdline

### ISSUE THREAD

**Issue by constantitus** [folke/noice.nvim#640]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Gentoo linux, 6.5.5 kernel 

### Describe the bug

- Using vim-fugitive's `Git push` command and pressing enter
Cmdline freezes and doesn't accept input (it's supposed to ask for my ssh password)
![image](https://github.com/folke/noice.nvim/assets/118078873/b96d369e-e77b-4ade-93da-5746e224e5cf)

- press enter a second time
![image](https://github.com/folke/noice.nvim/assets/118078873/dcc22bfb-ca6a-408c-92df-2de0d22f1969)

### Steps To Reproduce

1. have a git repository set up
2. use `:Git push` in vim

### Expected Behavior

Provide a way to input my password when using the `Git push` command

default nvim behaviour:
![image](https://github.com/folke/noice.nvim/assets/118078873/752550fa-f02d-46e5-ae90-e75da169a339)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    {
        "tpope/vim-fugitive",
    },
    {
        "folke/noice.nvim",
        opts = {
        },
        dependencies = {
            -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
            "MunifTanjim/nui.nvim",
            "rcarriga/nvim-notify",
        },
        config = function()
            require("noice").setup()
            require("notify").setup()
        end,
    },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
```

**Comment by folke** [comment]
Known issue that can't be fixed in Noice. See https://github.com/neovim/neovim/issues/20311

**Comment by constantitus** [comment]
I'm having issues with some other commands, such as `:map` being much harder to read with noice and notify
![image](https://github.com/folke/noice.nvim/assets/118078873/1d9ac5c2-1017-41d5-827d-908d612b283b)
Sorry for asking this here, but is a way we can use the normal neovim cmdline as a fallback ?

**Comment by folke** [comment]
Known issue and again needs to be fixed in core: https://github.com/neovim/neovim/issues/20715

See also the known issues list here https://github.com/folke/noice.nvim/issues/6

And no, it's all or nothing. `vim.ui_attach` doesn't allow what you want.
