### ISSUE TITLE
bug: messages breaking mappings

### ISSUE THREAD

**Issue by Sam-programs** [folke/noice.nvim#643]
### Did you check docs and existing issues?

- [x] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

ArchLinux 6.5.5-arch1-1

### Describe the bug

messages seem to add an extra `<CR>` after mappings
https://github.com/folke/noice.nvim/blob/main/lua/noice/ui/msg.lua#L131
i haven't read much of the code, am not sure how to fix this

it also seems to break `<up>` in keymaps
more info:
https://github.com/windwp/nvim-autopairs/issues/412#issuecomment-1784093285

https://github.com/folke/noice.nvim/issues/642
might be related

### Steps To Reproduce

install [nvim-autopairs](https://github.com/windwp/nvim-autopairs) and set it up
set report to 0
type {\<cr\>

### Expected Behavior

Expected:
```
Before        Input         After
------------------------------------
{|}           <CR>          {
                                |
                            }
------------------------------------
```
Behavior:
```
Before        Input         After
------------------------------------
{|}           <CR>          {
                            }

                            |
------------------------------------
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  "windwp/nvim-autopairs"
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.opt.report = 0
```

**Comment by folke** [comment]
That's odd. Something must have changed in Neovim. This used to be needed. Will look into it
