### ISSUE TITLE
bug: Error message every time I start writing the command `:lua `

### ISSUE THREAD

**Issue by MarcoCamilo** [folke/noice.nvim#644]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

MacOS 13.6

### Describe the bug

Every time I begin to write `:lua `, for each subsequent character I get the error message " query: invalid structure at position X for language lua" (X standing for any number). Therefore, I end up getting a lot of error messages, one for each character.

<img width="1415" alt="image" src="https://github.com/folke/noice.nvim/assets/72537451/ac7e898d-6f69-4481-8d9a-1e3e4dc309c2">

### Steps To Reproduce

1. Open nvim
2. Enter `: lua `
3. Start writing any subsequent command, like `require(...)`

### Expected Behavior

Error messages not to appear when writing correct lua commands.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by max397574** [comment]
this looks like a query and parser out of sync problem to me

**Comment by MarcoCamilo** [comment]
So how would I solve the problem?

**Comment by folke** [comment]
`:TSUpdate`. If that doesn't work, check the nvim-treesitter docs/wiki

**Comment by MarcoCamilo** [comment]
Thanks for the suggestion, I actually found the solution here: https://github.com/nvim-treesitter/nvim-treesitter/issues/3092
