### ISSUE TITLE
Search result is not disappearing

### ISSUE THREAD

**Issue by xbladesub** [folke/noice.nvim#647]
<img width="610" alt="image" src="https://github.com/folke/noice.nvim/assets/45129790/8f32663a-aa05-4ffe-aaa8-362c3080e348">

It doesn't disappear (green search result) even after `:nohlsearch`, but not always, sometimes it works as expected.

my config:

```lua
	require("noice").setup({
		routes = {
			{
				filter = {
					event = "msg_show",
					any = {
						{ find = "%d+L, %d+B" },
						{ find = "; after #%d+" },
						{ find = "; before #%d+" },
						{ find = "%d fewer lines" },
						{ find = "%d more lines" },
					},
				},
				opts = { skip = true },
			},
		},
	})
```

**Comment by folke** [comment]
Are you sure you're using the latest version?
Something related to this has been fixed a couple of weeks ago https://github.com/folke/noice.nvim/commit/e5a4c7a6ac3ef4c32f97a50c0b9b21e21c445c04
