### ISSUE TITLE
Override notification  level of messages

### ISSUE THREAD

**Issue by wangl-cc** [folke/noice.nvim#65]
**Is your feature request related to a problem? Please describe.**
I want to make some messages to a error or a warning like this:
```lua
{
  view = "notify",
  filter = {
    any = {
      { event = 'msg_show', find = '^RPC%[Error%]' },
    }
  }
  opts = {
    title = 'Error',
    level = vim.log.levels.ERROR,
  }
}
```

I wants to change its log level to `ERROR`, but it don't work, because the notify uses `msg.level`.

**Describe the solution you'd like**
The level specified in view or route can override the `msg.level`, like
```lua
level = self._opts.level or msg.level or defaults.level
```
and the make `self._opts.level` to `nil` by default.

**Describe alternatives you've considered**
A way to change message's notification level.

**Comment by folke** [comment]
Good point. Fixed!

**Comment by wangl-cc** [comment]
Thanks！
