### ISSUE TITLE
bug: Noice (?) changes custom highlight for Neorg

### ISSUE THREAD

**Issue by rodhash** [folke/noice.nvim#656]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-a84b454

### Operating system/version

MacOS ventura 14.1.1

### Describe the bug

Whenever I open Cmdline, noice resets my custom highlighting colors for Neorg.

In this quick vid I'm already using the minimal version to reproduce the issue and as soon as I open Cmdline, it changes all the custom colors.

https://github.com/folke/noice.nvim/assets/29671981/3fdeddfa-a94e-4732-95c1-5a4583aa443b

### Steps To Reproduce

1. Open the nvim w/ repro.lua config
2. Open any neorg file
3. Open the Cmdline and the custom highlighting colors get changed

### Expected Behavior

No HL changes when opening Cmdline.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
  "nvim-neo-tree/neo-tree.nvim",
  "nvim-lua/plenary.nvim",
  "rodhash/nvim-web-devicons",
  "MunifTanjim/nui.nvim",
  "rcarriga/nvim-notify",
  "nvim-neorg/neorg",
  "nvim-lua/plenary.nvim",
  "nvim-treesitter/nvim-treesitter",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

local nvim_set_hl = vim.api.nvim_set_hl
nvim_set_hl(0, "@neorg.headings.1.title"               , { fg="#d75fff", bold = true } )
nvim_set_hl(0, "@neorg.headings.1.prefix"              , { fg="#d75fff" } )
nvim_set_hl(0, "@neorg.headings.2.title"               , { fg="#ff5f00", bold = true } )
nvim_set_hl(0, "@neorg.headings.2.prefix"              , { fg="#ff5f00" } )
nvim_set_hl(0, "@neorg.headings.3.title"               , { fg="#7f7f7f", bold = true } )

require("noice").setup()
require("neorg").setup {
    -- configuration here
    load = {
        ["core.defaults"] = {
          config = {
              default_keybinds = false,
          },
        },
        ["core.concealer"] = {}

    }
}
```

**Comment by rodhash** [comment]
well .. it seems that updating my norg parser did the trick

**Comment by rodhash** [comment]
nevermind .. the issue is still here.

**Comment by rodhash** [comment]
Search and other prompts also resets the custom highlight color.. apparently this is happening only in neorg filetype

**Comment by Galicarnax** [comment]
Same issue here. Customized bg for code blocks in Neorg. Launch nvim, open norg file, custom bg is in use. Press `:` to enter any command, bg is reverted to Neorg's original. Doesn't happen with Noice disabled.

**Comment by Galicarnax** [comment]
Not all custom hl groups are reverted. To test, in gruvbox config, I override 
```lua
                ["@neorg.tags.ranged_verbatim.code_block"] = { bg = #"ff0000"  },
                ["@neorg.todo_items.urgent.norg"] = { bg = "#00ff00"  },
```
When Noice pops up, the first one is reverted, the second is not.

**Comment by folke** [comment]
Noice does not revert any highlights

**Comment by Galicarnax** [comment]
I guess it does not. But its popup triggers the chain of events that ultimately revert some custom highlights for `norg`. Any hints? @vhyrro? @danymat?

**Comment by Galicarnax** [comment]
I was able to solve the issue by defining a custom hl group in the config of `concealer` module of `neorg`:
```lua
        require("neorg").setup {
            load = {
                ["core.defaults"] = {},
                ["core.concealer"] = {
                    config = {
                    icons = {
                        code_block = {
                            highlight = "@test",
                        }
                    }
                    }
                },
            },
        }
```
and then in colorscheme config:
```lua
                ["@test"] = { bg = "ff0000"  }
```
Then, Noice popup does not change the color. Some strange interplay here between `conceraler` and `noice`...

**Comment by rodhash** [comment]
Maybe it's not the Neorg Concealer too .. just tried disabling it completely and yet the HL colors get messed up .. this is an annoying issue

**Comment by rodhash** [comment]
What worked for me was creating an autocmd specifically for this filetype (norg) ..

Yeah I know, that's a poor solution.. but the thing is, I got sick of my colorscheme changing EVERY time I use any command .. this situation made me go straight to a quick and dirty autocmd

This is a simple autocmd that applies the colors of my colorscheme:

```lua
vim.api.nvim_create_autocmd("FileType",{
  pattern = "norg",
  command = [[
    hi @neorg.headings.1.title  gui=bold guifg=#d75fff
    hi @neorg.headings.1.prefix gui=none guifg=#fe0000
    hi @neorg.headings.2.title  gui=bold guifg=#ff5f00
    hi @neorg.headings.2.prefix gui=none guifg=#d70000
    hi @neorg.headings.3.title  gui=bold guifg=#cd0000
    hi @neorg.headings.3.prefix gui=bold guifg=#5f5f5f
    hi @neorg.headings.4.title  gui=bold guifg=#ac4cce
    hi @neorg.headings.4.prefix gui=none guifg=#ac4cce
    hi @neorg.headings.5.title  gui=bold guifg=#5c5c5c
    hi @neorg.headings.5.prefix gui=none guifg=#5c5c5c
  ]]
})
```

**Comment by juniorsundar** [comment]
> What worked for me was creating an autocmd specifically for this filetype (norg) ..
> 
> 
> 
> Yeah I know, that's a poor solution.. but the thing is, I got sick of my colorscheme changing EVERY time I use any command .. this situation made me go straight to a quick and dirty autocmd
> 
> 
> 
> This is a simple autocmd that applies the colors of my colorscheme:
> 
> 
> 
> ```lua
> 
> vim.api.nvim_create_autocmd("FileType",{
> 
>   pattern = "norg",
> 
>   command = [[
> 
>     hi @neorg.headings.1.title  gui=bold guifg=#d75fff
> 
>     hi @neorg.headings.1.prefix gui=none guifg=#fe0000
> 
>     hi @neorg.headings.2.title  gui=bold guifg=#ff5f00
> 
>     hi @neorg.headings.2.prefix gui=none guifg=#d70000
> 
>     hi @neorg.headings.3.title  gui=bold guifg=#cd0000
> 
>     hi @neorg.headings.3.prefix gui=bold guifg=#5f5f5f
> 
>     hi @neorg.headings.4.title  gui=bold guifg=#ac4cce
> 
>     hi @neorg.headings.4.prefix gui=none guifg=#ac4cce
> 
>     hi @neorg.headings.5.title  gui=bold guifg=#5c5c5c
> 
>     hi @neorg.headings.5.prefix gui=none guifg=#5c5c5c
> 
>   ]]
> 
> })
> 
> ```

I tried the highlight override on catppuccin and tokyo night. That seems to work too.

**Comment by rodhash** [comment]
Yeah, not sure what exactly is broken between Noice and Norg but so far this was the best thing I could do here.
