### ISSUE TITLE
bug: Incorrect command-line mode filetype

### ISSUE THREAD

**Issue by mawkler** [folke/noice.nvim#660]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-d7359a8

### Operating system/version

Manjaro Linux x86_64

### Describe the bug

The filetype inside the floating command-line mode window is the same as the file I was when pressing `:`, even if I set the filetype explicitly with `buf_options`.

### Steps To Reproduce

1. `nvim -u path/to/init.lua test.md`
2. Press `:`, then `<M-o>` (which prints the current buffer's filetype)
3. `filetype: "markdown"` gets printed

### Expected Behavior

`filetype: "NoiceCommandline"` gets printed

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    'folke/noice.nvim',
    dependencies = { 'MunifTanjim/nui.nvim', 'rcarriga/nvim-notify' },
    config = function()
      local noice = require('noice')

      noice.setup({
        cmdline = {
          format = {
            cmdline = {
              opts = {
                buf_options = { filetype = 'NoiceCommandline' },
              },
            },
          },
        },
      })

      vim.keymap.set('c', '<M-o>', function()
        local filetype = vim.api.nvim_get_option_value('filetype', { buf = 0 })
        print('filetype: ' .. vim.inspect(filetype))
      end)
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Sam-programs** [comment]
noice does not set the current buffer to the command window.
otherwise it would mess with statuslines and other plugins.

**Comment by mawkler** [comment]
Please leave this issue open Mr. Bot

**Comment by folke** [comment]
You never left the original window, since you are in the cmdline.

Noice **IS** the real commandline and will behave the same as the regular cmdline.
