### ISSUE TITLE
bug: route for msg_show event works inconsistently

### ISSUE THREAD

**Issue by protiumx** [folke/noice.nvim#664]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Ubuntu 20.00 under WSL

### Describe the bug

Routes with filter on `min_lenght` or `min_height` does not work all the time. In some cases for very long 1 line messages, they are still shown in the default view (notify in my case).
I can see that the config is properly set by calling `Noice routes`

### Steps To Reproduce

Config for routes
```lua
routes = {
  {
    filter = { 
      event = "msg_show",
      min_length = 50,
      min_height = 5,
    },
    view = 'popup',
  },
},
```

Call a echo or`:lua print(...)` with a very long line. E.g. `:lua print(vim.o.errorformat)`

### Expected Behavior

Messages that are longer than `50` or have more than `5` lines should be shown in a popup.
I have also tried removing the `event_type`, but the route still doesn't work.
NOTE: this has been reported in https://github.com/folke/noice.nvim/issues/331 but I still cannot get the messages to redirect

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's caused by https://github.com/neovim/neovim/issues/21044

**Comment by budimanjojo** [comment]
@folke according to the issue you linked above, neovim v0.11 should have it fixed? But this is still not working for me in v0.11.4.
