### ISSUE TITLE
bug: Popping up cmdline when using a shortcut key.

### ISSUE THREAD

**Issue by oldqin97** [folke/noice.nvim#665]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 12.4

### Describe the bug

When using the kkoomen/vim-doge plugin to generate comments for functions in insert mode, pressing Tab to switch to the next section triggers the cmdline to appear. How can I prevent the cmdline from popping up when I press a specific shortcut key?

https://github.com/folke/noice.nvim/assets/48620148/d10d1ee8-2e59-4b5d-a14e-4a09eea2a07f

The quickly disappearing cmdline.
<img width="640" alt="image" src="https://github.com/folke/noice.nvim/assets/48620148/6fe58581-6bb7-4fe5-a3a2-638a35783207">
<img width="656" alt="image" src="https://github.com/folke/noice.nvim/assets/48620148/718549d7-52e5-4532-98d9-102bdfec6115">

Pressing Tab and moving the cursor within comments, in normal mode, doesn't trigger the cmdline.

### Steps To Reproduce

1. use kkoomen/vim-doge plugin
2. In insert mode, pressing Tab and moving the cursor within comments triggers the cmdline to appear.

### Expected Behavior

When I'm writing comments, I want to move the cursor to the next comment point by pressing Tab without triggering the cmdline.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by oldqin97** [comment]
> 您可能想`<silent>`看看https://neovim.io/doc/user/map.html#%3Amap-arguments

I think it has nothing to do with the shortcut keys. Using the "kkomen/vim-doge" plug-in and pressing the tab shortcut key will call the 'call setpos' method on the command line. If the noise plug-in executes all call setpos methods My problem can be solved without popping up cmdline.

**Comment by folke** [comment]
That's exactly why `<cmd>` exists for keymaps opposed to using `:`
