### ISSUE TITLE
bug: notify-send failed: Unknown option --print-id

### ISSUE THREAD

**Issue by AdrienLemaire** [folke/noice.nvim#669]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1811+gc95b9a32f

### Operating system/version

Ubuntu 22.04

### Describe the bug

I sometimes get countless notification 

![image](https://github.com/folke/noice.nvim/assets/260983/fe87ad12-39d7-438a-a29a-a7a8bbc0ecac)

It seems to be used in https://github.com/folke/noice.nvim/blob/92433164e2f7118d4122c7674c3834d9511722ba/lua/noice/view/backend/notify_send.lua#L80

I couldn't find anything related in nvim-notify code & issues.

Not sure how it works behind, but my system notify-send doesn't support this parameter
```console
$ notify-send --print-id
Unknown option --print-id
$ notify-send --version
notify-send 0.7.9
```

### Steps To Reproduce

I installed LazyVim following @craftzdog's [video](https://www.youtube.com/watch?v=fFHlfbKVi30), and noticed the problem from the beginning.

```lua
return {
  -- messages, cmdline and the popupmenu
  {
    "folke/noice.nvim",
    opts = function(_, opts)
      table.insert(opts.routes, {
        filter = {
          event = "notify",
          find = "No information available",
        },
        opts = { skip = true },
      })
      local focused = true
      vim.api.nvim_create_autocmd("FocusGained", {
        callback = function()
          focused = true
        end,
      })
      vim.api.nvim_create_autocmd("FocusLost", {
        callback = function()
          focused = false
        end,
      })
      table.insert(opts.routes, 1, {
        filter = {
          cond = function()
            return not focused
          end,
        },
        view = "notify_send",
        opts = { stop = false },
      })

      opts.commands = {
        all = {
          -- options for the message history that you get with `:Noice`
          view = "split",
          opts = { enter = true, format = "details" },
          filter = {},
        },
      }

      vim.api.nvim_create_autocmd("FileType", {
        pattern = "markdown",
        callback = function(event)
          vim.schedule(function()
            require("noice.text.markdown").keys(event.buf)
          end)
        end,
      })

      opts.presets.lsp_doc_border = true
    end,
  },

  {
    "rcarriga/nvim-notify",
    opts = {
      timeout = 5000,
    },
  },

```

### Expected Behavior

No such warning should be shown.

**Comment by pattybardo** [comment]
Running into same issue

**Comment by kenhuang1964** [comment]
Hey @AdrienLemaire I am also following his video and coming across this issue. Did you end up resolving this issue?

**Comment by AdrienLemaire** [comment]
I think I went and commented the related line in the codebase, no clean
solution

**Comment by folke** [comment]
You need at least libnotify version 0.7.10
See https://github.com/GNOME/libnotify/commit/652b4d6911e95adba15d3efddce08364a925877a

This is my config:

```lua
    local focused = true
    vim.api.nvim_create_autocmd("FocusGained", {
      callback = function()
        focused = true
      end,
    })
    vim.api.nvim_create_autocmd("FocusLost", {
      callback = function()
        focused = false
      end,
    })
    table.insert(opts.routes, 1, {
      filter = {
        ["not"] = {
          event = "lsp",
          kind = "progress",
        },
        cond = function()
          return not focused
        end,
      },
      view = "notify_send",
      opts = { stop = false },
    })
```
