### ISSUE TITLE
Open highlight/map in a normal buffer and focus on notification

### ISSUE THREAD

**Issue by duarm** [folke/noice.nvim#67]
**Is your feature request related to a problem? Please describe.**
I want to consult my mappings/highlights by running its respective commands, but their output are displayed in a notification for seconds before closing. I can only scroll the output with a mouse too.

**Describe the solution you'd like**
If possible, both should be displayed in a buffer, similar to messages, ideally this should be configurable tho, e.g. I personally would prefer a fullscreen buffer instead of a split like messages.

**Another solution**
Maybe a keybing to focus on the first notification, you would be able to scroll and search that notification, it would wait until you unfocus it to close. Also a hotkey to navigate between notifications. This should be added together with the previous solution tho, as they cover different needs.

**Comment by gennaro-tedesco** [comment]
I was thinking about a similar use case (in particular while running `verbose map <...>`) and thought that perhaps one may route output based on `cmd`: something along the lines of
```
routes = {
    {
      view = "split",
      filter = { cmd = "<insert cmd here>" },
    },
  },
```
I tried to combine some grammar from the events but haven't found a way yet (please correct me if this isn't what you meant, I may have misunderstood).

> but their output are displayed in a notification for seconds before closing

you _can_ move the focus into the notification window (`<C-w>w`): that keeps the notification from disappearing and you could in principle copy the content to a buffer for inspection.

**Comment by duarm** [comment]
> I was thinking about a similar use case (in particular while running verbose map <...>) and thought that perhaps one may route output based on cmd: something along the lines of

perfect, this could potentialy cover another need I have for filter some events to ignore/display in another way, e.g. I save my file quite a lot, so the saving notification is almost always present on my screen, I would like to filter the that particular event to something else like notifier.nvim or something.

> you can move the focus into the notification window (<C-w>w): that should keep the notification from disappearing and you could in principle copy the content to a buffer for inspection.

I see, what was happening was that I was searching and pressing enter to move the cursor to the match, but that closes the notification.

**Comment by gennaro-tedesco** [comment]
>  so the saving notification is almost always present on my screen

yes; at the moment I am filtering those out based on the message text, but I agree that introducing a filter/route based on commands rather than regex can simplify this a lot. Perhaps it is already possible, let's look into the docs some more :)

**Comment by duarm** [comment]
was able to make it work via regex, thanks

**Comment by folke** [comment]
Simply run `:Noice` after you ran `:hi`?

That will open the message history in a split
