### ISSUE TITLE
feature: Add a configuration option to set the anchor for notify messages

### ISSUE THREAD

**Issue by DannyStoll1** [folke/noice.nvim#677]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

It would be nice to be able to see notifications at the bottom right instead of the top right. There seems to be nonzero interest in such a feature, as evidenced by the following two discussions: https://github.com/folke/noice.nvim/discussions/469, https://github.com/folke/noice.nvim/discussions/676. However, after digging through the codebase, it appears that there is currently no way to do this.

### Describe the solution you'd like

I think the natural frontend for such a feature would be to add an `anchor` setting to `views.notify`, like there is for `views.hover`.

Were I more familiar with the backend, I would implement this in a pull request. If you could point me in the right direction for where to start, I'd be happy to work on adding such a feature.

### Describe alternatives you've considered

We could alternatively try to use `nui` to display messages, since it already supports customizing the anchor.

### Additional context

In my opinion, notify messages at the top of the screen can be quite distracting. If a user-configurable anchor is out of reach, it might be worth considering hard-coding the anchor to be in the bottom right instead.

**Comment by shreyas-a-s** [comment]
I just found out about this.

https://github.com/folke/noice.nvim/discussions/676#discussioncomment-8035360

Have you tried it?

**Comment by PlexSheep** [comment]
A user in #676 has found a [solution](https://github.com/folke/noice.nvim/discussions/676#discussioncomment-8035360)
