### ISSUE TITLE
No ui router for win (module 'noice.ui.win' not found) when running :checkhealth

### ISSUE THREAD

**Issue by amaanq** [folke/noice.nvim#68]
**Describe the bug**
Title, happens only when running checkhealth

**Which version of Neovim are you using?**
Gui(specify which GUI client you are using)? Nightly? Version?

Nightly 0.9.0

**To Reproduce**
1. Open neovim
2. Run :checkhealth

**Expected Behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/29718261/196009627-0ad3a783-df66-4681-aad1-5723f29270df.png)

**Noice Log**

<details>
<summary>Noice log</summary>
<pre>

Thu Oct  6 03:59:39 2022
...opt/nvim-notify/lua/notify/service/buffer/highlights.lua:153: Invalid buffer id: 4

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_get_option'
	...opt/nvim-notify/lua/notify/service/buffer/highlights.lua:153: in function 'set_opacity'
	...acker/opt/nvim-notify/lua/notify/service/buffer/init.lua:45: in function '_create_highlights'
	...acker/opt/nvim-notify/lua/notify/service/buffer/init.lua:38: in function 'set_notification'
	.../pack/packer/opt/nvim-notify/lua/notify/service/init.lua:73: in function 'replace'
	...vim/site/pack/packer/opt/nvim-notify/lua/notify/init.lua:212: in function 'notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:125: in function '_notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:151: in function <...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:128>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:34: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Thu Oct  6 04:03:24 2022
...opt/nvim-notify/lua/notify/service/buffer/highlights.lua:153: Invalid buffer id: 4

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_get_option'
	...opt/nvim-notify/lua/notify/service/buffer/highlights.lua:153: in function 'set_opacity'
	...acker/opt/nvim-notify/lua/notify/service/buffer/init.lua:45: in function '_create_highlights'
	...acker/opt/nvim-notify/lua/notify/service/buffer/init.lua:38: in function 'set_notification'
	.../pack/packer/opt/nvim-notify/lua/notify/service/init.lua:73: in function 'replace'
	...vim/site/pack/packer/opt/nvim-notify/lua/notify/init.lua:212: in function 'notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:125: in function '_notify'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:151: in function <...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:128>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:34: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Thu Oct  6 04:03:29 2022
...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:440: Invalid buffer id: 8

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_open_win'
	...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:440: in function '_open_window'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/popup/init.lua:252: in function 'show'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:143: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:29 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:29 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:29 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:29 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:29 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:29 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:31 2022
...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:440: Invalid buffer id: 8

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_open_win'
	...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:440: in function '_open_window'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/popup/init.lua:252: in function 'show'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:143: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:31 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:31 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:32 2022
...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:440: Invalid buffer id: 8

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_open_win'
	...m/site/pack/packer/opt/nui.nvim/lua/nui/popup/border.lua:440: in function '_open_window'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/popup/init.lua:252: in function 'show'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:143: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Thu Oct  6 04:03:32 2022
...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: Invalid buffer id: 7

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:102: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:101>
	[C]: in function 'nvim_buf_set_option'
	...vim/site/pack/packer/opt/nui.nvim/lua/nui/utils/init.lua:129: in function 'set_buf_options'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:156: in function 'render'
	...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:145: in function <...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:134>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:82: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:107: in function 'try'
	...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:29: in function <...im/site/pack/packer/opt/noice.nvim/lua/noice/ui/init.lua:22>

Wed Oct 12 17:07:39 2022
...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:165: E11: Invalid in command-line window; <CR> executes, CTRL-C quits

stack traceback:
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:119: in function <.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:118>
	[C]: in function 'nvim_win_close'
	...ite/pack/packer/opt/noice.nvim/lua/noice/view/notify.lua:165: in function 'hide'
	.../site/pack/packer/opt/noice.nvim/lua/noice/view/init.lua:90: in function 'display'
	.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:91: in function <.../pack/packer/opt/noice.nvim/lua/noice/message/router.lua:75>
	[C]: in function 'xpcall'
	.../site/pack/packer/opt/noice.nvim/lua/noice/util/call.lua:124: in function 'try'
	...site/pack/packer/opt/noice.nvim/lua/noice/util/hacks.lua:91: in function 'cmd'
	...hare/nvim/site/pack/packer/opt/hop.nvim/lua/hop/init.lua:264: in function 'get_input_pattern'
	...hare/nvim/site/pack/packer/opt/hop.nvim/lua/hop/init.lua:495: in function 'hint_char1'
	/home/amaanq/.config/nvim/lua/plugins/hop.lua:49: in function </home/amaanq/.config/nvim/lua/plugins/hop.lua:48>
</pre>
</details>

**Comment by folke** [comment]
I assume you enabled `debug=true`? That;s what you get for events coming in that we dont support.

Debug message. disable debug to disable it.

**Comment by amaanq** [comment]
oops, sorry! that was it, i had accidentally left it on :) thanks!
