### ISSUE TITLE
[Question] Substitute confirmation popup too small

### ISSUE THREAD

**Issue by Rlyown** [folke/noice.nvim#69]
Hi.

I am using the default configuration of noice without any changes. When I run a command like `:%s/aaa/bbb/gc`, the confirmation popup is too small and I can't see anything on it. Similarly, if I set the cmdline to classic mode as suggested on the wiki, substitute still pop up a window.

Could someone tell me how to set it up? I don't know which attributes are relevant to this. The following is the popup of confirmation.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/25147862/196049123-1b301dd3-1b66-4b50-b252-c5476250be2c.png">

**Comment by folke** [comment]
That's not normal. Something else is messing with the cmdline popup.

Try to reproduce it with https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by Rlyown** [comment]
@folke I have tried the minimal config by `nvim -u minimal.lua test.txt`. This problem happened again.

**Comment by folke** [comment]
Right, I see it now. Was testing something else :) Will look into it!
