### ISSUE TITLE
feature: display key sequence just entered.

### ISSUE THREAD

**Issue by sshelll** [folke/noice.nvim#690]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

![image](https://github.com/folke/noice.nvim/assets/49158400/0e34a754-1a17-453b-9699-84d8ee15c05c)

Sometimes I want to check the keys that I just pressed, especially when I defined a long mapping.

This information was originally displayed in the bottom right corner, but I couldn't  find it in noice.nvim.

### Describe the solution you'd like

Display the sequence anywhere should work for me.

### Describe alternatives you've considered

In the old UI, the command line always took up the bottom line and it cannot be hidden.

But in noice.nvim, the command line is hidden until you need to use it.

Maybe we can add an option to control this 'hidden' behavior?

**Comment by sshelll** [comment]
This feature is not really necessary for me.
But I think it's more proper to change the style of an existing component than just remove it.

**Comment by sshelll** [comment]
Are there any thoughts about this? It's 'stale' now😹

**Comment by folke** [comment]
you can already do this with lualine or any other statusline
