### ISSUE TITLE
bug: Long press backspace won't get the cmdline window to close

### ISSUE THREAD

**Issue by kgs233** [folke/noice.nvim#691]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2037+ge09adfdcf

### Operating system/version

Windows 11 23590.1000

### Describe the bug

as mentioned in the title

### Steps To Reproduce

1.enter :
2. Long press backspace 
![动画](https://github.com/folke/noice.nvim/assets/85022235/267119f9-0655-4f99-ad16-544c14a81618)

### Expected Behavior

cmdline window will be close

**Comment by Sam-programs** [comment]
Does this still happen on nightly ?

**Comment by kgs233** [comment]
Now, This is no longer the case.
