### ISSUE TITLE
Search popup customization

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#7]
Thank you for your work!

- Settings works for cmdline, but not work for search panel. Mb i didn't find decision in docs.
- Search panel has artefacts. I understand why that is it, but it annoys.
![image](https://user-images.githubusercontent.com/53742299/193617754-a45b88dd-7b43-45be-8e67-5442b7cdd4b0.png)
![image](https://user-images.githubusercontent.com/53742299/193617811-a47c163b-8420-440c-bd39-6fbf12c2a803.png)

**Comment by folke** [comment]
Yeah, my bad. I didnt add any docs yet on `filter_options`.

Lots of missing docs for the moment.

Your cmdline looks pretty noice though!
