### ISSUE TITLE
Status line components do not work

### ISSUE THREAD

**Issue by quantum-booty** [folke/noice.nvim#70]
**Describe the bug**
I can't see the statusline components in lualine.

**Which version of Neovim are you using?**
NVIM v0.9.0-dev-109-g0b71960ab

**To Reproduce**
I used the default noice configs:
`require("noice").setup()`

And the suggested config for lualine:
```lua
require("lualine").setup({
  sections = {
    lualine_x = {
      {
        require("noice").api.statusline.message.get_hl,
        cond = require("noice").api.statusline.message.has,
      },
      {
        require("noice").api.statusline.command.get,
        cond = require("noice").api.statusline.command.has,
        color = { fg = "#ff9e64" },
      },
      {
        require("noice").api.statusline.mode.get,
        cond = require("noice").api.statusline.mode.has,
        color = { fg = "#ff9e64" },
      },
      {
        require("noice").api.statusline.search.get,
        cond = require("noice").api.statusline.search.has,
        color = { fg = "#ff9e64" },
      },
    },
  },
})
```

**Expected Behavior**
I expect to be able to see the added lualine components.

**Screenshots**
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/28958399/196051151-a58abceb-1ef6-4614-8048-dafc08a86b1f.png">

**Noice Log**
:Noice log is empty

**Comment by folke** [comment]
You need to add that part to your existing lualine config.

What you're showing here, is not your lualine config at all.

**Comment by quantum-booty** [comment]
> You need to add that part to your existing lualine config.
> 
> What you're showing here, is not your lualine config at all.

Sorry I don't quite understand, what I showed in the screenshot is my lualine config. I haven't used lualine before so I'm just putting that config in init.lua for testing purposes.

**Comment by folke** [comment]
But your lualaine visible in the screenshot (the line at the bottom) **IS** configured. And not with what you have in the screenshot. The part I mentioned on the Noice website, also isn't enough. you need to properly configure lualine yourself.

Either way, this really seems to be a lualine configuration issue. Not really realated to Noice.

Did you run `PackerCompile` and restart Neovim?

**Comment by quantum-booty** [comment]
Yes I did run PackerCompile and restart Neovim. Could you elaborate on how I could properly configure lualine?

**Comment by folke** [comment]
Sorry, but no. I'm not going to give support on how to use lualine. Follow the docs at https://github.com/nvim-lualine/lualine.nvim/ and once that works and you are able to customize the lualine, then get back here if the Noice components would not work.

But they will work, once your lualine config works.

**Comment by quantum-booty** [comment]
Just to prove by point:
lualine is not visible when I comment out the config:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/28958399/196053296-b9a0edd2-b845-4c6a-9de7-a1f2c2b50f9b.png">
And now it is visible:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/28958399/196053306-f127e3a1-14e5-4458-9d9c-c2034a976ba0.png">

**Comment by folke** [comment]
ok, did you actually do something that should trigger any of the messages?

The statusline components won't show anything if they're empty.

Try triggering an error like `:foooooooo`

**Comment by quantum-booty** [comment]
This is what I see:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/28958399/196053408-ab1bfaf5-9a45-412d-bc68-792115da9a8c.png">

**Comment by folke** [comment]
Do you get anything when after that, doing:

`:lua vim.pretty_print(require("noice").api.statusline.message.get())`

**Comment by quantum-booty** [comment]
I get this:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/28958399/196053560-41e7c558-a7f2-4474-b2ae-afbca6d87394.png">

**Comment by folke** [comment]
That;s what it should show. So your lualine config isn't working.

**Comment by folke** [comment]
Are you sure that `noice` has been loaded when you set up lualine?

**Comment by folke** [comment]
Nevermind. It must be or lualine wouldn't load I guess

**Comment by quantum-booty** [comment]
I've just tried your lualine config in your dotfiles (I've deleted a few bits that uses plugins that I don't have):
https://github.com/folke/dot/blob/master/config/nvim/lua/plugins/lualine.lua

And this is what I'm getting:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/28958399/196053758-b5825397-1e11-413b-9e8f-3ade7f30fb22.png">

**Comment by folke** [comment]
I think I figured it out. Noice.setup should run before lua-line, otherwise it won't work. Will see if I can change it so it always works.

**Comment by folke** [comment]
Make sure you add `module="noice"` to the packer use statement of noice and do setup in the `config=` for noice.

**Comment by quantum-booty** [comment]
I added "after" in my lualine config and it worked:
   ` use { 'nvim-lualine/lualine.nvim', after = 'noice.nvim', config = [[require('config.lualine')]] }`
