### ISSUE TITLE
bug: Window navigation focus the Noice window

### ISSUE THREAD

**Issue by olatheander** [folke/noice.nvim#701]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux Kernel 6.6.9

### Describe the bug

Navigating windows e.g. with `<C-w>w` when a Noice message is shown put focus on the Noice message window. It's a bit unexpected that the notification window is part of the "navigation chain" and you get a bit lost before you realize why the expected window is not active.

![image](https://github.com/folke/noice.nvim/assets/16502929/8bf7e5ab-9285-41e1-8003-1012842764cf)

You typically need to do an extra `<C-w>w` to jump to the desired window.

### Steps To Reproduce

1. Trigger a Noice notification that is displayed for a few seconds.
2. Navigate with `<C-w>w` one or more times until you end up in the Noice message window.

### Expected Behavior

It would be nice if the Noice window can be excluded from the navigation since in most cases it's undesired to focus on that window.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's nvim-notify. You need to configure that
