### ISSUE TITLE
bug: Pop-up messages visibily execute using the cmdline, which is distracting 

### ISSUE THREAD

**Issue by qubitter** [folke/noice.nvim#706]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

### Operating system/version

MacOS 11.6

### Describe the bug

When editing a file with messages from a syntax highlighter (e.g. ALE), jumping between messages causes the `echom a:message` dialog to flicker in and out of view. Is it possible not to render this dialog when handling messages from a plugin?

### Steps To Reproduce

1. Open a file with a supported linter.
2. Make a change that will cause the linter to highlight an error.
3. Using the cursor, click in the highlighted area, then click outside of it. Observe flickering.

### Expected Behavior

Ideally, messages triggered by plugins wouldn't be rendered in the center-screen command dialog. See the attached file for the current behavior.

https://github.com/folke/noice.nvim/assets/11893617/705d0a76-dff5-4a0d-acdf-b343e2829d1b

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { 
    "catppuccin/nvim", 
    name = "catppuccin", 
    priority = 1000,
    config = function()
	    vim.cmd([[colorscheme catppuccin-mocha]])
    end,
    },
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  "hrsh7th/nvim-cmp",
  "dense-analysis/ale",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
-- add anything else here
```

**Comment by folke** [comment]
Check help for `<cmd>` and/or `silent`.
Not a Noice issue
