### ISSUE TITLE
Ability to turn off notification bubbles, but keep the statusline messages

### ISSUE THREAD

**Issue by quantum-booty** [folke/noice.nvim#71]
**Is your feature request related to a problem? Please describe.**
I would be nice if I could disable the notification bubbles, but have the statusline components working. I certainly find the notification bubbles a bit annoying, and would be more than happy to just see the message in the statusline.

If I have messages enabled, then I could both notification bubles and statusline messages.
```lua
require("noice").setup(
    {
        messages = {
            enabled = true,
        },
    }
)
```

<img width="639" alt="image" src="https://user-images.githubusercontent.com/28958399/196054531-022d46bc-57a1-434a-ab31-cf36d6670e69.png">
However if I set enable = false, both disappears:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/28958399/196054656-dd24b1cc-2624-416d-84d8-5c15f83c4c9a.png">

Looks like this could be achieved by skipping all message kinds in routes, but maybe there is a more elegant solution?
```lua
        routes = {
            {
                filter = { event = "msg_show", kind = "confirm_sub" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "emsg" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "echo" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "echomsg" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "echoerr" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "lua_error" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "rpc_error" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "return_prompt" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "quickfix" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "search_count" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "wmsg" },
                opts = { skip = true },
            },
            {
                filter = { event = "msg_show", kind = "" },
                opts = { skip = true },
            },
        }
```

**Comment by quantum-booty** [comment]
I think this solution is actually not bad.

**Comment by folke** [comment]
This is similar to what you have:

```lua
		routes = {
			{
				filter = {
					event = "msg_show",
					["not"] = {
						kind = { "confirm", "confirm_sub" },
					},
				},
				opts = { skip = true },
			},
		},
```

But I wouldn't advise using it like this. Whenever you execute a command, like `:ls`, you will only see the last line in the statusline.

To see the full output, you'll have to do `:Noice` after that

**Comment by folke** [comment]
Instead of `skip=true`, you could use `view="mini"`. That is a very minimalistic view bottom right of your screen.
