### ISSUE TITLE
bug: cannot hide cursor with `blend=100`

### ISSUE THREAD

**Issue by lljbash** [folke/noice.nvim#716]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2d33a76

### Operating system/version

Linux

### Describe the bug

Neovim supports hiding the cursor by [making it transparent](https://github.com/neovim/neovim/issues/3688#issuecomment-574544618). However, this won't work when enabling noice maybe because it already hides the cursor and redraws a fake one.

### Steps To Reproduce

```
set termguicolors
hi Cursor blend=100
set guicursor+=a:Cursor/lCursor
```
Also tried `NoiceCursor`.

### Expected Behavior

The cursor should be invisible.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Sam-programs** [comment]
Try `:hi NoiceCursor gui=nocombine blend=100`.

**Comment by lljbash** [comment]
> Try `:hi NoiceCursor gui=nocombine blend=100`.

Thank you for your suggestion! Adding `gui=nocombine` does not make any difference though. The cursor is invisible only in the cmdline.

**Comment by Sam-programs** [comment]
> Thank you for your suggestion! Adding gui=nocombine does not make any difference though. The cursor is invisible only in the cmdline.
Sorry i didn't understand what you were originally asking for.

The cursor highlight also needs `gui=nocombine` unless the background is cleared i think.
```vim
set termguicolors
hi HiddenCursor blend=100 gui=nocombine
set guicursor=a:HiddenCursor
```
And the `Cursor` highlight might be overwritten by themes so i changed the name.

**Comment by lljbash** [comment]
> Sorry i didn't understand what you were originally asking for.

Apologies for the confusion earlier.

When I disable noice, the following configuration works as expected:

```vim
set termguicolors
hi Cursor blend=100
set guicursor+=a:Cursor/lCursor
```

resulting in a invisible cursor that looks like this (both in text and cmdline):

![image](https://github.com/folke/noice.nvim/assets/11871224/920f4dac-90a4-4112-963f-5c9272a63990)

However, when noice is enabled and I use the following configuration:

```vim
set termguicolors
hi Cursor gui=nocombine blend=100
" or hi NoiceCursor gui=nocombine blend=100
set guicursor+=a:Cursor/lCursor
" or set guicursor=a:HiddenCursor
```

the cursor remains visible, as shown in this image (only in text):

![image](https://github.com/folke/noice.nvim/assets/11871224/07897974-a051-4812-bcf6-a6651285abb1)

After some experimentation, it seems that the issue may be related to the inability to modify `guicursor` after noice is loaded. I managed to partly restore functionality by setting guicursor before loading noice, like so:

```vim
" before loading noice
set guicursor+=a:Cursor/lCursor
```

However, this approach prevents me from making the cursor in the cmdline visible again (yes I can totally control the visibility of the cursor in the text area now).

At this point, I'm unsure about the underlying cause. I would greatly appreciate it if you could provide insights into how this works.

**Comment by Sam-programs** [comment]
> After some experimentation, it seems that the issue may be related to the inability to modify guicursor after noice is loaded. I managed to partly restore functionality by setting guicursor before loading noice, like so

Noice doesn't react to `guicursor` changes made on the command-line, it stores `guicursor` before starting the command-line then restores it after the command-line is exited.
However i don't know why it doesn't work at all after noice is loaded.

> At this point, I'm unsure about the underlying cause. I would greatly appreciate it if you could provide insights into how this works.

The `NoiceCursor` highlight is linked to `Cursor`, so when you make the `Cursor` highlight invisible the `NoiceCursor` highlight also becomes invisible.

**Comment by lljbash** [comment]
> Noice doesn't react to `guicursor` changes made on the command-line, it stores `guicursor` before starting the command-line then restores it after the command-line is exited. However i don't know why it doesn't work at all after noice is loaded.

oic, so everything I do with `guicursor` in cmdline is pointless. Changes will be reverted and `set guicursor?` will always get `a:NoiceHiddenCursor`.

**Comment by lljbash** [comment]
I can perfectly control the cursor visibility now by avoiding setting them in cmdline (e.g. using lua scripts).

Thank you very much for your time and patience.
