### ISSUE TITLE
How to disable popup messages?

### ISSUE THREAD

**Issue by andyl** [folke/noice.nvim#722]
After studying the documentation, I could not figure out how to disable common popup messages.

Just one example: When I turn off search highlights, I get a green notification with title = "Message" and content = "nohlsearch".

There are formatters, routes, filters, views, etc.  Which do I use to disable specific info and error messages?

I don't understand how it all fits together...

I want to disable messages based on their content.

This is probably a very basic question - sorry about that!  Once I figure it out I'll issue an PR to improve Noice documentation...

**Comment by dadav** [comment]
And the examples in the wiki didn't work? What did you try when you studied the docs?

**Comment by andyl** [comment]
No I could not find a wiki example that solved my use case.  For example, I tried the example below, modified for my message text.  No luck!

from https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#hide-written-messages-1 ...

```
  require("noice").setup({
    routes = {
      {
        filter = {
          event = "msg_show",
          kind = "",
          find = "nohlsearch",
        },
        opts = { skip = true },
      },
    },
  })
```

If you know the solution, please just reveal it!  :laughing:

**Comment by dadav** [comment]
Don't know the solution^^ I would've tried the same as you, but this config does nothing for me.

**Comment by dadav** [comment]
I also tried something like this:

```lua
  require("noice").setup({
    routes = {
      {
        filter = {
          event = "msg_show",
          find = "foo",
        },
        opts = { skip = true },
      },
    },
  })
```

But `:lua vim.notify("foo")` is still shown, so idk whats going on.

**Comment by andyl** [comment]
Thanks for giving it a try...

**Comment by dadav** [comment]
This should work:

```lua
  require("noice").setup({
    routes = {
      {
        filter = {
          event = "notify",
          find = "nohlsearch",
        },
        opts = { skip = true },
      },
    },
  })
```

**Comment by andyl** [comment]
@dadav - THANKS!

Also FYI - to filter multiple terms I used multiple routes like this...

```lua
require("noice").setup({
  routes = {
    { filter = { event = "notify", find = "ping" }, opts = { skip = true } },
    { filter = { event = "notify", find = "pong" }, opts = { skip = true } },
  },
})
```
