### ISSUE TITLE
bug: substitute is a character behind (v10)

### ISSUE THREAD

**Issue by scottmckendry** [folke/noice.nvim#725]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2098+g92672a161

### Operating system/version

Windows 11 23H2

### Describe the bug

This could be related to the known issue described [here](https://github.com/neovim/neovim/issues/20463). If it's a duplicate, please feel free to close it as such.

That being said, this is only occurring on nightly. I cannot reproduce the problem in the current v9 release. 

The best way I can describe the problem is that the cmd line is one char behind when doing substitute commands. For example, if I type `%s/text` the cmd line will show `%s/tex` instead. You can see this in the screenshot below:

![image](https://github.com/folke/noice.nvim/assets/39483124/895563fa-b86c-44d4-a09f-b7de48f4b552)

### Steps To Reproduce

1. Using the config provided, start Neovim and open a file.
2. Type `:%s/test`.
3. Note what has been typed vs. what is displayed.

### Expected Behavior

Typed characters and displayed characters should match.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    { "folke/tokyonight.nvim" },
    {
        "folke/noice.nvim",
        dependencies = { "rcarriga/nvim-notify", "MunifTanjim/nui.nvim" },
        config = function()
            require("noice").setup({
                cmdline = {
                    view = "cmdline",
                },
            })
        end,
    },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by MicheleGiacomini** [comment]
I think this is the same bug that was described in this issue #707.

**Comment by scottmckendry** [comment]
@MicheleGiacomini it looks that way. This is the same cursed behavior I've been experiencing. I'll close this one off.
