### ISSUE TITLE
feature: timeout control on messages

### ISSUE THREAD

**Issue by AdamBD** [folke/noice.nvim#726]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

It would be great to set a timeout on the messages, they tend to stay in place for a long time and can cover source code, especially when on small screen displays

### Describe the solution you'd like

An option to control the timeout length of all popup messages

### Describe alternatives you've considered

None

**Comment by simonsmith** [comment]
I used this:

```lua
require("notify").setup({
  timeout = 3500,
  stages = 'static'
})
```

**Comment by shreyas-a-s** [comment]
> I used this:
> 
> ```lua
> require("notify").setup({
>   timeout = 3500,
>   stages = 'static'
> })
> ```

This one.

Since the notification timeout is an already existing feature of nvim-notify, adding that option to noice would be kinda unnecessary.

**Comment by ilias777** [comment]
You can jump directly to the notification, error, message etc... by pressing `<C-w>w`:

https://github.com/folke/noice.nvim/assets/39212564/d87438ec-9e8d-452d-bd19-4e5e62656f00

Then you have the time to cover the message.

Or you send a specific notification to split, like mentioned in the docs.

Maybe this helps.

**Comment by kamalkech** [comment]
timeout control not working with this options

**Comment by shreyas-a-s** [comment]
> timeout control not working with this options

@kamalkech It would be great if you share the code of how you setup the plugin. Otherwise we never know the specifics because there are a number of ways by which we could set it up.

**Comment by Mu-Tsing** [comment]
@AdamBD I hope this will help you.

I found the "timeout" can only control the timeout of the lasting time except the total time. It means if you use some stages like "fade" or "slide", your message has a lower bound of the showing time. If you use "static", it will be the total time.

As others have commented on how to change settings with require, I provide how to change the option in Lazy.nvim: you can write it in you notify.lua like:
return {
        ...,
	opts = {
		stages = "static", -- other choice will has a minimal animation.
		timeout = 500, -- in ms, 1000 is one second.
	},
}

**Comment by anxi710** [comment]
> [@AdamBD](https://github.com/AdamBD) I hope this will help you.
> 
> I found the "timeout" can only control the timeout of the lasting time except the total time. It means if you use some stages like "fade" or "slide", your message has a lower bound of the showing time. If you use "static", it will be the total time.
> 
> As others have commented on how to change settings with require, I provide how to change the option in Lazy.nvim: you can write it in you notify.lua like: return { ..., opts = { stages = "static", -- other choice will has a minimal animation. timeout = 500, -- in ms, 1000 is one second. }, }

Think God, I find this, thank you.

I missed the stages option. :(

**Comment by yourpwnguy** [comment]
> You can jump directly to the notification, error, message etc... by pressing `<C-w>w`:
> example.mov
> 
> Then you have the time to cover the message.
> 
> Or you send a specific notification to split, like mentioned in the docs.
> 
> Maybe this helps.

Tell me the font you're using

**Comment by ilias777** [comment]
I'm using Wezterm, but in the website under FAQ &rarr; [here](https://www.monolisa.dev/faq#how-to-enable-stylistic-sets-for-the-kitty-terminal) you can find instructions how to setup in Kitty.

Keep in mind if you want to use the script variant, you have to buy the "complete" font option. The "basic" font option don't have the script variant.

To add nerd icons to make it nerd font, it has also instructions how to do this &rarr; [here](https://www.monolisa.dev/faq#how-to-enable-nerd-fonts-with-monolisa).
