### ISSUE TITLE
bug: ":hep", ":hl" and ":hp" get recognized as help command

### ISSUE THREAD

**Issue by anuramat** [folke/noice.nvim#730]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

NixOS 23.11

### Describe the bug

Pattern that is used for help command detection (`^:%s*he?l?p?%s+`) as both false positives (`hp`, `hl`, `hep`) and false negatives (`vert he` and so on)

### Steps To Reproduce

1. open nvim with installed noice.nvim and default opts
2. type `:hl ` (with a space)
3. observe the command getting recognized as help

### Expected Behavior

`:hl` doesn't get recognized as a help command

nice to have: `:vert he` and so on getting recognized instead (maybe make patterns take `string|bool(string)` values?)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{ "folke/noice.nvim", dependencies = { "MunifTanjim/nui.nvim" }, opts = {} },

	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by anuramat** [comment]
obv a minor one but it's triggering me

**Comment by shreyas-a-s** [comment]
Don't know if you've already found this way but by passing a new pattern for the help command, we can modify this behaviour:
```lua
require("noice").setup({
  cmdline = {
    format = {
      help = { pattern = "^:%s*help?%s+"},
    },
  },
})
```
I just removed two ? symbols from the regex that was provided in [README](https://github.com/folke/noice.nvim/blob/0cbe3f88d038320bdbda3c4c5c95f43a13c3aa12/README.md?plain=1#L125) and it works correctly. Don't know the reason behind that. It would be great if @folke could comment on the same whether it was a mistake or is it the intended pattern.
