### ISSUE TITLE
Doubt about warnings by lua_ls

### ISSUE THREAD

**Issue by shreyas-a-s** [folke/noice.nvim#744]
I had a doubt about why these warnings appear:

![image](https://github.com/folke/noice.nvim/assets/137637016/e26c59e8-f2db-4516-9cde-19986075ae15)

I have to clarify that the functionality works perfectly but since I am learning lua by tweaking neovim I wanted ask so that someone with more lua knowledge could share the know-how on the reason these warnings appear.

**Comment by b0ae989c** [comment]
It's a lua LSP issue. Don't worry about it. Both `get` and `has` are valid fields.

**Comment by folke** [comment]
Why do you open an issue for this? Sigh

**Comment by shreyas-a-s** [comment]
Thanks @b0ae989c for the clarification.

Sorry @folke, at that time I didn't know discussions section was a thing.
