### ISSUE TITLE
bug: floating notification is a jumpable windows reachable with <C-w> <C-w>

### ISSUE THREAD

**Issue by clanghans** [folke/noice.nvim#746]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

x86_64 GNU/Linux Ubuntu 22-04

### Describe the bug

I am not sure if it is a bug but it might apply for others as well.

Behaviour: 
When I `<C-w><C-w>` while a floating notification is visible the window switch happens and the floating notification is selected. 

Expected behaviour: 
Floating notification window is ignored. 

### Steps To Reproduce

1. Send notification - floating notification window appears
2. `<C-w><C-w>` switch windows - floating notification window is selected 

### Expected Behavior

Floating notification window is ignored. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You can configure the view's `winoptions` if you don't want it to show search results.

```lua
    win_options = {
      winhighlight = {
        IncSearch = "",
        CurSearch = "",
        Search = "",
      },
    },
```
