### ISSUE TITLE
Unwanted highlighted words in popup message's

### ISSUE THREAD

**Issue by kevinyyca** [folke/noice.nvim#751]
### Did you check docs and existing issues?

- [ ] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

`v0.9.4`

### Operating system/version

`Linux Mint 21.3`

### Describe the bug

I searched for "bg" in a file, and Neovim also highlighted thing's in the popup message.
![image](https://github.com/folke/noice.nvim/assets/121273910/73618947-7b6e-49a4-8e44-a4fce1c9cffe)

### Steps To Reproduce

1. Search for something anything.
2. The one or more words of the popup message will be highlighted.

### Expected Behavior

It shouldn't highlight a word in the popup message.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by shreyas-a-s** [comment]
From my investigation, it came into light that Noice, being an innocent guy, doesn't do anything particular with the highlights of notifications per se. He just takes notifications, hands it over to nvim-notify window and then nvim-notify takes over.

So then the person of interest became nvim-notify. He keeps some secrets to himself like the on_open option which we can modify like the one below so that you can get the desired behaviour out of him without hurting his ego.

```lua
  require("notify").setup({
    on_open = function()
      vim.cmd([[
        :nohlsearch
      ]])
    end,
  })
```
I hope this is the behaviour you expected.

**Comment by folke** [comment]
That way, hlsearch is cleared whenever a notification appears, which doesn't seem wanted.
For the nui and internal noice views, we solve this by overriding the `winhl`. See here:
https://github.com/folke/noice.nvim/blob/0cbe3f88d038320bdbda3c4c5c95f43a13c3aa12/lua/noice/config/views.lua#L159

Sometihng similar should be possible using nvim-notify in the on_open. Just set `vim.wo[the_win].winhighlight = ...`

**Comment by shreyas-a-s** [comment]
Thanks for letting mw know. You meant some thing like this, right?

```lua
require("notify").setup({
  on_open = function(win)
    vim.wo[win].winhighlight = "Normal:something..."
  end,
})
```

**Comment by folke** [comment]
These ones:

https://github.com/folke/noice.nvim/blob/0cbe3f88d038320bdbda3c4c5c95f43a13c3aa12/lua/noice/config/views.lua#L160-L162

But you need to concatenate them like you were doing

**Comment by shreyas-a-s** [comment]
@folke I know I'm very close but couldn't quite reach there yet. This is the code I currently have:
```lua
require("notify").setup({
  on_open = function(win)
    vim.wo[win].winhighlight = "IncSearch:'',CurSearch:'',Search:''"
  end,
})
```
It would be great if you could guide me a little it more to find the solution.

**Comment by folke** [comment]
Just remove the `''` from your winhl

**Comment by shreyas-a-s** [comment]
```lua
require("notify").setup({
  on_open = function(win)
    vim.wo[win].winhighlight = "IncSearch:,CurSearch:,Search:"
  end,
})
```
Like this right?

**Comment by kevinyyca** [comment]
It works as expected

**Comment by shreyas-a-s** [comment]
@kevinyyca Since we discussed a lot of different code in this thread could you share the code that worked for you?

**Comment by shreyas-a-s** [comment]
@kevinyyca Cool. @folke mentioned it was not the optimal version and I was trying to create a better version with his help. But if it works for you then what's the problem, right!
