### ISSUE TITLE
bug: Linter Spam Notification

### ISSUE THREAD

**Issue by AndreM222** [folke/noice.nvim#756]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

 0.9.5

### Operating system/version

Windows 11

### Describe the bug

The notifications from noice keep spaming when a linter is enabled with none-ls

### Steps To Reproduce

- Using lazy for package manager 
- Setup eslintd with none-ls
- move cursor around while programming

https://github.com/folke/noice.nvim/assets/98118238/275e2f58-caa3-4886-8688-a736e4042940

### Expected Behavior

Not spam the notification while moving around

### Repro

```Lua
    {
        "folke/noice.nvim", -- UI For Messages, CMDLine, and Popmenu
        event = "VeryLazy",
        dependencies = {
            "MunifTanjim/nui.nvim"
        },
        config = function()
            require("noice").setup({
                lsp = {
                    -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
                    override = {
                        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
                        ["vim.lsp.util.stylize_markdown"] = true,
                        ["cmp.entry.get_documentation"] = true,
                    },
                },
                -- you can enable a preset for easier configuration
                presets = {
                    bottom_search = false,        -- use a classic bottom cmdline for search
                    command_palette = true,       -- position the cmdline and popupmenu together
                    long_message_to_split = true, -- long messages will be sent to a split
                    inc_rename = false,           -- enables an input dialog for inc-rename.nvim
                    lsp_doc_border = true,        -- add a border to hover docs and signature help
                }
            })
        end
   },
{
        'nvimtools/none-ls.nvim', -- Linter and Formatting
        dependencies = 'nvimtools/none-ls-extras.nvim',
        config = function()
            local null_ls = require("null-ls")

            null_ls.setup({
                border = 'single',
                sources = {
                    -- Formatting
                    null_ls.builtins.formatting.prettier.with({
                        extra_args = function(params)
                            return params.options
                                and params.options.tabSize
                                and {
                                    "--tab-width",
                                    params.options.tabSize,
                                    "--trailing-comma",
                                    "none",
                                    "--no-semi",
                                    "--arrow-parens",
                                    "avoid",
                                    "--single-quote",
                                }
                        end,
                    }),
                    null_ls.builtins.formatting.clang_format.with({
                        extra_args = { "--style", "Microsoft" }
                    }),
                    require("none-ls.formatting.autopep8"),

                    -- Diagnostics
                    require("none-ls.code_actions.eslint_d").with({
                        diagnostics_format = '[eslint] #{m}\n(#{c})'
                    })
                }
            })
        end,
    },
```

**Comment by chalop** [comment]
I also had this issue. Over the noice setup config, setting the `lsp.progress.enabled` to `false` fixes it for me, but at the cost of losing all the lsp progress messages.

Would be nice to only filter out the `code_action null-ls` ones, any one has insights on this?

**Comment by crisidev** [comment]
I am able to prevent the spamming from null-ls with

```lua
progress = {
    format_done = {}
}
```

**Comment by AndreM222** [comment]
> I am able to prevent the spamming from null-ls with
> 
> ```lua
> progress = {
>     format_done = {}
> }
> ```

This is not really a solution. The message will pop but not spamming as before, just showing a black cube on the bottom right.

I do not want to close this until there is an actual way of fixing it.

Thanks though for the idea.

**Comment by crisidev** [comment]
Fair enough.. would my PR #791 solve your problem? I can reopen it and see what the author says..

**Comment by AndreM222** [comment]
> Fair enough.. would my PR #791 solve your problem? I can reopen it and see what the author says..

Might be a good idea. Though if people wanted to see if it was successful but not overload them with the same message I found this fix someone did for fidget which might come in handy. https://github.com/j-hui/fidget.nvim/pull/127

**Just giving ideas. I am still trying to think what might be best.**

` Though as well having a filtering feature could be pretty useful for unwanted stuff. `

**Comment by crisidev** [comment]
Nice.. I'll reopen my PR and try to implement both the disabled clients and a rate limiting based on how fidget does it.

**Comment by folke** [comment]
Check:
- https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#ignore-certain-lsp-servers-for-progress-messages
- https://github.com/folke/noice.nvim/issues/285#issuecomment-1595955253
