### ISSUE TITLE
bug: Statusline being duplicated when opening multiple files with nvim -p

### ISSUE THREAD

**Issue by rhs-rford** [folke/noice.nvim#775]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 commit 8744ee8

### Operating system/version

Debian 12

### Describe the bug

I'm using LazyVim, updated to current. When using nvim -p to open multiple files, on all tabs but the first file, the statusline is duplicated. Disabling the noice plugin fixes the problem. I even installed a fresh version of LazyVim on a fresh VM and had the same issue and disabling noice on that machine also fixed the problem.

First tab:
![image](https://github.com/folke/noice.nvim/assets/140105546/a599d361-ae90-4b8d-a82d-aaed31058a3b)
Second tab:
![image](https://github.com/folke/noice.nvim/assets/140105546/0927a437-6938-4d45-8c21-9c9878a3db5f)

### Steps To Reproduce

1. Run nvim -p _file1 file2_
2. Switch tabs to second file and the statusline will be duplicated

### Expected Behavior

Statusline should only be displaying once per tab.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by ParisTheProgrammer** [comment]
I also have this same issue, using LazyVim as well

**Comment by Sam-programs** [comment]
Here is a workaround:
```lua
vim.api.nvim_create_autocmd("TabEnter",{
	callback = function()
		vim.o.ch = 0
	end
})
```

**Comment by rhs-rford** [comment]
That fixed it. Thank you!

**Comment by Sam-programs** [comment]
This has been fixed in neovim https://github.com/neovim/neovim/pull/28522.
