### ISSUE TITLE
bug: Searching in oil.nvim with noice.nvim installed reveals hidden characters

### ISSUE THREAD

**Issue by rpop0** [folke/noice.nvim#794]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Debian 12

### Describe the bug

When searching with noice.nvim installed, certain hidden characters are revealed. This can easily be seen with the oil.nvim plugin
Search off:
![image](https://github.com/folke/noice.nvim/assets/38384209/face6597-5e7e-4536-9a29-1bc0364503e9)

Pressing /
![image](https://github.com/folke/noice.nvim/assets/38384209/18640d00-0e1b-41a0-be07-1ecdedf114ea)

### Steps To Reproduce

1. Install minimal config
2. Open nvim
3. Press - to open Oil
4. Press /

### Expected Behavior

No hidden characters should be shown.

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/noice.nvim",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    },
  },
  {
      'stevearc/oil.nvim',
      dependencies = {
          'nvim-tree/nvim-web-devicons'
      },
      config = function ()
          require('oil').setup()
          vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
      end

  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
vim.cmd([[colorscheme tokyonight]])
require("noice").setup()
```

**Comment by zmre** [comment]
Would love to see this reopened.  This is killing me. I can't figure out what Noice is doing to cause the IDs, which should be concealed, to show up.

**Comment by folke** [comment]
Install Neovim 0.10 or later.
In older versions I had to add a hack to work-around https://github.com/neovim/neovim/issues/17810

**Comment by zmre** [comment]
I'm on 0.10.4.  When I set `concealcursor`, the value I set seems to get cleared.  That said, I'm sorry I gave this a +1 without verifying that it was Noice's fault.  I just completely removed Noice and the problem is still happening for me, so something else is to blame.  Sorry for the noise.
