### ISSUE TITLE
Custom icons doesn't work

### ISSUE THREAD

**Issue by kaiphat** [folke/noice.nvim#8]
Reopen: https://github.com/folke/noice.nvim/issues/5

![image](https://user-images.githubusercontent.com/53742299/193621580-e4a1cc19-0f1e-41e5-90a1-35f2e7d2c4a3.png)

And there is first symbol `/` when i search
![image](https://user-images.githubusercontent.com/53742299/193621784-e5052d79-502c-4157-b8ca-31c1c96b59a3.png)

**Comment by folke** [comment]
your cmdline config should be under the main setup, not under the `views` key.

Now that I see it, it's definitely a bit confusing.

**Comment by gennaro-tedesco** [comment]
I am also having troubles getting the correct configuration grammar to work: in particular I am trying to configure options for `cmdline_popup` to remove the border and the description text (coincidentally the obtain the same look as in the screenshots above).  I am passing the options to `cmdline_popup` directly, although [the docs](https://github.com/folke/noice.nvim#-views) do mention this has to be done within the "views" table.
```
require("noice").setup({
	cmdline_popup = {
		border = { style = "none" },
		text = {
			top = "",
		},
	},
	routes = {
		{
			filter = { event = "msg_show", kind = { "search_count", "wmsg" } },
			opts = { skip = true },
		},
	},
	cmdline = {
		view = "cmdline_popup",
		opts = { buf_options = { filetype = "vim" } },
		icons = {
			["/"] = { icon = " ", hl_group = "DiagnosticWarn" },
                        ["?"] = { icon = " ", hl_group = "DiagnosticWarn" },
                        [":"] = { icon = " ", hl_group = "DiagnosticInfo", firstc = false },
		},
	},
})
```
Either way it seems neither work: am I trivially overlooking something?

**Comment by folke** [comment]
It should be:

```lua
require("noice").setup({
  views = {
    cmdline_popup = {
      border = { style = "none" },
      text = {
        top = "",
      },
      filter_options = {},
    },
  },
  routes = {
    {
      filter = { event = "msg_show", kind = { "search_count", "wmsg" } },
      opts = { skip = true },
    },
  },
  cmdline = {
    view = "cmdline_popup",
    opts = { buf_options = { filetype = "vim" } },
    icons = {
      ["/"] = { icon = " ", hl_group = "DiagnosticWarn" },
      ["?"] = { icon = " ", hl_group = "DiagnosticWarn" },
      [":"] = { icon = " ", hl_group = "DiagnosticInfo", firstc = false },
    },
  },
})

```

**Comment by folke** [comment]
Still need to add docs on `filter_options`

**Comment by folke** [comment]
I added an example at https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#clean-cmdline_popup

**Comment by kaiphat** [comment]
But icon for searching was changed with this configuration:) It's intresting. Thank you so much!
