### ISSUE TITLE
bug: QuickFixList with Filename after open

### ISSUE THREAD

**Issue by hoidOS** [folke/noice.nvim#802]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-7acf39d

### Operating system/version

MacOS

### Describe the bug

After the latest update, opening a file directly results in the appearance of a quickfix list at the bottom of the screen. The quickfix list contains a single line with the filename, and the cursor is positioned within this list.

### Steps To Reproduce

1. Open any file via the command line using `nvim init.lua`
2. Quickfixlist at the bottom of the screen buffername `nofile`

### Expected Behavior

The file should open normally without displaying a quickfix list.

**Comment by folke** [comment]
That;s not a quickfix list. Those are messages printed before noice was started.
Previously those messages were lost and would never show.

**Comment by hoidOS** [comment]
I see i am sorry i found the problem was with one of my autocmds. Thanks for the quick answer!
