### ISSUE TITLE
bug: Noice buffer appears calling `enable`

### ISSUE THREAD

**Issue by Rational-Curiosity** [folke/noice.nvim#804]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev commit 668b5fc15

### Operating system/version

Ubuntu 24.04

### Describe the bug

`:Noice enable` or `require('noice').enable()` opens noice buffer with messages when error messages

### Steps To Reproduce

1. Generate error message. Example `:echo err`
2. Disable Noice `:Noice disable`
3. Enable Noice `:Noice enable`
Then noice buffer appears with `E121: Undefined variable: err` 

### Expected Behavior

Noice buffer doesn't appear.

**Comment by folke** [comment]
Yes, when noice starts, it will load any previous `:messages` and show them so they dont get lost.

**Comment by Rational-Curiosity** [comment]
Thank you very much for the quick answer.

Please, consider don't display the noice buffer. I have to disable noice running macros
```lua
mapset("n", "Q", function()
  opt.lazyredraw = true
  local ok, noice = pcall(require, "noice")
  if ok then noice.disable() end
  vim.cmd([[
  syntax off
  noautocmd norm! ]] .. vim.v.count1 .. [[@q
  syntax on
  ]])
  if ok then noice.enable() end
  opt.lazyredraw = false
end)
```

because noice slows down macros a lot for example when macro search something.
Would it be possible for you to consider optionally don't display the buffer? May be with an option or parameter...

**Comment by folke** [comment]
Just changed it so that it only adds messages during the initial startup. Subsequent enables won't add the messages.

**Comment by Rational-Curiosity** [comment]
I really appreciate it. Thank you very much :smiley:
