### ISSUE TITLE
bug: Invalid 'event': 'SafeState'

### ISSUE THREAD

**Issue by Barmaley0** [folke/noice.nvim#805]
### Did you check docs and existing issues?

- [x] I have read all the noice.nvim docs
- [x] I have searched the existing issues of noice.nvim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 10

### Describe the bug

When starting Neovim it gives an error. So far I don’t see any problems, but they may arise. I’ll write as soon as they arise.
...l/nvim-data/lazy/noice.nvim/lua/noice/message/router.lua:36: Invalid 'event': 'SafeState'

### Steps To Reproduce

> nvim
at startup
![image](https://github.com/folke/noice.nvim/assets/133758633/5b31fdd1-1fde-4bf6-b8e8-1443db7ed787)

### Expected Behavior

There may be problems again

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by sajjathossain** [comment]
I'm getting the same issue

**Comment by thedevartisan** [comment]
Same, getting the same issue on Ubuntu 22.04.4 LTS in WSL 2

**Comment by qbnil** [comment]
Same here, was just about to submit the bug

**Comment by Barmaley0** [comment]
I got the update right away

**Comment by rofrol** [comment]
Pin to previous version for now

```lua
  {
    "folke/noice.nvim",
    tag = "v2.0.2",
  }
```

And do `:LazyUpdate`

**Comment by folke** [comment]
Sorry all. There's been a bunch of (good) changes on Neovim nightly to improve `vim.ui_attach`, but unfortunately that also means that some of my work-around no longer worked so I've been very busy fixing those things.

Apparently `SafeState` is a 0.10.0 only event. Didn't know...

The good news however that it no longer seems to be needed.

**Comment by thedevartisan** [comment]
> Sorry all. There's been a bunch of (good) changes on Neovim nightly to improve `vim.ui_attach`, but unfortunately that also means that some of my work-arounds no longer worked so I've been very busy fixing those things.
> 
> Apparently `SafeState` is a 0.10.0 only event. Didn't know...
> 
> The good news however that it no longer seems to be needed.

Thank you for reacting this issue so quickly!
