### ISSUE TITLE
feature:  Ability to toggle specific services

### ISSUE THREAD

**Issue by EdmundsEcho** [folke/noice.nvim#809]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

This is a great looking plugin.  The issue is how to turn it down.  I don't want all the noise, all the time.  Furthermore, there are many reasons to call a command to then study the output.  Something that cannot be done with a chip that only displays for a few seconds.

All in all, I really like this plugin.  However, it is mostly a distraction without the ability to turn things off without also having to figure out how to channel the information back to where the default has it.

Finally, my next step would be to thoroughly document how to customize the look and feel of the components.  Somehow  there needs to be a way to configure the high groups, the channels, the animations all in one config slot for each service (notify, cmd, messages etc. - I don't know all them).

### Describe the solution you'd like

xx

### Describe alternatives you've considered

xx

### Additional context

xx

**Comment by eyalk11** [comment]
Did you see `Noice Disable` ?

**Comment by EdmundsEcho** [comment]
I did try the Noice disable.  It seems to disable a lot of things.  I'm looking for a more fine-grained capability.

**Comment by folke** [comment]
You can already enable/disable multiple things. Check the readme
