### ISSUE TITLE
`vim.ui.*` functions

### ISSUE THREAD

**Issue by ranjithshegde** [folke/noice.nvim#82]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Since this plugin unifies so many components related to UIs, would you consider adding `vim.ui.*` support?

**Describe alternatives you've considered**
 There are already many plugins to address `vim.ui.input` and `vim.ui.select`. And `nui` also has some examples in its wiki to override `vim.ui.*` events. So, this is just a **one UI plugin/interface to rule them all** situation.

**Comment by folke** [comment]
I'll think about it!

**Comment by max397574** [comment]
@folke any updates on this?
especially `vim.ui.select` I don't really like right now

**Comment by folke** [comment]
I'm not going to add this in the short term. I use dressing.nvim myself and that works perfectly fine
