### ISSUE TITLE
bug: Cursor disappears after loading a session

### ISSUE THREAD

**Issue by i40west** [folke/noice.nvim#826]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

macOS 14.4.1

### Describe the bug

If Noice's `cmdline` view is enabled, and `sessionoptions` contains `options`, the `guicursor` setting is saved to a newly-created session with the value `a:NoiceHiddenCursor`.

This is pretty recent but I'm not sure exactly when.

### Steps To Reproduce

1. Using minimal `repro.lua`, open a file. ex `nvim -u repro.lua repro.lua`
2. `:mksession test.session`
3. The `test.session` file contains: `set guicursor=a:NoiceHiddenCursor`

### Expected Behavior

`guicursor` should be set to whatever I had it set to.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
      "folke/noice.nvim",
      dependencies = { "MunifTanjim/nui.nvim" },
      opts = {
          cmdline = {
              view = 'cmdline',
          },
      },
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.opt.sessionoptions:append("options")
```

**Comment by folke** [comment]
There's not really alot I can do about this.
You could create an `SessionLoadPost` autocmd and reset the cursor.

This issue will only happen when saving a session when the cmdline is open.

If you'd use a session plugin, then this wouldn't be an issue I think

**Comment by i40west** [comment]
Ok, thanks. I'm actually using `mini.sessions` but the problem still existed without it so I didn't include that in the minimal config. I'll use your workaround.
