### ISSUE TITLE
Make `nvim-notify` optional

### ISSUE THREAD

**Issue by clason** [folke/noice.nvim#83]
Now that the `mini` view is builtin which I personally find much less intrusive than the `nvim-notify` view, it would be great if the latter were no longer mandatory and only checked when the `notify` view is actually used.

(It might even make sense to make the `mini` view the default to have a more "standalone" out-of-the-box installation? Although I expect that most people will still prefer `notify`.)

**Comment by folke** [comment]
`nvim-notify` is no longer a hard dependency.

When not present, we use `mini` as a fallback. See the `fallback` key for the `notify` view.

I've also made it easier to configure default views for the default routes. Previously you had to override the routes with separate views.

For more details, see:
https://github.com/folke/noice.nvim#%EF%B8%8F-configuration
