### ISSUE TITLE
bug: no notification handler registered for "Dir" / "GUI"

### ISSUE THREAD

**Issue by kierun** [folke/noice.nvim#839]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-168+ge20c5fba2

### Operating system/version

Fedora 39.

### Describe the bug

When I open nvim, I get this warning. Then, I get a lot more. The "Dir" happens if I open nvim in termal, the "GUI" if I use nqim-qt.

### Steps To Reproduce

1. Open nvim. 

### Expected Behavior

No error is shown.

I suspect the handlers are missing either in the general configuration or mine. I could not reproduce it via the below repro configuration. Therefore, I suspect it is another of my plugins. However, I am not sure how best to debug it.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by kierun** [comment]
![screenshot](https://github.com/folke/noice.nvim/assets/3079575/ae7da6be-b0fd-48a8-9948-38eb2b6e1a5e)

**Comment by folke** [comment]
That's not noice. I don't show any errors like that.

**Comment by kierun** [comment]
How odd… My apologies. I was in the noice errors, so I thought it was. My bad.

**Comment by folke** [comment]
Well, Noice will capture and show all your errors wherever they happen, but that doesn't mean it's caused by noice...
