### ISSUE TITLE
Custom Lua command line

### ISSUE THREAD

**Issue by clason** [folke/noice.nvim#84]
A fun thing to do would be to check if the command line starts with `lua` and then
1. hide (conceal? `:sub` away?) the leading `lua `
2. turn on Lua syntax highlighting
3. show a special `☾` character as the prompt.

(By the way, is there any reason for the default `>_` prompt, which looks a bit off for me? I'd have expected something standard like `> `.)

**Comment by folke** [comment]
I [changed](https://github.com/folke/noice.nvim/commit/d203bff15450f88a63aee620852f1d98111f95c3) the default prompt in the meantime.

I actually implemented this idea and have it working locally, but it feels a bit weird tbh 😄

Will let you know once you can test it yourself. I'm probably not going to enable that by default.

**Comment by folke** [comment]
It is actually neat for `!` commands, since those can now have `ft=sh`.

`nvim-treesitter`, should probably add that as an injection for `vim`. Doesn't seem the case right now.

**Comment by clason** [comment]
> nvim-treesitter, should probably add that as an injection for vim. Doesn't seem the case right now.

PR welcome :) (If the parser supports it.)

**Comment by folke** [comment]
I just pushed the updates!

Example of `!...`
![image](https://user-images.githubusercontent.com/292349/196986946-c0afe6fb-ec9f-4ac4-a319-6d86e1f00634.png)

Example of `lua ...`
![image](https://user-images.githubusercontent.com/292349/196987086-78f9aa81-d12b-425e-af77-650e574c1463.png)

When the cursor is inside the concealed part, we show the full cmdline
![image](https://user-images.githubusercontent.com/292349/196987135-615790c1-5bf0-4bbb-b6b2-d4ec591aa662.png)

It's pretty easy to add custom cmdline formatters. See https://github.com/folke/noice.nvim#%EF%B8%8F-configuration

Exampe for `IncRename`:

![image](https://user-images.githubusercontent.com/292349/196989198-303eba25-01a0-4f09-856d-12bb323d5a3f.png)

```lua
	noice.setup({
		debug = false,
		cmdline = {
			format = {
				IncRename = {
					pattern = "^:%s*IncRename%s+",
					icon = " ",
					conceal = true,
					opts = {
						buf_options = { filetype = "text" },
					},
				},
			},
		},
         })
```

**Comment by clason** [comment]
Noice!

Random related suggestion: the `/` and `?` stand out a bit like a sore thumb now. Maybe conceal these as well and replace by a Unicode down and up arrow, respectively? (Either to the left or the right of the magnifier icon -- the former probably looks better.)

**Comment by wangl-cc** [comment]
Can we specify `kind_cc` manually? It's will be helpful to use same title and highlight for different cmdline, like search:
```lua
{
   search_down = {
     filter = '^/',
     icon = '',
     kind = 'Search',
   },
   search_up = {
     filter = '^?',
     icon = '',
     kind = 'Search',
   },
}
```

**Comment by folke** [comment]
Search now uses the `regex` ft. Make sure to install the treesitter parser to see it!

![image](https://user-images.githubusercontent.com/292349/197073619-1c5ce568-613c-4b6e-be1e-4ad999b9a198.png)

**Comment by max397574** [comment]
couldn't this be closed now?

**Comment by folke** [comment]
@max397574 yep! 

Unless @clason has more ideas 😉

**Comment by clason** [comment]
> Unless @clason has more ideas 😉

I do! `?` instead of `:h `
