### ISSUE TITLE
bug: inserting an automatic <CR> after easymotion

### ISSUE THREAD

**Issue by danielreis1** [folke/noice.nvim#840]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

windows 10, using alacrity and wsl

### Describe the bug

have the following simple mapping:
`vim.keymap.set({"n", "o"}, 'tt', "<Plug>(easymotion-sn)")`
I call it from normal mode
the problem is that an automatic <CR> (enter) is inserted right after I press enter on the easymotion, it's just on this easymotion, as far as I know, I have other easymotions where this isnt happening:
example:
`
vim.keymap.set({"n", "v", "o"}, "j", '0<Plug>(easymotion-j)')
vim.keymap.set({"n", "v", "o"}, "k", '0<Plug>(easymotion-k)')
`
doesnt have this problem

the culprit in my noice.vim config is:
`
messages = {
    enabled = true, -- enables the Noice messages UI
    view = "virtualtext",
    view_error = "messages", -- view for errors
    view_warn = "messages", -- view for warnings
    view_history = "messages", -- view for :messages
    view_search = false,
  },
`
I have tried changing all view types, and most different combinations:
example:
view = "notify",
view_error = "notify",
the problem is still there

the only way to fix this is to set enable = false in that part of the config, it should be simple enough problem to reproduce

### Steps To Reproduce

1.
set the following in your noice.vim config, on top of the default config
`messages = {
    enabled = true, -- enables the Noice messages UI
    view = "virtualtext",
    view_error = "messages", -- view for errors
    view_warn = "messages", -- view for warnings
    view_history = "messages", -- view for :messages
    view_search = false,
  },`
2. install easymotion
3. set keymap for this easymotion: `vim.keymap.set({"n", "o"}, 'tt', "<Plug>(easymotion-sn)")`
4. test

### Expected Behavior

an automatic <CR> (enter) appears, it's not supposed to appear, <CR>

**Comment by folke** [comment]
I don't use easy-motion and other plugins like flash.nvim, leap etc don't have these issues.
Noice also doesn't add any enters anywhere.
