### ISSUE TITLE
bug: using classic mode for cmdline still have completion window floating middle of the screen

### ISSUE THREAD

**Issue by dhruvinsh** [folke/noice.nvim#846]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 11.5

### Describe the bug

When command mode set to classic, completion floating appear middle of the screen.

<img width="1247" alt="image" src="https://github.com/folke/noice.nvim/assets/33428164/a5e7b700-e324-4495-89f6-add4b9dd2fe2">

### Steps To Reproduce

1. set `cmdline` view mode to `cmdline`
2. type any command and hit `tab`
3. completion will be in the floating window.

### Expected Behavior

Completion floating menu should have automatically appear bottom left corner where the command is.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/noice.nvim",
    opts = {
      cmdline = { view = "cmdline" }
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by b0ae989c** [comment]
This is not a bug. Your config does not work, since the dependency `MunifTanjim/nui.nvim` is missing. `noice` works as expected for Neovim v0.10.0 on macOS. Should close.

![Screenshot 2024-06-11 at 2 36 09 AM](https://github.com/folke/noice.nvim/assets/141280278/9b5b7381-cdd3-4434-aad0-e00b078a285a)
with the following config
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)
vim.opt.incsearch = false
local plugins = {
	"folke/tokyonight.nvim",
	{
		"folke/noice.nvim",
		dependencies = {
			"MunifTanjim/nui.nvim",
		},
		opts = {
			cmdline = { view = "cmdline" },
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
vim.cmd.colorscheme("tokyonight")
```

**Comment by dhruvinsh** [comment]
Thanks @b0ae989c for point it out. And my bad that I haven't provided proper reproducible config. In my main system I am using `Lazyvim`, so I am pretty sure that `nui` is present. And I do not see the same behaviour. I will get the bare reproducible config and report there since `noice` on its own work fine.
