### ISSUE TITLE
feature: priority of lsp progress

### ISSUE THREAD

**Issue by konosubakonoakua** [folke/noice.nvim#847]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

When I am browsing the lua code base, the lsp progress shows up very frequently, and the fzflua picker contents are blacked out by the lsp progress message.

### Describe the solution you'd like

So, can we have some something like 'z-index' to lower the priority of lsp progress message?

### Describe alternatives you've considered

disable lua lsp progress

**Comment by folke** [comment]
you can already configure that. check the win options in the views
