### ISSUE TITLE
It stops working on `showcmd` is routed to notify

### ISSUE THREAD

**Issue by lourenci** [folke/noice.nvim#85]
Thanks for the plugin.

As soon as a macro gets recorded, the plugin stops working. This wasn't an issue before. Ways to reproduce:
- `HEAD@main`
- route show mode to the notify route as per https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages
- Start to record a macro (e.g. `qq`)

**Comment by Shougo** [comment]
> As soon as a macro gets recorded, the plugin stops working

What do you mean?  Please provide more information.
I have tested it and it seems works.

**Comment by lourenci** [comment]
As soon as I hit `q{register}` to start recording a macro, I receive the following notifications (and the plugin stops working 😢):

<img width="489" alt="image" src="https://user-images.githubusercontent.com/2339362/196849636-cbada574-a1df-4b5e-ae86-50fa2ffc613a.png">

My noice setup:
```lua
require("noice").setup({
	routes = {
		-- show macro recording
		{
			view = "notify",
			filter = {event = "msg_showmode"},
		},
	},
	cmdline = {
		icons = {
		  ["/"] = {icon = "/"},
		  ["?"] = {icon = "?"},
		  [":"] = {icon = ">_"},
		},
	},
	lsp_progress = {
		enabled = true,
	},
	views = {
	  mini = {
		border = {
		  style = "single"
		},
	  },
	}
})
```
