### ISSUE TITLE
`mini` view and which-key

### ISSUE THREAD

**Issue by ranjithshegde** [folke/noice.nvim#86]
**Describe the bug**

I created [this](https://github.com/folke/which-key.nvim/issues/350) issue on `which-key` repo thinking its partially a which-key problem

Which key sends a message on every key press like this
![wk](https://user-images.githubusercontent.com/10258296/196880935-d8d6ffe2-a57e-4549-aee4-0ca2464570bc.png)

When using noice with `mini` view, it prints these msgs as `virt-text`, which lies on top of the which-key window itself

![noice](https://user-images.githubusercontent.com/10258296/196881224-ff0953ca-ebc4-420a-bbc0-2dae2cfab696.png)

I have exaggerated the example in the picture

**Which version of Neovim are you using?**

NVIM v0.9.0-dev-136-gfad558b6af
latest nightly

**To Reproduce**

1. Install noice & which-key
2. setup keymaps
3. Use `mini` view (default now if `nvim-notify` is not installed)
4. Press any key/s

**Expected Behavior**

Only which-key shows up/ or, I can filter out which-key messages

**Noice config**
```lua
            use {
            'folke/noice.nvim',
            config = function()
                require('noice').setup {
                    cmdline = { view = 'cmdline', view_search = 'cmdline' },
                }
            end,
            requires = 'MunifTanjim/nui.nvim',
        }
```

**Comment by ranjithshegde** [comment]
While digging into which-key codebase for `nvim_echo` calls, I just realized I can put `show_help = false` in the config that does reduce some of these messages.

Others like keypress messages are still displayed by `noice` & overlap with which-key window

**Comment by folke** [comment]
Yep, this is not really a bug tbh :)

Which-key, like other plugins uses nvim_echo. In Noice, you can decide what to do with it.

I still need to see how this can be improved.

**Comment by ranjithshegde** [comment]
> I still need to see how this can be improved.

Perhaps make key_press messages within which-key configurable the same as `show_help`?

**Comment by ranjithshegde** [comment]
> > I still need to see how this can be improved.
> 
> Perhaps make key_press messages within which-key configurable the same as `show_help`?

Just submitted a small PR to add that option in `which-key`. 

I guess then the main issue is the window-overlap. Not sure if it is even an issue or a matter of preference

**Comment by folke** [comment]
You can fix the overlap with properly configuring the zindex of the mini view. 

Closing this, since it's a config issue and you actually added a config option to whichkey as well to make this better. Thanks again for that :)

**Comment by ranjithshegde** [comment]
> You can fix the overlap with properly configuring the zindex of the mini view.

Thanks. I guess you mean `zindex` as passed to `nvim_open_win` config opts? 
I will dig deeper into how `mini` is handled, maybe I can add it to the wiki once I do!

> Closing this, since it's a config issue and you actually added a config option to whichkey as well to make this better. Thanks again for that :)

No problem. Love this plugin. Thanks for your amazing work and unbelievable efficiency! Will try to contribute PRs here once I have a bit more time to dive into the codebase
