### ISSUE TITLE
delete/change with a search show a lot of popups

### ISSUE THREAD

**Issue by seocamo** [folke/noice.nvim#87]
**Describe the bug**
if you do delete/change with any search ex. d/{ or c/{ you got a lot of notifications with the search register so /{ in this example
i do got a popup with a text about a loop detect but the other popups move it out of view fast i don't know what it is saying

**Which version of Neovim are you using?**
Nightly
NVIM v0.9.0-dev-101-g9cb2a6903
Build type: RelWithDebInfo

**To Reproduce**
1. open a file nvim with the plugin install
2. make a delete search ex. d/{
3. see the popups for a few mins.

**Expected Behavior**
no or just 1 popup with the search register

**Noice Log**

<details>
<summary>Noice log</summary>
<pre>
no text in the log...
</pre>
</details>

**Messages**
fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

E37: No write since last change
E162: No write since last change for buffer "noice://63/notify?filetype=notify"
fatal: not a git repository (or any of the parent directories): .git

**Comment by folke** [comment]
Can't reproduce this. Can you check with the latest version?

If you still have this problem, then please create a minimal.lua https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue

**Comment by seocamo** [comment]
yes this is not a problem after rebuild neovim and packersync
