### ISSUE TITLE
bug: Getting E445: Other window contains changes while closing diffview

### ISSUE THREAD

**Issue by Sunil-Chauhan** [folke/noice.nvim#871]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Linux

### Describe the bug

I'm getting this error E445: Other window contains changes while using :DiffViewClose from diffview plugin.
It looks it is not an issue from diffview: https://github.com/sindrets/diffview.nvim/issues/302

### Steps To Reproduce

Use the sindrets/diffview.nvim plugin.
1. Open diffview with :DiffViewOpen
2. Close diffview with :DiffViewClose

### Expected Behavior

Should get this error.
Error executing Lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(tabclose):E445: Other window contains changes

**Comment by folke** [comment]
How is this a Noice issue??

**Comment by Sunil-Chauhan** [comment]
Closing the diffview works as expected when disabling the noice.
