### ISSUE TITLE
bug: Weird Behavior using Noice

### ISSUE THREAD

**Issue by ashton** [folke/noice.nvim#880]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0 LuaJIT 2.1.1716656478

### Operating system/version

MacOS 13.6.7

### Describe the bug

Sometimes I get a weird message of `Not enough room` just using nvim normally

![image](https://github.com/folke/noice.nvim/assets/95974/6fc0284a-773d-401f-a133-6076ad518eed)

When I took this screenshot, the fact of opening the command bar and typing `:Noic` was enough to generate this message.

### Steps To Reproduce

- I have no idea, as I mentioned, just typing `:` to open the command bar and then typing `Noic` was enough to make it happen, several times.

### Expected Behavior

Not show this message randomly

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/noice.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by b0ae989c** [comment]
Can not reproduce. Please provide a minimal repro config where this issue appears.

E36 is related to invalid window size.

**Comment by folke** [comment]
Never seen this error, so 100% your config. Closing

**Comment by ashton** [comment]
@b0ae989c I understand but even I don't know how to reproduce it exactly, it's an error that happens sometimes and doesn't have a regular trigger. :( Is there a chance to be something related to using small terminal windows? I use Iterm2 with "splits" in a reduced window

![image](https://github.com/folke/noice.nvim/assets/95974/c3ea5f75-d0a2-4189-8a6f-27c0098ad4e4)

**Comment by ashton** [comment]
@folke as I commented above, I understand you closing the issue, and I know is probably related to my config, I'm just trying to get help on some clues or some direction where can I start debugging this, or start the troubleshooting from, I love using Noice but this error is pretty annoying and I'm totally lost :(

**Comment by folke** [comment]
I have no idea, sorry
