### ISSUE TITLE
lsp progress causing memory leak

### ISSUE THREAD

**Issue by quantum-booty** [folke/noice.nvim#89]
With lsp_progress enabled:
![image](https://user-images.githubusercontent.com/28958399/197062096-93d7d883-dc8c-49b5-bd68-bfd3fd2c7e53.png)
After I exit neovim, it leaves this error in my terminal:
...m/site/pack/packer/opt/noice.nvim/lua/noice/view/nui.lua:146: Failed to delete line%   

With lsp_progress disabled:
![image](https://user-images.githubusercontent.com/28958399/197062454-e0297076-119a-402d-b9f0-ceed73e795c3.png)

**Comment by folke** [comment]
Damn, good catch!!

The problem was that we keep re-rendering the same buffer, and as such keep creating new extmarks. The old extmarks weren't cleared.

The fix clears the extmarks before rendering the new ones.
