### ISSUE TITLE
bug (likely neovim upstream): noice.nvim causes `vim.on_key` to not trigger on count

### ISSUE THREAD

**Issue by thunder-coding** [folke/noice.nvim#906]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Arch Linux (all packages up to date)

### Describe the bug

Noice.nvim partially breaks `vim.on_key` and causes it to not recieve the count key.

### Steps To Reproduce

1. Use the below config (tested on both my machine as well as VM, both Arch Linux)
2. Press some number and other keys keys
3. Number keys don't show up, but other letters and symbols do.

### Expected Behavior

noice should not break `vim.on_key`

Also this is very likely a NeoVim bug but I decided to report it here first as folke as the author of this plugin must have a better idea of what NeoVim API when used here is breaking `vim.on_key`

### Repro

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	spec = {
		{
			"folke/noice.nvim",
			event = "VeryLazy",
			opts = {
				-- add any options here
			},
			dependencies = {
				-- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
				"MunifTanjim/nui.nvim",
				-- OPTIONAL:
				--   `nvim-notify` is only needed, if you want to use the notification view.
				--   If not available, we use `mini` as the fallback
				"rcarriga/nvim-notify",
			},
		},
	},
})

local keylogger_ns = vim.api.nvim_create_namespace("keylogger")

vim.on_key(function(key, typed)
	vim.print(typed)
end, keylogger_ns)
```

**Comment by folke** [comment]
![image](https://github.com/user-attachments/assets/8216e301-3172-49c0-9a5a-07baeb106477)

```lua
local keylogger_ns = vim.api.nvim_create_namespace("keylogger")
local keys = {}
vim.on_key(function(key, typed)
  table.insert(keys, vim.fn.keytrans(typed))
  vim.notify(vim.inspect(keys))
end, keylogger_ns)
```

IT does work, but noice receives a cmd clear or cmd clear last and that hides the last print.
Not a Neovim, nor Noice bug.

**Comment by folke** [comment]
Reason is that if you type a number, NEovim waits (since it could be a count).
It only sends the number on next character, so together with the next character.

**Comment by thunder-coding** [comment]
> Reason is that if you type a number, NEovim waits (since it could be a count).
It only sends the number on next character, so together with the next character.

No, it doesn't (atleast by according to the documentation). It should trigger for every key pressed and also see https://github.com/neovim/neovim/issues/15527. 

Disabling noice and using the same init.lua as your suggested one printing the table, I am able to see number keys as soon as they are pressed without any other key. Noice.nvim is either calling a nvim function or setting a vim option which is likely triggering a bug in NeoVim, which is making it wait for another key to be pressed after the number.

**Comment by folke** [comment]
You're right. Just add a redraw and you'll see them

```lua
local keylogger_ns = vim.api.nvim_create_namespace("keylogger")
local keys = {}
vim.on_key(function(key, typed)
  table.insert(keys, vim.fn.keytrans(typed))
  vim.notify(vim.inspect(keys))
  vim.cmd.redraw()
end, keylogger_ns)
```

**Comment by folke** [comment]
The reason you see them right away without noice,
is because that would use the builtin notify, which is just an echo.
nvim-notify creates windows etc and those would only be displayed when doing a redraw.

Neovim automatically does redraws, but sometimes waits for a certain state to do it.

Adding the redraw like I did forces a redraw at that point.

So again, all pretty much how it's supposed to behave.

**Comment by thunder-coding** [comment]
Thanks! Didnt think that way! And sorry for the dubious and dumb bug report
