### ISSUE TITLE
bug: loop or previous error loading module

### ISSUE THREAD

**Issue by TM10YMhp** [folke/noice.nvim#910]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 10

### Describe the bug

When require the modules “cmp.entry” and “cmp.utils.api” the error “loop or previous error loading module” occurs, when trying to find the error I discovered that inside package.preload[module] at https://github.com/folke/noice.nvim/blob/1df01e495b3ac0e2f5f111eba759691a9c21bb72/lua/noice/util/hacks.lua#L170-L181 package.loaded[module] has the value of -5.6817549271743e-322, I don't know why it takes that value, for now setting the value to nil solves the problem.

```lua
   package.preload[module] = function() 
      -- print(package.loaded[module]) -- -5.6817549271743e-322
      -- FIX: loop and previous error
     package.loaded[module] = nil
     package.preload[module] = nil 
     for _, loader in pairs(package.loaders) do 
       local ret = loader(module) 
       if type(ret) == "function" then 
         local mod = ret() 
         fn(mod) 
         return mod 
       end 
     end 
   end 
 end 
```

### Steps To Reproduce

1. Run `:lua require("cmp.utils.api")` or `:lua require("cmp.entry")`

### Expected Behavior

prevent error “loop or previous error loading module”

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(
  vim.fn.system(
    "curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"
  )
)()

require("lazy.minit").repro({
  defaults = { lazy = true },
  spec = {
    {
      "folke/noice.nvim",
      event = "VeryLazy",
      opts = {},
    },
    {
      "hrsh7th/nvim-cmp",
      event = "InsertEnter",
      opts = {},
    },
  },
})

vim.defer_fn(function()
  vim.print(require("cmp.utils.api"))
  vim.schedule(function()
    vim.cmd("NoiceErrors")
  end)
end, 100)
```

**Comment by folke** [comment]
This was actually a bug in `lazy.nvim`, so make sure to update that as well.
I've also made some changes to the noice code, but those are more optimizations and won't necessarily have an impact on your use-case

**Comment by folke** [comment]
I had to revert that lazy.nvim change since it broke cmp for some reason.
Need to further look into this.

**Comment by folke** [comment]
Should be properly fixed now in both lazy.nvim and noice.nvim

**Comment by juniorsaldanha** [comment]
I've faced this issue right now, on a fresh arch linux, with a fresh startup config, only options.lua file, and a lazy.lua file.


![Screenshot_2024-10-06-03-50-27_14472](https://github.com/user-attachments/assets/c8d4ebc9-c743-41a5-8c7a-ea3c306de0c1)
