### ISSUE TITLE
bug: lag while typing %s command in cmdline

### ISSUE THREAD

**Issue by tednaaa** [folke/noice.nvim#911]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

Getting lags while typing `%s/some_text/{from_there}`

### Steps To Reproduce

> With noice cmdline

https://github.com/user-attachments/assets/ad593533-16c2-4490-a057-37747dda7ff1

> Without it

https://github.com/user-attachments/assets/c4208907-8dfe-478f-8fdb-03242860a654

### Expected Behavior

typing without lags

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
"folke/noice.nvim",
  event = "VeryLazy",
  dependencies = { "MunifTanjim/nui.nvim" },
  config = function()
    require("noice").setup({
      lsp = {
        override = {
          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
          ["vim.lsp.util.stylize_markdown"] = true,
          ["cmp.entry.get_documentation"] = true,
        },
      },
      presets = { command_palette = true, lsp_doc_border = true },
    })
  end,
},
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
First of all your videos look pretty much identical to me, so this is already a very minor thing.
Noice needs to do redraws to ensure the cmdline gets rendered. Otherwise you wouldn't see what you're typing.

**Comment by tednaaa** [comment]
so it can't be fixed or I do something wrong?

I tried changing the throttle setting and it flashes much less frequently, but I don't think it's solution

**Comment by folke** [comment]
All you can try i making sure you're using an up to date nightly.
Nothing much I can do about this. So can't fix,
