### ISSUE TITLE
bug(vim-visual-multi): Notification window doesn't expand or have black color

### ISSUE THREAD

**Issue by ilias777** [folke/noice.nvim#913]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-219+gc37695a5d-Homebrew

### Operating system/version

MacOS 14.5

### Describe the bug

The notifications that comes from vim-visual-multi are not expand if `stages = 'slide'` in the notify options and it's not possible to see the content.

<img width="1462" alt="slide_1" src="https://github.com/user-attachments/assets/7da8f817-6521-4077-a5bc-d1d53d11a357">
<img width="1462" alt="slide_2" src="https://github.com/user-attachments/assets/825765d5-b5e9-496f-9bc6-35ef9a970e29">

If `slides` is set to `fade` the color is black or sometime the same color as the background.

<img width="1462" alt="black_1" src="https://github.com/user-attachments/assets/0ae3ee1b-3fbe-4644-91e9-3645bff5ef6b">
<img width="1462" alt="black_2" src="https://github.com/user-attachments/assets/a9cc394e-6df6-453c-bfd3-480b45da0610">

If you look here closely the notification color is same as the background. After the `l` in the second line you can see the icon from the notification:
<img width="1462" alt="same_as_bg" src="https://github.com/user-attachments/assets/4eb2e800-faa2-493a-b60f-8dd839e819e8">

### Steps To Reproduce

1. Run: `nvim -u repro.lua`.
2. After lazy installing the plugins open the file with the command `:e repro.lua`.
3. Press following keys: `<C-n>` to start vim-visual-multi and then the keys: `\\C` to open the notification window to switch the case in this example.
4. You will see that the notification window is not expanding.
5. Try to change the `stages` to `fade` or `fade_in_slide_out`.
6. Press the same keys like in step 3.
7. The notification window now is black or the same color as the background.

### Expected Behavior

The notification window opens full as expected or they have the expected color.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

vim.g.mapleader = ','
vim.g.maplocalleader = ','

vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true

require("lazy.minit").repro({
    spec = {
        {
            'nvim-treesitter/nvim-treesitter',
            build = ':TSUpdate',
            config = function()
                require('nvim-treesitter.configs').setup({
                    ensure_installed = {
                        'lua'
                    },
                })
            end
        },
        {
	    "mg979/vim-visual-multi",
            branch = "master",
            event = 'VeryLazy',
		    keys = {
                      { 'cp', 'vip<Plug>(VM-Visual-Cursors)', desc = 'Create multicursors inner paragraph' },
                      { '<M-s>', ':VMSearch ', mode = 'x', desc = 'Search & create multicursors in visual mode' },
                      { '<M-s>', ':%VMSearch ', desc = 'Search & create multicursors' },
                      { '<M-c>', '<Plug>(VM-Visual-Cursors)', mode = 'x', desc = 'Create multicursors in visual mode' },
		    },
            init = function()
                vim.g.VM_maps = {
                    ['Motion ,'] = '',
                    ['Select l'] = '<C-Right>',
                    ['Select h'] = '<C-Left>',
                    ['Goto Next'] = '',
                    ['Goto Prev'] = '',
                    -- ['I BS'] = '',
                }
            end
	    },
	    {
            "folke/which-key.nvim",
            opts = {
                preset = 'helix',
            },
        },
            {
            "folke/noice.nvim",
            dependencies = {
                "MunifTanjim/nui.nvim",
                {
                    "rcarriga/nvim-notify",
                    opts = {
                        render = 'wrapped-compact',
                        stages = 'slide,
                        max_height = function()
                            return math.floor(vim.o.lines * 0.75)
                        end,
                        max_width = function()
                            return math.floor(vim.o.columns * 0.75)
                        end,
                    },
                },
            },
            opts = {}
        },
    },
})
```

**Comment by folke** [comment]
That's not noice?
You even specify it's an option to nvim-notify?

**Comment by ilias777** [comment]
I thought that was an noice issue, because noice uses nvim-notify.
Ok I try to set this issue in nvim-notify.

Sorry for the "noice" 😅

**Comment by folke** [comment]
After further looking into this, this is indeed something that worked before.
Reason it used to work, is that in Noice I [hacked](https://github.com/folke/noice.nvim/commit/5e55d0d46f672077f6ae0b69f4f6dfeb63b9ea33) into `vim.cmd.redraw` and any of the `getchar` and `input` functions.
When I detected that we were right before or inside such a function, I replaced stage to `static`.

I did it like that, because I thought that when Neovim was waiting for input, the main loop was blocked.

Recently I discovered this is simply not the case.

tbh, this hack was something I probably never should have done.

The correct fix is to add `vim.cmd.redraw()` calls when needed inside `nvim-notify`.

**Comment by ilias777** [comment]
Do you know maybe if it's possible to send these notifications to [dressing.nvim](https://github.com/stevearc/dressing.nvim) and skip `nvim-notify` notification for that specific case? I read the dressing docs, but I didn't find something that I can use for `vim-visual-multi`.

The only solution that I found and it's working, is to complete disable `Noice` if `vim-visual-multi` is running with this autocommand:

```lua
local visual_multi_group = vim.api.nvim_create_augroup('VisualMulti', { clear = true })
vim.api.nvim_create_autocmd('User', {
    pattern = 'visual_multi_start',
    callback = function()
        vim.cmd('NoiceDisable')
        vim.lsp.inlay_hint.enable(false)
    end,
    group = visual_multi_group,
})
vim.api.nvim_create_autocmd('User', {
    pattern = 'visual_multi_exit',
    callback = function()
        vim.cmd('NoiceEnable')
        vim.lsp.inlay_hint.enable(true)
    end,
    group = visual_multi_group,
})
```

Can I do something with `vim.cmd.redraw()`, maybe with this autocommand, or has this to be fix on `nvim-notify` side?

**Comment by folke** [comment]
In LAzyVim I just always use `opts.stages = 'static'` for nvim-notify

**Comment by ilias777** [comment]
I tested with `static` and it works for me as well now, but no with the other ones.
Thank you.
