### ISSUE TITLE
proposal: selection/filewise format filter

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/noice.nvim#92]
The work on [#84](https://github.com/folke/noice.nvim/issues/84) opens so many customisation possibilities! For instance the original `!` filter does not include file-wide (`%!`) or visual selections, so I tinkered with the modified versions
```
...
  fshell = { pattern = "^:%s*%%%s*!", icon = " $", ft = "sh"},
  vshell = { pattern = "^:%s*%'<,%'>%s*!", icon = " $", ft = "sh"},
...
```
I wanted to ask if you'd like to include them in your examples; however, they may be too niche of cases and may be clutter the README/Wiki. So, instead, what do you think about opening a [show-and-tell](https://github.com/folke/noice.nvim/discussions/categories/show-and-tell) discussion section where people could start showing their own customisations and looks? It will also help you on the long run getting rid of the _"how do I make X?"_ issues opened by users who at some point can be just redirected to the showroom section and copy&paste most of the grammar they need.

**Comment by folke** [comment]
Great idea. Go for it!

**Comment by gennaro-tedesco** [comment]
I started and included the examples [here](https://github.com/folke/noice.nvim/discussions/94) :)
