### ISSUE TITLE
bug: No macro ui

### ISSUE THREAD

**Issue by realhackcraft** [folke/noice.nvim#922]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 15.0 beta 4

### Describe the bug

There is no ui for macro recording.

### Steps To Reproduce

1. press `q`, then a letter in normal mode to record macro
2. there is no indicator when recording a macro that you are recording it

https://github.com/user-attachments/assets/ca87b7bb-67a0-47c4-9449-f8e6a91a992c

### Expected Behavior

An indicator somewhere, maybe bottom left or in a notify.nvim bubble to tell the user that they are recording a macro.

https://github.com/user-attachments/assets/a4c61021-014e-444e-86b1-6fe7cf755377

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by b0ae989c** [comment]
This is not a bug. `noice` does not monitor macro recording. Should close.

If you'd like a message when a macro recording begins, set up autocmd with `RecordingEnter`.

**Comment by realhackcraft** [comment]
Even if it doesn't, the macro recording indicator should be present.

**Comment by miron2363** [comment]
You can add this to your noice.lua
```lua
vim.api.nvim_create_autocmd("RecordingEnter", {
  callback = function()
    local msg = string.format("Register:  %s", vim.fn.reg_recording())
    _MACRO_RECORDING_STATUS = true
    vim.notify(msg, vim.log.levels.INFO, {
      title = "Macro Recording",
      keep = function() return _MACRO_RECORDING_STATUS end,
    })
  end,
  group = vim.api.nvim_create_augroup("NoiceMacroNotfication", {clear = true})
})

vim.api.nvim_create_autocmd("RecordingLeave", {
  callback = function()
    _MACRO_RECORDING_STATUS = false
    vim.notify("Success!", vim.log.levels.INFO, {
      title = "Macro Recording End",
      timeout = 2000,
    })
  end,
  group = vim.api.nvim_create_augroup("NoiceMacroNotficationDismiss", {clear = true})
})

```
