### ISSUE TITLE
bug: signature_help covers the current line

### ISSUE THREAD

**Issue by s1n7ax** [folke/noice.nvim#930]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-nightly+b991319

### Operating system/version

NixOS

### Describe the bug

I have noticed this issue for a quite some time on LazyVim. I don't use any custom configuration for noice.nvim.

When filling parameters, signature_help is being automatically triggered and the popup covers the current line in Normal mode and in insert mode.

I can recreate this behavior with
- `vim.lsp.buf.hover()`
- `vim.lsp.buf.signature_help()`
- inserting params

https://github.com/user-attachments/assets/9814a7c6-4697-43ff-813d-9ffb0f6b080b

After disabling Noice.nvim, the popup is displayed correctly.

![image](https://github.com/user-attachments/assets/4e3868ea-60ab-4ea5-abbc-3ac34068a89b)

I can see people have had the same issue, but solutions suggests to disable the feature.
https://www.reddit.com/r/neovim/comments/ymdb5u/comment/iyhnxgy/?context=3
https://www.reddit.com/r/neovim/comments/12i9a3o/how_to_avoid_popup_covering_cursor_in_insert_mode/

### Steps To Reproduce

1. Open a lua file
2. Use a function that has a big documentation

### Expected Behavior

Pop up should be opened without covering the current line. Overflow should be scrollable.

**Comment by max397574** [comment]
I guess you could really just disable the functionality since something really similar (exactly the same?) is done in core now anyways.

If you don't want that you should try to create a minimal repro.

**Comment by s1n7ax** [comment]
@max397574 Disabling hover and signature also removes it being auto triggered. There is some more highlights available in noice.nvim compared to the native. Mostly I miss auto trigger.

**Comment by max397574** [comment]
simply create an autocmd for it
```lua
vim.api.nvim_create_autocmd({ "TextChangedI", "TextChangedP", "InsertEnter" },{
  callback=function()
    vim.lsp.buf.signature_help()  
  end
})
```

**Comment by dpetka2001** [comment]
You could just set the `max_height` of the message to be proportional to the window height. Something like
```lua
{
  "folke/noice.nvim",
  opts = {
    lsp = {
      signature = {
        opts = {
          size = {
            max_height = vim.api.nvim_win_get_height(0) / 2,
          },
        },
      },
    },

  }
}
```
should work I believe.

**Comment by EricDriussi** [comment]
Hi there! I would also rather keep using noice for consistency with the rest of the UI.

Unfortunately the code from the comment above produces an error (Number is not an integer) and even if it did work it wouldn't break as soon as the split or window is resized. Plus this happens with width as well.

It seems to me that it might have something to do with positioning. For example even if it does fit in the window as a whole, as soon as it overflows the split it gets bumped to the top of the window.

![image](https://github.com/user-attachments/assets/13f25e0a-3ff4-4a80-a0b8-00ece1d68434)

**Comment by madflow** [comment]
This is still an issue

**Comment by gaussfff** [comment]
This is still an issue

**Comment by smzm** [comment]
After a year... still an issue

**Comment by yorik1984** [comment]
Its not a bug.
See my config
```lua
opts = {
    ...
    lsp = {
        signature = {
            view = "hover",
        }
    },
    ...
    views = {
        hover = {
            size = {
                width = "auto",
                height = "auto",
                max_height = math.floor(vim.api.nvim_win_get_height(0) * 0.5) - 2, -- <- THIS matter
                max_width  = math.floor(vim.api.nvim_win_get_width(0) * 0.6),
            },
        }
    }
}
```

**Comment by EricDriussi** [comment]
> Its not a bug. See my config
> 
> opts = {
>     ...
>     lsp = {
>         signature = {
>             view = "hover",
>         }
>     },
>     ...
>     views = {
>         hover = {
>             size = {
>                 width = "auto",
>                 height = "auto",
>                 max_height = math.floor(vim.api.nvim_win_get_height(0) * 0.5) - 2, -- <- THIS matter
>                 max_width  = math.floor(vim.api.nvim_win_get_width(0) * 0.6),
>             },
>         }
>     }
> }

Yay! This does the job!
For some reason doing exactly the same but following @dpetka2001 suggested structure didn't seem to do anything.
So putting the config inside `opts.views.[VIEW].size` instead of `opts.lsp.signature.opts.size` does seem to work for me, I'm guessing I didn't understand the docs.

Thanks a lot!
