### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by MinaMatta98** [folke/noice.nvim#933]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Arch Linux x86_64 Kernel: 6.6.40-rt36-x64v2-1-xanmod1-rt

### Describe the bug

Sometimes, the dap ui would be paused as it's waiting for user input:

This is it blocking on wait:
![image](https://github.com/user-attachments/assets/7089b435-73b5-41e9-89e9-a0f74f84d322)

This is after hitting escape:
![image](https://github.com/user-attachments/assets/7cb361b0-aae0-442e-a22c-8d9d20fc8aeb)

Realize that the options became clear.

I have noted issue #674 , but this pause also occurs if I do something as simple as a file rename. This will cause the screen to block as noice is awaiting input.

My lua dotfile for this setup is available here: https://github.com/MinaMatta98/Neovim-Revamped-Dotfiles/blob/master/lua/plugins/ui/noice.lua

### Steps To Reproduce

1. lua require("dap").continue() <--- This will always trigger it
2. File rename

### Expected Behavior

The event will not block the loading of the UI and I would be capable of selecting from the options in the attached images 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by freezlite** [comment]
Same problem, I don't see dap ui select menu, everything blocked, it waits until I pick something

**Comment by freezlite** [comment]
It seems related https://github.com/folke/noice.nvim/issues/938 installing dressing plugin fixed problem
