### ISSUE TITLE
bug: Notifications seems block `ui.select`

### ISSUE THREAD

**Issue by ragu-manjegowda** [folke/noice.nvim#938]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Arch Linux

### Describe the bug

When there is notification, `ui.select` seems to be blocked from being shown. Hitting escape/q makes it visible and disappear without taking any input.

Issue appears with both `nvim-notify` and `mini` 
Issue appears with `notify.replace = true` 

### Steps To Reproduce

1. Open nvim with provided `repro.lua`
2. Use keymap to trigger notification followed by `ui.select`

### Expected Behavior

Destroy the notification or move it down and let ui.select come to foreground and accept user input.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        {
            "folke/noice.nvim",
            config = true,
            event = "VeryLazy",
            dependencies = {
                "MunifTanjim/nui.nvim",
                -- "rcarriga/nvim-notify",
            }
        }
    }
})

local function get_selection(choices, selection_opts)
    local co = coroutine.running()
    local selection_made = false
    local selected_choice = nil

    vim.schedule(function()
        vim.ui.select(choices, selection_opts, function(choice)
            selection_made = true
            selected_choice = choice
            if co then
                coroutine.resume(co)
            end
        end)
    end)

    if co and not selection_made then
        coroutine.yield()
    end
    return selected_choice
end

local function test_input()
    vim.notify("Send notification")
    local os_choices = {
        "Linux",
        "macOS",
        "Windows",
    }

    get_selection(os_choices, {
        prompt = ("Choose remote OS (found OS '%s'): "):format(os),
        format_item = function(item)
            return ("Remote host is running %s"):format(item)
        end,
    })
end

vim.g.mapleader = " "

vim.api.nvim_set_keymap('n', '<leader>t', '', {
    noremap = true,
    callback = test_input
})
```

**Comment by Vladmel1234** [comment]
I have the same issue,
The workaround of downgrading to 4.4.7 also worked for this issue.

**Comment by gbelouze** [comment]
Downgrading did not solve this for me. However hacking into `vim.ui.select`, for instance by installing [telescope-ui-select.nvim](https://github.com/nvim-telescope/telescope-ui-select.nvim), did it.

**Comment by zayihu** [comment]
+1, installed dressing.nvim to fix this behavior, disabled input, only need vim.ui.select

**Comment by nicholascross** [comment]
This is still an issue.  Confirming work around of using dressing.nvim (defaulting to telescope) for selection worked well for me.

**Comment by dapetcu21** [comment]
This is an issue, yes. It seems to be because `ui.select()` seems to want synchroneous user input, so nvim-notify only gets the chance to render the first frame of the notification animation. As a workaround, I modified the default animation to skip the fade-in animation, which I actually seem to prefer.

As a more permanent fix, I think we need a better UI for selections instead of relying on nvim-notify.

https://github.com/dapetcu21/nvim-notify/tree/slide-out

```lua
{
    "dapetcu21/nvim-notify",
    branch = "slide-out",

    config = function ()
      local notify = require("notify")

      notify.setup({
        render = "wrapped-compact",
        stages = "slide_out", -- <==== This is the workaround
      })
      vim.notify = notify
    end,
  },
  ```

**Comment by Jay-Madden** [comment]
I am also facing this issue. Installing [telescope-ui-select](https://github.com/nvim-telescope/telescope-ui-select.nvim) allowed me to get around this.

**Comment by miguno** [comment]
+1, still an issue. Code actions are shown in notifications and therefore cannot be selected.

**Comment by dvnatanael** [comment]
This issue still persists in 4.6.0 when using nvim-notify (uncommented the dependency in the above repro).

I am on nvim v0.10.0 and Windows 11.

**Comment by ramrom** [comment]
tested 4..60 on nvim 0.10.0 on ubuntu and osx.
still seeing this issue as well.

**Comment by northgreen** [comment]
I naively thought that abducting `vim.ui.select` and put `opts.kind` to non-nil value (`idx` or `items`) will fix the problem,such as
```lua
local us = vim.ui.select

function vim.ui.select(items, opts, on_choice)
    if not opts.kind then
        opts.kind = 'idx'
    end
    us(items, opts, on_choice)
end
```
But I found that this didn't work :(
So I overwrite the function with `Nui` and ignored `opts.kind`,I think it will be helpful:
```lua
---@diagnostic disable-next-line duplicate-field
function vim.ui.select(items, opts, on_choice)
    opts = opts or {}

	--process the opt
    local prompt = vim.F.if_nil(opts.prompt, "Select one of")
    if prompt:sub(-1, -1) == ":" then prompt = prompt:sub(1, -2) end
    opts.format_item = vim.F.if_nil(opts.format_item,
                                    function(e) return tostring(e) end)
    on_choice = vim.schedule_wrap(on_choice)

    local Menu = require("nui.menu")

    local line = {}
    for _, value in ipairs(items) do
        local it = opts.format_item(value)
        table.insert(line, Menu.item(it, {v = value}))
    end

	--dynamicaly calculate the height of the popup window
    local win_h = vim.api.nvim_win_get_height(0)
	---@type integer|string
    local h = '50%'
    if #line < win_h / 2 then
		h = #line
	end

    local popup_options = {
        relative = "editor",
        position = {row = "50%", col = "50%"},
        size = {width = '50%', height = h},
        border = {
            style = "rounded",
            text = {top = prompt, top_align = "center"}
        },
        win_options = {winhighlight = "Normal:Normal"}
    }

    local menu = Menu(popup_options, {
        lines = line,
        max_width = 20,
        keymap = {
            focus_next = {"j", "<Down>", "<Tab>"},
            focus_prev = {"k", "<Up>", "<S-Tab>"},
            close = {"<Esc>", "<C-c>", "q"},
            submit = {"<CR>", "<Space>"}
        },
        on_close = function() on_choice(nil) end,
        on_submit = function(item) on_choice(item.v) end
    })

    menu:mount()
end
```
