### ISSUE TITLE
bug: search autocompleted text from cmp is invisible

### ISSUE THREAD

**Issue by avario-cpu** [folke/noice.nvim#942]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows

### Describe the bug

https://github.com/user-attachments/assets/47159518-59b7-458d-a11a-778f62fe01a8

Text selected from nvim-cmp will be invisible until a whitespace is added, or any other change are made to it.
This only happens when accepting the immediate (right below the input field) suggestion.

### Steps To Reproduce

1. Open search
2. Type
3. Accept the first suggestion (c-y in my case)

### Expected Behavior

Accepted text shows up

**Comment by b0ae989c** [comment]
Could you provide a repro config?

**Comment by avario-cpu** [comment]
> Could you provide a repro config?
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true

require("lazy").setup({
  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-buffer",
      "hrsh7th/cmp-cmdline",
    },
    config = function()
      local cmp = require("cmp")

      cmp.setup.cmdline("/", {
        mapping = cmp.mapping.preset.cmdline({
          ["<C-y>"] = cmp.mapping(cmp.mapping.confirm({ select = true }), { "i", "c" }),
        }),
        sources = {
          { name = "buffer" },
        },
      })
    end
  },
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    opts = {
      -- Add your noice configuration here
    },
    dependencies = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    }
  }
})
```

**Comment by b0ae989c** [comment]
This looks like a redraw issue related to #923. Have you tried to rollback?

Also, your repro config is not an actual repro. See the example repro in the issue template. https://github.com/folke/noice.nvim/blob/448bb9c524a7601035449210838e374a30153172/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L65-L73

**Comment by avario-cpu** [comment]
Sorry for not correctly using the template. Shall I redo ? (It will take a while prob like 1hour+, I'm a total noob and research everything new im doing, I don't mind whatsoever tho.)

Yes I had tried rollbacking, to 4.4.7 and 4.4.6. Doesnt fix it.

A funny but working fix would be to:

```lua
    config = function()
      local cmp = require("cmp")

      cmp.setup.cmdline("/", {
        mapping = cmp.mapping.preset.cmdline({
         ["<C-y>"] = cmp.mapping(cmp.mapping.confirm({ select = true }), { "i", "c" }),
        }),
        sources = {
          { name = "buffer" },
        },
      })

      local feedkeys = vim.api.nvim_feedkeys
      local termcodes = vim.api.nvim_replace_termcodes
      local function feed_space_backspace()
        feedkeys(termcodes(" <BS>", true, false, true), "n", true)
      end

      cmp.event:on("confirm_done", function()
        vim.schedule(feed_space_backspace)
      end)
    end
```

**Comment by b0ae989c** [comment]
Yes this workaround will work because `vim.api.nvim_feedkeys` invokes new keyboard input, and forces a UI redraw.

If v4.4.6 didn't fix your issue, then there may be a bug further back in `noice` or `nvim-cmp`.
