### ISSUE TITLE
[Question] How to disable cmdline

### ISSUE THREAD

**Issue by ray-x** [folke/noice.nvim#96]
**Describe the bug**
I want to disable the cmd line as when working together with wilder.nvim it is a bit laggy (might be other reasons, not sure ATM).

**Which version of Neovim are you using?**
neovim latest

**To Reproduce**
```
  require("noice").setup({
    cmdline = {
      enable = false,
    },
    lsp_progress = {
      enabled = true,
   }
 }
```

**Expected Behavior**
cmd should be the neovim default when 'enable=false'

I am happy to enable cmdline as long as it is not laggy. 

Also I did try the suggested solution with https://github.com/folke/noice.nvim/issues/27 but not working for me.

**Comment by max397574** [comment]
>     WARNING: This api is considered experimental.  Usability will vary for
>    different screen elements. In particular `ext_messages` behavior is subject
>    to further changes and usability improvements.  This is expected to be
>    used to handle messages when setting 'cmdheight' to zero (which is
>    likewise experimental).

**Comment by ray-x** [comment]
I did following from cmd line
```
:packadd noice.nvim
:lua require("noice").setup({cmdline = {enable = false}, messages={enable=false}})
```
Still command line becomes a noice floating window.

**Comment by folke** [comment]
The docs literally mention as also seen in the comment above, that cmdline is always active when you enable messages. It's a current limitation of the Neovim api

**Comment by ray-x** [comment]
As mentioned above, my setup is this:
`{cmdline = {enable = false}, messages={enable=false}}`
the cmdline and messages should be both disabled, But I still see a floating cmdline.
Does it mean there is no way to disable `cmdline` ?

**Comment by folke** [comment]
Enabled. You're missing the `d` at the end

**Comment by ray-x** [comment]
Ok, it is disabled. when I set `enabled=false` to both.
Should it be named `enable` instead of `enabled` or put another option `disable`?

**Comment by folke** [comment]
Why? It's clearly stated in the docs. So no, I won't rename it.
