### ISSUE TITLE
bug: Treesitter error with `nvim-cmp` docs

### ISSUE THREAD

**Issue by dpetka2001** [folke/noice.nvim#962]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-881+g865ba42e0

### Operating system/version

Linux Mint 21.3

### Describe the bug

When auto-completing in Python files and the `nvim-cmp` completion menu pops up, when traversing through the available entries the following error pops up
```lua
   Error  07:17:11 PM msg_show.lua_error Error executing vim.schedule lua callback: ...y/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: No parser for language "text"
stack traceback:
	[C]: in function 'assert'
	...y/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
	.../.repro/plugins/noice.nvim/lua/noice/text/treesitter.lua:39: in function 'highlight'
	....00.1x/.repro/plugins/noice.nvim/lua/noice/text/init.lua:68: in function 'highlight'
	...Tx 6.00.1x/.repro/plugins/nui.nvim/lua/nui/line/init.lua:58: in function 'highlight'
	...Tx 6.00.1x/.repro/plugins/nui.nvim/lua/nui/line/init.lua:73: in function 'render'
	...00.1x/.repro/plugins/noice.nvim/lua/noice/text/block.lua:98: in function 'render'
	....1x/.repro/plugins/noice.nvim/lua/noice/lsp/override.lua:52: in function 'stylize_markdown'
	...00.1x/.repro/plugins/nvim-cmp/lua/cmp/view/docs_view.lua:64: in function 'open'
	...on/MITx 6.00.1x/.repro/plugins/nvim-cmp/lua/cmp/view.lua:299: in function 'callback'
	... 6.00.1x/.repro/plugins/nvim-cmp/lua/cmp/utils/async.lua:138: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
I don't see this error in Lua files and since I don't do anything else except Python and Lua, I'm not sure if this also occurs with other languages as well.

### Steps To Reproduce

I'm using LazyVim distro but was also able to reproduce this without LazyVim with this [minimal repro](https://gist.github.com/dpetka2001/7f09b281e88f8a7bf1715de0ad5886b1).

1. Open a Python file
2. Start typing `print` and go through the available entries
3. The error should pop up

### Expected Behavior

No error should pop up. I'm guessing this has something to do with the latest Treesitter changes on Neovim nightly, because it's not reproducible with Neovim stable 0.10.1.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
I think I know what's causing this. There's an upstream recent change where get_parser no longer errors when no parser is available and returns nil instead. Will look into it tomorrow. not home right now

**Comment by dpetka2001** [comment]
No problem. Thanks a lot :smile:

**Comment by folke** [comment]
Should be fixed now. Let me know if the problem would persist

**Comment by dpetka2001** [comment]
All good now. If I find something else over the next couple of days I'll comment here.

Tnx again :smiley:
