### ISSUE TITLE
bug: Two confirm()'s one after the other don't update the text in the confirm window.

### ISSUE THREAD

**Issue by dapetcu21** [folke/noice.nvim#968]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows 10

### Describe the bug

Two confirms in quick succession will exhibit a weird behavior where the second confirm window will resize to the correct size, but keep the text contents of the first one.

![image](https://github.com/user-attachments/assets/3e1eb5cf-cc97-463f-9dd1-febeefe86bf3)
Then:
![image](https://github.com/user-attachments/assets/de9ed6b8-555e-4254-93fc-f5aacefb8818)

### Steps To Reproduce

`call confirm("This is a longer text. This is a longer text.") | call confirm("Meow")`

### Expected Behavior

![image](https://github.com/user-attachments/assets/3e1eb5cf-cc97-463f-9dd1-febeefe86bf3)
Then:
![image](https://github.com/user-attachments/assets/b8f1ef5f-2f45-4c6e-a9bf-487be264e9e6)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by qlaq2435** [comment]
I’m experiencing the same issue, when I use "qa" cmd, similar to what you described.
The related information about Noice is as follows:
```
        version 4.5.2
        tag     v4.5.2
        branch  main
        commit  df448c6

```

**Comment by dapetcu21** [comment]
Still an issue

**Comment by dapetcu21** [comment]
This is still an issue
