### ISSUE TITLE
feature: Add Transparency Configuration recipe 

### ISSUE THREAD

**Issue by ubes111** [folke/noice.nvim#971]
### Did you check the docs?

- [X] I have read all the noice.nvim docs

### Is your feature request related to a problem? Please describe.

When switching your Neovim setup to use transparency, there are a couple of issues with the Noice plugin:

1. Notify warning message:

```
Warn  01:23:54 notify.warn nvim-notify Highlight group 'NotifyBackground' has no background highlight
Please provide an RGB hex value or highlight group with a background value for 'background_colour' option.
This is the colour that will be used for 100% transparency.
```

2.  Formatters' progress bar and messages:
The progress bar and messages from formatters still retain a background, despite the transparency setup.

### Describe the solution you'd like

Configuration recipe ensures that:

- The NotifyBackground warning is resolved by explicitly setting a background color for transparency.
- The formatters' progress bar and messages also conform to the transparent setup.

### Describe alternatives you've considered

To fix both issues, the following configuration can be applied:

```
require("noice").setup({
    views = {
        mini = {
            win_options = {
                winblend = 0, -- Set winblend to 0 for the mini view
            },
        },
    },
})

require('notify').setup({
    background_colour = "#000000" -- Set background color to fix transparency issue
})

vim.notify = require("notify")
```

### Additional context

<img width="1025" alt="Знімок екрана 2024-10-16 о 01 27 41" src="https://github.com/user-attachments/assets/0c5f163c-8510-4a8a-87d4-d1304b1e2894">
<img width="218" alt="Знімок екрана 2024-10-16 о 01 31 22" src="https://github.com/user-attachments/assets/0649da72-f3f3-4b26-bb3f-d39cab194d2d">

**Comment by darkard2003** [comment]
I have the same issue, shows same error when cappuccin transparency is enabled

**Comment by ubes111** [comment]
> I have the same issue, shows same error when cappuccin transparency is enabled

Hey! To fix this, add the following snippet to your config:

```
require('notify').setup({
    background_colour = "#000000" 
})

vim.notify = require("notify")
```
