### ISSUE TITLE
bug: MacOS word motion keys

### ISSUE THREAD

**Issue by wilfredjonathanjames** [folke/noice.nvim#978]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

14.7

### Describe the bug

Hi, I'm on Mac and would like to use the mac movement keys (opt+arrow keys, opt+delete, etc) when searching, renaming wiht inc-rename.nvim, or entering commands. I'm pretty sure wezterm is sending the correct escape codes.

### Steps To Reproduce

1. Open nvim with noice.nvim on mac
2. Open the command input popup
3. Type two words
4. Press `Opt+LeftArrow`
5. Try again, this time using `Opt+Delete`

The popup will close.

### Expected Behavior

The second word would be deleted. and the popup would remain open.

**Comment by folke** [comment]
This is a limitation of Neovim, not noice
