### ISSUE TITLE
bug: "lsp_doc_border" not work after commit 3cd84d4

### ISSUE THREAD

**Issue by LinoWhy** [folke/noice.nvim#984]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.3-dev-14+gfb5a0e28db

### Operating system/version

Ubuntu 22.04

### Describe the bug

After update to release v4.6.0, lsp_doc_border doesn't work anymore.
Just revert the commit 3cd84d4 makes lsp_doc_border config work as expected.

### Steps To Reproduce

1. update noice to latest release
2. open a lua config file and show some lsp hover,
3. go to noice repo and revert the commit 3cd84d4
4. repeat step 2

### Expected Behavior

Setting lsp_doc_border works again.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "folke/noice.nvim",
      opts = {
        lsp = {
          -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
          override = {
            ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
            ["vim.lsp.util.stylize_markdown"] = true,
            ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
          },
          hover = {
            silent = true, -- set to true to not show a message if hover is not available
          },
        },
        presets = {
          long_message_to_split = true,
          lsp_doc_border = true,
        },
      },
    },
    -- add any other plugins here
  },
})
```

**Comment by PetarMetodiev** [comment]
I can confirm:
![image](https://github.com/user-attachments/assets/f782d611-8750-4ad8-a43c-c1ea25b4133d)

**Comment by folke** [comment]
How are you triggering hover? I really can't reproduce this...

**Comment by PetarMetodiev** [comment]
I am using the [default config](https://www.lazyvim.org/keymaps#lsp) for LazyVim, so <kbd>K</kbd>

**Comment by PetarMetodiev** [comment]
I installed it ~2 years ago following [these instructions](https://www.lazyvim.org/installation), so I guess main?

The border problem started happening last week after I updated my dependencies with `<leader>l` and then <kbd>S</kbd>.

Just checked and I have no updates.

The changelog (`<leader>L`) says this:
```md
# Changelog

## [12.44.1](https://github.com/LazyVim/LazyVim/compare/v12.44.0...v12.44.1) (2024-11-03)


### Bug Fixes

* **blink:** use release version ([7ebed53](https://github.com/LazyVim/LazyVim/commit/7ebed5349d49dd9996d61155bc12605871058ec1))
* **copilot:** properly process tab with copilot and blink. Fixes [#4692](https://github.com/LazyVim/LazyVim/issues/4692) ([fa37396](https://github.com/LazyVim/LazyVim/commit/fa3739678af494b8657d68ddc44bcc598f9bd00a))
* **java:** jdtls run with args ([#4689](https://github.com/LazyVim/LazyVim/issues/4689)) ([0403e80](https://github.com/LazyVim/LazyVim/commit/0403e80a8e6250130fe94af1034a6f0760a24ca8))
```

**Comment by folke** [comment]
Must really be something else, not idea what. The repro below works as it should forme:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "neovim/nvim-lspconfig",
      config = function()
        require("lspconfig").lua_ls.setup({})
      end,
    },
    {
      "folke/noice.nvim",
      opts = {
        lsp = {
          -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
          override = {
            ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
            ["vim.lsp.util.stylize_markdown"] = true,
            ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
          },
          hover = {
            silent = true, -- set to true to not show a message if hover is not available
          },
        },
        presets = {
          long_message_to_split = true,
          lsp_doc_border = true,
        },
      },
    },
    -- add any other plugins here
  },
})
```

![image](https://github.com/user-attachments/assets/02ef650f-3935-4869-bfc0-eab66c80f247)

**Comment by PetarMetodiev** [comment]
Indeed it was something else. I tried disabling all my plugins and then enabling them one by one. I narrowed it down to this line:
```lua
  {
    "neovim/nvim-lspconfig",
    init = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get() -- <- THIS LINE

      keys[#keys + 1] = {
        "gk",
        function()
          vim.diagnostic.goto_prev({ float = { border = "rounded" } })
        end,
        noremap = true,
        silent = true,
        desc = "Go to previous diagnostic",
      }

      keys[#keys + 1] = {
        "gj",
        function()
          vim.diagnostic.goto_next({ float = { border = "rounded" } })
        end,
        noremap = true,
        silent = true,
        desc = "Go to next diagnostic",
      }

      keys[#keys + 1] = {
        "ga",
        vim.lsp.buf.code_action,
        noremap = true,
        silent = true,
        desc = "Code Action",
        mode = { "n", "v" },
        has = "codeAction",
      }
    end,
    opts = {
      -- ...
      },
    },
  },
```

When I remove it (together with the code that depends on it), the border comes back. Also removing the mapings one by one didn't bring back the border, so this makes me think the marked line is the issue.

For reference I followed the instructions [here](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps)

**Comment by folke** [comment]
Thats your problem.
Since a recent change in NEovim, Noice has to override things like `vim.lsp.buf.hover`.
Since you're calling that in init, you won't get the correct methods.

Just pushed an update to LazyVim that works around this

**Comment by PetarMetodiev** [comment]
Thank you very much! I will be waiting for the next LazyVim release then.

**Comment by uthmanmoh** [comment]
Can confirm border works on hover now after commit 7616816 in LazyVim which changes the hover keymap from:
```lua
{ "K", vim.lsp.buf.hover, desc = "Hover" },
```
to
```lua
{ "K", function() return vim.lsp.buf.hover() end, desc = "Hover" },
```

**Comment by LinoWhy** [comment]
Thanks for the help!
