### ISSUE TITLE
bug: lsp progress view broken

### ISSUE THREAD

**Issue by MarcoBuess** [folke/noice.nvim#986]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Windows 11 23H2

### Describe the bug

I'm using the following opts for lsp progress loading animation:
```lua
      views = {
        notify = {
          replace = true,
        },
      },
      lsp = {
        progress = { view = "notify" },
        override = {
          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
          ["vim.lsp.util.stylize_markdown"] = true,
          ["cmp.entry.get_documentation"] = true,
        },
      },
```
this seems to have stopped working since I updated today. The notify view now doesn't get replaced for lsp progress, it rather spames a notification for every update on lsp progress.

### Steps To Reproduce

set the following opts:
```lua
      views = {
        notify = {
          replace = true,
        },
      },
      lsp = {
        progress = { view = "notify" },
        override = {
          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
          ["vim.lsp.util.stylize_markdown"] = true,
          ["cmp.entry.get_documentation"] = true,
        },
      },
```
open a file using `lua_ls`.

### Expected Behavior

Lsp progress notification gets replaced properly.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {
      views = {
        notify = {
          replace = true,
        },
      },
      lsp = {
        progress = { view = "notify" },
        override = {
          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
          ["vim.lsp.util.stylize_markdown"] = true,
          ["cmp.entry.get_documentation"] = true,
        },
      },
      presets = {
        lsp_doc_border = true,
      },
} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Are you using snacks.nvim or nvim-notify?
Can you show a screenshot?

**Comment by folke** [comment]
Also, make sure to update all plugins first

**Comment by MarcoBuess** [comment]
@folke Sorry for the late response, just wanted to confirm, that it is working after the latest changes.
