### ISSUE TITLE
bug: noice seems to break vim.fn.input() and vim.ui.input() in insert mode

### ISSUE THREAD

**Issue by andrewferrier** [folke/noice.nvim#987]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1103+g04274a4173

### Operating system/version

Arch Linux

### Describe the bug

`vim.fn.input()` and `vim.ui.input()` do not show any popup or other prompt when invoked from insert mode and `noice` is being used (with its default options). With noice-less NeoVim, these work correctly in this circumstance.

(For the record, I discovered this issue whilst investigating https://github.com/andrewferrier/debugprint.nvim/issues/86 - it affected a user of mine who would normally expect a prompt in insert mode - this works correctly for me as I don't normally use noice (although I've tried it, and it's a fantastic demonstration of what can be done with NeoVim - thanks for all your hard efforts!)).

For more information, it's likely easiest to follow the repro steps.

### Steps To Reproduce

1. Put in place the `init.lua` below in a fresh NeoVim config (e.g. using `NVIM_APPNAME`).
2. Comment out `noice.nvim` by commenting line 6 in `init.lua`.
3. Load NeoVim.
4. Enter insert mode by pressing `i`, press `<C-G>a`. Note that `abc` is entered.
5. Remaining in insert mode, press `<C-G>b`. Note that a prompt appears in the command line, type something in, hit `<CR>` and see it entered into the buffer.
6. Remaining in insert mode, press `<C-G>c`. Enter something and hit `<CR>`. You will not see it in the buffer since we aren't correctly handling the callback, but if you type `:messages` you'll see what you entered.
7. Quit NeoVim, uncomment the line so that `noice` is loaded, and reopen NeoVim, wait for noice to be installed/loaded.
8. Repeat steps (4)-(6) above. (4) should work as before, but (5) and (6) will silently fail and no prompt will be shown, except that the cursor will change to a block shape (unclear which mode it is in now).

### Expected Behavior

I would expect that the prompts will be shown for both `vim.fn.input()` and `vim.ui.input()` in insert mode as they are in normal mode, when using noice.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "folke/noice.nvim", opts = {} },
	},
})

-- Works
vim.keymap.set("i", "<C-G>a", function()
	return "abc"
end, { expr = true })

vim.keymap.set("i", "<C-G>b", function()
	return vim.fn.input("Prompt: ")
end, {
	expr = true,
})

vim.keymap.set("i", "<C-G>c", function()
	vim.ui.input({ prompt = "Prompt: " }, function(input)
		print("INPUT WAS " .. input)
	end)
end, {
	expr = true,
})
```

**Comment by folke** [comment]
That;s because you're in an expression mapping. It's not allowed to create windows in that case.
Cant fix.

**Comment by andrewferrier** [comment]
@folke thanks, that's good to know. I will say I do find `expr` mappings to be a bit flaky in general. This spurred me on to find an alternative for my plugin and I think `vim.api.nvim_put` will do what I wanted to insert text, so I'll switch to that. Thank you.
