### ISSUE TITLE
bug: `config.lsp.hover.silent` doesn't work with Snack

### ISSUE THREAD

**Issue by igorgue** [folke/noice.nvim#990]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

NixOS 24.11

### Describe the bug

Using `config.lsp.hover.silent` no longer works with `Snacks`, it used to work with `notify.nvim`.

### Steps To Reproduce

Set the flag to *true*, then you'll get the notification of empty messages instead of it being filtered out.

### Expected Behavior

Filter out messages.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
You're probably using a verison of LazyVim older than 3 hours

**Comment by igorgue** [comment]
@folke okay, let me update, thanks for answering!
